### ISSUE TITLE
Special penalties & bonuses listing in the points section

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#100]
Only some tests list the points for Not attending and Outstanding performance.
I would suggest that we remove the points from the individual score sheets and only keep it in the general rules?
The other option would be to add it to all the tests.

**Comment by LoyVanBeek** [comment]
We even discussed removing Outstanding performance completely, but ultimately left things as they were.
Being a software engineer, I suggest reusing this general rule instead of duplication.

**Comment by LoyVanBeek** [comment]
This is also only for the TC members. @kyordhel could you do some TeX magic with the score sheet template? I can try to do it, but my LaTeX knowledge is not that deep and moreover the makefile is broken :sob:

**Comment by kyordhel** [comment]
Wait @LoyVanBeek, in theory I've fixed the rulebook's makefile on the last commit (it built properly on my computer). Will check it ASAP
