### ISSUE TITLE
Speech Recognition & Audio Detection Test Score Sheet does not follow new layout

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#102]
For most of the stage 1 tests there is a new layout of the score sheets which incorporate the three tries.
Speech Recognition & Audio Detection Test still has the old layout.

**Comment by LoyVanBeek** [comment]
@kyordhel could you do your TeX magic?

**Comment by kyordhel** [comment]
Pffffffffffffffffffffffffffffffffff

Just pulled. Make fails to build the rulebook. I have the scoresheet ready but I would prefer not to save the file nor commit.  Here my output:

    ! Misplaced alignment tab character &.
    <argument> Robot &
                       team cooperation
    l.174 \section{Robot & team cooperation}

Shall I fix it?

**Comment by LoyVanBeek** [comment]
Yeah, @dirkholz somehow broke the makefile. The previous version works though. If you find any issues, please fix them so we can release an updated rulebook ASAP.

**Comment by kyordhel** [comment]
Solved.

BTW I hate LaTeX, I hate people, I hate me.
