### ISSUE TITLE
Make not (always) working

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#103]
Makefile may not run on all distros

**Comment by kyordhel** [comment]
@LoyVanBeek,
I just deleted my RuleBook dir and got a fresh version from the repo. I had no trouble running Make.
Could you please check with the following line?

    $ make dofullpdf

**Comment by LoyVanBeek** [comment]
That works!
I have one error though
```latex
! LaTeX Error: Command \celsius already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.32 \newcommand\celsius{}
```

When I press r <enter> it finishes though

**Comment by kyordhel** [comment]
Pfffffff...
No idea, to me it compiles perfectly (both, rubber and pdflatex)!
Which versions of pdflatex do you have? Did you tried to delete the whole directory and pull it again?

**Comment by LoyVanBeek** [comment]
Yes I did, it seems to be something with my latex install. Whatever, good enough for now
