### ISSUE TITLE
Contradiction in Speech Recognition and Audio Detection Test

### ISSUE THREAD

**Issue by growolff** [RoboCupAtHome/RuleBook#105]
In page 59 of the current RuleBook, in the introduction paragraph says: "The robot is allowed to turn to the operator and ask it to repeat the question, and the operator will repeat the question only once before moving again behind the robot...". 

Instead, in the section 5.4.6.2 **Indirect Speech Recognition** says: The robot may turn its microphone towards the operator and ask for only one repetition of the question.  The robot should then answer without asking for confirmation.

This confuses me, what can the robot do or not do? If the robot's microphone is turned towards the operator, it means that the robot will do 'Direct Speech Recognition' instead of a second attempt of 'Indirect Speech Recognition'.

Thank you in advance.

**Comment by balkce** [comment]
I think the issue of confusion is with the words of "indirect" and
"direct"; they only convey the INITIAL position of the operator relative to
the robot. The first set of 5 questions (direct) are with the operator in
front of the robot, and the second set of 5 questions (indirect) are with
the operator somewhere outside the front range of the robot.

You decide how to solve the second set of questions: (a) you can turn the
robot/microphone towards the operator and ask for a repetition of the
question or (b) carry out the recognition without doing turning. Depending
on which solution you decide to do, the points will be different.

**Comment by balkce** [comment]
I re-read the whole section again. I'm sorry, I'm not seeing the contradiction: the task description in 5.6.4 is pretty straightforward, clearly stating what Direct and Indirect speech recognition means and what the robot can and cannot do in both phases. And, the Introduction paragraph you pointed out states that it only applies to the second phase of the task, which is inline of what is stated in 5.6.4.2. 

I'm closing this issue.
