### ISSUE TITLE
Robo-Nurse Speech Recognition

### ISSUE THREAD

**Issue by LoreChile** [RoboCupAtHome/RuleBook#106]
I have a question regarding speech recognition in the robo-nurse.

How far from Granny will the shelf be? This is to know the distance that the robot will have to listen and recognize voice commands from Granny and if this will be heard indirectly.

Thanks!

**Comment by LoyVanBeek** [comment]
The setup we had in Germany for this was that a chair wit Granny was very near the shelf. I didn't measure it, but see for your self please in the [map](https://github.com/RoboCupAtHome/RuleBook/blob/19bd45968a9f8985ffdde911e3af06d5357288ba/GermanOpen2015/locations.pdf) for that environment: location 1 was the shelf, the square left of location 2 is chair of Granny. 

China will be different, but even TC does not know how, but we will arrange the arena to make all challenges possible of course.

I hope this clears up your question.

**Comment by dirkholz** [comment]
For the future: questions like this should go to the mailing list,  not into the issues ...
