### ISSUE TITLE
[Restaurant] What to do when the waving person cannot be detected

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#113]
When a robot misses the calling or waving person, the most logical behavior is to just continue to go to the kitchen and take a command to go to some table there. 
Once the robot is commanded by the waiter to go to some table (i.e. the table at which the waiter detected a call), the robot cannot score points for detecting the call anymore. 

The amount of points of points for going the the second table then must be much lower to make an incentive to do the detection and localization of the calling/waving. 
Maybe the points given should even be less than for the first table, because the robot already showed it could go to a table. 
I propose the make the scoring as such:
- Noticing and localizing the second table by waving/calling. It has to be clear to the referees that the robot detected and localized the call:  25
- Going to the second table: 10
- Taking an order from the second table: 5
- Getting instruction for 2nd table by waiter: 2

**Comment by balkce** [comment]
I agree with your kitchen-workaround idea.

The only thing is that I'm not so sure about reducing the points for the second table, since we're grading those abilities as well in this test, and if the robot does both well, it makes sense that it should receive twice the points of doing one table. I would just score the detection of the waving/calling very high to incentivize teams.

**Comment by LoyVanBeek** [comment]
Taking a second order from the waiter is a backup plan. The other option is to just stop the challenge if you cannot get 2 orders.
We're being lenient with allowing this fallback option, the robot already have shown enough that they can do this also in stage 1, so I would keep the points as they are.

**Comment by balkce** [comment]
I'd rather have the backup plan over stopping the test: more to show.

**Comment by LoyVanBeek** [comment]
Indeed, so I would like to keep the scores as I proposed them. Its a backup for when you fail, so less points for that.

**Comment by LoyVanBeek** [comment]
Other suggestion and conclusion: If you fail to get the call of the calling or waving person, you do not get points for going to the calling person, obviously.
You will only get the points for taking the order, after the waiter tells the robot to go the table number that was waving.
