### ISSUE TITLE
Speech recognition: indirect speech recognition test

### ISSUE THREAD

**Issue by reinzor** [RoboCupAtHome/RuleBook#115]
![image](https://cloud.githubusercontent.com/assets/4176023/9206197/b5f4d89e-4066-11e5-8578-4362187a7b1b.png)

The robot should localize the sound source; challenge might consist of two parts:
- Ask the robot to navigate or turn towards the speaking person
- Respond to a question

**Comment by LoyVanBeek** [comment]
Accepted!
