### ISSUE TITLE
Finals: possibility to get a restart when a hardware problem occurs

### ISSUE THREAD

**Issue by reinzor** [RoboCupAtHome/RuleBook#116]
When a team is experiencing hardware problems; there should be a possibility to fix these for the Finals. There are only 5 teams and it really sucks when you can't attend the finals for a couple of reasons:
- 1/2 of the total points
- We all want to contribute something to the RobocupAtHome Community and show what we've have made during the last days / years
- Fair competition

**Comment by rokusottervanger** [comment]
Bump
Take the finals of the MSL for example; they don't start until the robots are ready, because otherwise it's not a very fun competition for any team.

**Comment by LoyVanBeek** [comment]
Kind of agree. The MSL lets 10s tot 100s of people waiting, while @Home keeps on pushing forward for a select and small audience.
There should be a time limit of course, maybe also for MSL actually but thats beyond our control of course.
