### ISSUE TITLE
Cooperate with Rescue League

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#119]
RoboCup Trustees want us to cooperate somehow with the rescue league.

**Comment by kyordhel** [comment]
No major changes in the rulebook for 2019. Rescheduling for 2019.

**Comment by moriarty** [comment]
🤦‍♂️ Can we bump this to 2020?

**Comment by moriarty** [comment]
:+1: I don’t even know where to begin with this cooperation: but with a lot of changes coming for 2019, 2020 is slightly more realistic.

**Comment by justinhart** [comment]
Is this on the agenda for 2020?

**Comment by LoyVanBeek** [comment]
I hope not. Request is also for 2015... The only collaboration I saw in 2019 was a rescue robot searching for stuff while the @home robots were out for a nice dinner in the Restaurant. Given the constraints on manpower we already have, I don't think we should do this. 
@kyordhel any requests for this cooperation this year?

**Comment by kyordhel** [comment]
As usual, Trustees try to encourage inter-league collaboration.

I would focus first on fostering an internal collaboration (joint teams, code sharing, cross-research etc), and then approach to other leagues, but as Exec I'm obliged to mention this
