### ISSUE TITLE
Standardize the continue rule

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#120]
We should have a standardized Continue-rule, like showing the given command encoded into a QR-code. At least get rid of the typing on the robots. Then understanding the command by speech gives 100% of the points, a QR-code 25%, OCR on printed text eg. 50% and OCR of written text 75%. Anyways, make it standardized. Then, a command generator like the one for GPSR can show a command on a laptop and generate a QR code. If speech fails, just show the robot the laptop.

**Comment by kyordhel** [comment]
This is done.
