### ISSUE TITLE
All robots should speak English during the RoboZoo

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#122]
Eliminates the home-team advantage.

**Comment by LoyVanBeek** [comment]
Side-note: English is a foreign language to all teams

**Comment by kyordhel** [comment]
Local language for all teams, participation mandatory (50 pts penalty when not participating), tests grants no points.

**Comment by balkce** [comment]
Addendum: test grant *few* points.

**Comment by kyordhel** [comment]
@balkce the test grants 50 pts to the absolute winner (25 appearance, 25 performance) while the other tests grant between 150 and 250 points each. Few than 50pts means?

**Comment by LoyVanBeek** [comment]
Currently,RoboZoo grants 1/5th of the maximum achiev**able** score in the other test. 
We could normalize this to the maximum achiev**ed** score, to keep the test relatively insignificant. 

But, that makes it very complex, just giving points is better then.

**Comment by kyordhel** [comment]
In my humble opinion there is no big difference if we grant zero points or 10. Giving fewer than 50 will lead to a lack of interest of the teams, so the test must be set as mandatory OR we make it thematic with some specific challenges (dish washing, pancake flipping, milkshake making, etc.) and keep the points.

**Comment by balkce** [comment]
Didn't we notice that most teams were scoring around 50 points in the other
tests? I thought this was the reason that triggered this change.

In any case, making it only obligatory will make teams not work for a good
show. While, the typical whoring for points (even for a few) provides
sufficient reason for this incentive.

But I get your point. Making it obligatory will save us some trouble
logistically and scoring-wise.

I don't really want to waste time with this test more than needed: it's a
show, I don't really care about its scoring.

C

**Comment by LoyVanBeek** [comment]
Updated the rulebook for this in https://github.com/RoboCupAtHome/RuleBook/commit/e5b593030c6c5baa4602bbc1d6659db5c3b0b661
