### ISSUE TITLE
More similar questions for speech recognition

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#124]
More similar questions make it harder to distinguish between them.

**Comment by LoyVanBeek** [comment]
And make the questions about the arena and objects etc. 
Generate such questions.

**Comment by kyordhel** [comment]
Going beyond speech recognition and aiming also for NLP/NLU?
RoCKIn *Speech Understanding Functionality* benchmark provides pre-recorded audio files along with spoken commands and robots are required to provide: audio, transcription and *Command Frame Representation*

**Comment by LoyVanBeek** [comment]
Done in https://github.com/RoboCupAtHome/reo2016/blob/master/speech_recognition/speech_recognition_questions.csv
