### ISSUE TITLE
Integrate EGPSR with Restaurant: Robots Outside for long time!

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#126]
Mention examples of possible robot roles and tasks (clean table or floor, guide people to table, count people in the waiting line, serve drinks, combos, make suggestions, have food remains to take home, etc).

Incomplete information: Serve me combo SaversPack 1 (which includes a beverage but does not specify which).
Erroneous information: Robot bring me some milk (in a bar where is no milk) or a coke (coke is sold out).

Complexity plus:
- We have several robots in race conditions to serve the available objects which may not be replaced.
- Robot/Team does not know preemptively which GPSR category is being asked for
  - Bring a coke is Cat1, but changes to Cat 3 if coke is sold out
  - Bring a combo requires a beverage to be specified
  - Having people at the entrance may occur at any time

**Comment by LoyVanBeek** [comment]
Related to #118

**Comment by kyordhel** [comment]
Not for this year. Minor changes only.
