### ISSUE TITLE
Write section "Smart Home Devices"

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#13]

**Comment by LoyVanBeek** [comment]
Maja will contact Local Organizing Committee

**Comment by kyordhel** [comment]
I will wait till have specs to write this sections

**Comment by kyordhel** [comment]
Partially done. Approval required before closing issue

**Comment by LoyVanBeek** [comment]
Rockin@Home does this: http://rm.isr.ist.utl.pt/projects/rockin-competitions-wiki/wiki/GCRHome#Home-automation-controller-networked-device

**Comment by kyordhel** [comment]
@LoyVanBeek, @balkce  according to the Rulebook:

*The list if Smart Home devices will be provided to teams as soon as it becomes available and has been granted by the Local Organization and approved by the Technical Committee. This list must be announced at least one month prior the competition. In case that this list does not become available for that date, Smart Home devices may still be present at the arena for testing, but no additional score can be achieved for its use. This is to maintain fair conditions among all teams.*

The announcement was not made. I'm closing this issue and no points will be scored for interacting with smart home. However, I think we should allow teams to set up their own for demonstration.
