### ISSUE TITLE
Navigation: Allow robot to still reach object via different approach

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#132]
The spirit of the test is not to move the obstacle, but to reach the goal somehow and not stop.
- You may move the obstacle and reach one side of the table
- You may also notice the obstacle and just go to the other side of the table.

**Comment by kyordhel** [comment]
What will happen with the "Open the door" challenge in the navigation test. It would be nice to have it as "mandatory" for 2020 as it became mandatory to detect when the door opens in previous years.

Plus, I believe there should be no penalty if the robot decides to "kindly interact" with furniture

**Comment by LoyVanBeek** [comment]
Indeed, functional touching is allowed. E.g. for opening a door using the robot's base for pushing it open
