### ISSUE TITLE
Allowing Drones

### ISSUE THREAD

**Issue by tik0** [RoboCupAtHome/RuleBook#148]
Will flying drones (e.g. quadrocopter) be allowed for the open-challenge or finals?
And if so:

- What are the security issues to fulfill?
- What is the minimum/maximum size/weight?
- Only teleoperated or autonomous as well?
- Only recommended standard models, or also self-build drones?

**Comment by kyordhel** [comment]
I will rely on common sense for answering this question: 

** Would you like to have a drone flying around all your apartment? **

I fear I wouldn't. At least, not in the @home context (rescue presents a completely different scenario). Reasons include, but are not limited to:

- Noise. 
- Drone couldn't fly above 3m from floor. 
- Reliability: A home robot should be able to map the house and detect changes during normal operation without using a drone. 
- Security: drone crashes small/fragile objects. 
- Security: Drone exits the arena and scares/annoys audience and/or other teams. 

Therefore, I find it hard for the TC to approve it. However, having the Open Challenge an special nature, you must provide a comprehensive description of what you are trying to do.

**Comment by dirkholz** [comment]
Simply "no", drones are only allowed in robocup rescue in areas with safety
nets. There won't be such bets in @home, so you would not be allowed to
have the drone fly. As long as it is not flying though you may do whatever
you want with it (although that's somewhat useless i need to admit) ...

**Comment by tik0** [comment]
OK, the missing nets are a thing.
Thus, we can close the conversation, due to security reasons.
But anyway, nothing is "useless" at all in @home from my POV.

**Comment by LoyVanBeek** [comment]
Drones are fun, so not useless in that regard. They would be able to do most of the tasks actually, I think, though manipulation would be difficult and speech recognition limited by its own noise.
I'd like to allow this, but have to agree with the security concerns.

**Comment by tik0** [comment]
There are actually numerous other tasks which can be nicely done with drones inside apartments.
 Also the DARPA has a program regarding this, which makes drone an emerging scientific field in the near future (https://youtu.be/Y56iJ4ZOgmY?t=45s).
Thus, the TCs might consider that in the upcoming years.

But anyway, one has to admit that the missing walls makes it hard to mimic a real apartment for drones.

**Comment by kyordhel** [comment]
They may be thousands of tasks that can be done using drones in home/office environment, one just need to take a look to Cinderella or Snow White and replace the nice birds and mice with drones! Or maybe something like Alfred Hitchcock's *Bitds*. Still I feel drones does not fit in with the spirit of @home.

Anyway, @home is a Peer-driven competition and the TC are volunteers from the teams, sso if all teams feel like using drones, that TC will promote it for sure,

I agree with Dirk. For security concerns no flying drones will be allowed.
