### ISSUE TITLE
Write section "RoboZoo"

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#15]
Same as last year, but:
* No gifts are allowed!
* Later about the score amount
* Also design the token handling system

**Comment by LoyVanBeek** [comment]
Some ideas: 
Maybe score on different categories: 
- Friendliest robot
- Best looking robot
- "I would allow/want this in my house"-award. 
Instead of handing out tokens, the audience votes on a board or laptop we put up.

**Comment by kyordhel** [comment]
Done!
RoboZoo now allows 2 awards!
