### ISSUE TITLE
Challenge speech recognition, asking for repetition

### ISSUE THREAD

**Issue by reinzor** [RoboCupAtHome/RuleBook#152]
Page 56:

> "Question repetition: In the second phase, if the robot turns towards the operator to be
> asked once again, it should clearly state that it requires a repetition of the question once
> it finishes turning, so as to cue the operator to do so."

So you may only ask for a repetition if you have turned towards the correct operator? Or can you always ask for a repetition? @Rayman

**Comment by kyordhel** [comment]
Correct. I think the rulebook is quite clear here. Robot may:

- Answer the question at the first attempt.
- Turn, face the operator and clearly ask to repeat the question, then answer the question.

More attempts are not allowed.
