### ISSUE TITLE
"One click" start button: No terminal

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#157]
Make even more specific in the rulebook that the **_one click_ start button** must be easy understandable and doable by a referee, including:

- Big, green physical button on the robot
- Big green start-labeled button in mobile device
- A simple GUI on a computer onboard
- A keyboard stroke.

However, invoking command terminal by pressing enter in a screen full of terminals is not acceptable.

**Comment by LoyVanBeek** [comment]
Actually, I'm fine if the single keyboard stroke is pressing <enter> on a prepared terminal command. 
In stage 1, its benchmarking, not intended for actual users.

**Comment by balkce** [comment]
Agreed on keyboard stroke on a prepared terminal command. We've done this
for quite a while.

C
