### ISSUE TITLE
Make report for Person recognition as well. 

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#158]
This way, we its much clearer whether the robot did it correctly, less chance of good/bad luck.

**Comment by kyordhel** [comment]
Wow! All those reports make me think that we don't trust teams anymore! Are we seriously thinking they are chasing points? ;)

**Comment by LoyVanBeek** [comment]
Most importantly, its easier for us and less room for doubly incorrect robots.
