### ISSUE TITLE
Person recognition report

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#159]
As it is, person recognition scoring is unfair. Stating operator gender is coin-flipping and is hard for the referee to have confidence on what the robot said (can't be asked to repeat) or if it has correctly identified the operator.

Consider for instance female operator standing behind another female (crowd of 7 with 5 males). Robot states that the operator is sitting and points to them both, the standing one and the siting one. Also, if the robot approaches to the sitting woman there is no warranty that the operator was identified correctly as female.

Following changes are advised:

- Pdf report delivered upon rest completion, containing:
- Picture of the operator during training stating them gender.
- Picture(s) of the crowd with:
    - Each detected face framed and labeled stating gender and pose.
    - Face of the operator framed and labeled stating gender and pose.
- Scoring will change as follows:
	- Detecting operators pose will be considered only if it was correctly found in the crowd.
	- Points given per person in crowd.
	- Hits minus mistakes
		- Correctly detect a person grants +M points.
		- Incorrectly detect a person (false positives) grants -M points.
		- Correctly state the gender/pose grants +N points.
		- Incorrectly state the gender/pose grants -N points.
		- State gender/pose for false positives grants no points nor penalty.
		- State unknown gender/pose grants no points.
	- No report, no points.

**Comment by LoyVanBeek** [comment]
- The original version has pose only for the operator. Do you want to change that to all poses?
- Normalize points from the report to the amount of people present and max attainable points scored given that number.

**Comment by kyordhel** [comment]
I wrote it down as we agreed in Einhoven, so the answer is No. Pose shall be stated for the operator only.

No normalization. We need to change the scoring then as follows (scoring points are dummy):
Let F be the total amount of female and M be the total amount of male in the full crowd minus one (operator).
- Correct number of people in crowd (based on picture) +10pt
- Each correct female (based on picture) +10 * 1/(F+M)pt.
- Each incorrect female (based on picture) -10 * 1/(F+M)pt.
- Each correct male (based on picture) +10 * 1/(F+M)pt.
- Each incorrect male (based on picture) -10 * 1/(F+M)pt.

**Example 1.** Crowd is 8, 4 male and 4 female, operator is female.
Robot takes a picture having only 6 people in it and reports:
- 6 people in the crowd (10pts).
- 2 female as female (+20/7 pts).
- 2 male as male (+20/7 pts).
- 1 female as uknown (0 pts).
- 1 male as uknown (0 pts).
It grants then a total of 10 + 40/7 = 16pt.

**Example 2.** Crowd is 8, 5 male and 3 female, operator is male.
Robot takes a picture having only 6 people in it and reports:
- 6 people in the crowd (0pts, because of the plant).
- 1 plant as male (0pts).
- 2 female as female (+20/7 pts).
- 1 female as male (-10/7 pts).
- 2 male as male (+20/7 pts).
It grants then a total of 50/7 = 4pt.

**Example 3.** Crowd is 7, all are male.
Robot takes a picture having all 7 people in it and reports:
- 7 people in the crowd (10pts).
-  6 male as female (-60/6 pts).
It grants then a total of 10 + Max(0, -60/6) = 10pt.

**Note:** that the operator is not considered in this count since it is scored separately. Also, your score does not get penalized regardles how many mistakes you did with the crows. This is in order to encourage teams to try but making cheating extremely difficult.

**Comment by LoyVanBeek** [comment]
Indeed, normalize for the crowd size. 

But, I **don't** agree on the crowd being larger than the picture: if the robot misses people because the field of view of the camera is too small: too bad for the robot, find a way to scan the whole crowd.

**Comment by kyordhel** [comment]
Loy!!!!


No, no, no, no. Sorry, I didn't explained it well. The crowd is not that big. Look at the examples: eight people is large enough. 

What I meant saying that only part of the crowd is in the root's FOV is: let's say you have 4 people in row with operator in the left most position. Robot uses operator to detect crowd and centres on the operator, detecting only 3 out of 4 (right of the image and nothing on the left). 

There is no need for scan to cover the whole crowd. Of course this is an approach, but the whole crowd must fit in a picture without panning.

**Comment by LoyVanBeek** [comment]
Then I'm still confused on why that is approach in scoring is better than taking the full amount of people and dividing points by that. If a robot then only sees and correctly labels 6 people but there are 8 in total, your points are divided by 8, not 6. Getting the whole crowd is better. 

I don't want to look into the implementation in the robot, just the result. If the robot counts people with its laser scanner and covers the whole crowd at once, fine.

**Comment by kyordhel** [comment]
You are thinking it too complex. 

Think about a 4 people crowd. For some reason the robot takes the picture and you (Loy) see only 3 people and half at the left of the picture and a lot of free space in the right, enough to fit 10 people more, the crowd was not centred. Robot identifies 3 out of 3 in the picture which is perfect BUT I wouldn't grant the same score (perfect) since crowd size is not correct. Another robot that identifies 4 out of 4 deserves more.

**Comment by LoyVanBeek** [comment]
I was aiming for simplicity actually :smiley: 

But I see what you mean, but still don't agree with giving any points for ignoring e.g. half the crowd while counting the crowd. Find a good pose or strategy to count everyone.

E.g. If a robot has a small FoV, it should use its base or head to counter that limitation.

**Comment by LoyVanBeek** [comment]
I implemented it how it should be in my interpretation.

Scoring the examples according to https://github.com/RoboCupAtHome/RuleBook/commit/1291618e73b513081531c827ff5705c7b8e693d4 

### Example 1
 8 people in the crowd, 4 males, 4 females
-  Robot reports 6 people: 0
-  2 females as females: correct: (1/8)*(2*60) = 15
-  2 males as males: correct: (1/8)*(2*60) = 15
-  1 female as unknown: no points : 0
-  1 male as unknown: no points : 0
-  Operator pose correctly: 20

total: 35

### Example 2:
 Crowd is 8, 5 male and 3 female, operator is male.
- 6 people in the crowd: 0
- 1 plant as male (0pts): 0
- 2 female as female: (1/8)*(2*60) = 15
- 1 female as male (-10/7 pts). (1/8)*(1*-60) = -7.5
- 2 male as male (+20/7 pts). (1/8)*(2*60) = 15
- Operator pose also correct: 20

Total: 42.5

### Example 3. 
Crowd is 7, all are male.
- 7 people in the crowd: 10
- 6 male as female: (1/7)*(6*-60) = -51.4
- 1 male as male: (1/7)*(1*60) = 8.5

total: 10 - 51.4 + 8.5 = -32.9, but 0 because no negative final scores given.

**Comment by kyordhel** [comment]
Ok, take a look at the pictures! Let's say the operator is Marge.

You inspect the robot's report and you see the following.

![simpsonswrong](https://cloud.githubusercontent.com/assets/8583949/14601578/28dd4a14-0563-11e6-891a-0a5f70ebd562.jpg)

This picture clearly shows only 4 people (and a half) so, according to what you propose, the robot gets Marge + 3 out of 3 in the report = full score.

But then you have this other report from other team

![simpsonsok](https://cloud.githubusercontent.com/assets/8583949/14601633/95771196-0563-11e6-94f2-40bb024e1a60.jpg)

Here the Crowd is complete and properly labeled. You have Marge and 4 out of 4 in the report so full score!

But one failed detecting Lisa and the other succeed. Plus you, as TC, know what the robot could have seen (I don't mind the hardware) from its position 3 meters away from the crowd:

![simpsons](https://cloud.githubusercontent.com/assets/8583949/14601695/f2631a12-0563-11e6-8fbb-84b809e551e9.jpg)

I see no implementation considerations here and as TC we don't give a single (Donald) Duck about robot's hardware or software. Is a *family picture* problem: robot see the whole crowd or not. If robot has super awesome lenses and needs to step back, is **its problem**, not ours. That's why, in the example, we score with a Marge + 4 counting, because if you can't see the whole family, you don't deserve complete score.

**Comment by kyordhel** [comment]
Loy,

I don't get where the 260 comes from. This people counting scoring is for just the crowd part of the test. The rest remains untouched. 

In the current version of the scoresheet it says "Correctly state the number of man in the crowd" and "Correctly state the number of woman in the crowd" so, instead of that we add the scoring from the report. Is about 20 points, max 40.

And I am even more confused now. I think we are discussing for something we both agree.

**Comment by LoyVanBeek** [comment]
I updated my comment to not mistake the *'s for formatting but for math. That's what messed up with the 260 there. The total score for the challenge is 150 points, 10+20 are given for operator stuff, so it should be 120 points, divided over all persons. Also reflected in the updated comment. 

As above, if the robot is not smart enough to turn and take a look for Lisa in the first picture above, I don't agree it deserves full score for stating the crowd size. Yes, it counted all in its field of view, but that's not enough: take a look around!

**Comment by kyordhel** [comment]
I apologize for any further offense (none made but still) but the scoresheet looks really confusing now. Shall I correct the file commenting your lines JIC you don't like them?

Also, the operator should not be scored as part of the crowd since detecting operator's gender may be performed during training and, even if the robot cannot locate the operator, still may have stated their gender correctly. Back yo our beloved family.

The operator's (Marge) gender is wrongly identified during training:
![marge](https://cloud.githubusercontent.com/assets/8583949/14604359/7c48c60a-0573-11e6-8293-3f873270b7ee.jpg)


But later, during recognition, is correctly labeled, though Marge wasn't identified as the operator.

![simpsonsoper](https://cloud.githubusercontent.com/assets/8583949/14604384/a4177cf8-0573-11e6-8c66-6f06baa4cd43.jpg)

In this case, no points are granted for stating operators gender. Poses are also not stated (too bad), however, in the crowd 4 out of 5 genders are correct, thus they should be scored.

Best!

**Comment by LoyVanBeek** [comment]
Please update the scoresheet indeed. 
These examples could go into the rule book as well BTW.

**Comment by kyordhel** [comment]
They should, or we can enable the wiki of this repo and refer to it for detailed explanation in the rulebook. 

Hope there are no copyright problems for using the yellow family.

**Comment by kyordhel** [comment]
Loy, it's done. I don't think it can be simpler or more specific without adding 90 pages of explanation. Check if you like it for closing this issue.

**Comment by LoyVanBeek** [comment]
Thank you very much. We were definitely heading for the same thing. I will change the scoring though, as getting all genders correctly is more than twice as hard than counting faces. I'll change to 80 points for getting all genders correctly and 10 for counting

**Comment by semeyerz** [comment]
In my opinion we should give more points for the actual recognition of the operator.
Right now we give 100 points for gender recognition, 20 for pose and only 20 points for the actual recognition of the operator.
This makes this task really focused on gender recognition.

**Comment by LoyVanBeek** [comment]
Gender is easier to guess. 
Out of pose, gender and face recognition, I think gender is the most difficult. 
But I'm open to suggestions.

**Comment by kyordhel** [comment]
We have been finding the operator since 2009. In fact, since Who is Who (an later, Cocktail Party) the robot needed to find the operator not in a crowd but in a whole room. Check old rulebooks and there were no more than 200/1000 points for that, while now is 20/150.

Problem solved since then. Granting more points would be stepping back.
