### ISSUE TITLE
Check collision avoidance in all directions

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#160]
During RIPS and Navigation test, the robot is being tested for collision avoidance when navigating forward. However, during many tests robots go backwards or side-wise (those which can). It is important to check safety in all movements.

Following is advised (for RIPS):
- Check collision avoidance when navigating backwards.
- Check collision avoidance when turning
- Check collision avoidance when navigating left-right (omni-directional robots only)

**Comment by LoyVanBeek** [comment]
But then again, humans don't do this either, but that doesn't means robots should neither... 

Making the robots go backward or sideways won't be easy either.

**Comment by kyordhel** [comment]
Yes, but robots are not humans, so we can't expect them to have the same _rights_. I'm not saying that we must test this for Leipzig, but we should aim to that direction. It won't be easy for sure and most teams won't like it, but neither they liked the emergency button at the beginning.

Thinking in an environment with children/blind people, the robot must be the one who takes care of them at any time. I don't know when a 3yo will be spying me from behind, so, if I know there are babies around I take extra precautions.

**Comment by LoyVanBeek** [comment]
This was addressed in https://github.com/RoboCupAtHome/RuleBook/commit/c14658cb2df68080447172854dcef0879202033e according to our discussion
