### ISSUE TITLE
Door opening: make a test panel

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#162]
We really want robots to be able to open a door. Its included in navigation  and in manipulation but nobody even tries. 
Can we come up with some road map for door opening that will lead up to opening any door in a few years?
E.g.
1. door with a brightly colored, easy to grasp handle. No lever needed, just pull without even rotating the arm and the door should open.
2. Same sort of handle, but the gripper will have to adapt to the rotation of the handle as the door rotates. 
3. Handle is not bright anymore
4. Standard handle for a normal shop
5. First rotate the lever like a normal door.

**Comment by kyordhel** [comment]
Kinda solved by now. Closing
