### ISSUE TITLE
Categories & commands in EEGPSR

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#168]
Add categories to EEGPSR and allow teams to choose a command category. Categories are related to:
- Object manipulation:
  - Serving an order
- Human-Robot Interaction:
  - Learning person name/face and later find them in a room.
  - Fetching order

Also commands will be more open, leaving the implementation to the teams. For instance, if a person asks for a breakfast, is up to the robot how to serve the breakfast, either serving cereal with milk in a plate (great score) or just place a bottle of juice (few points).

**Comment by LoyVanBeek** [comment]
Can you take a look at the comment? Why mention the custom operator here specifically, can't we make it part of the continue rule and give that a bad score?

**Comment by LoyVanBeek** [comment]
Also, can a team choose the same category 3 times? Of do they need to have a different category for each team?

**Comment by kyordhel** [comment]
The custom operator is mentioned explicitly because otherwise the team can't operate the robot, it's not allowed. We could modify the Continue Rule but honestly I don't want to see teams jumping the fence to shout some commands and finally end with the QR. GPSR/EEGPSR heavily depend on ASR, that's why a custom operator was added in the beginning, but I'm more into removing custom operator than modifying Continue Rule.

Acout categories. Yes, teams can choose solve only CatX. Scoring is per ability so if the robot already found a person and follow them, it won't score again for doing the same. With some luck you may get different commands (e.g. Cat1 serve breakfast first, then open the door) but there are much more chances of an higher score if team choose something different.

**Comment by LoyVanBeek** [comment]
OK, maybe state this even more explicit then. I'll do that

**Comment by kyordhel** [comment]
Test is quite complex as it is. I'll add later all explanations in the appendix.

**Comment by LoyVanBeek** [comment]
OK, can we close this issue?
