### ISSUE TITLE
Data collection storage

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#171]
What would be a good place to store the collected data? I originally though to put the data in [git lfs](https://git-lfs.github.com/) but since the data is static, this doesn't make too much sense. 
An FTP server would be better or some other large file storage. 
The largest file collected at the RoboCup European Open 2016 is about a whopping 7 GB in size.

**Comment by kyordhel** [comment]
What about uploading it to the @Home site, or to a server like Mega and put the link in the @Home site. @dirkholz any idea regarding this?

**Comment by johaq** [comment]
No data collection anymore in the rules.
Closed.

**Comment by nickswalker** [comment]
For folks who come across this later: sharing data is of course still encouraged. It looks like Mega worked fine for @LoyVanBeek's needs. Additionally, you may want to consider one of the many scientific data archiving services out there. These issue DOI's and handle versioning too, making your data easier to cite for future users. Some also integrate with funding agency databases, if you have reporting requirements for government funded research, etc..

https://zenodo.org (50GB max)

https://figshare.com/

https://datadryad.org/stash (300GB max)

I've found zenodo easy to use so it's what I'd recommend.
