### ISSUE TITLE
[Brainstorm] Spoken directions

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#177]
When I tell a human to go somewhere or give directions, I say for example "Go to the end of the corridor, then to the left and the second right" 
This could also be interesting for the RoboCup

**Comment by swayshuai** [comment]
Ahhh, I have seen a paper written by Prof. Kollar in this spoken directions. It has its difficulty in language understanding, and grounding. Very hard.... Here is the link of the paper. [http://www.media.mit.edu/cogmac/publications/kollar10.pdf](url)

**Comment by kyordhel** [comment]
Something related with *Help me carry* and a possible test for #261

**Comment by johaq** [comment]
Could be added to the roadmap but not for this year.
