### ISSUE TITLE
Make procedure for tests inside and outside very clear

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#187]
Some teams were unsure about the procedure of starting a challenge. It should be 100% clear:
# Inside the arena
1. Prep your robot at the designated setup position, close to the actual start position
2. Once the previous robot is done, you push, teleop or carry your robot to the correct position
3. When the referee says so, you push a single button or give 1 speech command to the robot and from then, its on its own
# Outside the arena
1. Prep your robot outside of the arena
2. Knock the entrance door when the robot is ready to start
3. After a little time, the referee (and not a team member) opens the door and the robot must drive in. The robot may have to wait for a couple of minutes, as the referees ready the arena and themselves for the test.

**Comment by kyordhel** [comment]
Not quite, since tests like *Follow me*, *Tour Guide*, *Restaurant* and the one described in #261 require no door. Standard procedure is already defined in the General Rules, but for time constrains the robot does not enter the arena in most tests anymore.
