### ISSUE TITLE
Arena requirements in rulebook

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#188]
1. Decorations etc of which we now have a list
2. Require that the inside of the arena can talk with the outside, which makes starting a challenge easier. You can easily check whether the robot is ready

**Comment by swayshuai** [comment]
The width of the doors......orz

**Comment by LoyVanBeek** [comment]
I think there is a vague requirement saying 'standard door width in the hosting country' or something. 
Some minimum dimension should indeed also be specified.

**Comment by kyordhel** [comment]
There is a vague rule saying that the arena uses the specifications of a standard apartment in the host country. That's USA standards in USA, European standards in Europe, and a fountain in the courtyard in Mexico. 

I don't need a rulebook to take off my shoes and use sliding doors in Japan for entering in a room with a 50cm tall table. Therefore, I think no robot should adapt to a rulebook, but to the environment.

**Comment by LoyVanBeek** [comment]
https://github.com/RoboCupAtHome/RuleBook/commit/96f43639a2289198fa72742095394c8a0c7e314c adds suggestions for arena decorations
