### ISSUE TITLE
Expect robots to behave like a human when rules are unclear

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#189]
We want robots to do the logical thing to do. 
It should not be necessary to state that the robot should face a table when attending it in the Restaurant challenge, for example.

**Comment by kyordhel** [comment]
Totally agree on that, but this will require a lot of common sense and somehow enters in conflict with what was described in #201

**Comment by LoyVanBeek** [comment]
Agreed.

What this stems from is a case where the command for the robot was: "Go to the living room and look for an apple", or something like that. The robot went to the living room, then straight back t the kitchen because that is where the apples were supposed to be by default. There was no apple in the kitchen...
I ended the discussion on that with "What would you do?"

Same goes for the restaurant challenge: to 'be at/reach a table', you should face that table, if you are going or should be attending that table. I don't want to add that line to the rulebook, because attending the table should imply that you must face that table and don't just stand beside it.

**Comment by kyordhel** [comment]
I am adding Milestone for NAgoya 2017 to this issue. General rules must show the following rule (to be added in future pull request):

> Unless stated otherwise, it is expected that the robot always behave and react in the same way a polite and friendly human being would do. This applies also to how robots should address the problems in order to solve the assigned task, including addressing people, serving meals, storing the groceries, cleaning, arranging stuff, etc. As rule of thumb, ask your closest non-scientist neighbor to solve the task and take notes.
>
> Keep in mind that the goal of RoboCup @Home having robots interacting with real people in domestic environments. This means that the average user will not know any specific procedure on how to operate the robot, but they will interact with it as with any other human being.

**Comment by LoyVanBeek** [comment]
Do you make the PR for this or do I?

**Comment by kyordhel** [comment]
I'll do.

**Comment by kyordhel** [comment]
Solved in #268
