### ISSUE TITLE
Require to reach tables to within manipulation reach

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#190]
Just like in the navigation test when a waypoint is blocked and the robots must still need to reach some thing to grab something from it. 

Attending a table for certain means being able to put some food there or face it to take an order.

**Comment by swayshuai** [comment]
Agree. And I think it means the robot should face to the waypoint

**Comment by kyordhel** [comment]
For restaurant, I wouldn't grant any point during the training phase, and for the delivering phase score if

a) there is no doubt the robot is facing the customer that placed the order (as with Sergio that has no manipulator but a tray)
b) the drink/combo is placed in the table.

That's it.

**Comment by LoyVanBeek** [comment]
In a restaurant, if I have to get out of my chair to get my order, its a very bad waiter. Same should apply for the robots.

**Comment by KathrinEvers** [comment]
What do you mean by training and delivering phase? I would give points for reaching/facing the person that asked the robot to come and then for correctly understanding the order (rephrase), then of course choosing/grabbing the right object, maybe even for attempting to grab the right one when it's obvious that the recognition has worked. Is all of that training phase for you?

**Comment by LoyVanBeek** [comment]
Training (in restaurant challenge) means learning where the tables are.
Delivery is bringing the orders, but before that(and after training) the robot must also take the orders (a separate ordering phase)

During training, we should not give (much) points. Only when the robot proved it actually learned the positions of the tables, it should get some points. 
Proving it learned a position is done by going there when command by the location name. 

Or course, we can give a few points for going to a table to learn the location (e.g. after following it), but only giving a significant amount of points for going there again after being commanded so.
