### ISSUE TITLE
Require teams to have a visualization on the TV or projector

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#192]
Just put up your RViz to show what the robot is seeing. Don't visualize everything to save data, but show at least something.

**Comment by swayshuai** [comment]
It is not easy. To show something in rviz using the TV, we must have a ros server on robots, and a rviz client on another computer which can connect the TV.
Then we must make sure that WIFI IS AVAILABLE.

**Comment by LoyVanBeek** [comment]
Definitely. Please see https://github.com/RoboCupAtHome/RuleBook/pull/182#issuecomment-230121173

**Comment by kyordhel** [comment]
Not necessarily RViz but it should be straightforward. I mean, how many engineers do you need to setup a projector.

How are we going to couple this with @Home SPL

**Comment by LoyVanBeek** [comment]
What is the problem with SPL in this regard? 

Of course, it doesn't have to be RViz, but something interesting at least. What I want the audience to see and understand is that, for example, the robots have a very limited view of the world.

**Comment by fpolster** [comment]
I like the Idea of using the TV to display information for the audience, but I think live robot sensor data has some inconveniences e.g. additional setup time for teams needed and a big increase in wireless network traffic. 

My idea would be to give the audience some information on the test like:
 - short description of the sub-task 
 - how much time is left for the try 
 - check boxes to signal accomplished sub-tasks (could be extended to scores)

**Comment by kyordhel** [comment]
After watching some old videos (2009~2012) I realized that more than any screen, a robot solving a household task is awesome enough to have the audience entertained.

Regardless how advanced your mapping algorithm for outdoor navigation may look on screen, a robot taking out the garbage or flipping a pancake will win the audience (even though is not half as challenging than the former).

**Comment by LoyVanBeek** [comment]
So not TV required.
