### ISSUE TITLE
Advise teams to record video

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#193]
Helps solving disputes. The referees are (still) human and see tens of tests a day and cannot remember exactly what happened. 
Th referees are still right though, we decide what e.g.  is good or close enough.

**Comment by swayshuai** [comment]
Can venue provide wireless loudspeaker to make sure everyone can understand what robots say during the test？

**Comment by LoyVanBeek** [comment]
This is usually the case, but there is always some trouble with the wireless transmitters that have to be attached and plugged in to the robots. 

But regardless, it still doesn't help in remembering what happened in in every of dozens of tests.

**Comment by kyordhel** [comment]
Such video recording was not necessary in former years. Maybe we should create scoresheets that are Referee and Team proof. Obvious to score, and have a workload loose enough to prevent referees from fall asleep during tests.

**Comment by balkce** [comment]
It helped this year. The judges are human, and even with fresh eyes some
things may slip by. What Loy proposes seems good to me: advise to record,
but the judge has final call.

**Comment by LoyVanBeek** [comment]
The video recordings have helped a few times this year, also during the European Open. 
We want robots to be faster and I can't have my eyes on both the robots and the scoresheet. 
The scores are only debatable if you have evidence, and video can be good evidence for that. 

I do agree what we shouldn't go the Russian 'dashcams everywhere' route though.
