### ISSUE TITLE
More PDF reports

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#194]
These PDF reports are very handy for the referees to score things with and for later reference; we should implement that where possible. 

Could be used for:
- SLAM-generated maps
- Waypoints on the map (both teached by the teams beforehand or recorded by the robot during a challenge)
- Paths the robot has taken
- Obstacles encountered
- Algorithms or packages with their settings used

**Comment by swayshuai** [comment]
It is a good idea, but it may not easy to generate PDF about paths or something. 
Maybe we can provide teams with some PDF toolkit (in python?).

**Comment by LoyVanBeek** [comment]
What at least TechUnited does is to simply generate [HTML with e.g. PNG images and print that into PDF. ](https://github.com/tue-robotics/tue_robocup/blob/master/challenge_manipulation/src/pdf.py)
A previous team member tried generating a PDF with some C library and got really sad :-). 

We can provide some hints and recommend libraries indeed.

**Comment by kyordhel** [comment]
Please no more PDF report files. We want robots succeeding in tasks in such a way that a report is not needed. For instance, in restaurant, if a robot can go back to a table and place a drink on it, I have no doubt it learned where the table is. That's the performance I want to see, no a poor performance that requires more reporting to be scored.

Team pumas use C++ (before it was C#) to generate a TEX file that is compiled using LaTeX. I see no problem in giving toolkits to teams as long as the RC federation pays me for the coding.

**Comment by balkce** [comment]
There are some tasks that aren't obvious to know that the robot achieved
them, other than through convoluted testing (we know it learned where the
table is after it grabbed an object and delivered it there). The reports
helped this year it seems (the tests I judged didn't require them so I
wouldn't know); if there are tools out there already, pointing teams
towards them seems a relatively easy thing for us to do. No coding required
from our part.

**Comment by LoyVanBeek** [comment]
The PDF reports are handy where they are used now (manipulation+obj. recog. & person recognition) and could be useful to compare the execution of a test in more detail later, regardless of points per se. 
For the following and guiding, it could be interesting to compare the paths the robots took on their way back. Then you might spot that one robot took a shortcut for example, or did not follow its exact route when following. 
It doesn't matter for the scoring, but its interesting none the less. 

For Restaurant it does not make sense indeed. 
During (EE-)GPSR, the generated plan could be displayed in a report so it can be scored later, regardless of the task execution. 
A team with a good planner can still fail during the execution, but perhaps get some points for a good plan. Other teams can observe that as well andSame goes for other use that planner for next year.

**Comment by kyordhel** [comment]
Loy,

How is the state of PDF reporting for 2017 rulebook? I don't see the reporting anymore.

I think is going to be impossible to check reports from three sub-leagues.

**Comment by kyordhel** [comment]
None of those tests are there anymore.
Closing
