### ISSUE TITLE
Reduce time spent on 'solved' tasks

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#200]
Focus on the tasks that most teams still struggle with. 
For example: Navigation, going to some defined waypoint is something the large majority of the RoboCup@Home robots can do. So, don't test that specific skill 3 times but focus on other stuff. 

To do this in an informed way, we need some **statistics** from the score sheets.

**Comment by swayshuai** [comment]
Do anyone have the score sheets this year?

**Comment by LoyVanBeek** [comment]
Yes, @swachsmu has them and would gather those statistics.

**Comment by kyordhel** [comment]
We don't need the scoresheets, we have the scores per test and that would suffice to tell no team has mastered any skill yet.

**Comment by LoyVanBeek** [comment]
True, but I think all the teams showed that they can detect a door has closed and drive via an alternative route. 
This takes time, that we could spend on other interesting stuff.
