### ISSUE TITLE
Test with larger grammar

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#202]
Speech Recognition currently works with 50 predefined questions with 50 predefined answers.
Later, we ask the robot complex commands, which are not fully predefined but at least fit a grammar. 
The speech recognition test should also test this, as passing this test would then be closer to what is needed in later tests (GPSR and EE-GPSR)

So, instead of the 50 questions, have a smaller set of fully defined questions but also questions like:

```
- What is the <N>th largest <city|river|lake|...> of <Brazil|China|Germany|Japan|Canada|...>?
- Who is the <main character|main location|...> in the <book|movie|...> <...>
```

Etc

**Comment by balkce** [comment]
I like this.

In fact, I would go as far as removing the use of fully-defined questions altogether, and stick with only grammar-based questions for this test, since more than half the teams came away with some points for this test.

This seems to be a good step-forward.

**Comment by kyordhel** [comment]
I had some discussion with Komei about this. He want a new generator that is context-sensitive and perform an environmental planning (world model updated after command execution) so questions and new commands can be congruently generated accordingly.

About the predefined questions, I agree in that they are useless now. Speech recognition is not the issue, but the speech understanding. Plus, having teams tied to predefined grammars caused more trouble than help.

**Comment by balkce** [comment]
I actually think that a pre-defined grammar for this test is fine.

What Komei suggest seems more appropriate for GPSR.

C

**Comment by swayshuai** [comment]
I like this idea though we will have more work to do with answers. :)
Maybe we can have more “home-related” questions， such as questions about furniture, food, soorts?
I'm curious about how TC could get so many questions previously .

**Comment by LoyVanBeek** [comment]
Googling for 'trivia questions'. 

Honestly, I don't really care for the actual answers, as long as the robots make clear they understood the question 100% correct. Eg. "What is the 2nd largest city of the Netherlands?" --> "In the Netherlands, the 2nd largest city is a bit smaller than the largest city". 
It does make for a weird scene to the audience though, so the robots should give real answers. 
If we have grammar early enough, the teams can google those themselves (or let the robots do it on the fly).

**Comment by balkce** [comment]
Maybe have minimal points for just hearing the question (repeating the
question back to the user) and have much more points for actually answering
it via googling it or having a local knowledge-base, providing evidence
that it actually understood the question.

**Comment by kyordhel** [comment]
My idea was to change the predefined questions to GPSR commands and, as answer, the robot should explain how to execute the command.

*Robot, could you bring me a cold beer*

1. Go to the fridge in the kitchen.
2. Open the fridge.
3. Find a beer.
4. Take the beer.
5. Come back to the living room.
6. Find Mauricio.
7. Handover the beer.

Finally, I would penalize with 5000 points the robot for leaving the fridge open.

**Comment by balkce** [comment]
Ok. Just don't get too strict if the description is not "granular" enough
for you: e.g. the step "find the beer" is kind of already included in the
step "take the beer". And if you don't agree, I bet teams would make a fuss
about the whole "what does 'take' mean" and I don't want to get
philosophical during the competition.

**Comment by swayshuai** [comment]
Mau's idea sounds great! Maybe we won't call this test as "speech recognition", but "High Level HRI Test"
In stage I , we test nearly every fields in robots' abilities like manipulation, expect language understanding and task planning. I think we can have a try in this "high level HRI test". First five questions in  'trivia questions' for speech recognition, and another five questions in 'home-task' for language understanding and task planning.

**Comment by LoyVanBeek** [comment]
I really like that idea. 
Also, still split the scores: little bit of points for repeating the question, many for doing this understanding + planning. 

An addition could be to ask the robot "What do you mean with 'Take the beer'?" :arrow_right: "I go to the fridge, open the fridge, look for a beer and grab it."

**Comment by balkce** [comment]
Sounds good.

The only thing I would add is that we do need to put forward an actual
grammar for both cases (trivia and language understanding).

Expecting teams to use an open grammar, from what I saw in GPSR, is
unrealistic right now, even more so in Stage 1. And I'm more interested in
understanding and planning.

Maybe we could put a roadmap to use open grammar in the following years,
once we see teams are able to do this.

PS. What I mean by "open grammar" is a grammar that may change from the
sample that we put up in GitHub, with more actions/questions that aren't
there. Planning for the unknown is a Stage 2 skill in my opinion.

**Comment by LoyVanBeek** [comment]
For a roadmap, we could start with a grammar with a output space of e.g. 1000 commands, then 10.000, then 100.000 etc and finally completely open. ('open' is relative, I won't ask it -for now- to 'build me a spaceship')
Some approximate limit on the amount of words in a command would also be nice I think, as I could not even finish my sentence to one of two robots. The command simple took too many words :disappointed: 
I'm not sure what a reasonable number is and whether that is the way to state that complexity (probably not).

**Comment by balkce** [comment]
Agreed.

**Comment by LoyVanBeek** [comment]
Another idea, if we decide to go with the High Level HRI test, is to allow teams to skip e.g. the speech recoognition from audio-part, eg. after it fails the first time. Of course, this gives a LOT less points.
Then, the robots gets a command given in a different way but must still do the understanding and planning.

**Comment by swayshuai** [comment]
Oh, continue rules again......

If we decide to use continue rules to skip the audio-part, we can have an option in harder sentences. For instance, we can give the teams chances to receive an "open grammar" sentence. This sentence isn't simply generated by grammar generator. Our TC member can regenerate the sentences. For instance, the grammar generator gives a sentence "grasp the apple from the dinning_table"; we can regenerate the sentence as "hi robot, how can you take the apple from the dinning table" . If teams fail, we have continue rules :) 

By the way, I have no idea with how to test sound localization in this High Level HRI test. Any ideas?

**Comment by LoyVanBeek** [comment]
We did not allow the continue rule in the Speech Recognition test, because then, there is no test left.
But with High-Level HRI, the most interesting stuff happens after speech recognition. So a contnue rule would make sense still. 

Regarding Sound Source Localization: Before giving the actual command, I can say "Hi robot..." then the robot must look at me and then I say the rest of the command. 
More or less how you would ask a person something in a noisy environment.

**Comment by LoyVanBeek** [comment]
Another option would be to have the robot answer questions about the environment, e.g. "Where is the fridge" or "Where did I leave my keys/glasses/phone/wallet?" etc.  That is a real-life feature and also requires some understanding of the world.

**Comment by kyordhel** [comment]
After checking the Pull-request #213 I can see that no big grammar is required. In theory, all ASR should be able to handle that. Yet, even with fixed grammar NLP is a big problem since it will require removing the sound-source location part, as well as define a nice dialog mode. Do we want this?

As is, the test will require answering 16 questions, reason for which using the Continue Rule and other interfaces makes no sense (we may further adapt it). Plus, the rulebook says that we will provide the list of questions. Here we have two options,
- give the list of questions as currently stated, which will errase the NLP since the question are fixed, or
- we (aka I) modify the test and carefully  design a grammar so NLP is required to solve the test

**Comment by LoyVanBeek** [comment]
Why does NLP require to remove SSL?

**Comment by kyordhel** [comment]
It does not *requires to completely remove* SSL, but 8/8 makes a 3-tries test quite long and complex for adding NLP to it.

Either we may:
- Make it single try and add a (robust) story and more NLP, while keeping SSL.
- Change from 8/8 to 5/5/5 ASR, SSL, NLP respectively

Properly designed, NLP is very challenging and almost no team has a robust one (it must be reusable for a Stage2 test), so that should be reflected in scoring. Also, while ASR and SSL must not allow Continue Rule, is a different story for NLP.

**Comment by LoyVanBeek** [comment]
Having a different sort of split would be my suggestion as well. 
What sort of questions do you suggest for NLP then? With coreferences or something else entirely?

**Comment by kyordhel** [comment]
For NLP anaphora and ellipsis resolution are almost mandatory, while dealing with inference requires to set a specific domain (targeting all @Home is too much for now). Contextual Reasoning is always desirable but hard in a text that has no context change.

Here some examples:
- [Storing Groceries] Put the drinks on the middle shelf, the fruit goes above, and the snacks with the cookies [at the right].
- [STT&CU] First place the carpet, then the plate on top of it, right in the middle. After that place the fork at the left of the plate, and the knife and spoon on its right.
- [Restaurant]
  - _Customer 1:_ A vegetarian burger and beer combo for me
  - _Customer 2:_ For me... the same, but with beacon, please.
- [Breakfast] Bring me some (scrambled) eggs with toasts and a coffee. Oh, and please add two sugar cubes to it.
- [RoboNurse] There are two red pill bottles in the shelf. Bring me two pills from the big one and one from the small one.

**Comment by balkce** [comment]
I think the original idea of explaining what the robot would do given a GPSR command is more than enough for the NLP part. As stated, the NLP proposed right now is quite complex, and I'm pretty sure no team is able to do it. Maybe put it as part of the EEGPSR categories if need be, but for a Stage I test is too cruel.

**Comment by kyordhel** [comment]
@balkce I was just answering @LoyVanBeek question, not actually proposing such change.

_If you ask **me**_, I think the inclusion of NLP must be deeply discussed first in EC to get an orientation. _Do the league really want to focus NLP?_ I don't think so, or at least, maybe only in SSPL. Considering the techniques _à la mode_, big amounts of data will be required in the chosen domain to train these systems. More important, dealing with NLP requires the robots to be operated by people from the audience because if we provide any kind of example set, corpora, or grammars, it won't be dealing with natural language, but fooling ourselves with robots recognizing expected data created for that purpose.

**Comment by LoyVanBeek** [comment]
I do think the examples @kyordhel mentioned are useful ways to command any personal assistant type device, be it a robot, smartphone or Alexa-type device. It is very difficult though and I haven't seen systems that can handle this complexity yet. 

For now, doing commands like "Where is the {object} (e.g. table -> kitchen)" is good for me. 

We can however define a roadmap of ASR/NLP/NLU complexity and increase difficulty yer by year. If we put that roadmap in the rulbeook, teams can develop those techniques before we define the challenge it is going to be used in.

**Comment by komeisugiura** [comment]
I agree with defining the roadmap for SLU/NLP/NLU.

ASR in the strict definition is not going to be the main target of RoboCup@Home. At least for SPL robots, using third-party ASR engines is reasonable since APIs are provided.

As @kyordhel suggested, accurate ASR will be sooner or later available for robots, so putting more emphasis on how the recognized text should be understood will be more important in the coming years.

**Comment by LoyVanBeek** [comment]
Agreed. I would even be OK with operators speaking into their own smartphone/smart-speaker/Alexa and then having the robot execute the spoken task.

**Comment by LoyVanBeek** [comment]
I created a separate issue to define a roadmap, see https://github.com/RoboCupAtHome/RuleBook/issues/217

**Comment by LoyVanBeek** [comment]
The SPR test clearly addresses this issue. The roadmap on what NLP/NLU tasks are to be done in the future are in #217
