### ISSUE TITLE
Robots' abilities in Manipulation & O.R. Test

### ISSUE THREAD

**Issue by swayshuai** [RoboCupAtHome/RuleBook#205]
In this test, scoring in robots' abilities is a good idea. In my opinion, these abilities should be reflected：
- [ ] grasp an object (basic)
- [ ] grasp many objects (manipulating speed)
- [ ] grasp an object besides the shelf (avoid obstacles when manipulating)
- [ ] grasp a lying 'wide' object on the floor, like bottles (different postures to manipulate)
- [ ] grasp an object which is very high or very low (manipulating space)
- [ ] grasp a small object
- [ ] grasp a strange object (like cloth)
  ......

Robots' Abilities  in object manipulation need to be improved.

**Comment by LoyVanBeek** [comment]
Definitely. Also see https://github.com/RoboCupAtHome/RuleBook/issues/76.
Could you add those there as well? Then I can close this issue and we have everything in 1 place.

**Comment by swayshuai** [comment]
Other abilities mentioned in #76 . 

- Grasp something from a bin (with like 8-cm high borders)
- Place the object face-forward (so you need bi-hand manipulation or at least re-grasp and plan)
- Manipulate a switch
- Manipulate a big object so you need 2 hands.
- Arrange the groceries from the shopping bag into a shelf
- Taking out the plastic bag from the trash bin.
- Use a ladle to serve soup from a pot
- Flipping omelette/meat
- Whipping eggs or cream with a whisk (manually).
- Mop the floor / Brush the floor (broomstick)
- Pressing buttons in a keyboard (dialing phone, copy machine, calculator).
- Handling digital (flat button) control panels (microwave, digital washing machine, conductive stove).
- Picking something out of a box/bag
- Grasp a soft cloth is hard enough... I'd love to see your's as well though.
- Grasp a old-style phone horn
- Wipe a table/shelf with a cloth (actual use case from @RobotRose)
- Grasp a towel from a hanger
- Pick up a pen
- Pick up a pill
- Pick up a tray/plate
- Pick cutlery from the drawer
- Grasp a moving object (with may be something simple for starters)

I'm trying to rearrange these abilities.

**Comment by johaq** [comment]
This is for the roadmaps. Could be already added to the temporary version: https://docs.google.com/document/d/1-QNMROnmVhEll8ZL-iTbqeeAhRjrcUbbdLcupx_hC2U/edit?usp=sharing
