### ISSUE TITLE
Remove references to @Home Wiki

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#21]
Nobody is paying attention to the Wiki, is outdated and teams always have trouble to register, login and update.

I have removed wiki from the "Setup & Preparation" and "Concepts behind the competition", however there are wiki references in the Rulebook.

**Comment by dirkholz** [comment]
Unfortunately, that is not a solution!

We have to use a wiki, or rather a place teams can (MUST!) add team information, publications etc.

But I totally agree that a stupid non-functional old wiki hosted in Aachen is not the solution and I think we need something new. Perhaps there is already stuff like this in the google apps that we could use with our @home account. I'll check that!

**Comment by LoyVanBeek** [comment]
How about https://github.com/RoboCupAtHome/RuleBook/wiki?
Never used it, not sure if thats an option with permisions etc.

**Comment by kyordhel** [comment]
Well, the RuleBook wiki should be for further explanation of the rulebooks. The @Home league contains the RuleBook, not otherwise. It may be well a "quick" solution but not optimal.

I'm with Dirk, we may try those apps

**Comment by LoyVanBeek** [comment]
@dirkholz @kyordhel How are we with this? I see the latest edit to the wiki was this year, so it is still in use.

**Comment by kyordhel** [comment]
I'm not sure who is responsible/in charge of wiki. Create an account takes long time (some weeks), also most information is outdated (teams that no longer exits, broken links, etc.).

I'm not saying that current wiki is dead, but it clearly doesn't met our needs. I'm open to suggestions.

**Comment by LoyVanBeek** [comment]
One suggestion is the wiki here at GitHub. 
Another is to make the original AtHome wiki better somehow. What of our needs doesn't it meet?
