### ISSUE TITLE
RobCup@Home 2017 deadlines

### ISSUE THREAD

**Issue by tkelestemur** [RoboCupAtHome/RuleBook#212]
Hello,

I couldn't find qualification submission deadline for this year's competition on both website or rulebook.
Is it announced? or should I wait?

**Comment by LoyVanBeek** [comment]
Hi @tkelestemur, the Organizing Committee of the competition sets these deadlines. 
You can ask them at OC@robocupathome.org. 
As I'm only TC I do not know the exact date, but I expect it to be somewhere early February.

Such information can be found on http://www.robocupathome.org/call-for-participation when it is updated for next year.

**Comment by kyordhel** [comment]
Dear Tarik,


No deadlines has been set yet since the Trustees are still negotiating the terms for SPL robots. You may expect the deadlines will be something like previous years, and most likely to be announced on the first days of January.


With kind regards,

Mauricio.

________________________________

**Comment by tkelestemur** [comment]
I just saw that Call for Participation is announced with deadlines.
Thanks for you replies.

**Comment by LoyVanBeek** [comment]
> Call for Participation
> RoboCup 2017 RoboCup@Home League
> July 25 - 30, 2017 (Nagoya, Japan)
> http://www.robocup2017.org<http://www.robocup2017.org/>
> 
> http://www.robocupathome.org<http://www.robocupathome.org/>
> 
> http://wiki.robocup.org/wiki/@Home_League/
> 
> RoboCup is an international scientific initiative with the goal to advance the state of the art of intelligent robots through competitions (RoboCup@Home, RoboCup Soccer, RoboCup Rescue, RoboCup@Work and RoboCup Junior).
> 
> The RoboCup@Home league aims to develop service and assistive robot technology with high relevance for future personal domestic applications. It is the largest international annual competition for autonomous service robots and is part of the RoboCup initiative. A set of benchmark tests is used to evaluate the robots' abilities and performance in a realistic home environment setting. Focus lies on the following domains but is not limited to: Human-Robot-Interaction and Cooperation, Navigation and Mapping in dynamic environments, Computer Vision and Object Recognition under natural light conditions, Object Manipulation, Adaptive Behaviours, Behaviour Integration, Ambient Intelligence, Standardization and System Integration.
> 
> The RoboCup@Home league is itegrated by three sub-leagues officially referred as
> 
>   *   Domestic Standard Platform sub-league (Toyota HSR)
>   *   Social Standard Platform sub-league (SoftBank Robotics Pepper)
>   *   Open Platform sub-league
> 
> This message describes the preregistration and qualification procedure for RoboCup@Home League 2017.
> Important dates:
> 
> Feb 5, 2017 Intention of Participation
> Mar 12, 2017 Preregistration and Deadline for qualification material
>                         (Team Description Paper, Team Video, Team Website, Information in @Home Wiki).
> Mar 26, 2017 Qualification announcement
> 
> The qualification procedure consists of the following two steps:
> 
> 
> Step 1) Intention of Participation (strongly recommended)
> 
> The team sends an email to the Oranizing Committee <oc@robocupathome.org<mailto:oc@robocupathome.org>> to indicate your intention to participate in the RoboCup@Home 2017 event, including the following basic information:
> 
> Team Name:
> Sub-league:
> Platform:
> Country:
> Affiliation:
> Team Leader Name:
> Contact information (E-mail):
> Web site:
> 
> Only one platform can be specified per team.
> 
> The e-mail subject should be: [@Home2017-Participation] (YourTeamName)
> 
> Please check the email is encoded in UTF-8 using only the ISO-8859-1 character set.
> 
> **** Deadline: Sunday, 5th Feb. 2017 23:59 GMT *****
> 
> 
> 
> Step 2) Qualification Material Submission (mandatory)
> 
> The team ***MUST*** send an email to the Oranizing Committee <oc@robocupathome.org<mailto:oc@robocupathome.org>> to participate in the qualification process for the RoboCup@Home 2017 event. Please fill in the following information:
> 
> Team Name:
> Sub-league:
> Country:
> Affiliation:
> Team Leader Name:
> Contact information (E-mail):
> Link to a team video:
> Link to a team web site devoted to their efforts:
> Team Description Paper (TDP) attached to the email based on the official template.
> 
> The e-mail subject should be: [@Home2017-Qualification] (YourTeamName)
> 
> Considerations:
> 
>   *   Only one platform can be specified per team.
>   *   All the publications and software to be evaluated for qualification ***MUST*** be in the team’s website.
>   *   The email must be encoded in UTF-8 using only the ISO-8859-1 character set.
> 
> Important Notice:  As platforms are independent, you must send an application email for each platform you want to compete in, specifying different team names in each. Qualification Material (e.g. video and TDP) must match the robot to qualify.
> 
> **** Deadline: Sunday, Mar. 12, 2017 23:59 GMT *****
> 
> 
> 
> Instructions for the Team Video
> ===========================
> 
> As a proof of running hardware, each team has to provide a qualification video. As a minimum requirement for qualification, we consider showing the robot(s) successfully solving at least one test of the current or last year's rulebook.
> 
> [Standard Platforms Only] The robot shown in the video must not be altered or modified in any way.
> 
> 
> 
> Instructions for the TDP
> ===========================
> 
> The TDP is an 8-pages long scientific paper, detailing information on the technical and scientific approach of the team’s research, while including also the following:
> 
>   *   Innovative technology and scientific contribution
>   *   Photo(s) of the robot
>   *   Focus of research/research interests
>   *   Re-usability of the system for other research groups
>   *   Applicability of the robot in the real world
>   *   Brief, compact list of the 3rd party robot's software (e.g. ROS vision should be included, but not OpenCV).
>   *   [Open Platform Only] Brief, compact description of the robot's hardware.
>   *   [Standard Platforms Only] Specify all external computing devices, if any.
> 
> For the TDP, please use the Springer LNAI format<http://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0> used in the RoboCup Symposium submissions and limit yourself to 8 pages without altering margins or spacing. You may download a template for the TDP from here<https://github.com/RoboCupAtHome/TDPTemplate>.
> 
> 
> 
> Instructions for the Web site
> ===========================
> 
> While the TDP goes into detail about the technical and scientific approach of the team’s research, the website should be designed for a broader audience, including:
> 
>   *   Photos of the robot(s)
>   *   Videos of the robot(s)
>   *   Description of the approaches and information on scientific achievements
>   *   Relevant publications (last 5 years, preferably available to download)
>   *   Link to repositories with software for the community
>   *   Team members
>   *   Previous participation in RoboCup
> 
> 
> 
> Evaluation criteria:
> ===========================
> 
> Qualification materials will be judged by the following criteria:
> 
>   *   Team description paper (clarity, scientific contributions, re-usability by the league, applicability in real world)
>   *   Qualification Video (navigation, human-robot interaction, people/object recognition, object manipulation and new features)
>   *   Website (multimedia, publications from last 5 years, downloadable content, open-source software and other contributions)
>   *   Relevant Scientific contribution/publications (downloadable papers and open-source software)
>   *   Novelty of approach (what you do is new for @Home)
> 
> We encourage teams to produce self-explicative videos for a general audience where complex tasks are solved. For Team Description Papers focus on the scientific contribution and avoid brief descriptions of the overall system.
> 
> Note to experienced competitors: Major changes are being done in the rulebook. You may download the latest version from: https://github.com/RoboCupAtHome/RuleBook
> 
> 
> 
> With kind regards, and looking forward to see your team in Nagoya,
> The 2017 RoboCup@Home Organizing and Technical Committees
