### ISSUE TITLE
Storing Groceries inconsistencies

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#219]
I've found the following inconsistencies in the *Storing Groceries* test. Some of them suppose a step back from previous year and require either correction or removal of unused rules, while also afecting GPSR and Stage II tests.

- HRI poorly defined
  - Is not clear what the operator will command the robot to do.
  - Is not clear how the operator will command the robot.
- Shelve specifications
  - It is unclear which shelves will be used.
  - Specifications are outside the range of SPL robots.
- Scoring and Scoresheet
  - There are no points for recognizing operators command (other tests grant).
  - No scoring difference between known/alike objects.
  - Middle shelf grants same points as top/lower shelf.
  - Test violates the _no penalty_ policy:
    - No points given for opening the door, but penalty for requesting help (aka don't even try?).
    - Penalty for false positive.
  - Recognizing + Grasping + Placing = 30pts, while in GPSR is about 10.
  - Unclear scoresheet entry _Every correctly label 2 unknown objects of the same class with the same label in the report file_.
  - Scoring system should be straight forward (e.g. no coring examples needed).

**Comment by LoyVanBeek** [comment]
I fixed most of the issues you listed, but not where I disagree. 
- HRI
  - There is no HRI needed (just a start command or start button, no points for that)
- Shelve specs:
  - All the shelves will be used. 
  - Reach: No robot (from OPL, SSPL, DSPL) will be able to reach all shelves, but will be able to see all the objects in there. They are too slow to put something in all the shelves anyways... A platform differentiation may be needed if we want to correct this, but there's maybe a smaller amount of objects, or a _lower_ but _wider_ shelf to fit the same amount of objects?
- Scoring
  - Only start command, so no points for commands
  - No difference between known and alike objects: we didn't have a difference in previous years either. 2 score-categories (known&alike and unknown) is also easier to divide 10 object classes over. 
  - Previous year also did not have different amount of points for different heights. Makes scoring convoluted as well. 
  - To make the test consistent, there are now more objects in total, thus I reduces the amount of points per object. Perhaps increase amount of points in GPSR or reduce total score here.

**Comment by kyordhel** [comment]
Counter-argument time:

- Starting procedure is OK now.
- I am not sure that Pepper and HSR can _see_ what there is in the two bottom shelves. If by design the robot is unable to _see_ there, those heights should be excluded.
- We still need to specify, from the objects available on the table, how many are unknown, how many alike and how many known. This is more for the referees and OC than for teams.
- For 3 minutes, opening a door and allocating 5 objects seems too much to me. While related, I think that benchmarking door opening and object recognition/manipulation does not fit well. I rather would go for remove the opening door part to get out the best of classification, or to remove the benchmarking and encapsulate the test in a nice story about storing groceries (robot enters arena, gets command indicating table and shelf, and then allocates all similar objects all together, being some of them behind a door or inside a basket).

**Comment by LoyVanBeek** [comment]
- I get your point on the reach and field of view of the SPs and I'm considering it, but if a robot is by design unable to reach certain corners and not see them, that is interesting to know before I buy one. To really compare robots, I want to compare their reach as well. Also, robots are a system, it may always move back to see the complete shelf and compensate small field of view with its base. 
- 3 known, 2 like and 5 unknown objects on both table and corresponding ones in the cupboard.
- I considered awarding 1 minute extra time for opening the door. Not sure though. I don't want to spend too much time on story-fluff, I think its relate-able enough already. The robot should know where the groceries are to be stored without command.

**Comment by LoyVanBeek** [comment]
TODO: 

- [ ] Clear up how to deal with the unknown objects. 
- [ ] Mention tht objects on the table can be occluded somehow?
