### ISSUE TITLE
[Severe] scoring and time inconsistencies

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#221]
I've found severe scoring  and timing inconsistencies in Stage I tests, for instance:

Test                | Time | Score | Task               |
--------------------|------|-------|--------------------|
Help me carry       |  4m  |  150  | 3x re-enter arena  |
Storing Groceries   |  3m  |  250  | 5x pick & place    |
Speech and Prs Rec. | 10m  |  300  | 8x answer question |
GPSR                | 10m  |  250  | 3x random command  |

It seems to me that the rulebook is extremely biased towards speech recognition and manipulation.

Of my special concern is Help-me-carry. I find completely unrealistic that the robot may leave and reenter the arena three times (regarding scoresheet) in 4 minutes, while also it needs to train the _professional walker_, perform manipulation, object recognition, avoid obstacles and move people/furniture (I'm opening issue #220 on this matter). This is, by far, the most complex test and the less rewarding one.

### Scoring comparison table
In the table below I'm presenting the requested abilities and their score in each test

Ability               | GPSR | Crry | SpPR | StGr |
----------------------|------|------|------|------|
Count objects         |  10  |      |      |   0  |
Count objects (feat.) |  20  |      |      |   0  |
Count people          |  10  |      |  10  |      |
Count people (feat.)  |  20  |      |  10  |      |
Follow a person       |  20  |  10  |      |      |
Guide a person        |  20  |   0  |      |      |
Pick object           |  ~3  |   0  |  10  |      |
Pick obj. (hand over) |  --  |   1  |      |      |
Place object          |  ~3  |   5  |      |  10  |
Reach location        |   0  |   6  |      |      |
Re-enter arena        |  --  |   6  |      |      |
Recognition (Gesture) |   6  |      |   0  |      |
Recognition (Person)  |  ~5  |      |   0  |      |
Recognition (Speech)  |  10  |   2  |  10  |   0  |
Recognition (Feature) |  20  |      |      |   0  |
Recognition (obj-a)   |  ~6  |      |      |  10  |
Recognition (obj-k)   |  ~3  |      |      |  10  |
Recognition (obj-u)   |  --  |      |      |  10  |

Abilities marked with a dash are tested in Stage 2, therefore not included in GPSR. Abilities marked with zero are related to the test focus but untested.

### GPSR
From my point of view, GPSR tests integration, so whatever ability is tested there will grant less points than in other tests focusing in it. This is OK. What matters in GPSR is that the task is solved, not how it was solved.

What I find unacceptable is that GPSR require abilities that are not being tested in State I, specially when many of them were almost mandatory in previous rulebooks and quite challenging but with a good degree of success (e.g. finding a [waving?] person in a room).

### Timing
It seems to me that we are asking too much from robots for a 3~4 minutes test. Things turn darker if we consider that TC needs to take care of so many goals three times per robot. Considering the help-me-carry, it is impossible to me to enter and leave the arena 3 times per test for 12 robots (per sub-league) for a test that will be run 3 times for a big total of 72 runs!

On the other side of the specter, Speech and Person Recognition (patched as is now) gives the feeling of being long and boring. In that test, 16 commands must be given to 12 robots (per sub-league) three times for a grand total of 576 questions. I hope the audience feel enthusiastic about it and we have enough drinking water for this.

### Consensus
It is important to reach consensus on how referees are going to score, as well as where the league is aiming. Stage I tests affect both GPSR **and** EEGPSR, so they must be designed carefully.

**Comment by balkce** [comment]
I think most of these can be fixed by assigning a soft limit in the time for each test and then reducing/increasing something inside each of the test so they fit that limit. 

For example: speech recognition could fit if the number of questions is reduced.

**Comment by LoyVanBeek** [comment]
I tried fixing issue #219  and #220 by modifying the scores.
For that, I used my big [skill matrix](https://docs.google.com/spreadsheets/d/1PSWYtbsTVJ_VwJigtwUL6vpzhvJHb_TalWKY1eG1Yms) again to have consistent scores all around.
