### ISSUE TITLE
Questions on the Storing Groceries test

### ISSUE THREAD

**Issue by nohernan** [RoboCupAtHome/RuleBook#229]
Hello,

my team and I have the following questions regarding the Storing Groceries test:

1. An example of putting objects of the same class together in the cupboard is given in the first paragraph of section 5.1. In such an example a new pack of cookies is placed besides an almost empty pack of cookies, does this imply that there might be duplicate objects, in the table and in the cupboard, during the execution of the task?
2. It is not clear when the robot must open the cupboard door, must it be the first thing the robot does? Could the robot ask for the door to be open after grasping an object?
3. In section 5.1.4 there is a numbering list in which item 5 is empty.
4. The sentence "A correct label for these may constitute be" in item 7 of the numbering list of section 5.1.5 is incorrectly formed. A possible fix for it might be: "A correct label for these may be constituted by". This item 7 has a list with three bullets, the idea in the second bullet is contradictory since it suggests assigning the same label to unknown objects within the same class but how we are supposed to get the class of unknown objects.
5. There is a bullet list in section 5.1.7, the last item in such a list says: "Put objects in the table and corresponding ones in the cupboard...", it should read: "Put objects in the table and the corresponding ones in the cupboard..."
6.  Our main concern is: does a shelf in the cupboard only contain objects of a single class? 

Regards,
Noe

**Comment by LoyVanBeek** [comment]
Hi Noe,

1. The test implies (could be made more explicit) that there the are 2 instances of each class: an empty one in the cupboard and a new one on the table. 
2. When to open the door is completely up to the robot. 
4. About the unknown object classes: More or less the same way people may distinguish between unknown people; you might still recognize a person even though you do not know their name (label). We would like the same for robots and objects: recognize that two objects are of the same class and thus deduce that they should go together. 
6. No, most likely both ends of a shelf have different objects, eg. cookies on the left end and juice on the right end. 

When I have some time, I'll fix the grammar issues, but a pull request would also be much appreciated :-)

**Comment by furushchev** [comment]
Hi,

We have questions:

> 1. The test implies (could be made more explicit) that there the are 2 instances of each class: an empty one in the cupboard and a new one on the table.

- What do 'instance' and 'class' mean? I read 'class' as, for example, 'drink', and 'instance' is 'plastic bottle', right?
- Where do you know this information? I looked into the rulebook carefully but could not find any description about this.

> 4. No, most likely both ends of a shelf have different objects, eg. cookies on the left end and juice on the right end.

- Does it mean there are objects which belong to just 2 classes in one shelf?

And we'd like to ask one more question:

- A robot must open a 'single' door (not double door) before starting pick-and-place, right? How is the geometry / type of the door?
(e.g. shape of the knob / position of the knob / is there the door closer? and so on)

Thank you very much in advance!

**Comment by LoyVanBeek** [comment]
Hi @furushchev 
The difference between classes and instances is: "Car" is a class of objects, but the object "my car" is an instance of that class. Object "Your car"  is another instance of the same class. 
So, translating to this test, there are many classes of objects: Coke, Sponge etc. There are 2 instances of each, so Coke 1 (on the table) and Coke 2 (in the cupboard). 

Each shelf will have 2 objects on it. 

We have not (yet?) set any constraints on the geometry of the cupboard door handle.

@kyordhel should we define constraints on the [cupboard](https://www.google.nl/search?q=cupboard&source=lnms&tbm=isch) door handle geometry?

**Comment by kyordhel** [comment]
Kinda nope. 

IMHO, the test is quite straightforward. You have a freaking mess of groceries on the table that must be placed into the cupboard. 

For instance, think you have a nice ceramic pot and some transparent flasks with pasta inside. It make sense the robot would open the pasta bags and pour the content in the appropriate flask (e.g., fusilli with fusilli and not with spaghetti). Guess what the nice ceramic pot would be for? Yes! Cookies! And all the delicious cookies go there. 

Do anyone needs to be instructed on how to arrange those groceries given the geometry of the cupboard and what a class and an instance is? I think, no. Little Amy (who is 3yo) probably does not know those words not what a geometry is, yet she understands from where to steal the cookies. 

Let's not oversimplify the test. We ant robots to do local planning, not to run state machines. 

Cheers.

**Comment by furushchev** [comment]
I understand and agree your philosophy.
I just wonder there can be unfairness between teams who know additional information not written in this rulebook and them who don't.

I still don't get an answer for the question:

> Where do you know this information? (I mean '2 instances of each class') I looked into the rulebook carefully but could not find any description about this.

If this information is from some 'implicit rules' which, for example, only teams who participated previous competition know, I think we must clearly describe them on the rulebook regardless of the philosophy.

**Comment by kyordhel** [comment]
This is the first time this test will be run, so I can't find any chance of a team having the experience advantage.

Other than that, I think the test is already over-specified. The robot finds a cupboard with some items into it and must place there the just bought groceries. I don't find myself placing objects in random order, but pasta with pasta, beans with beans, and so on. Should there be no pasta in the cupboard, then I use an empty space.

Or what I am missing here? No supermarket guy has ever had a problem understanding this task and often they don't have a degree.
