### ISSUE TITLE
Add other than waving in Restaurant

### ISSUE THREAD

**Issue by balkce** [RoboCupAtHome/RuleBook#23]
There are other ways to order a robot to come to a table other than waving (via voice for example). 

The waving person could also be saying something like "robot come here" as well as waving.

**Comment by kyordhel** [comment]
As always thinking on how to score best for Golem!!!!

Anyway. I agree with the idea. When the waitress is not paying attention to your waving, usually people shout at him something like: "are you blind, azzhole? Come here and take my order now!"

OR, ading the SmartRestaurant option, we may have tables with an annoying red light indicator (like those in airplains), so you may press the button and wait for the retarded stewardess to bring you your damn coffee... err.. i meant the robot, to pay attention to you.

**Comment by balkce** [comment]
Added it.
