### ISSUE TITLE
[Help me carry] Standard bag and box

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#231]
The rulebook states that

> The operator gives the robot a command to carry something, e.g. a box or a bag.  E.g. "Carry this box"

Box and bag are not listed within Section **3.2.5 Objects**, therefore teams don't know what to expect (nor do I). In some discussion I read that for Pepper a lightweight paper gift bag with rigid handle (See figure below) might be used, since Pepper's arms are not strong, however, I find it difficult for any robot to locate that handle unless is wrapped with a bright and contrasting color.

Whatever solution we provide, the objects should be described in both, the test and the Objects section.

Figure 1: Lightweight paper gift bag
![birthday_paper_gift_bags](https://cloud.githubusercontent.com/assets/8583949/22788426/1643adbe-eee0-11e6-9d8a-6e086b597df5.gif)

**Comment by dirkholz** [comment]
while i like the intention of this test, i doubt that you will see "a nice
solution" but instead hacky stuff that is neither impressive nor coming the
intended capability any closer ... my two cents.

For now I'd say go ahead, but i think we really need to change the overall
concept of all tests to be a "solvable problem" but requiring a real
solution rather than a hack

**Comment by LoyVanBeek** [comment]
That sort of paper bag is more or less what I had in mind indeed. 
For this challenge, I'm less concerned with the manipulation and I'd be OK with giving the robot the bag when it is sticking out it's arms zombie-style without paying attention. 
Same for a box. 

Picking it up is a nice extra, but not core to the challenge.

**Comment by kyordhel** [comment]
Let's be congruent then. 

**Manipulation and Object Detection/Recognition (120pts)**

      60 Bag handover (3 x 20)
      15 Place object (3 x 5)
      30 Moving moveable object
      10 3D Object recognition
    +  5 Small object recognition
    ----------------------------------------------------------------------
     120 Total

**Navigation (90pts)**

      30 Follow Operator (Reach the car 3 × 10)
      30 Online mapping (Reach inside the arena again 3 × 10)
    + 30 Indoor navigation (Reach destination 3 x 10)
    ----------------------------------------------------------------------
      90 Total

**Human-Robot Interaction (30pts)**

      15 Fetch destination (Speech Recognition 3 × 5)
      10 Move aside from person (Person Recognition)
    +  5 Ask person step aside (Person Recognition)
    ----------------------------------------------------------------------
      30 Total

In summary we have:

| Ability                  | Points  | Perc. |
|--------------------------|---------|-------|
| Manipulation & Obj. Rec. | 120 pts | 50.0% |
| Navigation               |  90 pts | 37.5% |
| Human-Robot Interaction  |  30 pts | 12.5% |

This tells me that the test is not about Navigation. If we pay special attention to the Hand-Over, although difficult, it rewards a team with up to 60 points, while avoiding a small object (something with which almost all robots failed and neither Pepper nor Toyota HSR are designed for) grants only 10.

It gets even worse. In Leipzig if a robot rammed over the small object, I allowed the test to continue, but Sven ended the test (considered as Major collision). If a team is unlucky, it may perform the handover once and finish the test because it didn't see the small object, while a luckier team may perform the handover trice.

Now, going into benchmarking, we have 3/test x 3 runs = bag handover, but only 3 times asking a person to step aside which, in my opinion, is much more important. In addition to this, evade a person grants 10 points (person is no different from any other object), but interacting by asking gently to step aside grants only 5.

This takes me to the worst part. *Reach the destination* entry that grants up to 30 points for indoor navigation (same as a more challenging outdoor navigation) while HRI grants only 5.

Once more, we don't have a *guide human* in this test that is replacing Navigation and Follow & Guide, there is also no door opening (something eR@sers already shown a Toyota HSRcan easily do in seconds), but instead we have nine hand-overs.

My proposal is to adjust scoring and do only one run as follows.

**DSPL & OPL**
1. Robot follows Human H1 to car.
2. Robot take bag/box whatever
3. Robot carries object to Beacon B (e.g. Dinner Table)
  - Once at the house, robot needs to open the door.
4. Robot finds Human H2 close to B and asks them to help carrying groceries.
5. Robot guides H2 to car.
  - Once out the house, a person will cross on robot's path

**SSPL**
1. Robot follows Human H1 to car.
2. Robot is asked to find Louise Strongman in room R
3. Robot goes back to home
  - While going back, a person crosses robot's path.
  - While going back, a person steps in front of the robot and asks the time.
4. Robot finds Louise Strongman in room R and asks her to help carrying groceries.
5. Robot guides H2 to car.
  - Once out the house, a person will distract Louise Strongman, robot needs to realize and continue guiding

Once the robot enters the house, it will need to deal with
- Small object
- 3D Object

**Comment by LoyVanBeek** [comment]
The scores indeed give more points to non-navigation issues. I tried to make scores consistent over the various challenges, so that doing the same thing in different challenges yields the same amount of points. Which is also a sensible thing to do, I think. 
The consequence is the first part of your issue. 

I like the suggestion of different scenarios in your comment, I'll try to write them in somewhere today.
