### ISSUE TITLE
Training data for known&alike objects

### ISSUE THREAD

**Issue by tkelestemur** [RoboCupAtHome/RuleBook#232]
In Storing Groceries task, it is mentioned that there will be 5 known&alike objects on the table. When will team have access to types of objects? I've seen that last year only a [pdf file](https://github.com/RoboCupAtHome/Leipzig2016/blob/master/Objects.pdf) provided for objects. Will it be same this year or are you going to provide any CAD or point cloud data before competition? 

Thanks you.

**Comment by kyordhel** [comment]
Known and Alike objects are publicly available during Setup days for teams to train. The PDF you have seen is for relating the object in the picture with its assigned official name. In this sense, an apple most likely will be named *apple* while a bottle of カルピス might well be labeled as *rice juice*.
