### ISSUE TITLE
Prepare for German Open

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#237]
The following major changes are required
- [ ] Balance test for they score in multiples of 50.
  - [ ] Reduce *Cocktail Party* max score to 250 (alternative for Storing Groceries must score the same).
  - [ ] Rise *Speech and Person Recognition* max score to 250, or reduce it to 200.
- [ ] Remove unused command sheet in EEGPSR.
- [ ] *Set a table and clean it up*
  - [ ] Reduce max scoring to 300.
  - [ ] Reduce test main description to 1 line (send extra to Appendix).
  - [ ] Move example to appendix.
  - [ ] Reduce objective size (move explanation to Appendix).
  - [ ] Offer alternative  for SSPL (for 300pts).
- [ ] Rise max scoring of *Restaurant* to 300.
- [ ] Clamp EEGPS to 300 (normalize if a team made more than 300?)
- [ ] Continue Rule for Manipulation

Advised minor changes
- [ ] Sort tests alphabetically

**Comment by LoyVanBeek** [comment]
Are all the issues fixed?
