### ISSUE TITLE
Continue rule for manipulation

### ISSUE THREAD

**Issue by iocchi** [RoboCupAtHome/RuleBook#238]
In order to take into account the request of some teams to simplify the manipulation tasks of the SSPL (Pepper) robots (concerns also confirmed by SoftBank) and at the same time to not introduce too many changes in all the tests, still giving the possibility to teams to work on this topic, I would like to propose the introduction of a "continue rule for manipulation" (possibly only for SSPL sub-league).

The aim of this rule is similar to the continue rule in speech recognition: that is to allow the robot to continue the task, if it is not able to accomplish a manipulation action in the middle of it.

The rule could sound like this:
Whenever a test requires the manipulation of an object (e.g., grasping, dropping, etc.) the robot (**not the team members**) may ask for help in this task. For example, the robot can get close to the object, clearly indicate that the object to be manipulated has been recognized, move its hand close to the object, open the hand, say "can you please give me the object?", close the hand when the object has been placed within its hand.
The score for this action will not be granted, but the test can continue and the robot can gain score for the next phases of the test.

**Comment by LoyVanBeek** [comment]
I think I can live with this, given that we define a strict measure for closeness. e.g. within a few centimeters or even touching the object-to-grab.

**Comment by balkce** [comment]
Seems reasonable.

C

**Comment by kyordhel** [comment]
Updated #237 
I have two questions on that regard.
1. The Continue Rule should be extended to all fields (i.e. the robot can ask for help to solve any task in a reasonable way) or be restricted for manipulation and speech recognition.
2. *Set the table and Tidy up* is manipulation dependent. My plan was to add a Cocktail Party Reloaded (e.g. Birthday party) as alternative for SSPL. This still proceeds?

**Comment by iocchi** [comment]
I think these two questions should be answered by TC.

Anyway, I'll give you my opinion:
1) Not really. It is better to specify exactly what we allow to bypass and in which way and maybe only for some platforms.
2) Yes

**Comment by kyordhel** [comment]
Luca @iocchi, the job is done.
I would like you, @balkce and @LoyVanBeek review the last changes in pull request #242 to merge and close this issue.

**Comment by balkce** [comment]
I reviewed the pull request changes. All good from my side.

C
