### ISSUE TITLE
Questions of Speech and Person Recognition Test

### ISSUE THREAD

**Issue by arturo8602** [RoboCupAtHome/RuleBook#240]
Hello, I have some questions and commentaries about this test:

1.- This test is evaluating only person detection and description, but the problem of learning and identification of a person is not included like in previous years. Some teams have been working hard in these abilities so we think it should be included in this test. We propose it can be a bonus (in a similar way that opening the door without human help was included in the Storing Groceries Test) by modifying the task as follows:

Start: The robot starts at a designated starting position and announces it wants to play riddles. A person stands in front of the robot. The robot learns the person (the robot instructs the person to perform a setup learning procedure).

Waiting and turn: The robot states when it has learned the person and waits ten second while the person merges on a crowd which is in the robot's back. When the time elapses the robot must turn around (about 180°) and find the crowd.

Finding the operator: After turning around, the robot must find the person in the crowd and approach or point him. The person stands in front of the robot and the rest of the people surround the robot.

The riddle glame: Standing in front of the robot, the operator will ask 7 questions from the list...

(The rest of the task continues as is described in the rulebook).

2.- In section 5.3.8, the total score (excluding penalties and bonuses) should be 230.

3.- In the Appendix A, the section A.1 states there will be 8 questions, but in the Speech and Person Recognition Test, including the score sheet, only 7 questions are considered.

4.- In section A.3, the answer of the question 8 is 'None You are a robot'. Does this answer imply that some operators of the test will be robots?

5.- In section A.4, in the question 7 “What objects are in the closet?”, which is the correct way to answer?:
a) The robot answers by using information of the scenario received before starting the test, or
b) The robot moves to the closet, count the objects, returns with the operator and reports the result.

I found these grammar issues in the rulebook:

6.- In section 5.3.4, in the Asked questions section, a 's' is missing:
'The distribution of questions to be randomly asked is a follows'
It should be:
'The distribution of questions to be randomly asked is as follows'

7.- In the question 5 of section Predefined Questions in A.4 the name of the league is incorrect: 'RoboCuo@Home' 

Arturo Rodríguez, member of Team Golem

**Comment by kyordhel** [comment]
1. I agree, the test is a poor merge of Person Recognition and SpR&AT. I would like to add the features you request but it is not possible due to time constrains. Most probably the detection features will be tested in GPSR.

Test Score will change to be rounded either to 200 or 250, same as the number of questions. Officially I would say is 7, but yet I find some inconsistencies.

In question 8 of A.3 we wrote a funny way of not answering (robot answered the question but does not know the gender). However, thanks for the idea, maybe we will include other robots.

In question 7 of section A.4. the robot assumes the arena is in its "normal state", i.e. does not need to move.

Thanks for marking the typos. Will correct them later.

**Comment by kyordhel** [comment]
After committing #897fbd6 I am adding this summarized checklist:

1. [ ] Add person learning & recognition.
2. [ ] Total score wrong sum **fixed**
3. [ ] Number of questions mismatch **fixed**
4. [ ] Indetermination in examples **fixed** (removed).
5. [ ] Unspecified if robot needs to check the arena state before answering **fixed** (added remark).
6. [ ] Typo **fixed**
7. [ ] Typo **fixed**
