### ISSUE TITLE
Questions of GPSR

### ISSUE THREAD

**Issue by arturo8602** [RoboCupAtHome/RuleBook#241]
Hello, we have some questions and commentaries about this test:

1. In Appendix B, section B.2, the number of attempts is not clear. This is my interpretation:
  - A command is generated.
  - The default operator repeats the command up to three times.
  - After three failed attempts of the default operator the team can try again the same command with a custom operator.
Is this interpretation of the rules correct? Or the custom operator is also part of the three attempts? 

I found these grammar issues:

1. In section 6.6.2, in the point 6 “Exiting the arena”, the word must is repeated: “The robot must must prove”.
2. In section 5.5.5, in the section “Getting instructions”, '1nd attempt' should be replaced by '1st attempt'.
3. In section B.2, the word Section is repeated: '(Section Section 3.8.15)'

Arturo Rodríguez, member of Team Golem

**Comment by kyordhel** [comment]
1. Thanks for the typos.
2. The robot receives a command max 3 times. Teams decides how.
3. Robot receives max 3 commands. If it fails to recognize all 3 commands (9 attempts), the test is finished.
