### ISSUE TITLE
Help me carry challenge setup description inconsistent

### ISSUE THREAD

**Issue by fibonatic** [RoboCupAtHome/RuleBook#245]
In tests/HelpMeCarry.tex at the setup subsection (starting at line 14) there is an inconsistency about whether there are only bags or also boxes. Because line 15 mentions both, but line 20 only mentions bags.

**Comment by fibonatic** [comment]
Further in that section it seems that the robot only has to carry bags, so would the (new) operator have to carry the boxes?

**Comment by kyordhel** [comment]
@fibonatic Whatever the operator has to transport is irrelevant for the performance of the test.
Inconsistencies are now corrected in #269, the robot will only transport an Official Shopping Bag (although other objects like sacs, plastic bags, boxes, crates, and groceries might be present close to the car for realism purposes).
