### ISSUE TITLE
Placement of an object - Storing groceries

### ISSUE THREAD

**Issue by nohernan** [RoboCupAtHome/RuleBook#246]
Hello there,

reading the score sheet for the Storing Groceries task, I noticed that the robot can put an object anywhere in the cupboard and more points are given when the placement is near objects of the same class. I think 
this is part of the task description and should be clearly stated in section 5.1.4 Task. Can you add this note to the task description, please? Or, probably, you don't intend a placement anywhere in the cupboard?

Regards,
Noe - Golem Team

**Comment by LoyVanBeek** [comment]
The idea is indeed to place e.g. apples and apples together in the cupboard. 

Unfortunately, I don't have much time the coming days to put this in. Could you perhaps make a pull request with this fix?

**Comment by nohernan** [comment]
Hello Loy,

I can do the pull request. First, clarify some questions, please. Does the placement of an object in the cupboard have to be exclusively near objects of the same class? I don't quite agree with this idea, since the objects in the cupboard might be in a shelf that is out of reach for the robot, I think the placement should be anywhere in the cupboard and, preferably, near objects of the same class. Of course, those placements near objects of the same class get more points. Do you want me to  add this thought to the rulebook and make the pull request?

Cheers

**Comment by LoyVanBeek** [comment]
Hi Noe,

The idea of the challenge is to also demonstrate both recognition and grasping at the same time, by performing the useful task of storing groceries. 
That is done by placing two objects of the same class together. You can place it somewhere else, but you'll get less points (this is already in the scoresheet). 
Of course, the corresponding item can be out of range of the robot, but that should be an incentive to build robots with a larger reach. Robots with a larger reach are better suited for this task and may get more points if they have their software in order as well, thus are a well integrated system.
