### ISSUE TITLE
About handover in Help-me-carry

### ISSUE THREAD

**Issue by arturo8602** [RoboCupAtHome/RuleBook#249]
I have a question about Help-me-carry. In section 5.4.4.4.1 the line “The operator hands a bag to the robot to carry” I see at least three posible scenarios:
a) The easiest.- the robot only puts its hand in a position to receive passively the bag (in this case it is not necessary to see the bag). The person places the bag in the robot's hand.
b) The hardest.- the robot searches the bag and estimates its position to grasp it. The person doesn't colaborate with the robot. 
c) An intermediate option.- Both the robot and the person colaborate. The robot actively searches the bag, but the person also delivers the bag moving his hand with the intention of placing the bag in the robot's hand.
I suposse it will be a scenario similar to b or c considering that this test is focused in object detection and manipulation, but I think it should be specified clearly which kind of scenario is expected in this test adding a section to define the term 'handover' and when it will be considered as correct. 

In section 5.4.6.6 the term handover is wrong: “Bag pick-up: If the robot can't handover the bag from the operator”, because the robot doesn't deliver the bag to the person. The robot is the one who receives the bag.

Arturo Rodriguez, Team Golem

**Comment by kyordhel** [comment]
@arturo8602 let's assume for a second you are not interacting with the robot but with another human being, for instance... me. What would you expect me to do? Of course you wouldn't hang the bag in my hand passively waiting, do you? Often there is some sort of collaboration, human A extends its hand, B grasps the object, and A releases the object when feels B pulls or somehow knoews the object is secured.

Following criteria will be used:

- Robot puts up hand begging for a bag and closes after some time: 0 points
- Robot puts up hand and closes it after bag-insertion: 1 point maybe?
- Robot picks up bag from ground: 5 points
- Robot takes it from my hand, human only puts hand forward slightly as it would do with another human: 20 points

**Comment by LoyVanBeek** [comment]
This links to https://github.com/RoboCupAtHome/RuleBook/blob/master/tests/HelpMeCarry.tex#L39 and https://github.com/RoboCupAtHome/RuleBook/blob/master/scoresheets/HelpMeCarry.tex#L11 

This could indeed be clearer. I've also identified another way to do this. A clarification is in https://github.com/RoboCupAtHome/RuleBook/pull/250
