### ISSUE TITLE
Anaphoric references in Speech and Person Recognition Test

### ISSUE THREAD

**Issue by arturo8602** [RoboCupAtHome/RuleBook#251]
In the examples of the questions of the SPR test, there are questions with mention to a previous question, for example: 

Section A.4. Object Questions:
7. What objects are in the closet? ->The shampoo, soap, the sponge and a cloth.
8. How many are they? ->There are four objects in the closet.
9. Do they belong to the same category? -> They are all cleaning stuff

But in the command generator of the github there are no questions with mentions to previous questions.
It should be convenient either add this kind of questions to the command generator or remove this examples from the rulebook if including anaphoric references in questions won't be part of the test. 

Arturo Rodríguez, Team Golem

**Comment by kyordhel** [comment]
Considering robots must have anaphora/ellipsis resolution for normal operation, ¿could you please open an issue in the CommandGenerator repository? The command generator should be compliant with the rulebook.

Thank you!

**Comment by balkce** [comment]
Are we sure we want to ask this from the teams in Stage 1? Anaphoric references is kind of a big deal if memory serves me right.

**Comment by LoyVanBeek** [comment]
Related: the roadmap  proposed in https://github.com/RoboCupAtHome/RuleBook/issues/217 (no assignment yet to what should be realized when)

Anaphora resolution was also included in https://github.com/RoboCupAtHome/RuleBook/commit/bd3e42974ab6d023fef2b0ce6ccb02cfee405cf8 of the Speech Recognition challenge which was merged with Person recognition into SPR. So I agree the generator is missing the anaphoric references.

**Comment by balkce** [comment]
Ok, then.

Then we should also add to the generator that it can only ask for appropriate anaphoric references.

I would NOT like to have something like:

1.- What objects are in the closet?
2.- How many of them are female?

Or:

1.- How many are they?    (meaning, asking an anaphoric reference without a prior question)

I hope somebody from the TC is up to the task in adding this, since I don't see it as trivial.

C

**Comment by LoyVanBeek** [comment]
Talk is cheap indeed. Of course, human effort is also possible: I usually generate the questions beforehand and can thus inject this sort of questions. It's not pretty though
