### ISSUE TITLE
Set a table and clean it up

### ISSUE THREAD

**Issue by arturo8602** [RoboCupAtHome/RuleBook#252]
On page 68 section 6.2.1.Example, there is a contradiction about the location of the items, first says:
“Several items are placed on the table: a plate, cutlery, a cup, napkins, a basket with bread, a ...”. But after says: “The basket with bread, a napkin, and the cereal box are on the kitchen counter...”, and then says “the plate, the cutlery, and the cup are inside a closet”. 
I suppose the objective of the first line I mentioned was to set the objective of the robot, but the redaction is not clear. Maybe “Several items will be placed on the table by the robot: a plate, cutlery, a cup, napkins, a basket with bread, a ...” could be more appropriate. 

I also found a contradiction between the line 6.2.6.4 where it is mentioned that an order is composed by 6 objects (3 easy and 3 difficult) and the score sheet in the section grasping objects where there is assigned 6x10 for easy-to-grasp objects and 6x15 to hard-to-grasp objects.   

Some typos:
1) Page 68 section 6.2.1. Example:
The robot starts moving these items, one by one, from their original position to the table.
It should be:
The robot starts moving these items, one by one, from their original location to the table.

2) Page 69 section 6.2.2. Goal sentence 3:
locations and cleanup dirt ansd spills from the table.
It should be:
locations and cleanup dirt and spills from the table.

3) Page 69 section 6.2.5. Task 3. Searching for objects:
... on the kitchen counter on inside the closet.
should be:
... on the kitchen counter or inside the closet.

4) Page 69 section 6.2.6. Additional rules and remarks:
3. Collisions: Slightly touching the table. Driving...
should be:
3. Collisions: Slightly touching the table is allowed. Driving...
5)  Page 69 section 6.2.6. Additional rules and remarks:
...stop the robot (Section Section 3.8.1)
should be:
...stop the robot (Section 3.8.1)

6)  Page 70. 6.2.9. OC instructions:
... the objects, as specified in item ?? of section 6.2.6
I don't know how it should be, but the answer marks should be replaced by something

7) Page 71
For each successful grasp of an hard-
It should be:
For each successful grasp of a hard-
(This typo is repeated three times in the same page). 

Arturo Rodríguez and Ivette Vélez, Team Golem

**Comment by kyordhel** [comment]
@arturo8602 thanks for the typos and inconsistencies between the test and the scoresheet.

This test must be shortened and rewritten in a more abstract way. The table must be set with all elements in place. Details about which ones are placed first or last, or are easy or hard to grasp are too much detail and must be left to common sense.

A pull request will be made available after German/Japan Open

**Comment by ytbilly3636** [comment]
It seems that the contradiction about the number of grasping objects is not modified.

> I also found a contradiction between the line 6.2.6.4 where it is mentioned that an order is composed by 6 objects (3 easy and 3 difficult) and the score sheet in the section grasping objects where there is assigned 6x10 for easy-to-grasp objects and 6x15 to hard-to-grasp objects.

Are the numbers in the score sheet (6x10 and 6x15) correct?
I think they are 3x10 and 3x15.

**Comment by LoyVanBeek** [comment]
The task is, for multiple objects:

1. grab item from original location
2. place on table
Operator can have a meal
3. grab item from table
4. place back on original location. 

This adds up to an object being grasped 2x and thus the total number of grasps is 6.

**Comment by ytbilly3636** [comment]
@LoyVanBeek 
I understand.
Thank you for your answering.
