### ISSUE TITLE
[Finals] Number of robots

### ISSUE THREAD

**Issue by HideakiNagano21** [RoboCupAtHome/RuleBook#255]
A team would like to have three robots for their collaborations in finals 
but only two robots could have been applied via application form.
I don't think that three robots could be inspected in the robot inspection. 
How about the finals?

**Comment by kyordhel** [comment]
All robots **MUST** be inspected before participating in any test,
including the finals. There is no exception for this rule nor there will
ever be. The reason of RIPS is to test safety.

As local tournament Japan Open can opt for use their own home rules
regarding minor aspects (e.g. different language or allowing 3 robots per
team), but the same won't be allowed in the international competition.

In former years, team ToBI has used up to 5 robots, all were inspected but
only two were registered as "robots" and the rest as "external devices" for
they were way too small (toy sized) to complete a single test and were
meant to extend the main robot perception. If this is the case, I see no
problem. In other cases I can't imagine a task that requires three robots.

**Comment by kyordhel** [comment]
All robots **MUST** be inspected before participating in any test, including the finals. There is no exception for this rule nor there will ever be. The reason of RIPS is to test safety.

As local tournament Japan Open can opt for use their own home rules regarding minor aspects (e.g. different language or allowing 3 robots per team). The same can't be granted in the international competition.

In former years, [team ToBI has used 3+ robots in Demo/Open Challenge and Finals](https://www.cit-ec.de/sites/default/files/teamTobi2016.jpeg). All were inspected in RIPS, but only two were registered as "robots" and the rest as "external devices" (they were too small to complete a single test and were meant to extend the main robot perception). If this is the case, I see no problem. In other cases I can't imagine a task that requires three robots, but also I see no problem in having 9 robots doing stuff in the finals as long as they are safe.

**Comment by HideakiNagano21** [comment]
I see. 
More than two robots could be inspected in RIPS but only two of them could be registered as "robots". 
I will tell them about this. 
Thanks.

**Comment by kyordhel** [comment]
Not quite.

All robots that might (even potentially) cause any kind of harm to a human must be inspected first and must comply with all security constrains stated in the rules. If a robot is very small (like in the case of ToBI's AMiRo), it is not consider a robot for @Home anymore, but more like external hardware.

Yet, everything meant to be used during a test must be previously approved by the TC. For instance, a lightsabre is not a robot, and yet I wouldn't allow it during the competition.

**Comment by HideakiNagano21** [comment]
I understand. Thank you.
