### ISSUE TITLE
Minimum Score for Finalists

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#259]
Considering this far the best 2 of each league _ascend_ to the Finals, it becomes necessary to propose a safety criterion: minimum scoring.

The main reason is to prevent having a team with a very low performance become a finalist. However, the requirements must be chosen carefully or there may have no finals at all. Participation in most (all-1) tests of each stage could be a requirement, as well as being in the Top 10 of all @Home.

**Comment by balkce** [comment]
This one is tricky.

On one hand, I agree: I don't want a mediocre team on the finals, even less so on the podium.

On the other: it would be really weird to have NO teams on the finals or the podium.

Frankly, if we specify a criteria and no teams satisfy it, it would mean that NO team of the league jumped the threshold, which means the WHOLE league is mediocre. There being no teams in the finals would be a loud wake up call to the whole community (kind of like the canary with the miners), but doing it like this would be harsh and there would definitely be backlash by the community.

I think carrying out the finals with the two top teams per league, regardless of their performance, is fine. However, we could build a criteria of performance ourselves and if one or both teams did not satisfy it, we could call it out during the last team leader meeting as a slap in the wrist to the community.

**Comment by LoyVanBeek** [comment]
Also, what would happen if of say OPL 5 teams get the minimal score but 0 or only 1 of the SPL robots do? I  certainly would not hope so, but it could happen.

**Comment by kyordhel** [comment]
Many teams are very annoyed for the possible scenario @LoyVanBeek is suggesting. In my opinion, a team that can't successfully solve one stage 2 test has no place in the finals (I've seen some unfortunate 5th places in such situation and it was very bad press).

For instance, lets say that Top 3 of DSPL teams manage to score between 600 and 900, while the best OPL just made 200. In that case you are leaving out one 600 in favor of one 200. Fairness apart, I don't think such team has something cool to show in the final.

**Comment by kyordhel** [comment]
I guess consensus was: no minimum performance for finalists this year. 

Closing issue.
