### ISSUE TITLE
Task Remarks

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#280]
I have remarks/questions about some tasks.

**Speech and Person Recognition**
I think the separation into understanding and correctly answering a question is good. But what is the reason that it only exists for the 2nd part, the blind man's bluff game? I think it would make sense to have the same distribution of points in the riddle game for the questions.

**Help-me-carry**
Since the changes to the bag handover, picking up the bag and placing it gives only 10 points. With the time restrictions, teams probably would be better off to just ignore the bag and go for completing the guiding at the end which gives 25 points. Is this intended since the tasks mainly tests navigation? Then why not cut the bag entirely?

**GPSR**
The score sheet suggests that completing the third given command gives more points than completing the first. I think the intention was of course to award robots to complete multiple tasks so I think it should state clearly that the additional points for the later commands are only awarded if the previous command was completed successfully. Thats how it was scored at the German Open anyway but I still think this should be clearer in the rulebook.

Johannes
Team ToBI

PS: Is this format fine or do you prefer to have remarks about separate tasks in separate issues?

**Comment by kyordhel** [comment]
Please open one issue per test. Is quite hard to track changes considering
several (even though may be related).

**Comment by johaq** [comment]
Ok. Separate issues now.
