### ISSUE TITLE
Help-me-carry: Bag pickup

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#282]
**Help-me-carry**
Since the changes to the bag handover, picking up the bag and placing it gives only 10 points. With the time restrictions, teams probably would be better off to just ignore the bag and go for completing the guiding at the end which gives 25 points. Is this intended since the tasks mainly tests navigation? Then why not cut the bag entirely?

**Comment by kyordhel** [comment]
We try to make consistent the scoring all over the tests. In *EEGPSR* you get about 10pts for a pick and place, and about the same in *Storing Groceries* (which tells me that Storing Groceries must be corrected), so it makes sense teams score the same here. Let's not forget that this test is all about safe navigation, online mapping, and people tracking. For matter of facts, yes, we removed the bag in the SSPL version.

This test is a good advisor. *Help-me-carry* makes easy for the TC to recognize which teams are trying to solve a task and which are just going after score.

**Comment by johaq** [comment]
I don't think teams who try to solve a task being punished with less points is desirable.

**Comment by kyordhel** [comment]
There is no punishment here, as no team is penalized. Trying to fly to the sun has its risks, but also big rewards; the rest can live their entire life on earth and nothing bad, nor remarkable will ever happen.

For instance, a team will never get a Best Manipulation award if skips the handover.

But I'm pretty sure you have a solution for that problem already, so why don't you send the pull request with the corrected test? I'm pretty sure the TC will be happy to review and merge the solution.

**Comment by johaq** [comment]
My suggestion was simply to reward more points for something in my opinion more difficult which is debatable of course. 
I also just saw your discussion about upping the time limit for this task which could be a nice way to get around this.

**Comment by kyordhel** [comment]
The test is _Speech **and Person** Recognition_, but person recognition is barely addressed. I favor the idea of rising the points of this test but not in speech recognition that seems covered enough to me.

About increasing the reward for grasping an object from the floor... Again I would ask if @Home is about scoring fake points for a meaningless competition, or actually try to solve chores.

**Comment by johaq** [comment]
To make a concrete proposition:
Put up hand, closing it after waiting time elapses ``2``
Put up hand, closing it right after the bag is inserted ``5``
Pick up the bag from the floor ``15``
Take bag from operator’s hand (natural handover) ``15``

4.2. Bag  delivery: The  robot  delivers  the  bag  to  the  instructed  destination.   It  may place the bag on the floor or onto the placement location **or hand the bag over to the nearby person**

Deliver the bag at the specified location by hand over ``5``
Deliver the bag at the specified location by placing it ``10``

I think this keeps the theme of the task (following and navigation)  while motivating teams to work on the carry part

**Comment by kyordhel** [comment]
Hand-over:
- Hand detection & tracking
- Object recognition
- Coordinated grasping
- Human-robot Interaction
Pick from floor:
- Solved in 2009 (Go get it)
- Object recognition

So, no go. And, again, the theme of the test is navigation, not manipulation.
