### ISSUE TITLE
GPSR: Score Sheet Clarification

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#283]
**GPSR**
The score sheet suggests that completing the third given command gives more points than completing the first. I think the intention was of course to award robots to complete multiple tasks so I think it should state clearly that the additional points for the later commands are only awarded if the previous command was completed successfully. Thats how it was scored at the German Open anyway but I still think this should be clearer in the rulebook.

**Comment by kyordhel** [comment]
#284 attempts to fix this issue. Hope is clear enough.
