### ISSUE TITLE
Blind man’s bluff game

### ISSUE THREAD

**Issue by mtlazaro** [RoboCupAtHome/RuleBook#287]
I found a bit confusing how the game is described. 
At the beginning it says: "A random person".... 
Then, you keep reading and find "The game will end when the 5th question has been made"
At this point it is not clearly explained that the game is done with 5 different people. 
After reading the scores then you realize that the robot has to turn towards 5 different people and answer their questions.

So just adding a sentence, "this process is repeated with 5 (possibly) different people" before "the game will end..." would clarify the development of the test.

**Comment by LoyVanBeek** [comment]
Does b0438b7 make things more clear?

**Comment by mtlazaro** [comment]
It is to me. I suggested the "possibly" since I would not see any problem in the same person doing more than one question.
