### ISSUE TITLE
Number of robots per team in Restaurant

### ISSUE THREAD

**Issue by furushchev** [RoboCupAtHome/RuleBook#292]
In the *Restaurant* test there are two robots performing in parallel (https://github.com/RoboCupAtHome/RuleBook/commit/91f20a1386b3e44f9d66baad4465fc636b8360f8).
Does it mean each team has two robots running the test in parallel, or two teams (each one with one robot) do the task in parallel?
(As far as I read the rule book, there is no part that addresses about it.)

(It might be ridiculous to ask such a too fundamental question, but I'm newbie to this competition.)

**Comment by LoyVanBeek** [comment]
This is a reasonable question, no worries. 

The idea is indeed to have 2 teams competing, each with their own 1 robot. This introduces a bit of a direct competition element and makes for a more realistic restaurant.

**Comment by furushchev** [comment]
@LoyVanBeek Thank you very much for super quick response and clarifying. 
In scoresheet, most of items are multiplied by 2, does it mean each one robot takes an order twice, right?

**Comment by kyordhel** [comment]
I see no need to clarify this in the rulebook, so I'm closing this issue (useful for FAQ).
If you feel the need of extra clarification, please correct it in a ```fix/#292``` branch  and make a pull request.

**Comment by furushchev** [comment]
I sent pull request #293. 

> In scoresheet, most of items are multiplied by 2, does it mean each one robot takes an order twice, right?

I assumed the answer of this question is yes...

**Comment by kyordhel** [comment]
Almost, a robot takes two orders (which is different from taking an order twice, implying the same order).

**Comment by furushchev** [comment]
@kyordhel Thank you for reply! Now everything is clear!

**Comment by LoyVanBeek** [comment]
A robot takes 2 different orders indeed, from different persons. There is no point in giving different persons the same order :-)
