### ISSUE TITLE
Questions about GPSR

### ISSUE THREAD

**Issue by arturo8602** [RoboCupAtHome/RuleBook#297]
We have a question about some commands generated by the GPSRCmdGen-master in the category I. There are some commands like:

* Bring me the pringles
* Give me the cereal
* Bring me the Jumex
* Put the cereal on the stove
* Give the cereal to emma

This commands had an unspecified location of the object or the person, which is the correct procedure for these kind of tasks? We have two possibles ideas:

1. Have a previous specified location given by the TC to the objects and persons, and when a command of this kind is given search on the specific location previously provided.
2. Ask where is the object or where is the person to the user that is giving the command.

**Comment by kyordhel** [comment]
Category one assumes that there is no need for asking questions. Therefore, you should relay in Robot's knowledge as stated in Object (category) locations Section 3.2.5 and 3.2.6:

> **Object (category) locations:** An object location object will be assigned to each object category. For example, Objects categorized as “fruits” may be usually found on the “kitchen table”, and unknown objects “unknown” may be usually found on the “trash bin”.
