### ISSUE TITLE
About participating in different league's open challenge

### ISSUE THREAD

**Issue by gouki-iwamoto** [RoboCupAtHome/RuleBook#299]
It is a question about open challenge.
A question about rule book (Last Build Date: May 24, 2017 Time: 979) 6.2.5.3 Team-team-interaction. 
Is it possible for a SPL team's robot to participate in OPL's open challenge and a OPL team's robot to participate in SPL's open challenge?
If it is possible, is it possible for Hibikino-Musashi@Home SPL and Hibikino-Musashi@Home OPL to participate in each other's open challenge?

**Comment by kyordhel** [comment]
SPL robots can participate in OPL's Open Challenge and Finals.
OPL robots can **NOT** participate in any SPL test.

It is important to remark that the Open Challenge will take place at the same time for both leagues, and that the Team Leader is required to be present during the whole Open Challenge of all teams. Make sure both teams fulfill this requirement before intending cooperation. Also, please address the OC one day before the Open Challenge for schedule

Regarding the bonus for *Team-team-interaction* (6.3.5. subsection 3), I announce beforehand that the bonus is not available for Inter-league forks of the same team. Regarding Team-Team cooperation Hibikino-Musashi@Home SPL and Hibikino-Musashi@Home OPL are considered as same team.

**Comment by balkce** [comment]
What @kyordhel said is correct.
