### ISSUE TITLE
Questions about command retrieval for EEGPSR

### ISSUE THREAD

**Issue by kyamama47** [RoboCupAtHome/RuleBook#304]
Hello.
I have some questions about command retrieval for  EEGPSR.(rulebook Last Build Date: May 25, 2017 Time: 1430)

In "C.2. Command retrieval explained", 
"Only three different commands are generated for a robot, if the robot fails to recognize all three commands (i.e. nine attempts), the test ends immediately."

I could not understand exactly when does the robot switch with another robot.
I thought there are two cases.

If Robot_A(teamA's robot) & Robot_B(teamB's robot) participate same test 
Case 1. 
 Robot_A : 1st command 1st attempt  FAILED
 Robot_A : 1st command 2nd attempt  FAILED
 Robot_A : 1st command 3rd attempt  FAILED
 Robot_A : 2nd command 1st attempt  FAILED   (Is the 5 minute timer reset here?)
 Robot_A : 2nd command 2nd attempt  FAILED
 Robot_A : 2nd command 3rd attempt  FAILED
 Robot_A : 3rd command 1st attempt  FAILED   (Is the 5 minute timer reset here?)
 Robot_A : 3rd command 2nd attempt  FAILED
 Robot_A : 3rd command 3rd attempt  FAILED
 Robot_A's test end.
 Change to Robot_B's turn
 Robot_B : 1st command 1st attempt SUCCEED
 Robot_B : execute 1st command
 Robot_B : return to designated position
 Robot_B : 2nd command 1st attempt  SUCCEED
 ～～～

Case 2.
 Robot_A : 1st command 1st attempt  FAILED
 Robot_A : 1st command 2nd attempt  FAILED
 Robot_A : 1st command 3rd attempt  FAILED
Change to Robot_B's turn
 Robot_B : 1st command 1st attempt SUCCEED
 Robot_B :  execute 1st command
 Robot_B : return to designated position
Change to Robot_A's turn
  Robot_A : 2nd command 1st attempt  FAILED   
  Robot_A : 2nd command 2nd attempt  FAILED
　～～～

Which case is correct? or Are there any other case?

**Comment by kyordhel** [comment]
There is no need to specify the build.
In EEGPSR robots are commanded in an interleaved fashion.
- Command A1 for robot A (up to 3 tries)
- Command B1 for robot B (up to 3 tries)
- Command A2 for robot A (up to 3 tries)
... and so on

Time is irrelevant for command retrieval as a robot can be commanded to do
anything at any time. Nonetheless, command retrieval time is considered
within the 5 minutes window for command execution, so the more time your
robot requires to fetch a command, the less time it has to accomplish the
task.

**Comment by kyamama47** [comment]
I understand. thank you for your reply.
