### ISSUE TITLE
Q: Defer changes to DSPL Speech and Person Recognition layout

### ISSUE THREAD

**Issue by nickswalker** [RoboCupAtHome/RuleBook#314]
#312 (with discussion in #289) substantially alters the difficulty and scoring of the Speech and Person Recognition task for DSPL by moving away from 360 degree sound localization (5.3.4.5). This hurts teams that have invested in 360 degree solutions, and comes fairly late in the competition cycle. Could this major change be deferred until next competition?

**Comment by balkce** [comment]
Are you able to do 360 degree SSL with only the hardware in the standard platform? As far as I remember, the number of microphones that come with a DPSL robot are not enough to carry out 360 SSL.

Remember that adding any hardware to a standard platform is not allowed.

**Comment by nickswalker** [comment]
We believe we can field a competitive solution using only the standard platform hardware.

**Comment by kyordhel** [comment]
Supporting @balkce's point, we have been informed that is not possible (regarding the state of the art) to perform 360° sound source localization with the HSR built in microphones. The TC finds absurd to test something outside robot's specification, so we came out with something the robot can actually do. While OPL and SSPL will be tracking SSL in 360°, DSPL will focus on speed in a problem that is considered pretty much solved regarding SotA.

If you believe you can solve 360° SSL with the HSR hardware, then show it in the Open Challenge, open-source your code, and then the TC will reward you accordingly for your innovation.

**Comment by LoyVanBeek** [comment]
I really hope you can show this and open source the work. That way, all teams can benefit and the DSPL can advance to the level of the OPL and SSPL is this aspect of RoboCup@Home.
