### ISSUE TITLE
Q: Collecting information before startup for Storing Groceries

### ISSUE THREAD

**Issue by nickswalker** [RoboCupAtHome/RuleBook#319]
In the groceries task, 5.3.3 says "the robot will start between the cupboard and the table in a random orientation". We take this to mean that the robot's sensors and data collection should be fully disengaged until the startup voice command or button press, and that teams cannot use any sensor data gathered while the robot is being moved into the startup position. Is this correct?

**Comment by kyordhel** [comment]
Actually, the referees don't mind at all. To get to the indicated spot you may either push the robot, use a joystick, or give to the robot a voice command. If the robot reaches the spot in a **completely autonomous way** none will dare to interfere but, if the robot is placed (pushed, joysticked, remote controlled, teleported, etc.), the referees may move it before pressing the start button. To what concerns to the Referees and TC, the robot can be plotting with Skynet if it feels like to fight before the start command/button is set.
