### ISSUE TITLE
Q: When is orientation randomized in storing groceries?

### ISSUE THREAD

**Issue by nickswalker** [RoboCupAtHome/RuleBook#320]
5.3.3 bullet 2 says that "the robot will start between the cupboard and the table in a random orientation." 5.5.7 says that the robot's startup "location" will be announced two hours before the assessment begins. The comment in #319 suggests that the referee may move the robot before the start of this task, suggesting that their could be task-time randomization. Does this "location" announcement also include orientation, or will the precise orientation be randomized just before the start of each team's run?

**Comment by LoyVanBeek** [comment]
The referees announce something like this:
![German Open storing groceries](https://github.com/RoboCupAtHome/GermanOpen2017/blob/master/StoringGroceries/waypoints.png?raw=true) (From the German Open early May)

There's a label 'Attempt 1&3'  and 'Attempt 2'. Teams put their robot roughly in the indicated spot, we tell it to face more or less to some direction somewhat facing the cupboard/table. When the team tells everything is ready (time and patience is limited during competitions), the referees say 'start' and then the robot does its job. 

That job includes adjusting its position/orientation to properly do the job. 

We will **not** mark down the position/orientation, @Home robots must be able to deal with such variations.

**Comment by kyordhel** [comment]
Comment in #319 relates to referees actually turning or pushing the robot a little bit aside when:
- The team seems to be carefully aligning the robot in a very specific (x, y, theta). 
- Some mysterious unauthorised landmarks appeared in the arena and the robot is aligned to them. 

As @LoyVanBeek said, time and patience are very limited. The referee may always cancel your slot of the robot is not ready within seconds.
