### ISSUE TITLE
Q: Definition of "start button" for DSPL

### ISSUE THREAD

**Issue by nickswalker** [RoboCupAtHome/RuleBook#321]
3.5.5 says that OPL robots should have a start button which is "any 'one-button procedure' that can be easily executed by a referee." HSR has on-board and remote e-stop buttons, but are teams allowed to use this same permissive definition of start button?

**Comment by LoyVanBeek** [comment]
I don't see why not. The purpose is to enable referees to start the robot in case a voice command doesn't work and typing a command on a keyboard over ssh etc is always a hassle.
