### ISSUE TITLE
The registration site of mailing list returns 404.

### ISSUE THREAD

**Issue by terakoji** [RoboCupAtHome/RuleBook#322]
1.4.1 says the participants can register to the mailing list of robocup@home.
But the presented link is not worked.

http://lists.robocup.org/listinfo.cgi/robocup-athome-robocup.org

Can administrator check it?

**Comment by furushchev** [comment]
Maybe this site is moved to another location?
http://lists.robocup.org/cgi-bin/mailman/listinfo/robocup-athome
CC: @LoyVanBeek @kyordhel

**Comment by LoyVanBeek** [comment]
Apparently it moved indeed. Thanks for finding the issue and together fixing it!
