### ISSUE TITLE
Q: ambiguous commands in GPSR

### ISSUE THREAD

**Issue by furushchev** [RoboCupAtHome/RuleBook#324]
I played command generator and found that some commands are ambiguous.
For example:

- Look for the soap in the bathroom
- Find the pringles in the bathroom

When the robot is regarded that he successfully looked for the object? Is it only he have to do is to say "I found soap!" in the bathroom, or does he need to pick it up to an operator?

**Comment by kyordhel** [comment]
I'm falling back to Rule **3.8.4. Expected Robot’s Behavior** (page 36). How a human would address the problem?

When mama asks me: for the soap, if I enter the bathroom and just shout "I found the soap", then I got an appointment for my ass with her sandals. Either she is asking me to retrieve the object, or to tell her exactly where the soap is. The same applies to robots, the robot may:
- Clearly state where is the soap (e.g. _"The soap is on top of the washing machine"_).
- Point at the object at grasp distance and state that the soap is there.
- Pick the soap and deliver it to the operator (also scoring for picking an object).

Is there a specific task to be accomplished? No, but neither there is in real life, and a General Purpose Service Robot must deal with that.

**Comment by LoyVanBeek** [comment]
In case of doubt, the robot is allowed to ask for more information as well.

**Comment by kyordhel** [comment]
@furushchev Why aren't you following the [guidelines](https://github.com/RoboCupAtHome/RuleBook/wiki/Guidelines:-Questions) for asking questions.

**Comment by furushchev** [comment]
> @furushchev Why aren't you following the guidelines for asking questions?

Sorry, I did not see the page. I'll follow from the next issue (if exists).

> When mama asks me: for the soap, if I enter the bathroom and just shout "I found the soap", then I got an appointment for my ass with her sandals. Either she is asking me to retrieve the object, or to tell her exactly where the soap is

This response may changes on what she will do next...

Anyway, when a robot received ambiguous commands, he can:
- interpret the commands based on common sense
- ask to resolve ambiguity

Thank you very much for clarifying!
