### ISSUE TITLE
Q: [Storing Groceries] Definition of "door open"

### ISSUE THREAD

**Issue by furushchev** [RoboCupAtHome/RuleBook#325]
In storing groceries task, a robot has to open door before pick-and-place objects.
My question is which state of door is regarded to be open.

Possible states after a robot tried to open door are:

- door is the same as before trial door is closed) → 0 point!
- ★timed out (1 min.) and door is partially open → ?? point
- ★door is seen as open but a robot may not be able to continue pick-and-place because the door is not enough open to do task → ?? point
- door is completely open (and then a robot can do the task to the end) → 20 points! 

For each ★ cases:
  - Can we ask TC to open the door completely if the door is partially open in such a case?

I'd like to know how we handle the middle state between completely close and open.

**Comment by kyordhel** [comment]
Again I see point chasing. A door is open (enough) or it isn't.
- If the door is open, the robot scores points.
- Of the robot is shut (or not opened enough), the robot does **not** score points.

It is responsibility of the robot to mind its own hardware and manipulate only those objects within reach. I don't see why the referee should interfere without the robot asking for it. If there is a collision, the test is finished.

**Comment by kyordhel** [comment]
Thanks for the edit :)

**Comment by furushchev** [comment]
@kyordhel Thank you for quick response!

> Question: why are you not following the guidelines for questions?

Sorry again, fixed.
Please note that I tried to add labels but maybe I don't have a right to do that.

> If the door is open, the robot scores points.
Of the robot is shut (or not opened enough), the robot does not score points.

I see! Now it's clear. Thank you very much!

> Again I see point chasing. A door is open (enough) or it isn't.

This is a competition and we all participants are more or less chasing points, I think.
One door panel of the two is removed ( https://github.com/RoboCupAtHome/RuleBook/issues/258 ) ...why? I think it's for those who want to earn another points even if they cannot open the door..

**Comment by kyordhel** [comment]
One thing is try to solve the task (actively aiming to solve the whole task), and other focusing in scoring as many points as possible, regardless which task is to be solved. Storing groceries not necessarily involves door opening, so one of the doors is removed to allow robots to give their best in such situations.

Please note that the door covers **at most** 1/2 the shelf, the following one is also possible:
![image](https://user-images.githubusercontent.com/8583949/27133776-ac67d0be-5113-11e7-93f1-e45106fd45f7.png)

This shelf has two doors and several other layers accessible. This is also valid and the robot may even not try to open the door at all.

**Comment by furushchev** [comment]
@kyordhel This is very clear example of the door! Thank you very much!

Now I see:

- A door is regarded as open if a robot do pick or place objects in the shelf which a robot opened without any problem
- A robot can continue the test even if he failed to open the door
