### ISSUE TITLE
Q: When and How to judge "confirming the choice" in Set a table & Clean it up 

### ISSUE THREAD

**Issue by hyaguchijsk** [RoboCupAtHome/RuleBook#326]
According to the section 6.4.8. score sheet,
"For asking for the meal variation and confirming the choice" is scored 10 points,
when this is scored and how to be judged?

In section 6.4.3. part 1-1, the robot action is described as:

1. "The operator requests the robot to set up the table"
1. "Optionally, the robot may ask the operator what has to be served"
1. "The operator replies with the randomly selected (and undisclosed) option"

So I understand 2. is "ask" and "confirm" must be attempted after 3.
Is it correct this action is scored after "Fetching command" ?

And, what to do for "confirming the choice"?
Does it mean that the robot simply repeats the meal variation?

**Comment by kyordhel** [comment]
I'm falling back to Rule 3.8.4. **Expected Robot’s Behavior** (page 36). How a human would address the problem?

I set as example the following dramatized dialog (I've seen this in so many movies):
- **```O:```** *Could you serve the table, please.*
- **```R:```** ```Yes, madame. Shall I serve tea and cookies as usual?```
- **```O:```** *No. I feel like warm soup tonight. With croutons please.*
- **```R:```** ```Your warm soup with croutons will be ready in a moment, your highness.```
- **```O:```** *Thank you, Robo-Alfred.*

The example meets all criteria explained in the rulebook. The robot is asked to set the table, then the robot proposes the standard setting which is overridden by a *custom setup* (the team provides three alternatives, the referees chose one randomly). Finally, the robot confirms the order.

There is no scripted way on how the robot must interact with the operator as long as the interaction is natural. The following example is also permitted although highly unadvised:

- **```O:```** *Robot, set the table.*
- **```R:```** ```You want me to set up the table. Is that correct?```
- **```O:```** *Robot, yes.*
- **```R:```** ```Understood. I will set up the table. If you want me to place the default setup, say: robot, default setup.```
- **```R:```** ```If you want me to serve frosties with milk, say: robot, serve the frosties option.```
- **```R:```** ```If you want me to serve choco-flakes with milk, say: robot, serve the choco-flakes option.```
- **```R:```** ```If you want me to serve apple and orange juice, say: robot, serve the apple option.```
- **```R:```** ```Please tell me, which option do you want me to serve?```
- **```O:```** *Robot, please serve the choco-flakes option.*
- **```R:```** ```You said: Robot, serve the choco-flakes option. Is that correct?```
- **```O:```** *Robot, yes.*
- **```R:```** ```Ok. I will set the table for serving choco-flakes. Please wait.```

Long and boring, but somehow effective assuming the operator will pay attention to three minutes of speech synthesis.

**Comment by hyaguchijsk** [comment]
@kyordhel Thank you for your clarification.
This dialog is really good example for me.
I understand what to do at the first step.
