### ISSUE TITLE
Q: Disturbances from outside in Help-me-carry

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHome/RuleBook#328]
In additional rules in the Help-me-carry test is stated:

5. Disturbances from outside: If a person from the audience (severely) interferes with the robot in a way that makes it impossible to solve the task, the team may repeat the test immediately.

I want to know a case and criteria of "it impossible to solve the task".

**Comment by kyordhel** [comment]
It happened once in Follow Me that a very enthusiastic child (maybe 5 or 6 years old) ran to the robot and hugged the machine. Of course this wasn't team's fault, yet the robot was immediately stop.

For further questions please follow the [Guidelines](https://github.com/RoboCupAtHome/RuleBook/wiki/Guidelines:-Questions)

**Comment by LoyVanBeek** [comment]
In general, the referees are the judge of this. 

The point of going outside the arena is to have some less controlled environment because that is where the robots will operate eventually.
