### ISSUE TITLE
Indirect speech recognition is unclear

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#33]
The part about turning in the indirect speech recognition is unclear and seems contradictory

**Comment by balkce** [comment]
I've made the explanation of the indirect part of the Speech Recognition test a bit clearer. The robot has two choices: either 1) turn its microphone towards to the operator, ask for a repetition, and then answer with no confirmation or 2) directly answer the question without turning its microphone and without confirmation.
