### ISSUE TITLE
latexonline.cc compile url for the rulebook is giving error 500

### ISSUE THREAD

**Issue by awesomebytes** [RoboCupAtHome/RuleBook#330]
Trying to get the latest rulebook with the link:
https://latexonline.cc/compile?git=git://github.com/RoboCupAtHome/RuleBook.git&target=Rulebook.tex

Gives
`500 Internal Server Error`

As a workaround for anyone else, an already generated PDF can be found at: http://docs.google.com/viewer?a=v&pid=sites&srcid=cm9ib2N1cGF0aG9tZS5vcmd8cm9ib2N1cC1ob21lfGd4OjY4MDk1MWU5OTVkOTA5Y2M

Gotten from the url: http://www.robocupathome.org/rules

**Comment by LoyVanBeek** [comment]
Thnx Sam. 

I'll try to contact the guy behind the service.

**Comment by LoyVanBeek** [comment]
Something is definitely off with the service. I deployed it's docker image to Heroku, to no avail: 

https://obscure-woodland-35354.herokuapp.com/compile?git=https%3A%2F%2Fgithub.com%2FRoboCupAtHome%2FRuleBook.git&target=Rulebook.tex&command=pdflatex

**Comment by LoyVanBeek** [comment]
Interestingly, the link https://latexonline.cc/compile?git=git%3A%2F%2Fgithub.com%2FRoboCupAtHome%2FRuleBook.git&target=Rulebook.tex&trackId=1500143297774 works for me again, but only after I switched off the Chome "uBlock origin" extension
