### ISSUE TITLE
Q: Grammar Generator Permanence?

### ISSUE THREAD

**Issue by MeeraWakim** [RoboCupAtHome/RuleBook#332]
For the Speech and Person Recognition task in Stage 1, the grammar generator outputs some grammatically incorrect/unconventional sentences. 

Will the people reading them in the competition alter these sentences to make them more correct/conventional, or will they be required to read them verbatim?

 Or will the grammar generator code change in any way right before the competition?

**Comment by LoyVanBeek** [comment]
The referees will apply common sense when using the generator, as it can indeed make up nonsensical sentences. 

The code will change to accommodate the object set present at the venue.

**Comment by justinhart** [comment]
So, to clarify, does this mean that we should parse what is output by the generator as English sentences, expecting the referees to correct the syntax when they read them? Might they change the syntax of relatively awkward utterances? For instance "Where is located the {placement}?" is an awkward sentence. Can we expect that a judge might say, "Where is the ${placement} located?"

**Comment by LoyVanBeek** [comment]
That example is indeed a bit awkward but a valid English sentence. 

@kyordhel, care to chime in?

**Comment by kyordhel** [comment]
This is an issue for the generator, I think.

Indeed; I must admit that not all the generated sentences obey (American) english common sense, which by the way is not compliant with Oxford grammar, to name one. Nonetheless, from the perspective of the rules, this should represent no problem for robots for the volunteers rarely repeat *verbatim* the given instructions, and that supposing they are grammatically correct (which often is not the case).

@justinhart I assume you are native English speaker. Could you please help us with a PR including some grammar corrections in the generator?

**Comment by justinhart** [comment]
We're still in the heat of preparing our team for RoboCup@Home, but when there's time, I'd be happy to address this.

**Comment by kyordhel** [comment]
@justinhart, can we address this now? Hope you have time.

**Comment by justinhart** [comment]
Yep. I'll take a look.
