### ISSUE TITLE
Using map during Storing Groceries task

### ISSUE THREAD

**Issue by tkelestemur** [RoboCupAtHome/RuleBook#338]
Hi everyone,

According to item 5.5.7 in the rulebook, the pose of the robot will be announced 2 hours before the actual test. In 2 hours, will the poses of table and shelf stay same ? If so, is there any limitation of using map that created during setup days?

Thanks,

**Comment by kyordhel** [comment]
Not poses but positions.

The robot start position (which will be announced 2 hours before the test) will be a big ```X``` in the arena map (if the test is held in the arena), or in a marked space outside if this were the case. This also means that the robot must be located there in any random orientation.

Regarding the coordinates and orientation of the table and the shelf within the arena, they will be at the same place within some reasonable limits. If the test is held outside the arena, we will try to place the table and the shelf more or less as they were in the arena.
