### ISSUE TITLE
Q: Crowd and General Quesitons in [EE]GPSR and S&PR

### ISSUE THREAD

**Issue by sjchoiAtBI** [RoboCupAtHome/RuleBook#339]
**Speech and Person Recognition**
1. In section A.1.3., it states that the robot is required to answer questions about "the crowd the robot observed at the very beginning of the test". Does this mean that for both the riddle and blind man's bluff game, all the crowd-questions for the tasks will be related to the crowd initially in formation for the riddle game when the robot turns around? 

2. Can it be assumed that when the crowd is in formation for the riddle game and pepper turns around to observe the crowd, everyone will be within a sufficient distance for Pepper to see every individual without having to move or turn further?

3. For the speech and person recognition task, it is required that the robot must leave the are. However in the scoring sheet no points or penalties are allocated for the exiting of the robot. Is the exiting of the robot mandatory for this task and if so, how are points given?

**GPSR**
1. When the robot answers, does the robot need to return to the operator or can answer directly? For example, when the operator asked the robot "where is James?" and the robot found James in the kitchen, so currently the robot is in the kitchen, does the robot need to return to the operator and answer that "James is in the kitchen" or can the robot  answer in the kitchen right away?

2. When the operator asked the robot to bring someone here, does the robot need to find all the rooms or will the operator specify where the target is? For example, does the operator say "ask Joe to come here" or "ask Joe _in the kitchen_ to come here?"

**General**
1. In the rulebook it states that volunteers who need to be recognized during the test will be available during the setup days. Will they be wearing a specific T-shirt fpr the duration of the setup and competition for recognition or are we required to recognize their faces?

**Comment by kyordhel** [comment]
### Speech and person recognition test:

1. Yes.

2. Not quite. The riddle game takes place **after** the robot takes a picture of the crowd. The distance between the robot and the crowd is about 2~3 meters, but the robot can of course take a step backwards to get a better FOV.

3. It takes much more time for the team to enter the arena and pick the robot, than it takes to the robot to leave autonomously. Hence, we request the robot to leave once it has finished so we can ask the next team to get ready while in transit.

### [EE]GPSR

1. Often the command will specify to whom the question must be answered. Something like:
- Tell **me** how many red objects are in the shelf.
- Find James in the kitchen and tell him the time.

When I was a toddler, I was required to be polite and approach to mama when answering a question or I faced the chance to make an appointment with her mighty slipper. The same level of politeness is expected from robots.

2. All objects have assigned predefined locations (e.g. paprika is stored in the fridge in the kitchen). It is expected the robot look there first. All this is explained in General Rules, section 3.2.6.

### General Rules
1. That statement is false. Section 3.2.8 states that *The TC makes the set of names available during the setup days*. The word *volunteers* is not mentioned in the General Rules in the rulebook, and any other mention is for the Referees/O.C. to be carried on max 2 hours before the test.

How you address people recognition is up to you.
