### ISSUE TITLE
3.2.5 Objects: clarify and condense

### ISSUE THREAD

**Issue by dirkholz** [RoboCupAtHome/RuleBook#34]
section is somewhat long and unclear, please try to condense the specficications into a set of very clear points.

Also, what's going to be exact number of objects, 10? I know training all these objects is time-expensive but decreasing the number of objects will make it simpler again. Instead, we should go for more and encourage teams to work on the training procecudres. Also, we could define some of the objects in advance, e.g., standard products you can get in (almost) every country, so that people can already train at home. We shouldn't decrease the total number though ...

**Comment by kyordhel** [comment]
We need another meeting to define that stuff.

We reduced the number of objects because
 - We were not using all (waste of money?)
 - We are including more challenging objects (apples, bannana, pear) which can't be simply "trained" because they look like but doesn't match exactly.

**Comment by kyordhel** [comment]
Objects subsection reworked

**Comment by LoyVanBeek** [comment]
Looks good. I 've been nitpicking some texts in 99edd0c
