### ISSUE TITLE
What questions can be asked during (EE)GPSR?

### ISSUE THREAD

**Issue by rokusottervanger** [RoboCupAtHome/RuleBook#340]
For the SPR challenge, the questions are clearly explained. They can be either predefined, about the state of the arena, about the list of official objects, or about the crowd. Obviously, in the (EE)GPSR, there is no person recognition phase, so I'm guessing the crowd questions will not be asked in these challenges (after the "answer a question" command). Is this the only change to the set of possible questions between SPR and (EE)GPSR?

**Comment by kyordhel** [comment]
I could be really evil (of course neither @LoyVanBeek nor @balkce would let me do this) and command the robot to:

- Tell to Ana at the coach how many girls in the dining room are wearing red blouses.
- Find a crowd in the living room, meet James at the bed, and answer him a question.

... among other questions of the sort, but that would require the team to choose a mix between Category  IV and Category VII.

In general terms, and of course after considering the chosen category, questions are more likely to be chosen from the set of Predefined Questions.

**Comment by LoyVanBeek** [comment]
For this year, I totally agree with @kyordhel. We want robots to succeed and won't be truly evil :smiling_imp: 

For later and practical use, I can totally imagine my mother asking her robot to count the number of plates on the table etc or the number of people who haven't had a drink yet.
