### ISSUE TITLE
Question about wifi antenna

### ISSUE THREAD

**Issue by gliese581gg** [RoboCupAtHome/RuleBook#341]
Regarding the use of routers, are we allowed to use a 40cm omnidirectional antenna to connect to the router?

For example :
https://www.amazon.com/WLAN-Omnidirectional-Antenna-2-4GHz-Distributed/dp/B01N1QFR6U/ref=sr_1_fkmr1_4?s=electronics&ie=UTF8&qid=1500028017&sr=1-4-fkmr1&keywords=om+06+antenna

**Comment by LoyVanBeek** [comment]
On your robot, complying with (local!) regulations? I don't see why not.
