### ISSUE TITLE
Q: [SPR] How to start the bluff game

### ISSUE THREAD

**Issue by hyaguchijsk** [RoboCupAtHome/RuleBook#343]
In the SPR task, after finishing the riddle game "The crowd will reposition" to prepare the bluff game.
While repositioning the robot must wait but
in the rulebook no description is provided how to start the bluff game.

I think some procedure is needed to start the bluff something like,
the OPERATOR will announce starting the game or the ROBOT will confirms to start the game.
For example; 
- The OPERATOR announces "Let's start the Bluff" after preparing.
- The ROBOT confirms "Are you ready ?" while the operator says "Yes".

Which is the way to start? or can teams decide the way to start the bluff with natural interaction?

**Comment by kyordhel** [comment]
Both approaches are valid. When children are playing those games, they never have a manual at hand, instead they rely on interaction to reach consensus. The same type of natural interaction is expected from robots in all tests. The rulebook imposes no limits on teams to address the problem of interaction.

The operator and volunteers will be willing to cooperate with the robot, so the robot can **briefly** instruct them on what to say (or press, in case of start button) to switch game. If the robot is a smart-wheels, it can always rely on its other sensors (e.g. laser and cameras) to detect when the people is ready to play and inform it or simply start. 

Is important to remark that all instructions shall be short, concise, brief, natural, and easy to follow (people have hard time listening to chatterer robots). All interactions considered as non-natural by the referees might be interrupted or not followed at all.

**Comment by hyaguchijsk** [comment]
Thank you for your quick response, I understand.
I'll prepare a natural way to make consensus.
