### ISSUE TITLE
Q: late declaration for external computing

### ISSUE THREAD

**Issue by maximest-pierre** [RoboCupAtHome/RuleBook#344]
Q: Can I still declare an external computing or is it too late. I know that the rulebook says to declare it at least one month in avance.

**Comment by moriarty** [comment]
I'm not a TC member, but ... the rule looks pretty clear.

Could you provide more information?

Not only is the deadline violated in 3.6 item 2, but possibly
Section 3.6 item 5 & 6 which are to provide other teams an equal opportunity... unless another team is already using the same external computing source.

**Comment by LoyVanBeek** [comment]
I got the request over e-mail as well and indeed the service is already used by a bunch of other teams. 
In this case, it is fine to use.
