### ISSUE TITLE
3.5.2. Number of tests: correct cross references and update/check numbers

### ISSUE THREAD

**Issue by dirkholz** [RoboCupAtHome/RuleBook#35]
Just make sure before the rulebook gets "final" to check all numbers and cross references (basically applies to the whole rulebook)...

**Comment by kyordhel** [comment]
Verified number of tests along the rulebook
Removed references to Basic Functionalities test
Removed RoboZoo as mandatory test
Removed Basic Functionalities test as mandatory test
Solved references to ??

**Comment by LoyVanBeek** [comment]
Looks good, closing the issue
