### ISSUE TITLE
#Slack group?

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#350]
Maybe there is already too much:

Multiple Mailing lists, a website, a wiki, several GitHub repositories with issues...

But I'm proposing a Slack group, just for off topic social discussions: for example, a team is working at home in the lab, and wants to share a link or video of their stuff working.

This is to maintain a little community throughout the year, and break the cycle of peaks near events and valleys when events are too far away.

For those who are using IRC, Slack is just a new IRC thing for users who prefer an app to a CLI

**Comment by moriarty** [comment]
Sorry- added issue via mobile:

For those who are using IRC, Slack is just a new IRC thing for users who prefer an app to a CLI

**Comment by maximest-pierre** [comment]
I think this is a great idea and this should help the new teams to see what the other teams are up to.

**Comment by iocchi** [comment]
I strongly agree on revising and remodeling all the communication infrastructure of @Home.

In this discussion please consider the following resources that are made available by the Federation to the leagues.

1. Forum already setup for @Home league currently used  by SSPL https://athome.forum.robocup.org/

2. Web space for leagues, see for example 
spl.robocup.org

Full access to these resources will be given to manage and configure the tools as preferred by the leagues.

If you have questions let me know.

**Comment by kyordhel** [comment]
I'm not sure. Formerly TC discussions were held in a Google group/forum,
and all the discussion took place there. Extremely slow. If people barely
answers emails (something they check 5 times a day), I can't imagine going
back to a platform.

For meetings, we used Skype. People turns politician and promises a lot,
but barely any commit is produced. Although it helped a couple of time to
reach consensus. In the end only make sense if EC is involved.

The wiki has a purpose: it should be maintained and updated by the
community including all q materials, publications, and scores. A memorial
for when teams disappear and the content of their pages is deleted.
However, nobody takes the effort of updating he info there.

**Comment by LoyVanBeek** [comment]
The Slack group would be for teams to discuss and chat. A Wiki and TC meetings are still useful and separate, though might be hosted on the same platform. 
But casual chat is very useful to the community as well. The DSPL has this, but a general RoboCup@Home slack chat group would indeed be nice. 

I didn't know about the Discourse-based [forum](https://athome.forum.robocup.org/) on , so I think we should link to it. That would be a place for questions other than the rulebook, where teams can answer questions like "How is such and such done"

**Comment by kyordhel** [comment]
@moriarty Is this Slack group going on or shall we close the issue?

**Comment by moriarty** [comment]
Sorry I took this down last year and then forgot
@LoyVanBeek has created:  https://gitter.im/RoboCupAtHome/Lobby

**Comment by LoyVanBeek** [comment]
Links to gitter and the forum have been added to the README of the rulebook. I have a tab pinnend to gitter, so chat me up :smiley:

**Comment by kyordhel** [comment]
So we have now gitter.im. Shall we continue with the Slack group or can we close this?

**Comment by LoyVanBeek** [comment]
I think we can close this, gitter should work fine.
