### ISSUE TITLE
Stage 1 three-tries: pointless and unnecessary

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#351]
The main idea of giving teams the chance to try 3 times a Stage 1 test was give them time to tune and fix the robot between attempts, allowing them to maximize their performance in multiple initial conditions. However, this year (and in previous one) all three attempts are executed one after the other, so this goal is not met.

In addition, for OPL, there is only two tries which is kind of the same (maybe worst) than having a slightly more complex test with a restart (not enough tries to check robust task execution, but integration can neither be fully tested).

Even worse. The arenas are extremely sub-utilized. Test pipelining have been dropped at least twice, and Trustees and LOC are not happy with the fact that **Stage 1 uses only 1 room per arena in each test**. Arenas are expensive and not using them is a waste of valuable resources. The idea of making three attempts was designed with pipeline in mind so there were at least 2 robots (preferably 3) in action all the time.

**Comment by swachsmu** [comment]
I only partially agree. The main idea of giving teams 3 tries was to get more representative results. A single try may fail just because of bad luck or something that can be easily fixed by just starting the robot again. We explicitly did NOT want the teams to tune for test.
The problem with the restart during a test is a robot standing for minutes in the arena without doing anything and team members running around fixing it. That is also no the ideal way to do.
However, other ideas are more than welcome!

**Comment by LoyVanBeek** [comment]
The 3 attempts are indeed to eliminate bad luck and very good luck, to promote stable, repeatable performance. Improving code between attempts is not the goal. 

The under-utilization of the arena is a consequence of the type of challenges in stage 1: more or less tests for 1 function that does not always include navigation (and thus in 1 room only). 
This year, we also gave each league 1 arena, meaning that the smallest league did not offer any arena time to the biggest league. The arena's were similar enough to allow for distributing teams over them at random, I think. 

Pipelining tests could solve this

**Comment by kyordhel** [comment]
@airglow, @awesomebytes, @HideakiNagano21, @justinhart, @mnegretev, and rest of TC: your thoughts, comments and proposals, please.

**Comment by justinhart** [comment]
Three attempts seems correct to me. If the robots as a whole were better at manipulation and there were teams out there making all of the grasps, then I'd say, "One attempt, and if not, then download the software that <team x> used." I think that this will be a "do it once" type of thing once there are robots that consistently do it on the first attempt.

**Comment by kyordhel** [comment]
No TC replies since Oct 22nd + no change policy. Closing.
