### ISSUE TITLE
Force manipulation in Storing Groceries

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#353]
Storing Groceries replaces the Manipulation (and object recognition) test. It's main goal is to manipulate objects, therefore all points must be scored by solving the problem, not by standing like a tripod and reporting. 

Here the changes:
- The robot needs to open a door
  - There is no help from human anymore
  - It gets additional time for doing so. 
  - the door can be opened at any time. 
- The robot must rearrange objects in the shelf by category
- The robot must move objects from the table to the shelf
- There is no specific order to perform the actions 
- Task driven: we expect empty table and arranged shelf. 
- The robot *may* deliver a pdf report
  - Only manipulated objects are considered.  
  - Allow us to give partial scoring for properly categorized miss recognised objects. 
  - PDF report is just a backup tool
- At least one of
  - cutlery (small)
  - cloth (amorphous)
  - alike (hard to recognise)
  - known light
  - known heavy

**Comment by swachsmu** [comment]
I agree as long as the opening of the door is not mandatory (one half of the shelf is visible and usable). The robot should be able to score with simple objects. I would offer simple and difficult objects at the same time, so that the robot can select what to take. Difficult objects (cutlery or cloth) should score more points. Concentrating on the manipulation makes the test more understandable for the audience.

**Comment by kyordhel** [comment]
@swachsmu I agree with the different object types. We would first need to define the _types_ though, such as small, light, heavy, crystal, cloth, bowl, etc.

Opening the door wouldn't be mandatory but necessary. Half of the objects can be seen and new objects can be placed in the open part of the shelf. If a robot want to see all the objects in the shelf, then it needs to open the door (i.e. no help from human). This, only if we want to make all robots are able to open doors. See #362.

**Comment by kyordhel** [comment]
@airglow, @awesomebytes, @HideakiNagano21, @justinhart, @mnegretev, and rest of TC: your thoughts, comments and proposals, please. We also need a volunteer to update the test.
