### ISSUE TITLE
New Object Recognition Test: What is this?

### ISSUE THREAD

**Issue by swachsmu** [RoboCupAtHome/RuleBook#356]
If we concentrate in Storing Groceries on the manipulation part, there would be space for another test concentrating on visual recognition and human-robot interaction: "What is this?"

The general idea is that a human is walking through the apartment and is pointing to various things (annotated places, furniture, objects, doors, etc.). The robot needs to recognize the pointing gesture, should point at the same thing, and says what it is. The task includes the robot needs to position hinself so that it sees and is able to evaluation the pointing. It needs to follow the human through the apartment.

The Pepper would be an ideal platform for repeating the pointing. The recognition of gestures seems to be there based on e.g. open pose. If the audience hears what the robot is saying, it would be an easily understandable task, which could be scaled from simple to very complex.

**Comment by balkce** [comment]
And if there is no pointing capabilities, the person could always show the
robot the object by putting it up in his/her hand, which has its own set of
issues (blurriness from movement).

**Comment by LoyVanBeek** [comment]
Could also be part of an extension of Speech&Person recognition i'm thinking about (would need to be renamed to 'Question Answering' though): just ask the robot questions about the current environment, eg. "What color is the thing on the shelf", "Name this thing" (while pointing) and the robot goes to find out.

**Comment by kyordhel** [comment]
@airglow, @awesomebytes, @HideakiNagano21, @justinhart, @mnegretev, and rest of TC: your thoughts, comments and proposals, please. We also need a volunteer to script this.

**Comment by kyordhel** [comment]
No major changes in the rulebook for 2019. Rescheduling for 2019.

**Comment by kyordhel** [comment]
@moriarty @justinhart This sounds somehow familiar. Shall we design a variant of a task or this issue is just closed?

**Comment by johaq** [comment]
Closed. Some aspects incorporated into Hand me That test.
