### ISSUE TITLE
Finals 3rd-4th place

### ISSUE THREAD

**Issue by iocchi** [RoboCupAtHome/RuleBook#359]
I suggest to introduce the finals also for 3rd-4th place in @Home as follows:

**10.00-10.30**
3rd-4th place (3 sub-leagues in parallel)
- Jury: 1 TC + 1 external + 1 from teams
- Score: 2/3 previous points + 1/3 jury

**12.00**
1st-2nd place (single track)
- as it is now

**Comment by kyordhel** [comment]
Agreed. If there is no further remark, I will start adding the amendments to the Rulebook as soon as the pending PR are merged
