### ISSUE TITLE
Proofreading and especially 'consistency checking'

### ISSUE THREAD

**Issue by dirkholz** [RoboCupAtHome/RuleBook#36]
Please ALL read the rulebook very carefully, and
* correct typos/grammatical errors, 
* check for consistency (e.g., giving 100 points max. for a test while giving penalties of 100/500 points), 
* clarify whatever remains unclear or is under-specified, and
* quickly notify the (rest of the) TC if anything is unclear.

Let's go! :)

**Comment by kyordhel** [comment]
As for consistency:
    - Penalties of 500 points reduced to -15
    - Penalties of 100 points reduced to -5
    - Open Challenge bonus for Team Cooperation defined to 5 (it was 500 out of 2500, now 5 out of 20).
