### ISSUE TITLE
Network Setup 2019 | The Evergreen Topic

### ISSUE THREAD

**Issue by warp1337** [RoboCupAtHome/RuleBook#363]
Hi all, I would like to discuss/improve/chart the network setup for Montreal. Our advantage over the last years is def. that Nagoya's LOC deployed a smoothly working and incredibly well documented setup already. So, who needs to be added to this discussion?

Let's start the discussion by incorporating the knowledge from 2017 #173

@LoyVanBeek @kyordhel @balkce

**Comment by warp1337** [comment]
Can someone tell me who I need to add to reach the LOC? @LoyVanBeek  @balkce  @kyordhel

**Comment by moriarty** [comment]
@JeffCousineau could you tag the LOC here?

**Comment by maximest-pierre** [comment]
It is quite early to determine the network, but we have someone that is in charge of the network. . We can either transmit all your requirements to him or give him his contact.

**Comment by warp1337** [comment]
Thanks @moriarty  @maximest-pierre . You are right, it is indeed quite early ... BUT the network setup is usually something that can either make people VERY happy on location or, in contrast, can make people very indignant --- leading to constant complaints directed towards the LOC ;) Trust me I've been there.

However, I have taken part in the RoboCup since 2010 (OPL and last year SSPL/OPL both) and I 'witnessed' different setups showcasing extremely different performances over the last years. The point I am trying to make here is, that I a) would not undervalue the importance of a working network infrastructure b) The LOC in Nagoya made an extremely good job, I strongly recommend adopting their setup. c) Especially for the SSPL and DSPL a stable WiFi is essential because these leagues make heavy use of external (local network!) computing. WRT c) I'd like to clarify that **I don't talk about web API's or any other cloud computing** (actually, I personally don't care about the uplink to the www) --- I am talking about a robot with limited computing capabilities talking to a laptop (or whatever) via WiFi. In order to do that, a working network is essential (Am I right? @justinhart, what about the DSPL wifi experience/requirements?). 

That being said, I would like to make a few more adjustments to the 'Nagoya setup' and the rules that were enforced on location (e.g. own wifi's were strictly prohibited, as well as wireless keyboards, or any other kinds of wireless transmitters ... you name it.) but that's something we could discuss later.

Please don't get me wrong. I know organizing this is looooooot's of hard work. However, I believe that, by adopting the Nagoya setup, one can actually make the LOC's life easier because it already implements a great deal of best practices.

So here's the Nagoya 2017 network guideline https://github.com/RoboCupAtHome/RuleBook/files/993340/RoboCup2017_WirelessGuideline_03.20170425._extracted.pdf

I would also strongly suggest to read through our 2017 discussion in #173 

Thanks!

**Comment by warp1337** [comment]
Oh, BTW, @HideakiNagano21 was part of the LOC in Nagoya, I guess he's the guy your sys ops should talk to.

**Comment by justinhart** [comment]
In my conversations with Toyota, they have emphasized that the HSR is
designed around the idea that a good LAN is important to provide offboard
compute capabilities to the robot. I agree on this point The internal
network seemed adequate for last year's competition. I think that, looking
forward, we should consider even expanding this if possible. Northeastern
had problems, and, yes, there are engineering solutions to their problems,
but I only see the amount of network communication going up. The HSR has 4
potential color feeds, a lidar that talks internally over ethernet, depth
images, and no way to beef up the compute infrastructure inside the robot,
in an academic environment that is pushing more compute-heavy resources
like deep learning. I say, look at last year's internal network as a
victory, but turn a cautious eye to the amount of network bandwidth
potentially required for next year.

I know that this conversation primarily concerns the internal network, but
the external network really needs discussion. We were pulling something
like 1kbps to the outside world last year, and this was a huge problem for
us. We need to carefully consider that the HSR and Pepper are both managed
partly off of central software repos. My team owns 2 HSRs. Last year when
we wanted to sync something that had been synced on our other HSR, an
operation that would have been trivial on my home network, it became an
all-day ordeal. If I recall, the solution ended up being going offsite and
copying files to a USB drive. I know that next year, we'll probably be
trying to send training data to a cluster back at UT. So, definitely agreed
on the point that you're discussing, but I'd like to see bandwidth to the
internet improved.

**Comment by maximest-pierre** [comment]
I will take these point to our next LOC meeting. I understand the SSPL and DSPL are going to need a lot of bandwidth. I will be updating this thread when I get more information about the networking from our network guy.

**Comment by warp1337** [comment]
@maximest-pierre @justinhart . Perfect. Thank ya'll.

**Comment by LoyVanBeek** [comment]
Limiting bandwidth per team is a good idea, for the rest I would like to keep the Nagoya2017 setup with perhaps more bandwidth going externally.

**Comment by justinhart** [comment]
I actually liked the idea of having exclusive access to the arena network
during competition, and having teams on practice networks when not in
competition. If, however, we could extend this to simply having one essid
for each team and that's what they use for both practice and competition,
that seems even better. Then there's no hurried reconfiguration of the
network between rounds.

Justin

**Comment by LoyVanBeek** [comment]
Ideally, there's exclusive bandwidth for 1 team during challenges and evenly distributed bandwidth during training. The hassle of arranging this is not manageable though, so then I would opt to keep the bandwidth limited at all times, also during competition.

**Comment by kyordhel** [comment]
@justinhart could you please delete the leading text when replying an issue from your email?

**Comment by justinhart** [comment]
Ack! Yes, I'll make sure to do that from now on.

**Comment by maximest-pierre** [comment]
Last night, we had an LOC meeting, I took all the points that were written in this thread and presented them to the rest of the LOC. We are going to have another more technical meeting with the venue for everything networking and power. This meeting will be in about 2 weeks.

**Comment by warp1337** [comment]
Awesome. Thanks. Please keep us posted.

**Comment by kyordhel** [comment]
Off topic so I'll delete this later.

@maximest-pierre, could you please send me the details (name, affiliation, email) of the @Home LOC to add them to the OC? It would be handy if they are up to date on what is happening in the OC (number of accepted teams, requirements, etc).

Thanks in advance

**Comment by kyordhel** [comment]
I was wondering whether it can be done with a radius server or not.

When I was in bachelor I set up a small radius server for 128 machines in theory (we never used more than 12 in practice, all downloading torrents through the uni gateway). It had radius MAC filtering and a scheduler so dynamically it was able to disconnect certain clients, keep them off, and allow them to reconnect later. Also I remember reading (that part was not used) it was possible to set a bandwidth quota and limit to each mac address.

Setback is that we would need tight coordination between the OC and the Network people, so they could white-list the competitor while at the same time banning the rest. I think this can be done with a web interface and some python/bash scripting.

**Comment by warp1337** [comment]
*bump* Any updates from the LOC?

@kyordhel Nice idea, but I agree, hard to enforce and maintain during the actual competition. Limiting the bandwidth at hardware-level for each subnet should also be possible though. 

I'd like to remember all of you that switching networks, including the tablet, on the Pepper is not _really_ reliable/robust, e.g, if you have two networks your list, sometimes Pepper switches between them randomly ... I bet this will cause serious panic attacks on site ;)

**Comment by maximest-pierre** [comment]
I got no update right now for the network for @home but tomorrow we are discussing the network in general.

**Comment by RemiFabre** [comment]
Hi,
Any news on this topic?
Thanks,

**Comment by warp1337** [comment]
As discussed earlier in this thread I am more interested in the _local_ connection bandwidth, i.e., from the robot to an external computing device. Again, have a look at this [document](https://github.com/RoboCupAtHome/RuleBook/files/993340/RoboCup2017_WirelessGuideline_03.20170425._extracted.pdf)

**Comment by warp1337** [comment]
What's the escalation of *bump*?

**Comment by LoyVanBeek** [comment]
@maximest-pierre any updates?

**Comment by maximest-pierre** [comment]
We are currently having problems with the venue on the networking side. The venue is not used to have this much network traffic on its infrastructure. I hope that this issue will be resolve soon.

**Comment by warp1337** [comment]
Thank you for the feedback! Fingers crossed.

**Comment by kyordhel** [comment]
No venue is, ever. When Jesus Savage organized RC in 2012, the contact person for the venue (the biggest convention centre in Mexico City) went WTF after checking the requirements for Internet, 4 times higher than the max capacity of the venue's infrastructure. They are used to host suits and tuxedos, not over 4000 tech freaks much hungrier of bandwidth than of food.

**Comment by warp1337** [comment]
Besides the outbound connection, @maximest-pierre can you make a comment on the local network? Did you have a look at the Nagoya setup?

**Comment by warp1337** [comment]
*bump*

**Comment by maximest-pierre** [comment]
I finally got some news. The local network is 1Gb/s switch on local. The outbound connection is going to be 10 Gb/s. We are also finalizing the plan for the wifi, IP assignment, and VLAN assignment.

Also, is somebody bringing a server with them? I would like to know beforehand to set up electrical and networking for it. (I will probably send an email to the mailing list later)

**Comment by justinhart** [comment]
Probably several teams will bring servers. I would count on almost 1 per
team.

**Comment by kyordhel** [comment]
@maximest-pierre please define *Server*. Hardware-wise, many gamer computers won't qualify as server, but their sustained power consumption would (e.g. i7 with two nVidia Quadro in bridge). I remember at least team Tech United Eindhoven and team AUPAIR having several desktops on their tables.

And servers won't be our only electrical problem. We need support for
- Power Wise
  - Robot charger 400W (Tiago)
  - Universal chargers for batteries (LiPo, NiMh, Lead/Acid). At least 3 per team, average 100W each.
  - One laptop per team member (average 8, worst case 24). Average 120W each (90W~180W).
  - One gaming desktop/server per team (1~2kW)
  - Soldering iron unit (60W)
- Network wise
  - 1 Gigabit ethernet cable per table.
  - 1 8-port gigabit switch per table (or none, teams will bring their own)
  - No wireless allowed

@justinhart Can you give us the power consumption of the HSR?

**Comment by justinhart** [comment]
It's written in Japanese. I'll email Toyota.

Justin

**Comment by maximest-pierre** [comment]
What I mean by server are the bulky power hungry server kind 1000w and more. 

The planned available power for a team is 120V 15A 60Hz (1800W)(Might change). 
Wireless is not allowed in the venue.

Right now we are planning to only give 1 Gbits per table.

That's all the information that I have for now. Also, things might change.

**Comment by warp1337** [comment]
@maximest-pierre Thanks for the update! Will you be able to limit the bandwidth for the arena network per team/vlan? That info would be great! I would also vote for a hard limit per team.

**Comment by kyordhel** [comment]
For the record, this is doable with *freeRadius* and a Mikrotik Router OS:
1. Setup the user/pass in *radcheck* table,
e.g. ```INSERT INTO radcheck VALUES ('','warp1337','Cleartext-Password',':=', 'warpass');```
2. Setup the up/down bandwidth limit (speed) in *radreply*
using **the same user name** as in *radcheck*.
e.g. ```INSERT INTO radreply VALUES ('','warp1337','Mikrotik-Rate-Limit',':=','56M/100M');```

Former example should limit the hard bandwidth usage of @warp1337 to 56M up and 100M down (on server side excluding noise, channel could use slightly more). There are also means to set a max overall usage quota.

Is important to remark that the router's OS/firmware must support setting a bandwidth limit. If this is not the case, the Radius will only grant (or not) access, but no limit will be imposed.

**Comment by warp1337** [comment]
Thanks, good to know.

**Comment by warp1337** [comment]
@maximest-pierre Can you give us an update? Actually, we are currently testing a setup for the German Open. If you are interested in the topology and the hardware we bought let me know.

**Comment by maximest-pierre** [comment]
It's going well the network topology is being finalized right now. It should be ready in the next week or so. Yes, I am interested in the topology and the hardware to compare it to what we have.

**Comment by warp1337** [comment]
Alright! We bought a Unify EdgeSwitch (24 ports) that hosts 9 VLANs. Additionally, we bought 3 Unify AP Pros (https://store.ubnt.com/products/unifi-ap-pro). Each AP provides 3 wifi SSIDs that are connected to a dedicated VLAN (one per team).  We limit the bandwidth per SSID to 10 mb/s up and download. All SSIDs have internet access which is routed by a Cisco consumer level router (also connected to the switch, std. gateway).

We did some tests today and are confident that the setup will do just fine. I will gather some data wrt total inter-/intranet traffic during the German Open (9 Teams at OPL/SSPL).

**Comment by warp1337** [comment]
@maximest-pierre Can you give us an update on the network situation?

**Comment by Atine** [comment]
Hi, do we have updates on this issue?

**Comment by warp1337** [comment]
*bump*

**Comment by warp1337** [comment]
I guess we all have experienced how important this issue actually was. Please, also look at the initial post date of this issue (Sep. 20**17**) I guess we can close this issue now. However, I strongly suggest to write down the lessons learned somewhere.

**Comment by RemiFabre** [comment]
We could setup the 4G plan for 2019:
#384 
Do we have someone from the loc to talk to?

There seems to be 3 network providers:
https://www.whistleout.com.au/MobilePhones/Guides/Best-phone-plans-for-travellers-in-Australia

Telstra seems to be the best? 59 dollars for 4GB for a prepaid phone.
https://www.telstra.com.au/mobile-phones/prepaid-mobiles/plus-packs#freedom-plus

**Comment by warp1337** [comment]
We should write this down in a dedicated document, including best-practices and lessons learned targeted at OC, LOC etc ...

**Comment by fabricejumel** [comment]
Florian,
could you send me your adress mail
fabrice.jumel@gmail.com

Regards

2018-07-13 13:10 GMT+02:00 Florian Lier <notifications@github.com>:

**Comment by moriarty** [comment]
@warp1337 Close this issue? Or just edit the title to 2019?

**Comment by warp1337** [comment]
Yo! @johaq just informed me that we see ~290GB traffic after 2 days at the German  Open 2019. I believe there are 9 teams.

**Comment by LoyVanBeek** [comment]
Some 20GB per team per day...

**Comment by johaq** [comment]
I will post stats for the whole competition after the competition next week.

**Comment by warp1337** [comment]
@johaq *bump* :)

**Comment by johaq** [comment]
Ok. So at German Open we had 9 teams with on average 9 team members. The competition took place from Wednesday noon until Sunday noon.
During the first 2 days we had traffic of 300GB(!!) with about 45 clients. I routinely checked for clients that were using a lot and reminded teams to be mindful. Then, during the last two days we "only" had 150GB with still around 45 clients. So either teams use a lot more during setup days and we need stricter monitoring then or the frequent reminders worked. Overall we had no big outages which is great.
My takeaways for Sydney would be to expect 15GB of traffic per team per day which is also in line with what we have seen last year at German Open. Also on average teams have 5 clients connected to the arena network but some teams have a lot more and other teams less.
Does someone know if Colm is reading this thread? If not I will also send these conclusions in an email.

**Comment by warp1337** [comment]
Also maybe keep this in mind https://github.com/RoboCupAtHome/RuleBook/issues/363#issuecomment-385353241 (comment from German Open 2018)

**Comment by LoyVanBeek** [comment]
As for SSIDs: I had a brief chat with Timothy Wiley of the Soccer SPL LOC and he said the number of SSIDs @Home wants (1 per team, for 25+ teams at a world cup) in one area would leave no bandwidth besides the SSID overhead. So that needs to change.
In Sydney, there was was SSID per arena AFAIK, which access allowed via MAC-address that could be entered in some online form. 

I didn't bother with the network, I just heard my team mates complain occasionally :smile:

**Comment by maximest-pierre** [comment]
Feedbacks from the team were positive to this setup. Some teams were confused on how to register there mac address but other than that everything seems fine.

**Comment by RemiFabre** [comment]
The network quality was excellent in my opinion, both wired and wifi. The local "network team" was very reactive.

**Comment by MatthijsBurgh** [comment]
The Wi-Fi speeds to our HSR were horrible. During the finals we used our own consumer grade router which provided way better wireless speeds.

Also using routers on your robot in client bridged mode wasn't possible. This is really required, because you need same subnet acccess, when using ROS 

The network in the teamarea was fine. Not the fastest internet I have seen on RoboCup, but pretty stable and sufficient speed.

**Comment by kyordhel** [comment]
I see little contribution in stating:
- this setup was awesome
- this other setup is a flipping crack

... unless we have the specifications and schematics of them. Please refrain your cheerleaders and focus on the engineering share.

What we know is:
- The overhead of 36 overlapped SSID will virtually use all bandwidth
- Sharing the same SSID but connecting to different vLAN provides much better performance and is cheaper
- The vLan must be accessible from the arena and the team area (wired?)
- In order to bridge, the devices must share the same subnet
- Directional antennas may work better but they are expensive

For my network people to research.
1. Is it feasible that all three leagues share the same SSID and just connect to a different (bridged) Access Point and work through the vLan?
2. Is it possible to have all devices in the same vLan work under the same subnet?
    - If not, which are our alternatives?
    - Is it possible to use routers to redirect traffic and make it transparent to ROS?
    - Would VPN work better in this case?
3. Would it be possible to use a radius-like server to authenticate clients trying to access the WiFi so only the competing team and the next one receive bandwidth, as well as all the network configuration so the device thinks it connected to a particular local network?
    - This would produce a super-strict schedule
    - VizBox would be necessary for this

Also, it would be nice if teams provide a list of network requirements.

**Comment by awesomebytes** [comment]
I don't know if it is a fair comparison but this year SSPL only had 6 teams and in Stage 2 just 3... in reality 2 competing. The usage of the WIFI was very low. Our team didn't have any issue as we already minimized our traffic taking this into account (50kbps with Rviz open with the debug stuff we need, if the reference number works for anything). Other teams complained that it was too slow. In my experience the network setup was very good, almost better than some days in the lab. Just don't stream image topics or massive TF trees.

Teams in the very back, specially (I think) OPL that had the furthest arena from the working tables, mentioned that they (and us, we were also in the very back, and the robot has a pretty crappy WIFI) had troubles booting the robots from there as the WIFI signal was very weak (the directional antennas were pointing in another direction, towards the arena).

**Comment by moriarty** [comment]
I think the HP / Aruba sponsorship and support they provided was great.
The only things missing this year:

1) WiFi coverage in team areas- the team areas were largely forgotten about.
2) The bridging issue which effected TU/e. I don’t know if any other teams had as much issues.
3) The Lack of connectivity between Official WiFi<->Team Area (which is on purpose) makes it difficult to transfer code/train/debug/etc... but we need this air gap to ensure there aren’t people connecting to robots from the team areas during their competition runs.
4) External Compute Area, was a last minute addition: apparently teams only need it in stage 2.

**Comment by warp1337** [comment]
I like the one SSID + multiple vlans approach. It think this is easily achievable. Traffic shaping on the other hand, additionally time/schedule based, is a different story. But I guess we can find this out?

One more remark: no matter what solution we implement, it cannot involve **installing kerberos, radius certs or whatever** bc teams will flip if they have to install additional stuff on their robot. This can however be mitigated by let them know in advance. In the ideal case they dont have to configure the network setup at att.

**Comment by LoyVanBeek** [comment]
I'd go for 1 SSID per arena. Otherwise, wifi clients go roaming and try to stay attached to any access point that just works, even if there is a more powerful signal from a different AP. Meaning: if you drive past another arena and attach to that AP when it has the same SSID. 

This won't happen with different SSIDs for each arena.
