### ISSUE TITLE
Roadmap: Standardization

### ISSUE THREAD

**Issue by MatthijsBurgh** [RoboCupAtHome/RuleBook#364]
In opinion of some Tech United members the league requires standardization for multiple reasons.

# Why
- To create a baseline software set, which enables new teams to be competitive from the start
- To enable easy sharing of code without (major) implementation issues
- By sharing standardized code, teams can focus on new development instead of reinventing the wheel or fixing their 'bad' software. This is the RoboCup philosophy.

# What
In the league ROS is used by (almost) all teams. ROS makes it possible to easily swap isolated parts of software. The ROS API is the perfect interface to standardize.
With the use of machine learning, the use of GPU's is increasing. Therefore it might be useful to also standardize some hardware parts related to this. (Maybe with some sponsoring by Nvidia)

# How
- Phasing in by a few new standards each year.
- Evaluation of performances to determine a 'default' node for a specific feature. This requires a list of minimal capabilities of this node.
- Standards should be determined by the teams, not the committees.

# To make it work
- Mandatory use of software in accordance with the standards.
- Good system architecture
- Good acces to the code of all teams
- Good documentation
- There should be a meeting/process/workshop/etc. which makes it mandatory for teams to participate in the development of the standards. (This doesn't mean teams should be forced to travel for this)
- Good long term planning

**Comment by balkce** [comment]
Just to add some other threads that are related to this topic:

#129 
#257 

I agree with this, definitely. However, in terms of roadmapping it, it'd be good to have year-to-year milestones to have this achieved in, say, 5 years. Like you've stated: "Phasing in by a few new standards each year." Any specific ideas of what standards, which years?

Do consider however, that there is such a thing of over-standardizing to the point that everybody has the same software/robot. I know that this is not what you want, so a good middle-ground should be the ultimate objective: provide new teams a good software base to start off from, but not negate innovation from more established teams by limiting them to the standard itself (e.g. the ROS topic only allows a PNG image, not RGBd).

**Comment by LoyVanBeek** [comment]
I've been thinking about this as well. 

I think everyone should be able to deviate from any standard but at the risk of getting behind the rest. Of your deviation should be so good everyone adopts your (small) deviation and make that the new standard. 

So, for every functionality, pick the thing that works best on the competition and declare that the baseline/standard for next year.

**Comment by kyordhel** [comment]
Abandoned.
