### ISSUE TITLE
[GPSR] Maybe check that robots understood intention rather than exact sentence

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#37]
If the robot does not exactly repeat the command but tells the command in its own words (correctly) this, to me, signifies some more intelligence than repeating the command word for word. 
If we want this, that should be told so in the rulebook explicitly.

**Comment by kyordhel** [comment]
Solved on GPSR, Section 5.1.4, subsection 3 and 4.1

Also added 4.2 with rules for missing information retrieval

**Comment by LoyVanBeek** [comment]
The additions fix this issue, so closing. I added a reference from the task to the remarks here,
