### ISSUE TITLE
Proposal for New SSPL Tests

### ISSUE THREAD

**Issue by AMR-** [RoboCupAtHome/RuleBook#372]
Hello all.  I have 3 new tests to propose for the SSPL (and potentially the other leagues).

In these tests, Pepper and a human will work together towards a purpose, just as we hope for humans and robots to partner and collaborate in real-world environments. The proposed tasks will also increase the entertainment value of the competition.

1 Replicating a Configuration of Objects
----------------------------------------
In this task, Pepper is allowed to view a configuration of objects. A human in a different room (or separated by a screen) has access to all of these object arranged arbitrarily. First, Pepper must describe the scene in front of it and instruct the human how to arrange their objects in an identical manner. Second, Pepper moves to the human’s area and views their setup. If the setup is wrong in
some fashion, Pepper will instruct the human to make the appropriate changes.

Details:
When the task begins, Pepper can view objects in front of it. Objects can include furniture such as tables, chairs, and stools, as well as smaller objects such as food containers and blocks. Objects could differ in size, color, and shape. Pepper will describe what is sees, using relational language. For example, “Place the green can on top of the yellow plate that is in the center of the table.” This first part of the task is limited to 5 minutes. Afterwards, a tournament official will go to the human’s configuration and introduce at least one additional error that Pepper will have to correct. At this time, Pepper is led to the human’s area for the second part of the task. After viewing the scene, Pepper should assess the errors present in the configuration and give additional instructions to fix them, such as “There should not be a coke bottle in this scene” or “The water bottle should be on the red plate, not the yellow plate.” Successive rounds might have increasing number of objects.

Scoring
Pepper will have 5 minutes for the first phase (description) and 5 minutes for the second phase (critiquing the human’s results). Teams will be scored according to the number of objects correctly placed in the first phase, both in terms of absolute position and in relationship to each other, and the number of successful corrections in the second phase

2. Balloon Sorting
------------------
Balloons are in room 1. Pepper must gather the balloons from room 1 and put them in room 2, while following instructions. A human participant might instruct it saying, “bring at least 5 red balloons to the living room” or “leave 2 blue balloons in the other room.” This is a competitive, timed task. 

Details
There are two rooms in this task. They may be labeled, such as the “bedroom” and the “living room”. At the beginning of the task there are 10 balloons total in one of the rooms. There is a ceiling fence in both rooms so that the balloons do not rise above 8 feet high. Balloons are yellow, red, green, and blue, in any number of each color. Each balloon has a string with a loop on the bottom at the height of Pepper’s head that can serve as a handle that Pepper is capable of grabbing.

A tournament official gives Pepper instructions regarding bringing balloons to the living room. These instructions could be piecemeal (“Please bring 3 red balloons. Now, please bring 2 blue balloons.”) or more expansive (“Please bring all balloons to the living room.”). Instructions could change over time, as a human changes their mind. For example, “I want 4 red balloons, not 3.” Pepper could be instructed to bring balloons back from room 2 to room 1, too, as in, “Remove the yellow balloons from the living room!” If Pepper receives “con- flicting” instructions, it should follow the most recent instruction (as well as previous non-conflicting instructions). Humans collectively will issue no more than 5 instructions total over the course of the task.

Scoring
Pepper will have 10 minutes to complete the task. The score will take into account what instructions Pepper was able to complete within the allotted time (judged by number of balloons moved out of total balloons to be moved). Balloons moved in error will count against the score.

3. Pepper Self Knowledge and Human-Understandable Communication
---------------------------------------------------------------
Tournament officials prepare a series of commands (hidden from competing teams) which they issue to Pepper during this task. After performing them, Pepper must describe what they just did in a high-level, human-understandable fashion.

Details
Tournament officials prepare a series of low-level commands that are not known by teams beforehand. These commands could include standard verbal commands, and could also be anything in the standard naoqi API, that will be fed to Pepper as a script. At the beginning of the task, tournament officials instruct Pepper to start making note of its own actions. Then, the tournament officials issue commands verbally or electronically for Pepper to execute. After carrying out the commands, Pepper is asked to describe what it has done in a high-level human understandable way. For example, if a command was issued to rotate Pepper’s shoulder a certain number of degrees, Pepper might say, “I raised my arm” or, “I wave hello in greeting.”

Scoring
Pepper has 5 minutes for the description part of the task. Points are awarded based on how much of the actions are encompassed by the description (maximum points for a description that touches upon each action performed) as well as quality of a description. Saying “I wave hello” is higher quality than “I raised my arm,” however if such a higher-level meaning doesn’t make sense in context points may be deducted instead.

---

An additional thought: if we have a number of tasks (in stage 1 or stage 2) teams could choose n out of N (i.e. 4 out of 7), for example to complete.  (It seems like there is something along these lines already, where teams are allowed to opt-out of certain tests.  This would be different, where there are a number of tests and each team can choose up to X tests to complete.)

If there is interest in adding these tasks, then the CMU team is committed to being engaged as desired in specifying these tasks further, to the level of detail and specificity required for the official rulebook.

Thank you.

**Comment by kyordhel** [comment]
Thanks for supporting the rulebook creation @AMR-, this is a good and motivating example for teams. I think I speak in behalf of the TC when I say that we really appreciate such enthusiasm.

Unfortunately, your proposals can't be accepted *as is*. Is simply too much information for a single issue  and it would be virtually impossible for us to track all changes here. Therefore, I would like to kindly ask you to submit once more your proposals following [these guidelines](https://github.com/RoboCupAtHome/RuleBook/wiki/Guidelines). My advise is to split this issue in four contributions, three pull requests with the test you are proposing, and one more with the changes requested in the additional thought.
