### ISSUE TITLE
Q: Pepper has no USB drive

### ISSUE THREAD

**Issue by AMR-** [RoboCupAtHome/RuleBook#373]
In 3.5.1, it says that teams are to collect data and store it on a USB stick.  Pepper has no USB slot, so in the SSPL I presume we are to put a USB stick in a computer which will communicate with Pepper over the network, and give that to the TC at the end?

**Comment by moriarty** [comment]
@awesomebytes what did the SSPL do last year?

**Comment by awesomebytes** [comment]
There is a USB port in the head but it's very hard to access. I haven't
tried to plug a pendrive in it. If it's lacking some kind of kernel/driver,
it won't work cause of root tho.

I guess doing a copy thru the network is the easiest solution.

**Comment by mtlazaro** [comment]
Dear all,

last year the TC opened an issue on Github where teams could add links to
shared folders with the data.
https://github.com/RoboCupAtHome/Nagoya2017/issues/7

This simplifies the process of collecting USBs for each test/team/league.

And we could take some time to upload the data so there was no problem in
using a different laptop.

Best,

Mayte.
SPQReL Team Leader (SSPL).


2017-12-13 23:12 GMT+01:00 Sam Pfeiffer <notifications@github.com>:

> There is a USB port in the head but it's very hard to access. I haven't
> tried to plug a pendrive in it. If it's lacking some kind of kernel/driver,
> it won't work cause of root tho.
>
> I guess doing a copy thru the network is the easiest solution.
>

**Comment by johaq** [comment]
As far as I know the TC decided last year to not score data collection because of time constraints.
So it was not relevant for scoring but nonetheless teams shared data at the link provided above.

**Comment by kyordhel** [comment]
@RoboCupAtHome/technical-commmittee  must add a remark or note in the test regarding how this will be handled in SSPL

**Comment by warp1337** [comment]
Accessing the USB port requires the head service hatch to be open, just saying :)
