### ISSUE TITLE
Latex compilation link gives 500 Internal Server Error

### ISSUE THREAD

**Issue by tkelestemur** [RoboCupAtHome/RuleBook#380]
https://latexonline.cc seems to be down.

**Comment by moriarty** [comment]
Correct.

I will open an issue with @aslushnikov in aslushnikov/latex-online. And if needed check for an alternative.

**Comment by aslushnikov** [comment]
LatexOnline is back to life, thank you for the heads-up.

**Comment by moriarty** [comment]
:+1 thanks @aslushnikov
