### ISSUE TITLE
Q: Using the public dataset/database

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#383]
Where can we find the public dataset that is discussed in the rule book?

The section 3.4 "Data Recording" details how the data should be recorded by the teams during the test. As an incentive, most (all?) tests award extra point if data was properly recorded. Yet I can't find a link to the database, nor any mention of it in the TDPs I have read. Is it actually used? Where can we find it?

Thanks,

(it seems that I don't have the rights to add a label)

**Comment by LoyVanBeek** [comment]
Unfortunately, we don't have a big webserver we can put stuff on. @dirkholz would maybe arrange some storage space at Google but I don't know the status right now. 

If you want some data, I have that at home on an external HD and can send what you are interested in. 

This is way less than ideal, sorry about that.

**Comment by AMR-** [comment]
I would also be interested in this.  Is there some way I can communicate with you privately to arrange shipping logistics?

**Comment by kyordhel** [comment]
@LoyVanBeek how much data is it? I might be able to arrange something with Pumas.

**Comment by LoyVanBeek** [comment]
Tens of GBs, not sure how much exactly. I offered everything on the mailing list after the tournament, IIRC. Each challenge had a separate WeTransfer link.

**Comment by kyordhel** [comment]
@LoyVanBeek at least 50GB (tests of TOP3 teams in 2017) I think is doable, but I'll check. If not, a MEGA link would do it.

**Comment by airglow** [comment]
I gonna ask if our university may can host it.

**Comment by LoyVanBeek** [comment]
Maybe I recalled incorrectly. I did not send out WeTransfer links after RoboCup Nagoya and  I don't have the data on my laptop or external HD. I do have the data from the European Open 2016 though and from Leipzig 2016:

# European Open 2016:
- [All challenges](https://mega.nz/#!FhMnAYQS!P22mTNvfDjU2GHf02G3omgmS715dQSURFTLuUfkdxic)

# Leipzig 2016
- [Finals](https://mega.nz/#!Y4czyLST!2TotbyL53DA2iIG6oZ9QkcEf94ktpm2_btJltj_J2dE)
- [Following & Guding](https://mega.nz/#!dwU1XRQB!czz2BtGLM5-ewaviBdtUIl62kECn3dJXljk50KB_7t4)
- [GPSR](https://mega.nz/#!UlFk3ZCQ!ooe0V2yksQ-3X35uIk8d-on8Plzh-CGbwDPoyvVa43Q)
- [Manipulation & Object Recognition](https://mega.nz/#!5k1FxAzY!DgtpcSjdOQmfQUVRm5iYoOuZ8r7h7G2GXMtjORsNjME)
- [Navigation](https://mega.nz/#!As9XiIzD!wYAWcquTKl6jBf2IifpnliRNQ34Ddhwe0X-pyEhebeE)
- [Open Challenge](https://mega.nz/#!R4EVwKKQ!2RgqoO2Fm8ba87yFcZKgIpI6mwHcaAvyo7_FR9_KNfE)
- [Restaurant](https://mega.nz/#!lpFjQTAS!wOO0ieAedr-JDrh166dOOqilMWBGsA3_Ij5t4an1mdI)
- [Speech Recognition](https://mega.nz/#!ts02iYRQ!L3McBFzodJG0UTmauCj2crSapmAr8GWwtB4FLGzQlEs)

**Comment by moriarty** [comment]
@kyordhel Could you create an additional label for items/topics which should be discussed in a future meeting?

I think this topic is very useful and we should have an approach to how it's handled going forward.
Maybe @dirkholz could get some space, but Google isn't a sponsor of RoboCup... so maybe it could be provided by Toyota or Softbank etc... It would still be best to have a decision and add some info to the wiki on how/what/when data is added to the dataset.

**Comment by RemiFabre** [comment]
Thank you for the fast answers !

Maybe the links collected in this issue should be added to the ReadMe of the git repository?

I'll keep the issue open a few more days to see if more data is found (Nagoya and pre-2016) and if a different storage platform is agreed on. Would a team controlled DropBox be an option? If so, I could try to arrange it.

**Comment by LoyVanBeek** [comment]
Links in a README would be good indeed, it's a shame already we need to piece together the data like this. 

Could you open a PR with that, or add it to the wiki at https://github.com/RoboCupAtHome/AtHomeCommunityWiki/wiki?

**Comment by RemiFabre** [comment]
(Pull request created)

**Comment by balkce** [comment]
Pull approved. Thanks for this.

**Comment by RemiFabre** [comment]
up! Have you found the rest of the data?
Again, if the main issue is the storage location, we can try to arrange something
