### ISSUE TITLE
Q: Actual state of @home's cloud computing usage and relying on 4G for internet access

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#384]
As internet stability seems to be the number 1 preoccupation when discussing cloud computing, why not rely on a 4G device as a backup internet connexion?
Are cloud services actually used during the competition?

More details:
## On 4G
I have read through all the RuleBook issues relevant to this topic and most 2016+ available TDPs. The only mention I can find of a 4G internet connexion is in #128 by @LoyVanBeek and it wasn't further discussed. Is there a rule/reasons against it? If not, I can see 2 ways of doing it:

1) Teams are responsible for handling this if they want to.
or
2) The OC/TC/LOC could have "official" 4G devices that are used on the competing robots.

One of the perks of option 2) is that the devices could be installed with monitoring software (the logs would then be used if cheating is suspected)
 Also, this solution would naturally be independent from the ambient wifi usage (#363) and pollution (the device could be tethered with the robot). 

## On cloud computing
We believe that the added value of cloud computing for robotics is huge. For a new team like ours, it's also an opportunity to access state of the art solutions (be it commercial ones) in areas where we're not specialists and focus on areas where we are.
Some TDPs mention cloud services (Google speech API, facepluplus, skybiometry) but were they actually used in the past competitions? Or were network issues too impactful?
We're trying to assess if relying on cloud services is a good idea.

Best regards,

**Comment by maximest-pierre** [comment]
I can confirm that some teams uses cloud computing service. At Walking Machine, we are using Google speech API. If I remember correctly the rules are that we are allowed to use 3 cloud computing max and declared it a month before the competition. Also, the robot must be able to complete the task even when there is no internet or unstable condition. At each of the competition, the internet is provided by the LOC. 

As a side note: Building a reliable network for 4000+ people is hard.

**Comment by RemiFabre** [comment]
Building a reliable network for 4000+ people is indeed hard. I come from the humanoid league and have witnessed terrible network quality.

A few years ago, betting on stable internet on site would have been crazy, but Nagoya's performance on the issue was very good.

**Comment by kyordhel** [comment]
@maximest-pierre 
1. Can the LOC guarantee the availability of a strong 4G signal in the venue related to @Home?
2. Can the LOC help teams to hire unlimited 4G connection with a local provider only for the duration of the competition?
  - If so, all teams should have access to the information and the same chances.

Regarding Open Platform League, I don't care, all is team's responsibility. For the Standard Platform Teams, all teams must have access to it and, if a device is to be used to ensure connection, all teams must have the same and LOC shall provide assistance to acquire them.

**Comment by maximest-pierre** [comment]
1. yes
2. no (No one does unlimited in Canada with sustained max speed)

**Comment by kyordhel** [comment]
@maximest-pierre Ok. Regarding point 2, we need plans then. Doing quick maths (please don't recall the meme), speech recognition wouldn't be a problem, but other type of data like localization or object recognition might have used all available high-speed bandwidth by the first day.

Let's say we want non renewable 3GB/month prepaid. What would be the cost? Do you think is possible you can buy about 24 of these packets (teams would need to transfer you the money first) so they can be delivered during setup days?

**Comment by maximest-pierre** [comment]
The quick math for it is around 50$ per 3gb slice. We will still need to check with the carrier to make sure that we can buy as much slice as we need without a slow down in quality.

**Comment by RemiFabre** [comment]
I must admit I forgot how different the prices are depending on the country. I'm currently paying 10 euros/month in France for 40 Go of data, stoppable any time (not bragging).

Even at 50 dollars per 3Go, we would pay for it without a doubt. What would change is the effort put into optimizing data usage

**Comment by awesomebytes** [comment]
Hello, I just would like to add my two cents as for a project I needed to
evaluate the viability of public 4G as the main network to transfer real
time information (HD video & audio + some extra data, think TF, 1-3MBps
approx). My findings were that the Telecom companies we tried would lower
your bandwidth suddenly at any time there was a peak of usage in the
network. So any day by the lunch break, just after work time, at dinner
time and at moments I could not really give an explanation what was going
on... The connection would not get thru more than a 10-20kbps if you tried
to send a continuous stream of data. Interestingly, if you did send chunks
of data from time to time (a couple MB every 10-20s or so) it would
-usually- not drop. Once the speed dropped you could only wait for it to
recover and it took plenty of minutes. When contacting the Telecom
companies about it they just said they could adjust the speed based on the
network needs.
In any other time of the day it would work super nicely tho.

This was tried in two different countries with very similar results. This
was 3 years ago.

I know it may not be surprising info and it's not very detailed but I hope
it helps someone to know this may happen.

For something like using cloud based speech recognition should be fine!

**Comment by RemiFabre** [comment]
Which countries was this performed on?

**Comment by awesomebytes** [comment]
@RemiFabre Spain and UAE.

**Comment by LoyVanBeek** [comment]
Please do keep in mind that some functions do need to have a very low latency, so localization with laser scans will need local processing anyways. I think that if you use it for face or object recognition, you can deal with delay/latency measured in seconds. Speech recognition is already annoying with such a delay. 

@RemiFabre I want your 40Gb/mo for 10 euros. The EU roaming law isn't bring that to NL yet.

**Comment by RemiFabre** [comment]
@LoyVanBeek Roaming has been making progress lately, maybe some day... And it's 40 GB :D

**Comment by kyordhel** [comment]
@maximest-pierre Any updates on this topic. We might need up to 20 of these devices for the competition.

**Comment by maximest-pierre** [comment]
I am going to check this out later today and come back with a more definite answer. This might also impact some of the leagues if we saturate the airwaves with a lot of wifi's.

**Comment by kyordhel** [comment]
Since Feb 23 we got no more info about the topic, and is too late now to make any adjustments. 

4G internet access is now out of discussion
