### ISSUE TITLE
[SSPL] Definition External Computing Device | Form Factor & Mobility

### ISSUE THREAD

**Issue by warp1337** [RoboCupAtHome/RuleBook#386]
I just skimmed through the rulebook and some other related issues, e.g., #366 #279 #243 

So ... the rulebook says:

> [...] the  robot  has  to  maintain  full  autonomy  when  using external  computing resources, meaning there may not be a human giving the robot any kind of instructions via external computing resources.  It is up to the team to prove to the Technical Committee (TC)  that  there  was  no  cheating  introduced  via  the external  computing  resources [...]
> 

Concerning this statement:

1) Last year, at Nagoya, I noticed teams setting up high performance desktop PCs (the ones you see in gaming commercials, e.g, 2x NVIDIA TitanX, Intel Xeon 4 Ghz, etc...) in front of the arena where the external computing devices had to be placed. I guess that's okay, so far, since we don't have any rule saying you can't bring your own high performance computer cluster. My 'problem' with that is, those machines were blocking the preparation area/table where other teams were placing their external devices too, i.e., usually laptops. The table was totally crowded and the space taken by cables, screens (!), keyboards, and mice of the desktop PCs was just ridiculous. 

**Thus, my proposal for the rulebook is that external computing devices have to be mobile, e.g, have to be setup before the task and removed after the task is done.** 

2) Based on 1) the threat of 'remote controlling the robot' is inherently mitigated since external computing devices have to be setup before and removed after the task. In Nagoya we also had the "hands-off the device rule" as soon as the ref starts the task --- which can be enforced and supervised by the refs.

**Comment by LoyVanBeek** [comment]
Sound very reasonable. Perhaps we can add some separate rack or table people put these devices in/on.

**Comment by warp1337** [comment]
Thx @LoyVanBeek, but this would actually encourage bringing high performance PCs doesn't it (that are additionally connected to the network all the time)?

**Comment by LoyVanBeek** [comment]
Maybe with a power switch per team, that gets switched on only a few minutes before a test and off directly after :-). 

But having a designated place for such external devices in a place easy to keep an eye on could help. Have ~2 of those spots, one for the active team and one for the team setting up.

**Comment by warp1337** [comment]
So, how do we write this down in the rulebook?

**Comment by kyordhel** [comment]
Some considerations on my side:
- OC-wise I'm a little bit uncomfortable with teams moving hardware between tests. In all Stage 1 there is no Setup time, and often we end up slightly behind schedule.
- The word _mobile_ is quite tricky, so I wouldn't use it. Teams not necessarily need to work with laptops (moving them can also be problematic) and that work might seem to enforce laptops only. I think a trolley with some PC's can do the trick.
- I agree in that no team shall ever permanently take control of the area for external computing. I agree on having CPU's there but not monitors, mouses and keyboards.

**Comment by warp1337** [comment]
> I agree in that no team shall ever permanently take control of the area for external computing. I agree on having CPU's there but not monitors, mouses and keyboards.

That is also okay for me, since is one of my biggest concerns. This can also easily be included in the rulebook.

**Comment by kyordhel** [comment]
Regarding implementation, the rule is partially there in the Open Challenge, as well as somewhere in (previous?) rulebooks.

1. As of 2016, it was stated that all external devices must be **inside** the arena during the test.
2. Open Challenge states that the participating team is responsible to leaving the arena in its initial condition after the test.

I would propose to reintroduce (1) and copy (2) to General Rules. That's a quick fix. Preferably, I would designate a special area outside the arena to place external devices. An Ethernet switch connected to the arena wireless would be available for the equipment there, and only the testing team and the next one are allowed in the area but are not allowed to touch anything during the test.

Major problem, we would need to add 1 minute setup to all test, but we can't do that (schedule is too tight).

**Comment by warp1337** [comment]
Okay, will do and make a pull request.

**Comment by warp1337** [comment]
I get your point concerning the additional minute, but to be honest, without such a rule the setup time is actually much longer because there is 'horrible' chaos in the preparation area: people are setting up things, thus blocking the table even if their turn is in like 30 minutes, people randomly removing things plugging and un-plugging cables (sometimes confusing cables too) ... you name it.

My proposal is:

1) There is a designated table outside the arena, but very very close to it, where external devices have to be placed. The table must be visible to the refs all the time.

2) The table can only be used by **3 teams** at the same time, not more. The order is dictated by the schedule, this is kind of a FIFO queue :). As soon as the test is done by one team they have to immediately remove their external devices from the table. Since we have a buffer of 2 teams, the others have at least 1 minute to setup (I guess that's how long it takes to bring the robot to its starting position, clear the arena, and give a go command). I would also like to propose the divide the preparation into to sections: a) the "3 teams area" and b) separated by barrier tape or something another area where people gather to actually enter preparation area.

What are your thoughts?

**Comment by kyordhel** [comment]
@warp1337 Apologies for the chaos outside the arena. The OC always tries to do their best, but we are not enough to control four hundred people.

I agree in your proposal. **However**, in the past we have had troubles with this kind of Q systems because teams do not respect the order, don't leave after the test, arrive late, etc. It's specially complicated when the robots didn't start and you change of team 3 times withing 5 minutes.

The solution has been simple. You have an OC member taking time, one controlling the door, and one on the  queue. Your system would require a fourth to control the second queue, the one in the table for remote computing. Unfortunately, rarely works. This means the OC needs to be of at least 12 people and that they must be permanently in the arena (unfeasible). As of today, the OC has only 7 people and it might be the case that not all of them attend or are available the 3 days of testing. Recruiting volunteers from the teams might be an option, but volunteers won't last long.

Sadly, I can't trust teams will self organize. Hasn't happened in the past for the convenience of the team, you can extrapolate from that experience.

**Comment by warp1337** [comment]
Alright, I see your point. The only thing we can enforce then is the "no screens and keyboards rule" Do you still want me to add this to the rulebook?

**Comment by warp1337** [comment]
Okay, PR is open. Feel free to inspect.

**Comment by kyordhel** [comment]
@warp1337 Not necessarily. There are many other options (only few of them came to my mind). For instance, we can add a strong (25pt) extraordinary penalty for not removing your stuff from the table in time, with the same premises as the penalty for Not Showing Up.

I'm against penalizing teams, but often a punitive measures are the only ones that actually work.

**Comment by warp1337** [comment]
I am okay with that. Can you guys comment on the PR so I can add the changes?

**Comment by kyordhel** [comment]
Just for the record, the PR is #388

**Comment by warp1337** [comment]
Can someone please review this?

**Comment by warp1337** [comment]
there we go ... it already starts to escalate ... #363

**Comment by LoyVanBeek** [comment]
I'm sorry, I've done all reviewing I can but it's up to the TC (@airglow @justinhart @awesomebytes etc.) to review and approve a change like #388.

**Comment by warp1337** [comment]
You should also consider my last comment in https://github.com/RoboCupAtHome/RuleBook/pull/388

**Comment by warp1337** [comment]
PR has been merged!
