### ISSUE TITLE
Q: VizBox Clarification

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#389]
The rulebooks states that the VizBox has to be "run on the robot". I am assuming it is fine if it is run on the external computing device but wanting to make sure.

Furthermore what about teams not using ros? I think this applies to several teams in the SSPL for example.

**Comment by LoyVanBeek** [comment]
Running on external computing should be fine. 

The ROS backend is essentially a sort of plugin, a different one should be easy to do, but you'll have to make that yourself. 
What other backend would you want? HTTP-POSTing instead of publishing/service-calling should be possible.

**Comment by johaq** [comment]
Ros is fine for us.
If this is mandatory maybe it should be clearer that teams not using ros need to provide their own alternative.

**Comment by warp1337** [comment]
I am interested in one thing: is it mandatory to run it? If not nobody will put effort into it unless it is not rewarded. Loy you know exactly how this turns out if not explicitly stated in the RuleBook. ;)

**Comment by kyordhel** [comment]
I would say **NO** at least for the first year (we need to test it first). However, we can officially announce Referees will rely on VizBox for all clarifications. Therefore, if we are unsure on whether to score or not, and there is no VizBox... well... too bad for your tea.

Just a thought.

**Comment by johaq** [comment]
"All robots are expected to run the VizBox" sounds kinda mandatory to me

**Comment by warp1337** [comment]
@kyordhel I just updated my comment above pls consider my networking concerns.

**Comment by warp1337** [comment]
@johaq Expect, in the context of a rulebook, sounds like an encouragement to me. However, I +1 @kyordhel 's answer. Still, I dont see the benefit if not used on a reeeeeeally big screen/tv

**Comment by kyordhel** [comment]
@warp1337 I stand for what I said. the organization can enforce the use VizBox use, but the robot's standalone performance during the competition is much more important than any helper tool, so if robots experience networking problems, then we suspend the use of the VizBox.

If there is something I'm missing, please clarify.

**Comment by kyordhel** [comment]
@johaq _All robots are expected to run the VizBox_ means precisely that: expected. In other words, the TC won't deny you the entrance to the arena if you don't use VizBox.

In similar situation is the jack connector for the RF Audio transmitter which often is not available. It is expected all teams use the audio transmitters, but most teams agree in that loud speakers cause too much trouble and the audience might not understand what the robot says anyway.

**Comment by warp1337** [comment]
@kyordhel No everything's fine 👍 All I was saying is, that I have my doubts that the network can handle the traffic people are causing regularly AND streaming images to the viz box from 8+ teams. And, again, I dont see the benefit if the box is running on a laptop screen. That's all.

**Comment by kyordhel** [comment]
@warp1337 Unfortunately, that's something I cannot answer. In theory the infrastructure should be able to do it, but in practice it depends on many variables ranging from electromagnetic interference to the amount of data you want to transmit (e.g. raw Kinect2 output at 60fps). Nonetheless, I support your point on having VizBox in a laptop screen. If we don't have a 90" Ultra-HD TV, is pointless.

I must say we might have up to 9 teams broadcasting at the same time (EEGPSR is 3 teams at the same time, and there are 3 leagues). Notwithstanding, I like natural HRI rather than internal state visualization, so in my ideal world of fantasy, VizBox wouldn't be needed, but let's give it a try.

**Comment by balkce** [comment]
Just throwing this out there:

There are some members of the EC that aren't comfortable with the idea of the vizbox since it introduces another variable with which things can go wrong. I'm not saying that they're completely against it, just worried about its implementation during the competition. 

I suggest to start this year with the visualization part of it as a way to settle conflicts with issues like "my robot did this and you didn't give me points for it". If teams don't want to implement it, fine, but they lose that convenience of resolving scoring conflicts.

**Comment by warp1337** [comment]
For that the viz box must feature recording, doesn't it?

**Comment by balkce** [comment]
I would suspect so, yes.

**Comment by LoyVanBeek** [comment]
The VizBox, as it currently stands, simply shows a story of the task, the dialog and has room to visualize something. This can be anything, including a live stream of your camera but it can also be throttled, a nicer rendering of RViz or whatever, as long as it comes over a ROS image topic. 
If you publish something else on that topic, fine. 

It should not be tied to ROS, if you need a different backend, should be possible as well but you'll have to make that yourself ATM. 

It does not record anything, it's just a webpage served from the robot or something connected to it.

**Comment by LoyVanBeek** [comment]
I don't like to award points for using it, it should just be there to aid the audience and thus shown on a projector like we had in Nagoya. 
Maybe there could be negative points for not having it or something. 
It's use should be so simple that it's not much effort, but improvements are very welcome to make that really true.

**Comment by airglow** [comment]
Just an idea to simplify the usage for teams. As all robots should be connected to the arena network anyway, may it`s possible to have a dedicated machine with the VizBox running. For teams that are running ROS, launch files can be created on a per team basis connecting to their ROS master.  
The other teams (which to my knowledge is just SSPL) can post on the address of the machine.

Also I don't see any sense in it when it's not connected to bigger screen to support the audience in what is going on there.

**Comment by warp1337** [comment]
I really hope team networks are separated O_O

**Comment by kyordhel** [comment]
@LoyVanBeek I think penalizing is the same as giving points scorewise. Teams using X have and advantage over teams not using it. The best way to encourage it's use is to provide a ready-to-use solution based on ROS
