### ISSUE TITLE
Scoring for team cooperation

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#39]
We have Team cooperation bonus (5pts) in Open Challenge of Stage 2.
Wake me up test allows 2 robots (same team) for serving breakfast, also in Stage 2.

It would be nice if we allow robots from different teams to cooperate on Wake me up also, granting a small bonus to the helper team equal to the amount of points for solving the task (even if that team didn't get to Stage 2). In other words, if team B helps team A having robot B placing the milk (succeed) and the fruit (fail) while robot A pours the cereal:
    - Team A gets 5pts for pouring cereal.
    - Team A & B get 1pt for placing milk.
    - Team A & B get no points for placing the fruit.

**Comment by kyordhel** [comment]
@dirkholz , @balkce , @LoyVanBeek 
Any comments? May I proceed?

**Comment by dirkholz** [comment]
you may,  yes!  :)

in fact,  I don't care,  this year it's completely yours.  let's see how
well it works at the German open,  we can still fix things after it ...

**Comment by LoyVanBeek** [comment]
Go ahead!

**Comment by balkce** [comment]
+1

**Comment by kyordhel** [comment]
Done!
