### ISSUE TITLE
Q: How to keep track of the changes in the RuleBook

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#391]
Hi,
Is there a standard way to keep track of the rule changes from one year to another?

In the humanoid league, the rules are published twice : 
- A full PDF
- A full PDF with changes with the previous year's RuleBook marked

Is this also done here? If so, apologies for the issue post.

If not, how do you guys do it? For example, I wanted to know if something important has changed from the 2017 RuleBook. I went back to a previous commit and tried:
- A direct diff between PDFs with diffpdf => Didn't work well enough, it got lost in the comparison after a while.
- A .tex diff with latexdiff. => Seems to work fine but should be done on every .tex file

I used the "build date" present in the PDFs to estimate the last commit for a given RuleBook version.

Thanks,
Remi

**Comment by LoyVanBeek** [comment]
There is a pull request to add a change log: https://github.com/RoboCupAtHome/RuleBook/pull/390

**Comment by kyordhel** [comment]
@RemiFabre to enhance Loy's answer: No, there is no changelog sop far in @Home.
We are discussing one in #390. Your idea of double rulebook will be more than welcome.

The list of changes for this year are:
- Storing Groceries  [ToDo]
  - Rebalanced scoring
- Set the Table and Tidy Up [ToDo]
  - Refurbished
  - Removed Set the Table part
  - Focused in cleaning
  - Cutlery and dish handling mandatory
- EEGPSR:
  - Refurbished
  - Reduced number of categories to 3.
  - Dealing with incomplete and erroneous information made mandatory.
  - Adjusted difficulty of commands based on 2017 performance.
- General Rules:
  - Backpack laptop for DSPL

**Comment by RemiFabre** [comment]
The dream would be to be able to generate a PDF with the changes marked automatically from any previous version of the files. I will try a bit harder to tackle this.

**Comment by RemiFabre** [comment]
Update : I tested a web based pdf diff solution and it works much better than the diffpdf tool : 
https://www.diffchecker.com/pdf-diff

**Comment by kyordhel** [comment]
This was addressed in #390 
Unless something else is required, I'm closing this issue
