### ISSUE TITLE
[GPSR] Scoring for command retrieval

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#395]
In the GPSR task if the robot repeatedly fails to understand the referee and then understands the custom operator on the first try it is awarded 5 points (Understanding the command on the 1st attempt (Custom Operator)).
If the robot only fails once to understand the referee and then gets it on the 2nd attempt it is only awarded 1 point (Understanding the command at a later attempt).
I feel that this is not fair and retrieving the command from the referee should always award more points than from a custom operator.
My suggestion would be to switch the scoring and award 5 points for understanding the referee at a later attempt and only 1 point for understanding the custom operator.
If you agree I can create a pull request for this.

**Comment by kyordhel** [comment]
Scoring is designed to push towards single-try command retrieval. This also helps to reduce the time for instructing the robot in favour of task-execution time.

As is, most teams will change to custom operator after the first try and stick with them. The suggested change will make strategic to try 3 times with the referee before trying with a custom operator. This is something TC has been trying to avoid. A test in which robots spend 2+ minutes in command retrieval is not appealing for the audience, and doesn't help to focus on the test execution. Also is worthy considering that the existence of a standard Command Generator greatly reduces the difficulty of command retrieval, so only reliable command acquisition is rewarded.

In my opinion, this shouldn't be changed. Let's see what the rest of the TC has to say about it.

**Comment by johaq** [comment]
If the rest of the TC agrees with @kyordhel  I would suggest to change at least the following:
```
If the robot appears to consistently not be able to understand the operator, 
the referees ask the team to use a custom operator or bypassing speech recognition
```
to state that the team has to indicate it wants to use the custom operator or change the rules to state that the referee will only try once anyway.

**Comment by balkce** [comment]
I would suggest to implicitly state that the test will do what teams are doing anyway, and not rely on "maybe" they'll do what we think they'll do.

Meaning: the judge should try only once. If successful: full points; if unsuccessful: custom operator will try with less points then the judge and with less and less point the more tries, with the possibility of using the CONTINUE rule.
