### ISSUE TITLE
Q: Will be there Pepper robots for lease in Montreal?

### ISSUE THREAD

**Issue by AMR-** [RoboCupAtHome/RuleBook#396]
I have heard conflicting things.  For SSPL, will Peppers be provided, or is each team expected to bring their own?  If Peppers are provided, are teams required to use the provided Pepper or can we bring our own?

**Comment by kyordhel** [comment]
The Organizing Committee was told Softbank Robotics is willing to bring robots for lease to Montreal. However, the terms and conditions are still unknown to us. To the extent of our knowledge, as soon as Softbank Robotics finishes ancillary arrangements, they themselves will contact teams to provide a lease contract specifying all details.

To the date, we have no further information.

**Comment by airglow** [comment]
Of course it's also possible when you bring your own unmodified Pepper.

**Comment by kyordhel** [comment]
# Update

**Yes**. There will be Peppers for lease in Montreal. It just came to my knowledge that

> Rental conditions will be the same as last year.

Information is as follows:
- **Period**: June 17 - 21, 2018
- **Products**: Pepper + Pod + charger
- **Failure:** Robots will be repaired at the Pepper Clinic or swapped (depends on damage).

SSPL teams will receive pricing and detailed information by the end of the week.
