### ISSUE TITLE
RoboCup Junior: Rescue Line Rules 2018: Rule 5.1; critical problem

### ISSUE THREAD

**Issue by roy71100** [RoboCupAtHome/RuleBook#398]
fellow competitors and staff,
i am a member of an israeli team in the RoboCup Junior: Rescue Line competition.
While reading the rules, i noticed that there is no clear reference to a situation in which the competitor believe that there has been a mistake in his round scoring and he does not agree to sign his scoring papers. 
what do you do in this kind of a situation? do you speak to a higher-ranking staff member?
thanks in advance,
Roy

**Comment by airglow** [comment]
Seems like you ended up in the wrong. This serves RoboCup@Home.

**Comment by moriarty** [comment]
This RuleBook is for *RoboCup@Home* 

For RoboCup Junior: Rescue you should contact the RoboCup Jr Rescue Technical Committee.

You have already posted your question in the correct location:
https://junior.forum.robocup.org/t/robocup-junior-rescue-line-rules-2018-rule-5-1-critical-problem/499

This is not the correct RoboCup league, so I will close this issue.
