### ISSUE TITLE
Category 3 BIG issue

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#40]
First, the rules for GPSR say:

    In general for all categories: The command is composed by three actions(...)

And looking into the scoresheet
- Asking reasonable questions (...)
- Performing the first task (...)
- Performing the first and second task (...)
- Successfully solving the complete command (...)

However, if we go deep into the specification for Category 3, we have:

    Category III: (...) This category includes counting objects (...) or people, (...)
    deal with incomplete information (...), state the gender or gesture (...),
    handling clothes, etc.

And getting into the example commands we have:

- Go to the shelf, count the drinks and report to me.

Explicitly three tasks with a challenging action: counting but no need to ask any question

- Take this object and bring it to Susan at the hall.

Which also requires no question to be asked, has one challenging action (hand to hand grasping) but is given in two tasks which actually involves four: 1) take this object from my hand, 2) goto the hall, 3) find a person (Susan) and, 4) deliver the object to her.

- Offer a drink to the person at the door.

Which requires the robot to ask for the specific drink to be delivered and is explained in two tasks which require 5 actions: 1) Go to the [drinks location], 2) take the [drink], 3) go to the door, 4) find a person and 5) deliver it to the person. But also can be understood as 1) go to the door, 2) find a person and, 3) ask which drink she wants, which is pretty trivial

Therefore, something here needs to be changed!

**Comment by egeerts** [comment]
Dear Mauricio,

Will there be an update on this topic before we see each other in Magdeburg?

**Comment by kyordhel** [comment]
@egeerts 

I would like to update ASAP but I wouldn'y like to take all decisions on this test. Before going further on this I really need some feedback from @LoyVanBeek @balkce and the other TC members

**Comment by LoyVanBeek** [comment]
Proposal: Cat. 3 is gonna be the same as cat 2, but with incomplete or incorrect info. The robot has to come up with a solution. Just saying "I cannot get the coke" is not good enough, the robot must solve the task some other way then.

**Comment by LoyVanBeek** [comment]
@kyordhel please review https://github.com/RoboCupAtHome/RuleBook/commit/ed918d07984095166ee7d0046c16a0d21966ce5d
