### ISSUE TITLE
When making the bed, what do we mean with "Professional mom"?

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#41]
We can be more specific here. If a robot is able to e.g. grab the point of a (well textured) blanket and put it straight, I want to award major points.

**Comment by kyordhel** [comment]
"Professional Mom" is that: someone's mother (or father) who professionally inspects the bed is well done. The kind of person you wouldn't dare to argue when is brandishing a sliper or wooden spoon.

I still remember my mother yelling at me when I was 8 and left my bed half made. Should I have 6+ years old children then I could provide my wife as Professional Mom, but you know... dating girls & Mr. Spock, oil & water...

This "Profesional Mom" inspects the bed and rates it from slipper to kiss (or zero to ten) and we proportionally award points.

**Comment by kyordhel** [comment]
We can get rid of the "Professional Mom", but also request the opinion of some "Mom from the audience" to rate the niceliness of the bed while we score the technical aspects (5 points apearance, 5 points performance).

Also, there are many ways to do bed, so I wouldn't set an "official score". For instance

Pillows over the blanket
![01](https://cloud.githubusercontent.com/assets/8583949/6895723/5fb493ee-d6e3-11e4-8e42-22ad05ceb0cb.jpg)
![02](https://cloud.githubusercontent.com/assets/8583949/6895728/6624d086-d6e3-11e4-890d-c7ff61a87a8d.JPG)

Pillows over the bed sheet with folded blanket
![03](https://cloud.githubusercontent.com/assets/8583949/6895731/6d748994-d6e3-11e4-9f7b-f93c43aa0f63.jpg)
![04](https://cloud.githubusercontent.com/assets/8583949/6895733/70752536-d6e3-11e4-9f6f-ef5b5e56a426.jpg)

Blanket over pillows
![05](https://cloud.githubusercontent.com/assets/8583949/6895737/7f1ab182-d6e3-11e4-9c65-f417a096b580.jpg)
![06](https://cloud.githubusercontent.com/assets/8583949/6895739/82b92f80-d6e3-11e4-89ee-1ddb60a2392b.jpg)

Plus a lot of variants. Maybe you will find the following score useful.

+2pt Grasping the blanket/duvet
+1pt Covering the bed sheet with blanket/duvet
+3pt No wrinkles or bearings in the blanket/duvet
+3pt Grasping the pillow
+1pt Correctly placing the pillow in the header

**Comment by LoyVanBeek** [comment]
That is indeed what I was thinking about.  Asking the audience is a nice touch. I don't expect a lot of teams taking this option actually

**Comment by kyordhel** [comment]
It is addressed now with something like:

For scoring purposes, the TC may require locals' opinion to check if the bed has been properly done.

There is no official scoring steps for doing the bed, just stated that we will pay attention on grasping sheets & pillows, covering and wrinkles.

If you like it, close the issue.

**Comment by LoyVanBeek** [comment]
I do like it, but I'd also include the scoring like you had above. Just awarding 10 points to a team doing 1 of the tasks and also to a team doing all 5 is not fair. 
I suspect this is not going to happen, but if we want to push this, we should be specific.

**Comment by kyordhel** [comment]
Honestly, I don't want to see teams neglecting the test and going straight to "grasp the corner of a duvet" because it grants 10 points. Pouring cereal grants 3 points, and grasping the corner of a cloth may be the same challenge, or easier with a lot of luck (it is difficult to guess if the robot really identified the corner and grasped it or teams are just trying luck).

I'm not against being more specific, and points were a mere suggestion. Also I don't know if announcing points is better or not, and I'm completely open to be convinced. I really would like to read what the silent members of the TC/EC think about it.

**Comment by LoyVanBeek** [comment]
Maybe we indeed just need to see and award points after a little discussion of the performances by all robots. 

@balkce What do you think?

**Comment by balkce** [comment]
We're entering a pseudo-philosophical area: "What does it mean to make a bed?"

The idea of bringing a local attendance opinion is a nice touch, and I think having a set of points for each subtask that involves "making the bed" I think is a good incentive for teams. To avoid teams going for "Oh, look, touching the duvet gives 2 points, lets just do that", I propose reducing the subtask into two:

- Covering the bed sheet with blanket/duvet. Extra points for no wrinkles and appearance.
- Positioning the pillow. Extra points for correct placement and appearance.

[This is how I do my bed. Don't judge me.]

And the extra points are potentially much bigger than the base points for each subtask of "Making up the bed". These extra points could then be judged by the "local mom".

a) If they go for it, and do a bad job, no points given, like anything else.
b) If they do just the basic job (just sloppily covering the bed and putting a pillow somewhere in the head of the bed), the "local mom" won't like it and won't offer any extra points. Then they would only receive the few base points, which is kind of a "for the effort" consolation price, and, although they would be few, I think they will be enough incentive for teams to go for it.
c) Obviously, if the "local mom" is impressed, nice bulgy extra points for the team.

**Comment by LoyVanBeek** [comment]
This!

**Comment by kyordhel** [comment]
Thanks @balkce. Solved
