### ISSUE TITLE
No sitting person will not attend robot's call.

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#410]
In [RuleBook/tests/CocktailParty.tex](https://github.com/RoboCupAtHome/RuleBook/blob/master/tests/CocktailParty.tex) line 33, this double negative is confusing and I am unsure of its meaning:
"No sitting person will not attend robot's call."

Are you saying that every sitting person will attend the robot's call? What does "attend" mean in this sentence? Are you saying that "All seated people will respond to the robot's questions: i.e., seated participants will always respond to the robot when directly addressed by the robot, even if they are 'minding their own business'"

Can this sentence be rephrased to make its meaning clear?

Thanks!

**Comment by kyordhel** [comment]
Regarding Oxford Grammar:

> The rules dictate that the two negative elements cancel each other out to give a positive statement instead, so that the sentence ‘I don’t know nothing’ could literally be interpreted as ‘I do know something’.
>
> Double negatives are standard in many other languages and they were also a normal part of English usage until some time after the 16th century. They’re still widely used in English dialects where they don’t seem to cause any confusion as to the intended meaning. 

Right sentence should be either:
a) _**No** sitting person will attend robot's call_, or
b) _A sitting person will **not** attend robot's call_

Regarding the verb _attend_, once more the Oxford dictionary has something to say:
2. **(attend to)** _[no object]_ Deal with.
Give practical help and care to; look after.
2.1. Give practical help and care to; look after.
2.2. Pay attention to.


@justinhart is native English speaker, so I think he's the most qualified to propose an alternate explanation and fix this issue. Or maybe we should add an appendix explaining Cocktail Party.

**Comment by justinhart** [comment]
I'll just update this to eliminate the double-negative. It's not
particularly common in the English language, though it's true that a double
negative resolves to a positive statement in English.

**Comment by justinhart** [comment]
Done.
