### ISSUE TITLE
Question about SPR

### ISSUE THREAD

**Issue by lerrytang** [RoboCupAtHome/RuleBook#417]
Hi,

Not quite sure about the rule for SPR.
When the robot is asked a question about object/arena,
is it allowed to move around and inspect before answering?
Or should it answer in-place?
I got confused because the former sounds like GPSR while the latter gives me a feeling a huge amount of hard coding may be necessary.

**Comment by airglow** [comment]
It's meant to be answered in place. Locations, objects and it's default locations will be announced during the preparation days. We expect answers based on the knowledge. Maybe something like this will come in the future.
