### ISSUE TITLE
Describing the crowd in Person Recognition test

### ISSUE THREAD

**Issue by LFBFerreira** [RoboCupAtHome/RuleBook#42]
I have a couple of doubts that are not explicitly mentioned in the Rule book:

1. The operator will be mixed in the crowd. When counting the number of people and respective genders, should the operator be accounted in that math?

2. When counting the number of people and respective genders in the crowd, do i only count the "crowd" where the operator is, or do i count everyone that might be present in the room, even if its just 1 person in the corner

**Comment by LoyVanBeek** [comment]
**1.** The operator is within/part of the crowd. The robot must mention number of people in the crowd, so also of the operator. 
**2.** The robot should describe the crowd the operator is part of. People separate of the crowd are not part of the crowd and should thus not be counted.

**Comment by kyordhel** [comment]
Answering 1 (which is kind of obvious)

The rulebook states that the robot must tell the number of people in the crowd. That means that if

    Crowd = {girl1, girl2, boy1, boy2, operator}
    then | Crowd | = 5

the robot must say "... five people in the crowd, two male and three female", asuming a female opeator; or say "... five people in the crowd, two male, two female and the operator Justin Bieber".


Answering 2

    You can count people and crowds as you want. There will be only 1 (one) crowd behind the robot and reasonably close to it (e.g. 3 meters ± 2m). A reasonably distance means that is far enough to fit in the robot's field of view but close enough for robot can quickly aproach to the operator.

We cannot warantee that only people from the crowd will be in the field of view of the robot. Even more, I am (and perhaps the rest of the TC also) mean enough to intentionally add some people nearby still visible but not being part of the crowd to keep it challenging.

For instance, if the test is done in the arena's living room and there is an audience of three thousand people seat in stairs 10m behind the crowd, the robot should be able to state the number of people in the crowd, ignoring the audience.
