### ISSUE TITLE
Autonomy & Mobility section exists twice

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#420]
Autonomy & Mobility is in 2.2 and 3.4.1. 

As both sections have the same statement, one should be removed.
3.4.1 even links to the penalty section(3.10.1.) that does not provide penalties regarding autonomy.

**Comment by kyordhel** [comment]
K. Grant you that one. 
Please write the PR removing the redundancy.Regarding instructions to the TC, I think those are given by EC and, for sake of space, should be kept separated from the rulebook. In any case, they need to be written first.
