### ISSUE TITLE
PDF Recognition Report for storing groceries not needed anymore

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#424]
Section 5.5.5.  PDF Recognition Report can be removed as it does not award any points.

**Comment by kyordhel** [comment]
For 2019 maybe. For now, TC might use PDF reports for clarification.

**Comment by warp1337** [comment]
To get this straight, the report is **not mandatory** as of 2018, but can still be used in order to discuss the scoring if smth is unclear?

**Comment by kyordhel** [comment]
@Home requires HRI. To me, no user wants to read PDF reports, they want results. I think we should push towards intelligent robots actively looking to solve problem and expect, at least, that they are aware of the nature of the problems that arise. PDF reports is, in my opinion, moving @Home closer to labs than to real environments.
