### ISSUE TITLE
StoringGroceries cupboard height not attainable

### ISSUE THREAD

**Issue by Atine** [RoboCupAtHome/RuleBook#426]
In the task storing groceries, the height of the cupboard will be 1.8m per the rulebook.
However, for HSR in the DSPL league, the max height its arm can reach is around 1.4m.

So assuming the shelves are evenly distributed, HSR will not be able to reach the top shelf?

**Comment by kyordhel** [comment]
That is correct. Toyota HSR won't be able to reach uppermost shelves.

Same rules are used for all leagues, and the height of the shelves is a global setting for all arenas (we can switch arenas for some tests). The referees will mind DSPL limitations when arranging objects.
