### ISSUE TITLE
[Cocktail Party] Interaction with sitting person might be unnatural

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#428]
Right now the rule book states that there are groups of 2 or 3 people with one sitting person.
Does it make sense to form a group during a real cocktail party where only one of the 2 or 3 persons is sitting?
Later in the task description it is stated that a sitting person is minding their(his/her?) own business.
I think this is even more confusing that this person although ignoring the waiter wants a drink?!

I would remove some of these parts and would suggest an overall shorter description to have a more natural cocktail party without all those special cases the teams have to model and the audience is not able to understand.

**Comment by LoyVanBeek** [comment]
The Cocktail Party challenge is for a new league, SSPL, which did not exist in 2011, not sure if that is relevant. 
Starting with a very do-able scenario and later increasing difficulty seems the way to go to me.

**Comment by kyordhel** [comment]
Both SPL leagues derive from OPL which performed Cocktail Party long ago and were replaced later by the ability tests. It made sense to resume progress. 

Nonetheless, if someone has a concrete proposal, a PR can be merged.

**Comment by semeyerz** [comment]
The point I wanted to make was more that the task is written to explicitly.
That means I am not arguing for simpler tests but for simpler rules.

It could even be harder for the robots if they can not infer so much from the rules.
I saw a robot doing really strange things like inferring that a person wants a drink only by seeing it sitting.
Also the robot was coming to the bar "knowing" that one drink will not be there and thus directly asking the bartender which drink is missing today.
So the robot does not react to the world but encodes directly what was written in the rulebook.
This is not only confusing for the teams to program but also for the audience.

Also for the TC it was pretty hard to actually arrange the people as indicated in the rulebook.
It could have just been:
* place 5 persons randomly in the living room. (some sitting, some standing)
* three of them want a drink two don't

**Comment by kyordhel** [comment]
That makes sense. Can you make the PR?
