### ISSUE TITLE
Question regarding Vizbox subscription topic

### ISSUE THREAD

**Issue by Atine** [RoboCupAtHome/RuleBook#430]
Regarding Vizbox, since the image topic subscribes to a `std_msgs/Image` type,
I was wondering if we (my team) could change vizbox so that vizbox itself listens to a `std_msgs/CompressedImage` to reduce transmission?

I understand it would be ideal that everyone  run the same Vizbox, however as 
`CompressedImage` and `Image` does not differ a lot visually, I suppose it wouldn't 
matter for clarification purposes.

**Comment by LoyVanBeek** [comment]
That would be great of course! If you make the change and submit it as a PR to the vizbox repo, I'll review and merge it.

**Comment by Atine** [comment]
Since the PR was merged, I will close this issue. Thank you!
