### ISSUE TITLE
[General Rules] Change score rectification procedure

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#431]
Section 2.1 states:

> Once  the  test  scoresheet  has  been  signed  or  the  scores  has  been  published,  the  TC
decision is irrevocable.

This section should be removed since it is not enforced. 
Alternatively we should talk about the procedure of signing and publishing. Fabrice told me in other leagues (work I think) at a test every team leader is present and has to sign off on the score. That is of course a lot of effort but can effectively prevent a lot of discussion. Personally I do not think this is feasible for @home but maybe we should discuss it.

**Comment by airglow** [comment]
I'm strongly against removing this section. At German Open it was a trade-off between publishing preliminary results right after the tests, which I also think is very important. I would stick to the current procedure but before handing them discuss the scoring between TC's and EC's. This was a strong error that we made at German Open, which should not happen again. 
If you really want to complain about that now we can revert the score to the state before the correction which does not change the end result at all.

**Comment by johaq** [comment]
I am also for keeping the section. But I think we should discuss the procedure.

**My proposal**: Invite the leader or a representative of every team to be present at every test (of their own team as well as others). Any issue with how the test is conducted or scored has to be addressed immediately. Discussions later in the day or even the day after are not allowed.

I think this would guarantee that each team is more involved in the rule book and avoid endless discussions afterwards. It also promotes exchange between the teams.

**Comment by kyordhel** [comment]
First, I would like to clarify that scores in RoboCup@Home are NEVER
published untill al scoresheets are signed.

Removing this section is a NO GO from the OC point of view. Morevover, I
invite you people to join OC to experience chasing Team Leaders while at
the same time handle the presure of all teams + venue requesting for scores.
Current procedure works so I invoke the Rule #1 of engineering: does it
work? Yes? Then don't change it.

**Comment by johaq** [comment]
I do not think that the current procedure works very well. You said it yourself: chasing team leaders and dealing with other teams is a nightmare. Hence my proposal which I think would fix or at least alleviate these issues.

**Comment by kyordhel** [comment]
Maybe, but so far when teams want the scores, TL goes th toe OC table to ask and signs all pending scoresheets.

I've no idea what happened in German Open, but in the international we have had problems with unhappy teams a couple of times and is tiring and time consuming, yet solvable. What you propose will lead to several teams complaining about tests that are already gone from referees' mind prior to advancing to Stage 2/Finals. That can potentially break up all logistics.

**Comment by johaq** [comment]
> What you propose will lead to several teams complaining about tests that are already gone from referees' mind

I feel my proposal does exactly the opposite. Complaints have to be issued right after the run, later discussions are not allowed anymore.

**Comment by moriarty** [comment]
I think this can be closed?
