### ISSUE TITLE
Q: Where is the Bar located in Cocktail Party?

### ISSUE THREAD

**Issue by AMR-** [RoboCupAtHome/RuleBook#436]
In the Cocktail Party task, are we told the location of the bar during setup days?

If not, what aspects of the bar allow us to identify it?  Will it be the only surface in the room with drinks atop it?

**Comment by awesomebytes** [comment]
Hello, the rulebook states (in section 5.1.6):

> 5.1.6. OC instructions
> 2h before test:
> • Specify and announce the rooms where the test takes place.
> • Specify and announce the location where the drinks are served.

The last line is the bar.

**Comment by awesomebytes** [comment]
I guess we should add it to: https://github.com/RoboCupAtHome/RuleBook/pull/440#discussion_r188052857 instead?

**Comment by LoyVanBeek** [comment]
Also possible, as long as it's clear

**Comment by airglow** [comment]
Expect the announcement to look sth. like [this](https://github.com/RoboCupAtHome/GermanOpen2018/blob/master/cocktail_party/cocktail_party_map.png) (- the initial pose, which is an error):
