### ISSUE TITLE
Q: There will be any bumps at the doors in the arena?

### ISSUE THREAD

**Issue by sungjae-cho** [RoboCupAtHome/RuleBook#445]
We will participate in the SSPL, and are curious that there are any thresholds of the doors in the home environment.

And one more thing, if there are any bumping obstacles on the floor, like the thresholds or wires, will it be removed by the committee?

**Comment by justinhart** [comment]
You mean like a literal threshold that the robot would need to get over? I
certainly hope not, as all of the robots are operating on wheeled bases to
the best of my knowledge. This is best directed towards LOC. Can someone
from LOC chime in?

Justin

**Comment by awesomebytes** [comment]
Sorry, I don't understand what's exactly the question, threshold on what?

Like what are the dimensions of the doors?

They are normal doors, standard size by the country where the contest is
happening. They should be wheelchair accessible to make some sense of how
wide they are. The handle has been one of the kind you push down (in case
that's also if your interest) in every Robocup@Home I've attended.

It's written somewhere in the rulebook, I'm currently on mobile so I can't
look for it right now.

**Comment by justinhart** [comment]
He means a literal threshold. A raised surface at the bottom of the door.

**Comment by sungjae-cho** [comment]
@justinhart What I mean is exactly what you said. I mean there is any obstacles that robots should get over by their wheels. 

@awesomebytes I meant this kind of things (https://www.stairheaven.com/door-thresholds) that robots have to get over.

**Comment by sungjae-cho** [comment]
One of the LOC, @maximest-pierre can guarantee that no steeply raised surfaces are in the home environment.

**Comment by warp1337** [comment]
Usually, based on my experience, there are thresholds that vary in height and form from year to year. Also, the teams may modify the thresholds if the TC,LOC and all the teams decide that they are too high for the robot, for instance. That being said, I haven't seen a threshold that a pepper robot wasn't able to drive over, in contrast to the Toyota platform, yet.

**Comment by sungjae-cho** [comment]
@warp1337 Last year, in Nagoya, our Pepper had trouble in getting out of the home while Help-me-carry scenario. We concluded that's because, 

- first, the door is too narrow not to be detected as an obstacle, and 
- second, the way out of the door was too steep for Peppers.

We think the first may be the thing we have to overcome 
but the second one should be eliminated because Peppers' wheels are not for climbing a steep heel.

**Comment by warp1337** [comment]
We were in Nagoya too (basically testing our pepper but also in the OPL, you might remember). I don't remember having trouble getting over the doorsteps. The doors is another story, i.e. too narrow, so yes you are right. There are ways to work around that, but that's maybe too Pepper specific for the Rulebook, but you should check the security distance in the Qi API

**Comment by awesomebytes** [comment]
I made a point about the way out of the door, but it was a bit too late,
people already made their maps and so and it was decided to not touch it to
not mess up anyone's setup.

**Comment by semeyerz** [comment]
I think the rulebook is pretty clear in that regard in section 3.3.2:

`3.
Floor:
The  floor  of  the  arena  as  well  as  the  doorways  of  the  arena  are  even.   That  is,
there will be no significant steps or even stairways.  However, minor unevenness such as
carpets, transitions in floor covering between different areas, and minor gaps (especially
at doorways) must be expected.`

**Comment by warp1337** [comment]
Regarding your last point @kyordhel, that's basically what I meant. @semeyerz Thank for pointing out the Rulebook. Also, everybody you can always apply common sense :) Doors are standardized (CA) so you should test that before the event, I am 100% positive that you can solve the door problem programmatically. Moreover, coming back to common sense, if there is an obstacle/bump whatever and no team manages to overcome it without destroying the robot, the arena will be modified after a mutual agreement/decision.

**Comment by maximest-pierre** [comment]
I can confirm that the arena is not going to have huge bumps or crevasse. Also for the doors, I need to check with the carpenters.

**Comment by airglow** [comment]
From my point of view there is no discussion needed here. The rulebook describes it quite accurate. Always imagine that you have to put your robot in, or in front of a random flat and it should operate like you expect an expensive product, which is a robot, to operate.

**Comment by sungjae-cho** [comment]
Thank you all for your detailed information and reassuring the home environment. 
See you all in Montreal!
