### ISSUE TITLE
Q: Is functional touching allowed in Storing Groceries?

### ISSUE THREAD

**Issue by tkelestemur** [RoboCupAtHome/RuleBook#448]
I didn't see any conflicting rule but wanted to make sure that non-prehensile manipulation of objects is allowed during Storing Groceries task. Example scenarios could be pushing objects aside to grasp an intended object or creating a space for an object in the shelf by pushing other objects in the same category.

And of course, the robot should not drop any object by doing this.

**Comment by kyordhel** [comment]
To me, it maps directly to *Functional Touching*, and same rules should apply. Other than this, sounds not only doable but something we should encourage.

Important: This has never been tried in a test before, so the referees most likely will interpret such behavior as a malfunction or collision. To avoid this, is very important that the robot announces it is about to (e.g.) *make space* for a third object by pushing others.
