### ISSUE TITLE
[SRAT] Degrees measured in meters

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#45]
Speech Recognitioon and Audio Test
Section 5.6.4

- The operator shall be between 0.75 and 1.0 meters away from the robot position.
- The operator shall be between -60 and 60 meters from the robot's center (front range)

**Comment by LoyVanBeek** [comment]
+1 and -1 radians? :smile:

**Comment by kyordhel** [comment]
Degrees is good enough for me, but we can also state

    arc sin ( sqrt(3) / 2 )

**Comment by balkce** [comment]
Fixed. Used degrees.
