### ISSUE TITLE
Q: About External Device for Audio Processing

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHome/RuleBook#454]
In the External Device for Audio Processing section, it says that it is good to use "The device can be used for sending the row signal to robot". So when operator command to robot, can we let the operator use the microphone we prepared?

In DSPL and SSPL, operator have external microphone to hear the command for audience. Can we make the operator use our microphone (External Device for Audio Processing) in the arena competition (ex: GPSR) and out of the arena competition (ex: Restaurant) ?

**Comment by semeyerz** [comment]
> can we let the operator use the microphone we prepared?

The rulebook says:
`using the following official microphone is allowed as a backup`

Sounds for me like you can not bring/use your own external microphone.

_Side note:_
I think that commit 9d2bd3a6f and especially 7bb17d60ead add some confusion on external audio devices for SPLs. There is an official microphone mentioned but not specified which one it is and isn't using an external microphone a huuuuge step back for @home?

**Comment by warp1337** [comment]
I would also like to point out that external microphones for speech processing would be a huge step backwards.

**Comment by kyordhel** [comment]
Back in 2010 there was a penalty of 100pts (10% of scorable points) for using non-on-board microphones.
To me, the continue rule completely neglects the need of any kind of microphone.
