### ISSUE TITLE
[Spoiler] P&G Challenge Setup

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#456]
### 1. Open Participation

First, as reminder, all competing teams will be allowed to participate in this challenge regardless if they advanced to Stage 2 or not (Stage 1 teams won't score). All you need to do is request participation with any OC member.

The Call is open to all teams from all leagues (including SSPL).

### 2. Objects
The objects to be used in this test will be actual eating utensils (i.e. tableware). If someone told you we were going to use a box of cereal as spoon, they lied to you.

The table setup to clean will have 6 objects with the following distribution:
- **Tableware:** Any three of ```{ bowl, cup, dish, glass, place mat }```
- **Cutlery:** Any two of ```{ fork, knife, spoon }```
- **Cascade Pod:** A Cascade Pod

### 3. Spill
In this test, the robot must clean a spill spot or some *breadcrumbs* from the table, depending on the table used for the test.

- **Table with tablecloth (soft surface):** A dry spot prone to be brushed. Some examples include:
  - Coffee or chocolate powder
  - Flour, salt, or sugar
  - Muesli
  - Breadcrumbs
- **Table without tablecloth (hard surface):** A wet spot prone to be scrubbed. Some examples include:
  - Chocolate syrup
  - Milk
  - Jam
  - Mustard

The color of the substance to be cleaned will contrast with the color of the table (e.g. red or black over white).

### 4. Setup
Teams may expect something like this (without the gift).

![image](https://user-images.githubusercontent.com/8583949/40313384-857052ae-5d0d-11e8-980c-2e09dcef9b5a.png)

**Remark:** We may use any kind of utensils available in the market (preferably lightweight ones and made of plastic). There is no restriction in the color or the contrast between the objects and the table. The image is for illustrative purposes only.

### 5. Running Example
Video belongs to homer@Uni-Koblenz. All people in the video allowed us to publish it.

[![German Open Setup](https://user-images.githubusercontent.com/8583949/40315106-62b6d59e-5d12-11e8-88d9-ff88bcc0c91d.png)](https://owncloud.uni-koblenz.de/owncloud/s/f4ydA5Y3PyrTFcC)
[Source](https://owncloud.uni-koblenz.de/owncloud/s/f4ydA5Y3PyrTFcC)

### 6. F.A.Q.

**Q:** Which table will be used for this test?
**A:** OC will announce it one day before the test. *Hint:* It will be close to the dishwasher.

**Q:** Will you announce the position of the setup within the table?
**A:** No, we won't.

**Q:** Can all teams participate?
**A:** Yes! Just inform your closest OC member.

**Q:** Can teams from SSPL also participate.
**A:** Yes! Just inform your closest OC member.

**Q:** Will there be any other objects in the table?
**A:** There might be any decorative objects in the table as in the arena's initial setup. However, the test area will have only those objects intended to be moved by the robot.

**Q:** Waht's the location of the Cascade Pod?
**A:** The location of the Cascade Pod will be announced at least 2 hours before the test.

**Q:** Can we use our own sponge/cloth/whatever to clean the spill?
**A:** Yes! Just be sure to present your cleaning device to the TC during the Robot Inspection.

**Q:** Can we use a tray or basket to move objects to the dishwasher?
**A:** Yes! If you plan to use a custom tray or basket, just be sure to present it to the TC during the Robot Inspection.

**Q:** The tableware and cutlery used in this test will be also used in GPSR/EEGPSR?
**A:** Yes! They will be normal known objects.

**Q:** Can I eat the Cascade Pod?
**A:** Please don't.

**Q:** Will there be cake after the test?
**A:** Yes! A delicious and moist slice of cake! But only for test subjects that complete all the tests.

**Comment by LoyVanBeek** [comment]
> The Call is open to all SSPL teams. 

This implies that it is for SSPL teams only, but it's for all leagues, right?

**Comment by kyordhel** [comment]
@LoyVanBeek All teams from all leagues

**Comment by semeyerz** [comment]
@kyordhel: will you add this to the rulebook's appendix?
As issue only few teams will see it.

**Comment by hugoleon18** [comment]
My team and I have some doubts about  the P&G Challenge:

1.- Does the robot have to navigate autonomously from outside the arena to the designated location?
2.- Is it necessary to give the robot a voice command to perform the task?
3.- Does the time run since entering the arena or when the command is given?
4.- If we require a restart, should we re-enter to the arena or can we start from the designated location?

I hope you can solve my doubts.

Thanks in advance

**Comment by kyordhel** [comment]
@semeyerz No, I don't have plans for that. It would be pointless now.

**Comment by kyordhel** [comment]
@hugoleon18 Please start your question in a separate issue.

Answering:
1. Yes (see 6.3.4.1).
2. Yes (see 6.3.4.2).
3. The timer starts when the referee opens the door (see 3.8.8.1).
4. Restart resets all the test but the timer. You start all over again from the outside (see 3.8.15).

**Comment by SJ-YI** [comment]
The cake is a lie!!!

**Comment by moriarty** [comment]
Can be closed?
