### ISSUE TITLE
Q: How will "designated position" for starting be designated and when?

### ISSUE THREAD

**Issue by AMR-** [RoboCupAtHome/RuleBook#458]
For GPSR, it says "The robot enters the arena and drives to a designated position where it has to wait for further commands."

How will this position be designated, and at what time?  Will we be told a specific position during setup days?  Can the robot just enter the designated entrance and be in the middle of the room?  Is the robot supposed to approach a person or otherwise approach a position designated only at test time?

**Comment by kyordhel** [comment]
All initial and designated positions are announced at least 2 hours before the test.

**Comment by LoyVanBeek** [comment]
In previous years, the organizers posted maps indicating the relevant positions for each challenge that needs it. 
The RoboCupAtHome github organization has a few repos related to tournaments, you can take a look at those. Eg. https://github.com/RoboCupAtHome/GermanOpen2018/blob/master/gpsr/gpsr_map.png
