### ISSUE TITLE
Q: About Final, Bronze Competition and winner of the competition

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHome/RuleBook#460]
I can find this sentences in 7.5 of the rulebook.

7.5. Final Ranking and Winner
The winner of the competition is the team that gets the highest ranking in the finals. There will be an award for 1st, 2nd and 3rd place. All teams in the Finals receive a certificate stating that they made it into the Finals of the RoboCup@Home competition.

If teams of bronze competition exceed total points which teams of the final, whether the place is replaced?

**Comment by kyordhel** [comment]
I do not understand your question. Could you please rephrase?

1. There is no bronze competition.
2. 1st & 2nd highest ranks advance to the finals, competing for the 1st place
3. 3rd and 4th highest ranks advance to the contest for the 3rd place.
At the end of 2nd stage, there is no way a 3rd place can get any higher than that.

**Comment by yuma116** [comment]
Thank you for your reply. I understood "2" and "3".
I have a question about "1". I can find "Bronze Competition" in 7.2 of the rulebook. But is there no "Bronze Competition"?

**Comment by kyordhel** [comment]
Sorry, my bad. I missed the last update.

There **is** a Bronze Competition, which maps directly to point 3 as a match in which 2rd and 4th best places go after the bronze. I've updated my former comment.

In one line: teams of Bronze Competition **can't** exceed the total points scored by teams on Grand Finale. Both are scored differently, hence normalized results cannot be merged and sorted.

**Comment by moriarty** [comment]
I will close this.

To clarify: Bronze Competition, is like a "Finals". Teams don't need to prepare something different for Bronze Finals vs. Gold Finals.

**Comment by kyordhel** [comment]
@moriarty as of 2019 on, there will be no more 3rd place finals. Only 1st and 2nd.
