### ISSUE TITLE
When will the final be held?

### ISSUE THREAD

**Issue by sungjae-cho** [RoboCupAtHome/RuleBook#461]
Following this schedule(http://www.robocup2018.org/?page=competition-schedule&lang=en), the final will be held in June 21. So, on June 20, is there no test in RoboCup@Home?

**Comment by airglow** [comment]
The linked schedule seems to target the soccer schedule. 

Schedule will be like this roughly:
* 16. June: Preparation Day
* 17. June: Preparation Day / Robot Inspection / may first Stage 1 tests
* 18. June: Competition
* 19. June: Competition
* 20. June: Competition
* 21. June: Finals

**Comment by sungjae-cho** [comment]
@airglow Thank you for your reply. Do you know when the schedule get fixed?

**Comment by kyordhel** [comment]
Focus on preparing for the competition. Schedules will be announced during setup days.
