### ISSUE TITLE
EEGPSR random category selection

### ISSUE THREAD

**Issue by Michiel29** [RoboCupAtHome/RuleBook#464]
The rulebook states that, for EEGPSR, after the team selects a category, the referee shall randomly decide between the normal, incomplete and erroneous scenarios for that category. My question is: will the team be notified of which scenario has been randomly selected, or is it our job to infer that?

**Comment by justinhart** [comment]
You infer it. It's intended to be really difficult.

**Comment by Michiel29** [comment]
Okay, thanks

**Comment by kyordhel** [comment]
@Michiel29 Once the test is running, the robot is on its own. That means no team interference. The robot must infer the scenario, although I don't see a reason to hide the chosen scenario from the audience (including the team).

I think there are some examples in the Appendix, but still. The command is:

> Bring me an apple

Apple is a fruit, and you know where fruits are (Fruits have predefined location). It might be the case that
1. The apple is there and you just need to go and retrieve it
2. The apple is somewhere else and the operator is expecting you to ask where
3. The apple is somewhere else but the operator does not know it

Me, as human, would go to the table/kitchen/whatever and check whether there are apples or not. If there is no apple there, I would yell at you asking where on earth are they. If you don't know (I assume I don't have to tell you, but a robot should), I might well be nice and look for some, ask you if you want a banana (assuming there are bananas) or just send you to the convenience store. Were my grand mother asking, then I would not yell, but go back and tell her that I'll go buy some.

Such kind of behavior we expect from a robot. It should be OK if
- There's no apple and the robot comes back and asks
- There's no apple and the robot comes back and tells you which other fruits are available
- There's no apple and the robot brings you another fruit instead, explaining there were no apples
- Etc

However, it would be **NOT OK** if
- There's an apple (nearby) and the robot comes back and asks
- There's an apple (nearby) and the robot comes back and tells you which other fruits are available
- There's an apple (nearby) and the robot brings you another fruit instead, explaining there were no apples
- There's an apple and the robot brings you a pear stating that it just gave you an apple
- Etc
 
### Why?
In the very first EEGPSR, categories were *3 at once*, *incomplete information*, and *erroneous information*. We found that, when teams know the category in advance, is pretty straightforward to add some heuristics to either fetch information or guess what could went wrong.

In the beginning, it was ok-ish, but that was 2013. Five years later robots should be a couple of steps forward in awareness, planning, and reasoning.
