### ISSUE TITLE
Q: Is it possible to schedule exclusive use of objects?

### ISSUE THREAD

**Issue by AMR-** [RoboCupAtHome/RuleBook#466]
In addition to teams being able to rent out objects during setup days, can there be a period of 1-2 hours during each setup day where all the objects are on a table in the arena and all teams are allowed to go and look at them?

**Comment by awesomebytes** [comment]
I don't know if the rules state anything officially off the exact number of
object sets and placement (and availability) but usually there are at least
2 sets, and the objects are in the arena.

You can also go buy at the supermarket the same ones (they are usually
common and cheap items) to have extra ones for continous testing.

**Comment by johaq** [comment]
Usually the objects should not leave the arena and are available to everyone there.
Some Teams go out and buy some of the objects (super market is disclosed by OC) to have a faster setup.
I think this is something the teams can sort out among them and there is no need for an official policy.

**Comment by kyordhel** [comment]
Unfortunately, no.

During setup days, all teams will get scheduled an *arena slot* for their exclusive use. Unfortunately, we can not grant the availability of the objects nor reserve its use. The OC is just made of volunteer organizers, we are not cops.

However, teams are allowed to buy their own object set at the closet store if they find it convenient. Also you can come to us and report if a team has performed a tactic anschluß of the official objects.
