### ISSUE TITLE
Last-minute VizBox Question

### ISSUE THREAD

**Issue by SJ-YI** [RoboCupAtHome/RuleBook#467]
I have two questions:

Q1: Is using the vizbox mandatory, like the teams not using one will be disqualified for the competition? 
Q2: If so, what is the MINIMUM amount of information vizbox should show? Is it okay to just show the strings? 

I am asking these because a) setting up the vizbox will take development time (which we lack), b) sending data over wifi will eat bandwidth (which is crucial for us who use external computation), c) adding more software/communications will add possible failure modes.

**Comment by moriarty** [comment]
Sorry to answer this with a question.

Have you tried using the visbox yet?
Are you using ROS?

**Comment by johaq** [comment]
Here this issue was also discussed:
https://github.com/RoboCupAtHome/RuleBook/issues/389

It is explicitly stated that using the vizbox is not mandatory but encouraged
