### ISSUE TITLE
Q: [Restaurant] End of Ordering Phase

### ISSUE THREAD

**Issue by rishihahs** [RoboCupAtHome/RuleBook#469]
From my understanding, the robot will take multiple orders before it goes to the kitchen (_"Hamburger with fries for table A and Orange juice for table B"_), rather than going to the kitchen after each order. When do we know that the ordering phase has ended? Will the referee notify the robot somehow?

**Comment by kyordhel** [comment]
In the same way any waiter/waitress would know it. Awareness and interacting with the customers.
In Restaurant like in other tests, the referee is not allowed to interact with the robot unless:
- The test explicitly states interaction
- By means of a general rule (e.g. Continue Rule)
