### ISSUE TITLE
Q: Contradiction in Help Me Carry?

### ISSUE THREAD

**Issue by guilhermelawless** [RoboCupAtHome/RuleBook#470]
Page 60 of the rulebook, regarding the bag pickup and delivery, it states:

- 4.2 Bag delivery: The robot takes the bag to the instructed destination. It may place
the bag on the floor or onto the placement location.

- 4.3 Asking for help: Close to the delivery location is another person. Facing that
person, the robot **must** kindly request for help carrying groceries into the house.

Is 4.3 during delivery, or afterwards? Does the robot really have to ask for help? Or only if it cannot deliver the bag by itself?

**Comment by kyordhel** [comment]
The test makes perfect sense if you consider that:

1. The person at the car is watching over the groceries
2. There are several bags with groceries to carry in.
3. The robot just carried one bag.
4. More hands helping are always welcome.

**Comment by guilhermelawless** [comment]
Thank you, we understood :+1:
