### ISSUE TITLE
URGENT: Latex does not compile!

### ISSUE THREAD

**Issue by rokusottervanger** [RoboCupAtHome/RuleBook#474]
The online latex compiler returns with errors.

**Comment by justinhart** [comment]
https://docs.google.com/viewer?a=v&pid=sites&srcid=cm9ib2N1cGF0aG9tZS5vcmd8cm9ib2N1cC1ob21lfGd4OjYwZDY3YTU4NmNiY2VhNzc

On Sat, Jun 16, 2018 at 3:08 PM, Rokus Ottervanger <notifications@github.com

**Comment by LoyVanBeek** [comment]
The compiled PDF is also posed to http://www.robocupathome.org/rules but @justinhart link points to the PDF directly. 

Regardless, PDF compiling is handy for ourselves as well.

**Comment by kyordhel** [comment]
Sorry, I'll try to fix it ASAP, although in my computer compiles fine with
rubber/pdflatex.
Maybe incompatibility of an older package with the latest Latex update?

**Comment by justinhart** [comment]
I'm pretty sure that it is the server getting spammed.

**Comment by moriarty** [comment]
It's compiling now.
