### ISSUE TITLE
Number of tests (EC decision for RoboCup 2019)

### ISSUE THREAD

**Issue by komeisugiura** [RoboCupAtHome/RuleBook#476]
Exec meeting on June 21, 2018
Participants (alphabetical order): Caleb, Komei, Luca, Mauricio, Sven, Tijn

Currently teams are super busy at the venue, and tend to spend their time for all tasks, and cannot focus on improving the modules for one task. Organization people are also always busy, which increases the risk of human error.

EC decision: 
- 1 test per day with possible repetitions of a test

**Comment by balkce** [comment]
It's important to mention that what we mean by three "tests", is more like three "scenarios" where the robot can carry out different tasks to be evaluated.

**Comment by benatuts** [comment]
Just connecting https://github.com/RoboCupAtHome/RuleBook/issues/574 here, as I think the new rulebook will require two scenarios per day to be able to fit everything into 3 days:
2 thematic scenarios x 2 stages + restaurant = 5 scenarios
