### ISSUE TITLE
Understandable tests (EC decision for RoboCup 2019)

### ISSUE THREAD

**Issue by komeisugiura** [RoboCupAtHome/RuleBook#477]
Exec meeting on June 21, 2018
Participants (alphabetical order): Caleb, Komei, Luca, Mauricio, Sven, Tijn

Currently the tests are complicated, and many things should be disambiguated in team leader meetings, which is not good for teams. 

Sponsors think the tests are boring. And, audience cannot see and hear what the robot is doing/saying.

EC decision
- We introduce an “outside scorekeeper”
  - Inside scorekeeper stays inside the arena same as this year
  - Outside scorekeeper stays outside the arena (=audience area)
- Teams are incentivated to make robots clearly show/tell that they have accomplished subtasks (=grasping, navigation, speech recognition/face recognition, …) to the outside scorekeeper
- It is team’s responsibility to show/tell that the robot has accomplished each subtask
- The teams/referees must NOT inform the outside scorekeeper that the robot has accomplished a subtask
  - e.g. Not allowed to say “Hey! The robot said it understood the command!!”

**Comment by johaq** [comment]
Main goal scoring should make it clearer when scores are achieved.
