### ISSUE TITLE
Open Challenge (EC decision for RoboCup 2019)

### ISSUE THREAD

**Issue by komeisugiura** [RoboCupAtHome/RuleBook#478]
Exec meeting on June 21, 2018
Participants (alphabetical order): Caleb, Komei, Luca, Mauricio, Sven, Tijn

In 2006-2008, most teams failed to obtain score in non-demonstration tests, therefore demonstration was introduced to introduce non-zero-score tests. 

However the situation has changed, and we do not need OC any more. Some teams even show the same thing in OC and Finals, which is waste of time.

EC decision
 - Remove Open Challenge

**Comment by kyordhel** [comment]
Implemented in #531
