### ISSUE TITLE
Scenario: wheelchair accessibility

### ISSUE THREAD

**Issue by jlunenburg** [RoboCupAtHome/RuleBook#48]
In order to specify the heights of doorsteps/thresholds etc of the floor and possibly the minimum width of walls, it might be a good idea to look at the requirements for wheelchair-accessible areas. If robots are developed to aid, e.g., the elderly, the environments they operate in will mostly meet these requirements.

**Comment by LoyVanBeek** [comment]
As for the door width: https://www.google.nl/search?q=minimum+door+width+for+wheelchair+access yields 36 inches i.e. 0.9144m 

As to the floor: the rulebook states the following:

> Floor: The floor of the arena as well as the doorways of the arena are even. That is,
there will be no significant steps or even stairways. However, minor unevenness such as
carpets, transitions in floor covering between different areas, and minor gaps (especially
at doorways) must be expected.

Given that we'd rather want to increase complexity and uncertainty, I'd say the current rules are clear enoguh. Moreover, the focus for RoboCup@Home is not just for elderly care but other homes as well.
