### ISSUE TITLE
About removing the finals and open challenge

### ISSUE THREAD

**Issue by airglow** [RoboCupAtHome/RuleBook#484]
I just want to start a discussion about the plan to remove both, the Open Challenge **and** Finals. 
I certainly get that it's useful to remove one, because teams tended to show the same, or very close ideas, for the Open Challenge as for the Finals. (I'm also in the opinion that this was caused by the massive amount of tests, such that there was simply no time to prepare yet another test).
However, when we now take them both that will also take a possibility for teams to present their research activities. I currently don't see any space for that in the current renovation of the rulebook, when we also throw out these open presentations. What we gonna miss out then will be great ideas that later on influenced many teams. I'm talking about things like the sound source localization, the world model, the usage of natural language to  communicate between robots, advanced reasoning, augmented reality interfaces, in general alternative interfaces, robot-robot collaboration, picking up hard things like papers, opening bottles, preparing sausages, taking out trash ... 
Further, for my impression, those challenges were those where people actually discussed afterwards their approaches.
I'm fine with removing them from where they are, but we should keep a place for teams to present their specialization somewhere (beside the poster).

**Comment by kyordhel** [comment]
You've a valuable point @airglow. In this regard, I must present some considerations:

## Considerations
### League wise
1. The new competition schema leaves little to no time for an open demonstration.
2. In many cases open demonstrations are poorly-prepared / improvised
    2.1. This is **not** how we expect teams to present their main research
3. Open demonstrations are very hard to score
    3.1. There is not a deterministic way to evaluate performance proportional to the competition standards
    3.2. Often the best demo/intention scores higher than the best robot
    3.3. In Finals, the 1st place may go to the best demo and not to the best robot

### From the Federation's perspective
1. People is protagonist, not robots
2. It is very hard for people to understand why a robot won
3. It is very hard for people to understand what is going on in an open demonstration
4. Final demonstration often has nothing to do with a domestic task

## Possible solutions
It seems people in the Federation is quite concerned about us. Teams look exhausted, referees are tired and become error prone, there are many tests and little success. From that, Trustees and EC came up with a solution, but we got also constrains.

### Constrains
- Two setup days + 3 competition days (2 First Stage, 1 Second Stage) + Finals
- We run 3 tests only, one per day
    - Tests run from 09:00 to 12:00 and from 15:00 to 18:00
        - Teams have time to fix and improve (improvise, adapt, overcome)
        - Teams have time to eat and sleep
        - Referees have time to eat and rest
    - A robot can re-enter the arena and test again as many times as time allows it (infinite runs)
    - Each test comprehends a different scenario in which the robot can execute many tasks
        - [S1] Cleaning the apartment
        - [S1] Hosting a party
        - [S2] ~To be defined~
    - The robot chooses the task to solve and how to solve it
    - Robot can always ask for human help
- At least two robots in the arena all the time
- There is something happening in the arena, always
- Finals is a regular task. Faster/better robot wins

### Solutions
An Open Demonstration for Finals seems to be out of discussion. The Federation wants to have an out-of-doubt winner. From audience perspective, the very best. Then, our main problem is when to schedule an Open Challenge. Running it after RIPS would steal focus from Poster Session, so maybe the Poster Session and the Open Challenge may fuse.

To deal with lazy demos, the EC decided to give max 1pt (one point) for the Open Challenge and schedule it after Stage 2. Same as Technical Challenge. This has the main con that many teams will loose absolutely any interest on it. Further, no finalist would risk the Final to present a 5 min Open Challenge. Scheduling after Stage 1 has the same effect but for Stage 2 teams. The winner would get a Certificate.

Other than that, **we are open to proposals.**
