### ISSUE TITLE
Storing Groceries [restructured][draft]

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#490]
## Main Goal

All groceries put away.

## Setup

Groceries have been delivered to the front door via some fancy online grocery service.

**Comment by nickswalker** [comment]
> **HINT**: The robot can ask the referee where to place the carried object (relative positions or pointing are both allowed).

Instead of framing this as a hint, it may match more with the rest of the tasks to include this as a Deus ex Machina in the remarks. That would also be the place to highlight whether we want to/how much to expressly penalize human help with the manipulation.

**Comment by johaq** [comment]
My proposed changes (pull request #520):
1. I removed a lot specific mentions of numbers. Again, I feel they are unnecessary to the execution of the task, makes refereeing harder and less flexible, and encourages teams to hard code information.
2. As @nickswalker mentioned I moved the hint to the DEM section as it fits better with the other tasks.

I also would like to discuss removing the part about the operation area being clear. I understand it has been added recently by request of some teams so I did not just want to remove it without discussing it.
I think it contradicts parts of the general rules (robot always being safe) and I do not feel it puts a lot of extra burden on teams. Robots without sufficient sensors can always announce going backwards and be safe that way.

**Comment by kyordhel** [comment]
Bump. Check #520

**Comment by johaq** [comment]
Regarding #545. One way I see to make this task significantly easier to setup would be to remove the part about grouping in categories. I would be fine with just seeing a robot get objects into the shelf

**Comment by kyordhel** [comment]
@johaq The point of this test is categorization. Pick and place is more or less a must.

**Comment by kyordhel** [comment]
As I see it, it is quite simple. You set the cupboard once (grouping apples with apples and cokes with cokes is trivial to us) and let the robots do their best. Every time a robot finishes a test you take the objects it moved back to the table.

Shouldn't take more than 10 seconds, but I agree description must be shorten.

**Comment by johaq** [comment]
The way I see it that is already in the rules. It states nowhere you need to reset the cupboard everytime.

I added back the 5-10 object range as requested and removed the clear area rule since no one seemed to object to removeing it.

**Comment by kyordhel** [comment]
@RoboCupAtHome/technical-commmittee Can we consider the Storing Groceries task as complete?

Can we close the issue?

**Comment by johaq** [comment]
I think so, yes
