### ISSUE TITLE
Take out garbage [restructured][draft]

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#493]
## Main Goal

There is no garbage inside of the apartment

## Setup

There is garbage inside of the apartment. For example: One paper basket near a desk, and one recycling bin and one compost bin near the sink.

**Comment by johaq** [comment]
Some proposed changes (Pull request #519):
1. The multiple collection zones seem unnecessary to me and overly complicated. Also, task is already hard without outside navigation. So I removed the outside one in favor of one zone near the entrance which also should be easily understandable by audiences.
2. Changed the bonus goals to emphasize the manipulation aspect. One rewards the robot for removing the lid from the bin and a very large bonus for carrying both bags at once to also have some encouragement for bi manual manipulation.
3. I think the bins should just be part of the normal arena setup. It's easier for referees because no additional setup required.
4. Added Deus Ex Machina rule to request a human to hand over the bag resulting in a 80% score reduction.

**Comment by kyordhel** [comment]
Thanks @johaq for the PR. I still have to review it, but from this comment I got some counter-arguments
1. This test was a perfect excuse to test unsupervised outdoor navigation. As you say, it might make more sense to have the containers next to the entrance, so let's think about any other test that allows us to test navigation outside.
2. No lids please. Any bucket with a bag can serve as trash container. We are not sure we can get an standard trashbin with a lid.
    - If you insist in having a bin with a lid, please look for an IKEA one add it to the Objects section under General Rules
3. Add it to the Objects section under General Rules
4. Let's not work with percentages but net points (e.g. 400pts).

**Comment by johaq** [comment]
1. Don't we have outdoor nav in restaurant and potentially GPSR? 
2. Was thinking sth like this: https://www.ikea.com/gb/en/products/small-storage-organisers/waste-sorting-bins/knodd-bin-with-lid-galvanised-art-10218937/
3. Will do
4. So far every DEM rule I have seen uses percentages

**Comment by kyordhel** [comment]
1. GPSR faith is uncertain. Restaurant is Stage 2. We need to test outdoor navigation in Stage 1.
    1.1. I'm not saying We must keep it in this test, just that we might need put it somewhere else.
2. I love it but teams will hate you. Those containers are almost invisible to the Kinect/Prime Sense
![image](https://user-images.githubusercontent.com/8583949/51386166-d3a22380-1b21-11e9-9a81-d957d74dce16.png)
3. :+1: 
4. In general rules is ok. In test I think it makes more sense to add points. I'll make an issue.

**Comment by johaq** [comment]
1. I see. Then I would actually prefer to only have the zone outside. Maybe put a toy garbage truck in it for the audience... Don't really see a good way to include outside navigation in other stage 1 tests.
2. https://www.ikea.com/gb/en/products/small-storage-organisers/waste-sorting-bins/knodd-bin-with-lid-grey-art-60312249/ should be more visible.

**Comment by kyordhel** [comment]
1. As an Eco-friendly person, I want to have robots separating trash (bonus maybe). Containers can be one next to the other. Up to you, buddy.
2. Better. we can tape the handle to make it visible. Also add some weight in the bottom to prevent flipping.
![image](https://user-images.githubusercontent.com/8583949/51386676-93dc3b80-1b23-11e9-9038-0130dd793a00.png)


3. This one will be awesome in the arena Easy to see specially when the robot takes out the bag. Good challenge for navigation.

![image](https://user-images.githubusercontent.com/8583949/51386670-89ba3d00-1b23-11e9-8cc5-45489435e167.png)

**Comment by kyordhel** [comment]
Not necessarily. Consider:
- **A:**
    - Kitchen's garbage always to Organic (Abfall?) black container
    - Studio's garbage always to Paper yellow container
- **B:**
    - Black garbage bag always goes to Organic (Abfall?) black container
    - Yellow garbage bag always goes to Paper yellow container

IMHO **B** is easier to track and score, but also less realistic in domestic environments (e.g. black or transparent bags are used for everything). **A** on the other hand requires more attention from the referee (perhaps labeling the bags) but is way more common. Also, **A** has the advantage of requiring less logistics (any bag will do), whilst **B** will have the OC struggling to get colored bags somewhere.

An hybrid approach **C** is also possible.

**Comment by kyordhel** [comment]
Merged.
