### ISSUE TITLE
Drink Delivery [restructure][draft]

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#494]
## Main Goal

All thirsty party attendees have been served a beverage of their choice.

## Setup

1. There are guests attending a party or reception, and some are thirsty.
2. There is a selection of drinks available, they are in a defined location

##  OC Instructions

Drinks need to be provided, locations of drinks need to be announced

**Comment by nickswalker** [comment]
> Telling the robot which drink is unavailable causes a reduction of 40\% in scoring for that particular guest.

Presumably this is mostly about not having the robot come up to the bar tender to ask for something that isn't stocked, but I don't see much problem with the robot doing something like this once at the beginning of the task. "Hey bartender, are we out of anything tonight?"
Things are rarely so neatly laid out that a person could tell whether the bar has or does not have something visually, so asking (once and remembering) actually seems more plausible.

**Comment by kyordhel** [comment]
@nickswalker I see your point. The idea here is to test reasoning over robust object recognition. Your proposal kind of voids this purpose, but makes a lot of sense. Honestly I'd like to keep both, but can't figure out how (specially without making the task overly complex or expand its description).

Could you please come out with an alternative for testing reasoning over robust object recognition?

**Comment by kyordhel** [comment]
@RoboCupAtHome/technical-commmittee Can we consider this task as complete?

Can we close the issue?
