### ISSUE TITLE
Restaurant [restructure][draft]

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#497]
## Main Goal

All patrons of a restaurant have been attended to. They have been offered menus, their orders have been taken and their food has been served to them.
Robots are operating in a previously unknown (not mapped!) environment.

## Setup

Ideally this test happens in a real world environment. Such as the Tim Hortons outside of the venue in 2018.

## TC/OC preparation

1. Have someone who speaks the local language and is polite to do the negotiation with the location.
2. DO NOT LET THE TEAMS KNOW WHERE IT WILL HAPPEN.

## TEAMS should note:

1. We don't guarantee WiFi, nor internet access (during any part of the competition).
2. Robots should be able to move to a new location easily and we will be as reasonable as possible but you must keep in mind your robots battery life.

**Comment by MatthijsBurgh** [comment]
@awesomebytes can you add me to this repo and assign me this issue?

**Comment by awesomebytes** [comment]
@MatthijsBurgh as far as I can see, you already self assigned yourself and you are already a member of the repo :+1:

**Comment by MatthijsBurgh** [comment]
We had some help of @kyordhel
