### ISSUE TITLE
[Manipulation] bookcase and table confusion

### ISSUE THREAD

**Issue by semeyerz** [RoboCupAtHome/RuleBook#51]
The manipulation task states that there can be different *heights* OR different *positions*.
Later on there is only a description for the bookcase with different heights.

Is it set that this task has to be performed in front of a bookcase or is it still possible that the robot has to grasp from different tables?

**Comment by LoyVanBeek** [comment]
The task must be performed in front of a bookcase, in which different positions are defined, at different heights.
