### ISSUE TITLE
(P&G) Dishwasher [restructure][draft]

### ISSUE THREAD

**Issue by awesomebytes** [RoboCupAtHome/RuleBook#511]
As discussed in the meeting from 2019.01.14 please add a draft for P&G Dishwasher test based on the previous one.

Allison Henry offered to do it, anyone knows her Github user?

**Comment by allisonh-tri** [comment]
hi, yes, I can do this.

**Comment by allisonh-tri** [comment]
though I strongly prefer the date to be expressed as 19/01/14 for sorting purposes. ;)

**Comment by balkce** [comment]
> though I strongly prefer the date to be expressed as 19/01/14 for sorting purposes. ;)

Thank you!

**Comment by allisonh-tri** [comment]
I'm getting to this now.  Bear with me.  I will start with adding the test from last year and will add comments to explain my updates as I make them.

**Comment by allisonh-tri** [comment]
Right.  So this is what I am starting from:

\section{Procter \& Gamble Dishwasher Challenge [DSPL \& OPL]}

\newcommand{\openpart}{%
All teams are allowed to participate and compete in the \textit{Procter \& Gamble Challenge} regardless of whether they advanced to the Stage II or not, and get the award.
}

The robot has to remove all dishes from a table (presumably after dinner) and place them into the dishwasher.

\subsection{Open Participation}
\openpart

\subsection{Focus}
This test focuses on object perception, manipulation, and planning.

\subsection{Setup}
\begin{itemize}
	\item \textbf{Location:} This test takes place in the arena. A dining table is located close to the dishwasher.
	\item \textbf{Dishwasher:} The dishwasher is near the table, preferably located in the same room. The dish washer is open and with all racks out.
	\item \textbf{Tray:} A plastic tray is located either on top of the dishwasher, or onto one of its racks. The tray may have tableware and cutlery placed inside already.
	\item \textbf{Table setting:} The table has several objects disposed in a typical setting for a meal for one person. These objects include tableware (e.g.~place mats, napkins, dishes, glasses), and silverware (e.g.~forks, spoons, knives).
	\item \textbf{Spot:} There is a dirty spot on the table next to the table setting that requires cleaning.
\end{itemize}

\subsection{Task}
	\begin{enumerate}
		\item \textbf{Entering the arena:} The robot enters the arena and navigates to the designated location.
		% \item \textbf{Fetching command:} The operator requests the robot to clean up the table.
		\item \textbf{Clean the table:} The robot takes all the tableware and cutlery to either the dishwasher or to the tray, as instructed (team's choice).
		\item \textbf{Filling the dishwasher:} If the robot placed the objects into the tray, it must proceed to put the tray onto one of the dishwasher racks.
		\item \textbf{Place the Cascade Pod:} The robot places the  Cascade Pod~into the dishwasher, preferrably inside the tab compartment.
		\item \textbf{Scrub spots and spills:} The robot detects spots and spills on the table and clean them up using the cleaning cloth or sponge it has retrieved previously.
		\item \textbf{Leave the arena:} The robot leaves the arena once it has finished cleaning.
	\end{enumerate}

\subsection{Additional rules and remarks}
\begin{enumerate}
	\item \textbf{Collisions:} Slightly touching the table is allowed, as well as slightly pushing some objects. However, driving over the objects or any other form of a major collision is not allowed, and the referees directly stop the robot (see~\refsec{rule:safetyfirst}).

	\item \textbf{Objects:} A total of 6 objects are used in this test following the distribution shown below:
	\begin{itemize}
		\item\textit{Silverware}: Any two objects.
		\item\textit{Tableware}: Any three objects, excluding silverware. At least one must be a dish.
		\item\textit{Cascade Pod}: One Cascade Pod.
	\end{itemize}
	All objects used in this test are taken from the list of standard objects (See~\ref{rule:scenario_objects}). All of them are considered to be known to the robot.

	\item \textbf{Safe placing:} Objects placed in the rack or tray must be placed gently and safely. It must be clear to the referee that the robot is trying to put the object in place and not dumping, throwing, or dropping it. Dumped and dropped objects won't be scored even if they land in the dishwasher/tray.

	\item \textbf{Special Objects:} The plastic tray and the Cascade Pod are provided by \textit{Procter \& Gamble} and are considered special objects. Teams are not allowed to use substitutes of them in this test.

	\item \textbf{Spots and Spills:} The referees must place a spot (e.g.~jam or chocolate syrup) or spill some liquid (e.g.milk) on the table before the test starts. The substance used to create the spot shall be clearly visible and contrasting with the table. When cleaning it, it must be clear the robot has detected the spot and is trying actively to clean it. The selection of the cleaning tool (sponge or cloth) is made by the team.\\
	\textbf{Remark:} When possible, no tablecloth will be used to ease cleaning. If removing the tablecloth is not possible, a dry spot will be used instead (e.g.~breadcrumbs or coffee powder).

	\item \textbf{Dishwasher:} Is up to the team to decide whether the robot will place the objects in the dishwasher's rack or in the official tray. When using the tray, it should be loaded into the dishwasher.

	\item \textbf{Dishwasher door:} Unless requested otherwise by the team, the dishwasher is open and with the racks pulled out by default. The team leader can, however, request the diswasher to be closed and score additional points for opening it. If the robot fails to open the door, it must clearly state it and request the referee to open it.

	\item \textbf{Human-Robot Interaction:} The robot is allowed to
	\begin{enumerate*}[label={\alph*)}]
	\item indicate the location of the cloth or sponge,
	\item ask the human operator what to do with food leftovers,
	and
	\item request operator's help to find the spot (e.g.~pointing at it).
	\end{enumerate*}
	This interaction is extensible to any kind of reasonable request from the robot when attempting to solve the task.

	\item \textbf{Open Participation}
	\openpart
	However, scoring in this test will be only considered for those teams who have advanced to Stage II. This way, no Stage I team can have an overall score higher than a Stage II team.

\end{enumerate}

% \subsection{Data recording}
% Please record the following data (See~\refsec{rule:datarecording}):
% \begin{itemize}
% 	\item Images of recognized objects
% 	\item List of moved items
% \end{itemize}

\subsection{Referee instructions}

The referee needs to
\begin{itemize}
	\item Place the table setting.
	\item Clean spots smudged by the previous robot.
	\item Place the new spot meant to be clean.
	\item Place the tray on the dishwasher or onto the rack, as requested by the team.
\end{itemize}

\subsection{OC instructions}
During Setup days:
\begin{itemize}
	\item Provide official cutlery and tableware for training.
\end{itemize}

2 hours before the test:
\begin{itemize}
	\item Announce the predefined location to take the command.
	\item Announce the predefined location of the Cascade Pod.
\end{itemize}

\newpage
\subsection{Score sheet}
\input{scoresheets/PnG.tex}

% Local Variables:
% TeX-master: "Rulebook"
% End:

**Comment by allisonh-tri** [comment]
I would like to add:

- points awarded for loading effectively - iterating position
- points awarded for perceiving dishes already loaded

I question the payload capacity of the robot to load the tray into the dishwasher.

- adding the soap into the soap box should be extra points.  ideally a soap box would be possible to open by a robot, but this seems unlikely.
- metallic silverware 

- can we omit cleaning the spill??  this does not seem like a necessary part of the dishwasher task nor something the standard platform could achieve in a way that would satisfy a real end user.

- soap pods should be accessible to the robot easily.  possibly in a cabinet the robot could open.

- robot presses start button on dishwasher or requests that button is pushed after finishing loading.

**Comment by allisonh-tri** [comment]
Something I am unclear on is whether there is a stage 1 and stage 2 dishwasher task and I am writing stage 2 and 1 is already written or if there is only 1 dishwasher task which is in stage 2.  Please clarify and please excuse my ignorance.

**Comment by balkce** [comment]
From what I understand, this is a Stage II test. The idea is to modify the way that it is written such that it follows the new philosophy of brief descriptions (as of now, it's four pages long).

As for omitting the cleaning-the-spill part: I agree. I would like to have a test that is straightforward, but challenging at the same time.

**Comment by kyordhel** [comment]
@allisonh-tri 

Better if you submit a PR to comment per line. Regarding your question, the Diswasher task is only for Stage 2 competitors, there is no equivalent in Stage 1. Also, don't put much effort on the options you give to teams, they will always choose the least effort. Robots can't handle metallic objects, will struggle with the cascadepod, and definitively can't place objects oriented, so just putting them inside suffice. 

So far it seems you have much faith in the league. I'll be sad to disappoint you. So far, only winners can handle this:

![image](https://user-images.githubusercontent.com/8583949/51868617-ba357e80-234e-11e9-998a-0b9979f5cbab.png)


# Objectives
The test must have a main objective. Teams only score if they complete the main objective. If your main objective is have the dishwasher loaded with 6 objects, is 6 or nothing.

Once the main objective was completed, we consider bonus objectives. A bonus objective makes the task more challenging.

# Restrictions
- Cap is 2500 pts
- Main objective ~750pts and 1500pts (lower is better)
- There is a limit of 2 pages including the scoresheet
- It is forbidden to tell teams what to do in which order

# Snippet
## Dishwasher task
The robot stores dirty dishes in the dishwasher

## Setup
- **Location:** The test takes place in the kitchen
- **Dishwasher:** The dishwasher is initially closed, empty, and loaded with the official tray.
- **Table:** The re are 6 utensils in the kitchen table, 3 from *cutlery*, 3 from *tableware* categories

## Main goal
The dishwasher has least 1 utensil inside.
**Reward:** Score calculated per object

## Bonus objectives
- Each additional object placed in the dishwasher
    - Tableware (200pts)
    - Cutlery (300pts)
- Place the soap in the dishwasher (400pts)
- Open the dishwasher's door (400pts)
- Pull the dishwasher racks (200pts)

## Additional Rules and Remarks
- **Safely placing objects:** Objects must be safely placed, not dropped inside.
- **Using the sink instead:** Objects placed in the sink contribute only with 50% of the score.
- ***Deus ex Machina:*** There is no score reduction for asking the referee to open the dishwasher and pull the racks.

**Comment by kyordhel** [comment]
@RoboCupAtHome/technical-commmittee Can we considered P&G Challenge as complete?

Can we close the issue?
