### ISSUE TITLE
Open Challenge becomes an Award [restructure][draft]

### ISSUE THREAD

**Issue by awesomebytes** [RoboCupAtHome/RuleBook#513]
As we discussed in the meeting from 14/01/19:

Open Challenge becomes an award. The proposal is to make it optional, have teams announce they want to do it and distribute their slots after the 2nd block of testing (after 6PM) so we can all enjoy learning about their research (and, as feedback was given it was boring for the common public, they most probably won't be there after 6PM). @balkce thank you for taking care of it.

**Comment by kyordhel** [comment]
@balkce Any progress?

**Comment by balkce** [comment]
I was waiting for the TC meeting tomorrow to announce it, but I might as well do it now:

The EC has come to the decision to remove the Open Challenge entirely. There will be some venues during the competition to present research demonstrations from teams to the league, if they so desire. There is also the idea modify the Finals ( #508 ) to provide another of venue for this. However, as of now, the Open Challenge is removed from the 2019 rule book.

I'll start working on these changes tomorrow.

**Comment by kyordhel** [comment]
Now it is official. We might keep the award for the voluntary demos, though.

**Comment by balkce** [comment]
This is now reflected in #531 .
