### ISSUE TITLE
RuleBook meeting 14/01/19 summary

### ISSUE THREAD

**Issue by awesomebytes** [RoboCupAtHome/RuleBook#514]
You can find the summary of the meeting from 14/01/19 here:

https://docs.google.com/document/d/1U1ytCT8FMhXeqGY2H4r-Svj5FrjradlZp5YNFVtvOcc/edit?usp=sharing

**Comment by kyordhel** [comment]
Sorry about the harassment (not really). This is a bump

- @johaq 
    - Clean Up (#492)
    - Storing Groceries (#490)
    - Take Out the Garbage (#493)
- @awesomebytes 
    - Receptionist (#495)
    - Farewell (#496)
    - Serving Drinks (#494)
    - Find My Mates (#499)
- @MatthijsBurgh 
    - Restaurant (#497)
- @justinhart 
    - GPSR (#510)
    - House guide HRI (#512)
- @allisonh-tri 
    - (P&G) Dishwasher (#511)
- @balkce 
    - No open challenge (#513)

So, guys... Any progress?

**Comment by balkce** [comment]
See #513 .
