### ISSUE TITLE
Enter Arena as Standard Task Start

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#518]
I'd like to propose to start every test with an enter arena procedure that is already part of some tests.
I mean the standard robot knocks, referee opens door for the robot.

I think this has some advantages:
- Clear start for referees. As soon as you open the door the task has started. No team members still typing on the robot in the arena etc.
- Easy to understand task start for the audience. Starts in the arena imo seem weird for the audience.
- Overall more consistency for everyone in the tasks.

**Comment by kyordhel** [comment]
I like the idea but this might mean a refactoring and rebalance of all tests.

**Comment by johaq** [comment]
I think this can be added when the task are otherwise finished. I could do the necessary changes then.

**Comment by justinhart** [comment]
At RoboCup it was decided that in the future entering the arena would be a mandatory start to tasks. If there is a stereotypical start position for the robot inside the area, then the robot should navigate to that position once the door has been opened.  This should be reiterated to the TC, and there should be formatting in the rulebook to make this clear.
