### ISSUE TITLE
New question regarding person recognition test

### ISSUE THREAD

**Issue by LoreChile** [RoboCupAtHome/RuleBook#52]
Regarding the interaction between the robot and the crowd:

Can the robot get inside the crowd?
Can the robot give instructions to the crowd, for example, that everyone look at him?

Thanks!

**Comment by LoyVanBeek** [comment]
Hey María, 
Currently, we don't have any rules regarding these tactics, but it is not in the spirit of the challenge.

@kyordhel should we explicity state that the robot must only *observe* the crowd *from a distance*?

**Comment by LoreChile** [comment]
Will you have further news regarding my question?

**Comment by kyordhel** [comment]
María,

The issue is closed. We see no point in getting into the crowd. Also the robot may ask anyting to the crowd, but is up to them to cooperate.
