### ISSUE TITLE
Scenario balance and task brainstorming

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#534]
So far, the balance between scenarios including PR in as follows:

<table>
	<tr>
		<th colspan=2>Stage 1</th>
		<th colspan=2>Stage 2</th>
	</tr>
	<tr>
		<th>Housekeeper (5)</th>
		<th>Party Host (3)</th>
		<th>Housekeeper (3)</th>
		<th>Party Host (1)</th>
	</tr>
	<tr>
		<td>Clean Up</td>
		<td>Farewell</td>
		<td>Clean Table</td>
		<td>Restaurant</td>
	</tr>
	<tr>
		<td>Help Out (GPSR)</td>
		<td>Receptionist</td>
		<td>Set the Table</td>
		<td></td>
	</tr>
	<tr>
		<td>I want this</td>
		<td>Serving Drinks</td>
		<td>Find my Disk</td>
		<td></td>
	</tr>
	<tr>
		<td>Storing Groceries</td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<tr>
		<td>Take out the Garbage</td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
</table>

Stage I balance is 5:3, while ideally we should have have 5/5 better 7/7. Likewise, in Stage II the balance is 3:1 while it should be 3:3 or 4:4. We can make an exception here since Restaurant is kind of *mandatory* (no other task can be tested in that time slot).

This means we must push a little bit and come out with at least 2 Party Host tasks for Stage I and at least two more for Stage II just in case.

**Remark:** *I want this* will be split, producing one Party Host test, and *Find my Disk* could be moved to Party Host, although the task involves only one person.

**Comment by johaq** [comment]
Maybe a stupid question since I could not attend the meeting but was the goal not to have a reduced number of tasks? This looks like the opposite.

**Comment by johaq** [comment]
Ah ok. So teams choose where to participate and if they overburden themselves it's their fault?
I see that as a little problematic since this favors teams who can just pull a ton of people. Small teams are put at an disadvantage even more so than before.

**Comment by kyordhel** [comment]
Exactly. That gets compensated by the fact that we don't force you to solve a test in which your research group has either not interest or expertise (e.g. team that do research in NLP and have very poor control).

The TC will try to keep this balanced as much as we can. We think we can cope this "small teams" issue by fostering collaboration between SPLs (sorry OPL). It might be naive but that's our most prominent solution.

Either way, we need more tasks.

**Comment by johaq** [comment]
Update:

<table>
	<tr>
		<th colspan=2>Stage 1</th>
		<th colspan=2>Stage 2</th>
	</tr>
	<tr>
		<th>Housekeeper (4)</th>
		<th>Party Host (3)</th>
		<th>Housekeeper (3)</th>
		<th>Party Host (4)</th>
	</tr>
	<tr>
		<td>Clean Up</td>
		<td>Farewell</td>
		<td>Clean Table</td>
		<td>Restaurant</td>
	</tr>
	<tr>
		<td>Help Out (GPSR)</td>
		<td>Receptionist</td>
		<td>Set the Table</td>
		<td>Hand me That</td>
	</tr>
	<tr>
		<td>Storing Groceries</td>
		<td>Serving Drinks</td>
		<td>Find my Disk</td>
		<td>Where is This?</td>
	</tr>
	<tr>
		<td>Take out the Garbage</td>
		<td></td>
		<td></td>
		<td>Party Pooper</td>
	</tr>
</table>

**Comment by johaq** [comment]
Updated table of current tasks and table of pull requests to have an overview of what still needs to be done. Feel free to comment if I missed something or if you made some changes.

<table>
	<tr>
		<th colspan=2>Stage 1</th>
		<th colspan=2>Stage 2</th>
	</tr>
	<tr>
		<th>Housekeeper (5)</th>
		<th>Party Host (5)</th>
		<th>Housekeeper (5)</th>
		<th>Party Host (5)</th>
	</tr>
	<tr>
		<td>Clean Up</td>
		<td>Find My Mates</td>
		<td>Clean Table</td>
		<td>Restaurant</td>
	</tr>
	<tr>
		<td>GPSR</td>
		<td>Receptionist</td>
		<td>Set the Table</td>
		<td>Hand me That</td>
	</tr>
	<tr>
		<td>Storing Groceries</td>
		<td>Farewell</td>
		<td>Find my Disk</td>
		<td>Where is This?</td>
	</tr>
	<tr>
		<td>Take out the Garbage</td>
		<td>Carry my Luggage</td>
		<td>Laundry Sort</td>
		<td>Stickler for the Rules</td>
	</tr>
	<tr>
		<td>Onlooker</td>
		<td>Robot Eye</td>
		<td>Is the Refrigerator Running?</td>
		<td>Bartender</td>
	</tr>
</table>

<table>
<tr>
		<th>Task</th>
		<th>Pull Request By</th>
		<th>Reviewed</th>
		<th>Latest Review Addressed</th>
		<th>Approved</th>
		<th>Closed</th>
</tr>
<tr>
		<td>Clean Up</td>
		<td>@johaq</td>
		<td>:heavy_check_mark:</td>
		<td>:heavy_check_mark:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>GPSR</td>
		<td>@justinhart</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:heavy_check_mark:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Storing Groceries</td>
		<td>@johaq</td>
		<td>:heavy_check_mark:</td>
		<td>:heavy_check_mark:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Take Out The Garbage</td>
		<td>@johaq</td>
		<td>:heavy_check_mark:</td>
		<td>:heavy_check_mark:</td>
                <td>:heavy_check_mark:</td>
                <td>:heavy_check_mark:</td>
</tr>
<tr>
		<td>Find my Mates</td>
		<td>@awesomebytes</td>
		<td>:heavy_check_mark:</td>
		<td>:heavy_check_mark:</td>
                <td>:heavy_check_mark:</td>
                <td>:heavy_check_mark:</td>
</tr>
<tr>
		<td>Receptionist</td>
		<td>No PR?</td>
		<td></td>
		<td></td>
                <td></td>
                <td></td>
</tr>
<tr>
		<td>Farewell</td>
		<td>No PR?</td>
		<td></td>
		<td></td>
                <td></td>
                <td></td>
</tr>
<tr>
		<td>Serving Drinks</td>
		<td>No PR?</td>
		<td></td>
		<td></td>
                <td></td>
                <td></td>
</tr>
<tr>
		<td>Help me Carry</td>
		<td>@syedaraza</td>
		<td>:heavy_check_mark:</td>
		<td>:heavy_check_mark:</td>
                <td>:heavy_check_mark:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Carry my Luggage</td>
		<td>@syedaraza</td>
		<td>:heavy_check_mark:</td>
		<td>:heavy_check_mark:</td>
                <td>:heavy_check_mark:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Robot Eye</td>
		<td>@justinhart</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Onlooker</td>
		<td>@syedaraza</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Clean Table</td>
		<td>No PR?</td>
		<td></td>
		<td></td>
                <td></td>
                <td></td>
</tr>
<tr>
		<td>Set Table</td>
		<td>No PR?</td>
		<td></td>
		<td></td>
                <td></td>
                <td></td>
</tr>
<tr>
		<td>Find My Disk</td>
		<td>@kyordhel</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Restaurant</td>
		<td>@MatthijsBurgh</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Hand me That</td>
		<td>@justinhart</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Where is This?</td>
		<td>@johaq</td>
		<td>:x:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Stickler for the Rules</td>
		<td>@johaq</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:heavy_check_mark:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Bartender</td>
		<td>@justinhart</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Laundry Sort</td>
		<td>@justinhart</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
<tr>
		<td>Is Refrigerator Running</td>
		<td>@justinhart</td>
		<td>:heavy_check_mark:</td>
		<td>:x:</td>
                <td>:x:</td>
                <td>:x:</td>
</tr>
</table>
