### ISSUE TITLE
[Poster-Session] Give points to poster session

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#54]
Grant 50 points (same as RoboZoo) to the best poster session, scored by teams like the Open Challenge in 2014 and before

**Comment by LoyVanBeek** [comment]
You also want to score the posters in different aspects? Seems like a lot of trouble for 50 points...

**Comment by kyordhel** [comment]
I don't like scoring for poster session (this issue is here upon request). In theory we do science and we should be proud of our research. No points were given in German open and all teams presented a poster.

If your poster is crappy is because you are not taking seriously the competition, nor your research

**Comment by LoyVanBeek** [comment]
+1

**Comment by kyordhel** [comment]
No points will be given
