### ISSUE TITLE
Pepper v1.8 features stereo cameras and no RGB-D sensor

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#542]
Robots to be leased in Sydney 2019 are Pepper v1.8 (not 1.8A), which differs from your Pepper 1.6 in that it uses a stereo cameras instead of the ASUS xtion RGB-D sensor. Although we have been told that the changes to the NAOqi interface are minimal, you might need to consider them. For further technical information, please consider [this document](http://doc.aldebaran.com/2-8/family/pepper_technical/video_Stereo_pep.html?highlight=camera).

Both versions of Pepper (v1.6 and v1.8) will be allowed and treated equally in the competition. You may use the one of your preference.

# Update 2019-02-21
#### Are you providing v1.8 and not v1.8A, right?
We will provide robots according to what the teams already have (except 1.6) so we will finally rent both versions : 1.8a & 1.8
#### Is it possible to mount a V1.6 head on top of V1.8 body?
No, there are not compatible
#### Can a team bring their own head and mount it on a rented body?
Yes but only to use on their respective version. 1.8 & 1.8a have not compatible head.
#### Is there an option for RoboCup teams to upgrade current v1.6 Pepper to v1.8?
The upgrade is not possible but they should not have any problem this year as they will be able to rent a Pepper 1.8a

**Comment by ristofer** [comment]
Is there any team that has worked with a Pepper v1.8 with ROS?  I would be grateful if you could tell your experience.

**Comment by kyordhel** [comment]
All teams in the SSPL have a Pepper v1.6. To the extent of our knowledge, there are no ROS packages yet tuned for the Pepper v1.8.

**Comment by joseastorgat** [comment]
Which version of naoqiOS  will peppers have, 2.5.x or 2.7.x?

If it is 2.7, will it be possible to downgrade it to 2.5? Checking the compatibility chart, it seems possible (here: http://doc.aldebaran.com/2-8/news/2.7/whatsnew2.7.html#use-pepper-s-display-to-download-the-new-system). We would like to confirm it.
