### ISSUE TITLE
Simple Stage I Tests

### ISSUE THREAD

**Issue by balkce** [RoboCupAtHome/RuleBook#545]
We are at a week from the deadline for the first draft of the rule book. I want to remind the TC and rule book authors that the intent of Stage I is to have simple tests that require a small amount of setup.

If I remember correctly (I may be wrong, please correct me if so), we are aiming to have 2 scenarios with at least 4 tests each to provide teams that can do a LOT of tests more points that those that repeat tests. Each scenario will be carried out at least twice, with at least 3 repetitions each. Considering that past years we've had 12 teams per league, that means that we will be carrying out around 36 tests for each scenario slot.

**THE POINT:** We need to have Stage I tests that are easy to set up and straight to the point.

I've read through some of the tests, and I believe that there are several that require simplification. Some examples: #520 , #528 , #529 . This is not an exhaustive list by any means.

I would ask the rule book authors to have a look #526 as an example. It has a simple description, specific objectives, straight to the point and very easy to setup.

**Comment by kyordhel** [comment]
@balkce Can we consier this as complete? What do you think we have pending in out ToDo list?

**Comment by balkce** [comment]
This issue can be closed. I think most of the task are simple enough now. The ones that aren't are on their way there. Closing issue.
