### ISSUE TITLE
[RoboZoo] Allow teams to vote

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#55]
Maybe redefine scoring as

- Appearance 20 (tokens)
- Performance 20 (tokens)
- Best demo 10 (Average of scores given by Team Leaders)

**Comment by LoyVanBeek** [comment]
@kyordhel So the tokens are normalized to 20 points for each category?

**Comment by kyordhel** [comment]
Yup! They are, since we cannot penalty the teams if we get no audience and not all tokens are used. Plies, the audience may get confused and cross-vote or so.

I would like to rework also the test to avoid the Senior Dance league but I think this is addressed as another issue. But if we make RoboZoo awesome and challenging, we may grant more points. With significative values

**Comment by LoyVanBeek** [comment]
Making it more challenging is something for next year I suppose.

**Comment by LoyVanBeek** [comment]
OK, agreed in TC meeting: leave it as is: 2x25 points given by audience with tokens.
