### ISSUE TITLE
Focus of @home

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#550]
I'd like to open a more general discussion about something that came up here and there in other issues. I realize right now finishing the rule book is the number one priority nonetheless I think this is something to think about long term.
Right now when you want to design a test you need to think about:
- it has to fit into the housekeeper or partyhost scenario
- it has to roughly fit into 5 or 10 minutes
- it has to be focused enough so the goal can be explained in one sentence
- it has to be open enough to allow for extra bonus goals
- it has to enforce generalized approaches to be solved
- it has to be easily understandable by the audience
- it has to be easy to follow by the audience
- it has to incorporate current hot research topics
- it has to be easy enough so new teams can solve it
- it has to hard enough as to not be trivial for veteran teams
- it has to be solvable by two very different standard platforms
etc.

I am by no means saying that robocup@home should only be one thing. But right now, to me, it seems like it tries to do a lot of things but does none of them right. This is exemplified by no one really being happy. The robocup trustees and EC do not like the rule book, the teams do not like the rule book and audiences do not understand the rule book. All of these different groups complain about different things showing in my opinion that by trying to be for everyone you are appealing to no one.

As I said before I do not think nor do I want @home to only have one thing in mind. But in my opinion there needs to be a clear priority, something that everything builds around. One sentence to tell someone that asks: "What is robocup@home about?"

Otherwise I think we will continue to have constantly changing rules every year running in circles instead of getting somewhere.

**Comment by justinhart** [comment]
Well, this is kind of what was discussed in #536 and in the Roadmap topic.

There have been a few suggestions.

1) Identify the RoboCup@Home equivalent 2050 goal.
2) Build a roadmap for progress.
3) Fit all tasks onto that roadmap, which can mean eliminating some tasks and introducing some new ones.

#536 was reopenned today, and @swachsmu left a really thoughtful discussion of this material there. Whether it is in this thread or that thread, I think that what needs to happen is, rather than a general discussion, the development of a general strategy for how we will address this.

But if I were to suggest it, I would suggest what I said in the 3 enumerated points above.

**Comment by justinhart** [comment]
Shall we start discussion on what a 2050 goal for @Home would be, or perhaps get this onto an agenda for a TC meeting?

**Comment by kyordhel** [comment]
The 2050 goal is pretty clear:

*Bring to people's homes low-cost domestic service robots capable of assisting them in their daily tasks*

From a 2006 perspective it was feasible, but after 25% of the allotted time has elapsed, it seems quite a challenge:
- We have not powerful enough batteries
- We have not powerful enough computers
- We are not close to have real HRI with machines
- Most of our problems require A.I.-complete solutions
- We don't have small, strong, safe, precise-enough actuators

To achieve the goal, we need **ROADMAPS** with pretty well studied milestones, as well as the will to put them into practice.

The rest seems to me quite straightforward.
- Task-driven milestones will make audience and sponsors happy every time they are reached and solved
- Tests can be designed to meet a milestone with bonus objectives set for the next milestone.
- Achieving a milestone is scientifically relevant, hence publications can be produced. 

Sounds trivial, but that would require an extra mile only a few are willing to give: set robotics before the economic and trophy rewards, and some times even before the personal career.

**Comment by kyordhel** [comment]
@justinhart 

> Shall we start discussion on what a 2050 goal for @Home would be, or perhaps get this onto an agenda for a TC meeting?

What about scheduling it after **finishing the rulebook** draft.

**Comment by kyordhel** [comment]
Bump!

**Comment by johaq** [comment]
Some of these restrictions were lifted. In terms of finding a 2050 goal, I would put this on the agenda to be discussed in Bordeaux.
