### ISSUE TITLE
Q: What are the dimensions of the bag for carrying groceries

### ISSUE THREAD

**Issue by nohernan** [RoboCupAtHome/RuleBook#555]
Hello, 

regarding the bag used in the Help-me-carry task, I see its description in Section 3.3.5 and some examples in Figure 3.2a and Figure 5.1. From there I don't get a clear specification of the bag used in this task. Could you please provide us with the approximate dimensions of such a bag?

**Comment by kyordhel** [comment]
Unfortunately, we can't. We don't know. 

The TC will go shopping and find adequate paper bags (preferably) for the challenge. Something between 15cm and 60cm would be reasonable. Most likely its weight won't exceed 200gr.

**Comment by kyordhel** [comment]
@nohernan if your question has been solved, please close the issue.
