### ISSUE TITLE
Q: State of the current draft

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#563]
Hi,

Just wanted to have a general idea of how much we can rely on the current state of the RuleBook. Can tests still appear/disappear for example?

The most up-to-date version is the 2019/restructure branch right?

Thanks,

**Comment by kyordhel** [comment]
#### Can we rely on the current state of the rulebook?
**Yes**. We will add Restaurant and perhaps a couple of tasks more.

#### Can tasks disappear
**Nope**.

All current tasks will stay. We can balance them by adding/removing points here and there though. It depends on how it goes on German Open.

#### Can new tasks appear
**Yes**. Perhaps one or two.  If they do, most likely won't be used in German Open

#### Is 2019/restructure branch the most up-to-date version?
**Yes, but...** All changes should be merged already into master.

New tests will be added to 2019/restructure to keep master stable during German Open.

**Comment by RemiFabre** [comment]
Thank you for the fast answer
