### ISSUE TITLE
Q: how is coat color assignment communicated?

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#568]
In "Farewell" is the coat color assigned and communicated to teams prior to the test, or must the robot elicit their coat color through dialog?

Also, the coats are mentioned in the bonuses, not the main reward. Is handling of coats required to score the main goal?

**Comment by johaq** [comment]
Robot must ask the guest for the coat color. "All guests have a name and coat color assigned." means that the referees will tell the volunteer before the test starts but not the team. 
Handling of coats can be ignored for main task. Although I think it would be nice for the robot to at least remind the guest to take their coat and not forget them ;)

**Comment by kyordhel** [comment]
@benatuts if your question has been answered/solved, please close the issue.
