### ISSUE TITLE
Move furniture between challenges

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#57]
Move couch, tables etc about a meter to the map changes

**Comment by kyordhel** [comment]
Most robots will get lost when localization fails.

Perhaps for the navigation test and we command the robot to move to that furniture so the robot will need to look where the hell is the bloody bookcase now.

**Comment by LoyVanBeek** [comment]
Exactly. 
Deal with it. :sunglasses:

**Comment by LoyVanBeek** [comment]
What changes can be expected in in the rulebook, we just have to actually move stuff as TC.
