### ISSUE TITLE
Q: When does restaurant and/or finals happen?

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#574]
Section 3.6.2 outlines a four day schedule but no accommodation is made for Restaurant (which appears to be neither Housekeeper nor Party Host), nor for the finals. It seems that some things will need to be cut to fit everything into the 3.5 days of competition.
(edit: also robot inspection)

**Comment by moriarty** [comment]
It seems fine, and much easier to fit than previous years.

The schedule outlined a sample schedule, the official schedule will be decided on and posted by the TC/OC on site.

**Comment by kyordhel** [comment]
The rulebook can't establish a schedule based on the LOC agenda. We will sole those issues *in situ*.
- Inspection takes place during setup days (as usual)
- Finals take place during *Finals* day (as usual)

**Comment by benatuts** [comment]
The example schedule is 4 days but the competition has only 3 (non-finals) days of testing. My understanding was the new rulebook was supposed to be more relaxed about time so that teams had a chance to recover and revise their code.

So, a realistic schedule would need at least three blocks on each day. Does that mean something like 9:00-12:00, 14:00-17:00 and 19:00-21:00 could happen?
