### ISSUE TITLE
Q: can SSPL friendly objects be assumed in the SSPL arena?

### ISSUE THREAD

**Issue by benatuts** [RoboCupAtHome/RuleBook#575]
Pepper has limited grasping ability. It can only carry extremely light items, its joints have limited accuracy/precision, it has limited reach, limited dexterity and no gripper pressure sensing.

The feasibility of some tests for Pepper is very much dependent on the items used and their placement. Some challenges for pepper include:

- Carry My Luggage - height of the bag handle (e.g., on a stool for graspability?)
- Clean Up: weight of objects
- Farewell: weight of coats (e.g., lightweight disposable ponchos?)
- Serve the breakfast: size/shape of spoon, volume of cereal box, height of table (children's spoons?)
- Groceries: weight of objects, nothing on floor, height of bin-opening
- Take out garbage: weight of bag, height of bin-opening, size of bin-opening
- Clean the Table: I think it is impossible to accommodate Pepper for this challenge
- Find My Disk: height of the bookcase (to see spines clearly)
- Set the table: size of cutlery, weight of cutlery, force for opening drawer, height of drawer, height of table, free clearance around objects in drawer
- Smoothie Chef: I think it is impossible to accommodate Pepper for this challenge

Also, GPSR and EGPSR could, by inclusion, require tasks that Pepper is physically incapable of performing.

Finally, 3.3.2 states that doors may be closed -- and this would require handles that are large and extremely lightweight for Pepper. 

To what extent is it reasonable to assume that the tests conducted in the SSPL arena will be varied to accommodate the physical limitations of Pepper?

**Comment by moriarty** [comment]
No.

I’ve tried to respond politely... but your list is too long and unreasonable, so I deleted all the response and think it is easier to just say no, we will not simply the rules of challenge to accommodate a specific robot.

**Comment by benatuts** [comment]
Just to be clear, though... it isn't "just" a specific robot. It is the entire social standard platform league that faces these questions.

In Stage I, the following tests appear to be possible in SSPL:

- Receptionist [Party Host]
- Serving Drinks [Party Host]
- Find My Mates [Party Host]
- Carry My Luggage [Party Host] (mostly)

In Stage II / Restaurant:

- Find My Disk [Housekeeper]
- Hand Me That [Party Host] (assuming it doesn't actually involve "handing")
- Stickler for the Rules [Party Host]
- Where is this [Party Host]
- Restaurant

Note that there's very few Housekeeper tasks that the SSPL can do.

Consider that an SSPL team could work very hard on grasping, but if Pepper is expected to pick up the same objects as OPL, then that effort has no benefit.

I don't believe it needs extra rules -- just a general principle (e.g., in section 3.3) that will ensure that objects lighter than 50g will be used in SSPL tests, that all benches/tables in SSPL will be around 60-70cm from the ground, and that there are no closed doors in SSPL.

**Comment by johaq** [comment]
I agree with @moriarty. To repeat, I don't think there will be any special accommodations for either standard league. This might seem weird and even frustrating, I understand. I'll try to explain and give some reasons.

First of, the rulebook in its current form is not expected to be entirely solved by just one team. It is our intention that teams focus on tasks that they think best fits with the team's and their robot's abilities.
Furthermore, I believe robocup has a lot of benefits for the people participating but as a benchmarking competition we also provide a service to others. Lay people can look at the competition and should be able to tell: Oh this is the current status of service robotics. This is stuff that robots are good at, this is where they still struggle. Likewise researches should be able to tell: I require a plattform with these abilities for my research. Let's see which robot performed best on the things I'm looking for. If we make things easier/harder for certain leagues we loose this comparability. I think it is perfectly fine for someone to look at the robocup scores and conclude: Hey pepper is pretty good as a party host but struggles as a house keeper.
Lastly, there are a lot ex machina rules in place that imo still allow pepper to solve tasks you say pepper cannot do. The better you use the robot's strengths here the better you will still score. Will you get the maximum points in the task? Probably not, but if it is true what you say about pepper's abilities you will not loose anything against the other pepper teams, right?

**Comment by kyordhel** [comment]
# SSPL has *Deus ex Machina*, so no.

No special rules will be made to match robot specifications. There are plenty tasks to chose from.

**Comment by benatuts** [comment]
The way I see it, the big points are scored in achieving the main goals and bonuses. If Pepper physically can't complete any main goal for Stage I Housekeeper, then there are no big carrots to focus efforts and the optimal strategy may devolve into "point farming", by invoking all the Ex Machina rules across as many separate tests as possible. I don't want to see SSPL become a point-farming game for Housekeeper scenarios, where it constantly asks for help to do anything: it isn't attractive to the audience/public and it doesn't look good for sponsors.

**Comment by johaq** [comment]
As far as I can see pepper can score 
- 200 points (5x40) in Clean Up asking for assistance in manipulation. Obj Rec is doable on pepper
- GPSR is hard to tell exactly but we did score significantly in those tasks in Montreal with the pepper
- Storing Groceries is admittedly very difficult. But as I said one robot does not have to solve everything
- 200 points in Take out the Garbage by having the bags handed over

This is just of a quick glance. But imo pepper can potentially score very well in 3/4 housekeeper tasks in stage 1. Granted it is not easy by any means but doable.
