### ISSUE TITLE
Q: Find My Mates Bonus reward ?

### ISSUE THREAD

**Issue by cdussieux** [RoboCupAtHome/RuleBook#579]
Hi,

5.4  Find My Mates [Party Host]
_Bonus rewards1.  Reporting the location and description of a third guest (500pts)._

It may be a very naive question, but what is this bonus meant to encourage ?
Is the third person expected to be way more difficult to find/describe than the first two ?
In which way ? 

Thanks

**Comment by kyordhel** [comment]
# TL;DR: Speed.

## Explanation
Moving around the house to find a standing person and then provide an accurate description can, from our experience, take between 2~4 minutes to a robot. If the person is sitting, lying, or engaged in an activity (exercising, dancing, cooking, cleaning) that requires movement, it is more likely that the robot won't see that person. Hence, finding 3 people in 5 minutes is quite challenging.

Our goal is that robots become as smart and efficient as their human counterparts who can complete the task in a few seconds.

**Comment by cdussieux** [comment]
Thanks
