### ISSUE TITLE
Q: What are the settings for Storing groceries?

### ISSUE THREAD

**Issue by nohernan** [RoboCupAtHome/RuleBook#585]
Hello,
concerning the task 5.9 Storing Groceries I got two questions:

1. Can we know the distance between the shelf and the table?
2. At the beginning of the task, is the robot facing the shelf?

I noted that in rulebooks from previous years the answer of these two questions was stated but they're missing in this year's rulebook.

**Comment by johaq** [comment]
1. No. But it will be close to the shelf.
2. Since not stated otherwise in the task, start signal is door opening so the robot starts in front of a door. The shelf will be part of the normal arena setup.

**Comment by kyordhel** [comment]
@nohernan if your question has been solved, please close the issue.
