### ISSUE TITLE
Q: Command generator in GPSR

### ISSUE THREAD

**Issue by cdussieux** [RoboCupAtHome/RuleBook#586]
Hi,

Shall we expect any major change with generated question from GPSR Command Generator ?
Former predefined questions used in Speech and Person Recognition are no more supposed to be asked ?

Thanks
Clément

**Comment by kyordhel** [comment]
# TL;DR: GPSR no, EGPSR yes.
- The GPSR grammar is [almost] finished. I won't touch it for German Open anymore.
- The EGPSR grammar hasn't been crafted yet. You can base on EEGPSR from past year + GPSR from this.

Changes will be pushed as soon as they are done (hopefully this week).

**Comment by cdussieux** [comment]
Great, thanks !
