### ISSUE TITLE
Balance testing slots (fair competition)

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#587]
It seems the rulebook is not crystal clear in this aspect, so a clarification is needed.

In principle, all teams get the same number amount of testing slots, with a minimum of 2 per block. If a DSPL|OPL|SSPL block ends early and the referee has 30 minutes to spare, she can open an extra testing slot only if DSPL|OPL|SSPL has 6 teams or less. If DSPL|OPL|SSPL has 7+, open an extra slot is not possible because one team would be left out.

It is important to make a hard rule that all teams in a league receive the same number of testing slots per block. Yet is up to teams to use them or not (e.g. broken robot).

**Comment by balkce** [comment]
Agreed. This clarification could go in Section 3.6.2 "Schedule". PR?

**Comment by LoyVanBeek** [comment]
XPL? What's that? I assume x = {O, SS, DS}, right?

**Comment by balkce** [comment]
> XPL? What's that? I assume x = {O, SS, DS}, right?

Yes. @kyordhel has a weird sense of writing style.

But you get used to it =P

**Comment by kyordhel** [comment]
Sorry, I'm editing that to make it BNF compliant.
