### ISSUE TITLE
Points in 'Where-is-this'

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#588]
> Give accurate directions or guide at least 5 people.
> 
> **Reward:** 300pts (100pts per direction/guidance).

5 * 100 = 500 last time I checked. Did I misunderstand or should I make a PR to fix to 500 points? Or to 'at least 3 people'?

**Comment by kyordhel** [comment]
A robot can't score unless main goal is achieved. This means you need to provide directions to all of them, and five is way too much for 10 minutes.

Therefore, I reduced it to 3 + 2.
- Main goal is 3 people (there is an errata there)
- Bonus goals per extra person (max 2).

So yeah, scoring is the same, but only 3 are mandatory.
