### ISSUE TITLE
Q: Can the operator signal when the car's location is reached? - Carry my luggage

### ISSUE THREAD

**Issue by nohernan** [RoboCupAtHome/RuleBook#593]
Hello,

regarding the test 5.1 Carry my luggage, can the robot ask the operator for a voice command or gesture once her and the robot reach the car? Let's say that before starting to follow the operator, the robot instructs her on how to signal that they have reached the car. Does this indication by the human incurs in a score reduction?

**Comment by kyordhel** [comment]
The robot can do an say whatever it wants as long as the interaction is natural.

Normally, when I acoompany someone to her cab, or any vehicle I do not know, I ask *is this your car?*, and it's perfectly normal.

A score reduction may apply based on how unnatural the interaction is.

**Comment by nohernan** [comment]
Question is answered. Thanks a lot.
