### ISSUE TITLE
Q: cascade pod, number of objects and hading over an object? - Clean the table

### ISSUE THREAD

**Issue by nohernan** [RoboCupAtHome/RuleBook#594]
Hello,

I got some questions with respect to the task Procter & Gamble: Clean the Table.

Just to make sure, a cascade pod is a sort of capsule as shown here https://goo.gl/images/iXmkEF, right? Will the OC provide this cascade pod for training along with the cutlery and tableware?

It is mentioned in the setup section of the task that on the table there are 6 objects. So I think there is a typo in the score sheet for this task where it says 7x-50 for pointing at object and handover an object, I believe it should be 6x-50.

I read that a human might hand an object over to the robot with a reduction of 100pts. What is expected of this interaction? i) the human clearly offers the object expecting the robot to recognize it and take it or ii) the robot makes a grasp movement with its grip open expecting the human to place the object in its grip, so the robot can close its grip and take the object? What is the behavior most likely to happen i) or ii) or somethign else?

**Comment by kyordhel** [comment]
1. Yes, that's the Cascade Pod.
2. P&G should provide us with enough samples for test, train, and perhaps even do laundry. The generosity of our sponsors knows no limit.
3. That's correct. It should say 6x
4. Depends on what the robot asks. The human assistant will do as requested in a natural way. The idea is that the robot has some sort of awareness and react accordingly. Both i) and ii) seem OK to me, being i) much more natural than ii) but all depends on the interaction.

**Comment by kyordhel** [comment]
Fixed in #601
