### ISSUE TITLE
Q: 3.3.3  Furniture: Drawers specification

### ISSUE THREAD

**Issue by cdussieux** [RoboCupAtHome/RuleBook#595]
Hi,

Cupboard is supposed to have at least two drawers, but are these drawers expected to be one above the other or side by side ?

Thanks
Clément

**Comment by kyordhel** [comment]
Honestly, we had in mind drawers which are side-by-side, but that's entirely up to what we have available in the venue. I've never seen a kitchen cupboard with stacked drawers, but I'm confident I would adapt to it without a problem, so the same should be expected from robots.

So the TL;DR; is: we don't know until we get there.

**Comment by cdussieux** [comment]
Fine
Thanks for your answer
