### ISSUE TITLE
Q: What is the maximum reward in Where is This? test?

### ISSUE THREAD

**Issue by carlosquinterop** [RoboCupAtHome/RuleBook#600]
In 6.9 **Where is This?** the main goal is to "Give accurate directions or guide at least 5 people" at 100pts per direction/guidance with a maximum reward of 300pts. The expected number of assisted people is 3 or 5?

**Comment by maximest-pierre** [comment]
This was reported in issue #597 and a Pull Request was merge to address this #599. If you want to discuss this further please add a comment to #597.

**Comment by kyordhel** [comment]
# TL;DR; Max reward is 2100pts; Main goal reward 300pts for 3 people (compulsory)

You can score up to 2100pts. The first three people will award 100pts each and additional people (4th on) will grant 200pts each. Additional points are scored for providing audio transcripts and understanding untrained operators.
