### ISSUE TITLE
Q: maximum time for GPSR 

### ISSUE THREAD

**Issue by JulioCCruzE** [RoboCupAtHome/RuleBook#603]
I think 5 minutes is very little time to complete the 3 commands, even more when the categories have merged into one and difficult commands can appear. Could there be the possibility of leaving it in 10 minutes as in previous years?

**Comment by johaq** [comment]
No, not possible due to scheduling.

**Comment by kyordhel** [comment]
+1 to @johaq's answer. All testing slots in Stage I are 5 minutes long, so GPSR cannot be any different. We expect robots to solve 1~2 commands tops. The third command is there so you can give up one, or to give you an extra bonus if you have an insanely fast robot (all tests are 1000pts but GPSR which is 1500).

If this answers your question, please proceed to close the issue.

**Comment by JulioCCruzE** [comment]
Since the main goal of the GPSR is to execute 3 commands it seemed to me that 5 minutes was not enough but if the third command is designed for extra bonus it makes more sense for me the time assigned for this test, thanks Mauricio.

**Comment by kyordhel** [comment]
Actually you can solve only one task and skip two.
