### ISSUE TITLE
Q: GPSR command 'replace by'

### ISSUE THREAD

**Issue by cduss** [RoboCupAtHome/RuleBook#605]
Hi,

Some GPSR commands are like:

> Escort the apple to the living room.
>
>Note : 
>Replace apple by Francis

What is the referee behavior ?
Does he instruct the robot with 'Escort  the apple to the living room.' and wait for the robot to answer : 
"I am not supposed to escort a fruit, who would you like me to escort ?"

Or am i misunderstanding the expectations of this command ?

Thanks
Cduss

**Comment by kyordhel** [comment]
What you describe is correct, the robot should be able to realize that it can't guide a fruit.

But most likely the referee will skip that command and generate another. I think we don't have erroneous commands specified in the rulebook for this year.

**Comment by cduss** [comment]
@kyordhel you're absolutely right, this question was a remnant of an old training set of mine, before your last update.
Sorry.
Thanks for the answer
