### ISSUE TITLE
Q: How the predefined locations for objects are announced?

### ISSUE THREAD

**Issue by mfinean** [RoboCupAtHome/RuleBook#608]
Could you please clarify how the predefined locations for objects is communicated? Is this there a zone all objects need to be brought to or does each object have a specific location and this is communicated in the setup days etc.?  Many thanks

**Comment by MatthijsBurgh** [comment]
The following in based on what happened in the past.

During setup days, a map is provided of the arena. All significant items(dinner table, couch, etc.) in the arena are labeled. Also a set of objects(coke, banana, etc.) is provided with labels. A default location for each object is provided.

**Comment by LoyVanBeek** [comment]
Extending on that, please take a look at repositories like https://github.com/RoboCupAtHome/Montreal2018 and similar ones.

**Comment by johaq** [comment]
Yes, to clarifiy:
Each object is part of a category (i.e. an apple is a fruit, milk is a drink, ...) and each category belongs to a location in the arena (i.e. you can find fruits in the kitchen cupboard and drinks in the fridge).

See also 3.3.5 in the rulebook for the official description.

**Comment by kyordhel** [comment]
§3.3.5 states:

> Some tests in the RoboCup@Home league involve recognizing and manipulating objects (See Figure 3.1b). The TC will compile a list of at least 30 objects for this purpose, assigning them official names... Each object has assigned a category (e.g. an apple and a banana belong to the fruits category). Each
object category has assigned a predefined location (e.g. an fruits can be found in the kitchen
table). **Assignments are announced during setup days (See Section 4).**

Typically, all ground knowledge for the robot is announced during the [first] setup days. We provide lists and each team is responsible of instructing their robots on the whereabouts for there is no standard.

@mfinean, if your question has been answered, please close the issue.
