### ISSUE TITLE
Can we get bonus points without getting full score of main task?

### ISSUE THREAD

**Issue by hibikino-musashi-athome** [RoboCupAtHome/RuleBook#609]
I saw the description  that "To score in a test, a team must successfully accomplish the main objective of the task; bonuses are not considered otherwise." in Section3.6.3, but does it mean "we can't get bonus without full score of main task"?
Can we get bonus in these case?
・when we use Deus ex Machina
   (when the person assists robot in some way.)

**Comment by johaq** [comment]
No, generally I would consider the bonus points as soon as points are scored in the main task. 
If I feel like a team is only going for a bonus goal and really just skipping most things in the main task to score some points, I would probably not award bonus points. I think this ties in a little bit with rule 3.9.2.

**Comment by kyordhel** [comment]
The main idea behind DeM is allow teams to complete the main task so robot look useful from the outside (audience). For those robots that excel at solving the task and can do more there are the bonus objectives. Nonetheless it only make sense to give an extra reward to those who made an extraordinary effort. 

Hence, bypassing the main task with DeM and chasing *easy* bonus points is considered as point farming, aka cheating, aka not playing fair.
