### ISSUE TITLE
Information about bag --Carry My Luggage

### ISSUE THREAD

**Issue by hibikino-musashi-athome** [RoboCupAtHome/RuleBook#611]
We should carry the bag in "Carry my Luggage" task, but will the bag be disclosed before the competition? Or, is the bag showed at figure3.2(a)?

**Comment by MatthijsBurgh** [comment]
I am not sure, but officially it isn't disclosed.

But I have to say. From previous years, it had been pretty obvious what the bag would be during the setup days.

**Comment by kyordhel** [comment]
Indeed, teams do not know in advance which bag they will carry, but it is
chosen from the list of official objects.

This means the bag has been known to the robots since setup days.
