### ISSUE TITLE
Q: Whose description should robot know and tell to operator? --Find my mate

### ISSUE THREAD

**Issue by hibikino-musashi-athome** [RoboCupAtHome/RuleBook#612]
In "Find my mate" task, robot should search the person and tell their description, but is the person who should be reported his description instructed? Or, should robot tell the description of anyone be found by robot(e.g the first person robot found)? If the person is instructed, how operator command to the robot?(only the name of guest?) How should robot colligate person's name and their place?

**Comment by johaq** [comment]
I'm not sure I understand. There are four people in the test area and each of them has a name assigned. The people are instructed to tell the robot their name if asked. The robot collect information on multiple persons and then report to the operator or collect and report them one by one.

**Comment by kyordhel** [comment]
@hibikino-musashi-athome, if your question has been answered, please close the issue.
