### ISSUE TITLE
Carry My Luggage - Start signal

### ISSUE THREAD

**Issue by mfinean** [RoboCupAtHome/RuleBook#614]
What is the start signal for tasks such as this where the robot starts at a predefined location? Will it still be a door opening as specified in the rules for default starting signal? Many thanks

**Comment by johaq** [comment]
A referee will tell you to finish setting up the robot and to step away.
Your robot needs to be ready at any time then. I would recommend that the robot indicates it is ready (i.e. by saying "waiting for my operator").
Time will start when the operator engages the robot.

**Comment by kyordhel** [comment]
@mfinean, if your question has been answered, please close the issue.
