### ISSUE TITLE
Q: Is it possible to prefix commands issued to robots?

### ISSUE THREAD

**Issue by mfinean** [RoboCupAtHome/RuleBook#615]
In all tasks, is it possible/allowed for the operator to prefix commands with some form of addressing the robot e.g. if the command is "Bring me....", is it allowed for the operator to say "HSR, bring me...."? Many thanks

**Comment by johaq** [comment]
If the robot requests to use a prefix I will use it. If the team asks me to use it I won't.
Generally you cannot rely on volunteers and referees to use the prefix but we try to be nice to the robot if the robot is polite.

**Comment by kyordhel** [comment]
@mfinean, if your question has been answered, please close the issue.
