### ISSUE TITLE
Q: How does a robot knows when a guest arrives in Receptionist?

### ISSUE THREAD

**Issue by mfinean** [RoboCupAtHome/RuleBook#616]
In the receptionist task, how do you know when a guest arrives? i.e. how do you know to go and open the door for a new guest? Many thanks

**Comment by johaq** [comment]
My reading of the rules is that when the test starts the robot can either open the door or request the door to be opened. Guests will then be coming through the door.

**Comment by mfinean** [comment]
Agreed, but that's why I'm asking - what is the definitive mechanism for knowing they are there. Is it a door knock that we need to hear?

**Comment by johaq** [comment]
Unless Mauricio (@kyordhel) clarifies this, we have the German Open next week and I will report how we handled the task there and possibly update the rules.

**Comment by kyordhel** [comment]
With over six experts on robotics, I’m pretty sure the TC can find an intuitive solution. RoboCup@Home is a competition by peers to peers after all, so Mauricio shouldn’t have the last saying.

If you ask me, I think people arrive either alone or in couples (as usual) and knocks the door (as usual). I din’t expect any robot to hear the doorbell, so telling the robot to attend the door would be fine. It might be the case also that other guest opens the door (as usual) and the newcomers slip in with not much idea on what’s going on.
