### ISSUE TITLE
[Protocol] Team Leader Meeting German Open 01.05.

### ISSUE THREAD

**Issue by llach** [RoboCupAtHome/RuleBook#618]
# Poster Presentations

* poster spots: in bar, outside bedroom wall and one tile of the kitchen
* don't hang them where the shelves will be standing!
* put up until inspection starts
* gettogether afterwards (8 o'clock)

# Inspection

* drive to inspection point, wait for exit signal, then exit arena via exit door
* additional devices need to be present during inspection and shown to the referees
* teams state their start and stop signals during the test
* on E-Stop: teams push out their robot

# General Stuff

* missing objects and shelves will be present approx. at noon
* testing & mapping slots before inspection (look @ git for slots)
* officially, we need to leave at 10
* all external devices need to be in the external computing area
** only mice are allowed on laptops, no additional keyboard
* best in DSPL will receive certificate for best domestic platform but teams will compete in OPL
* doors may be modified but all teams have to agree on one solution
* 5-6 teams will make it to stage 2
* !!! locations were updated !!!

# Task specific things

* teams need to specify which task they want to present in the TL meeting before the task
* teams can tell the referees not to include heavy and/or tiny objects in the task for their run
* task / slot cancellation at least 1h before slot
* schedule will be printed and put on the arena wall (maybe also on TV?)
* VizBox would be nice
* data recordings handed in after each run

# Network

* if network issues -> ask Johannes
* from the second setup day on (02.05) only laptops and robots are allowed in WiFi
* for all devices connected: avoid huge amounts of data if possible

**Comment by johaq** [comment]
We are gonna post the meeting minutes for the team leader meetings of the German Open.
I think the discussions about the tasks will be especially useful.
