### ISSUE TITLE
Q: Whats the purpose of predefined names in Find my Mates?

### ISSUE THREAD

**Issue by JosjaG** [RoboCupAtHome/RuleBook#619]
The Rulebook implies that the names of the 'mates' should be used but it is not clearly specified how. As I currently understand, the goal is to describe the guests based on who the operates asks for. So at some point in the challenge (I assume the timing of this moment does not matter), the robot should ask the operator who to describe and then based on the name provide the location and unique description of the person with that name. 

If this is correct, I suggest updating the goal of the challenge from ```Report to the operator the description and location of at least two party guests.``` to ```Report to the operator the description and location of at least two party guests based the name provided by the operator.``` or something similar.

**Comment by johaq** [comment]
Yes you understand correctly, the operator will tell the robot something like: "Tell me about Mia." The robot needs to find out who Mia is.

You already proposed an improvement so you should open a pull request where we can discuss your proposed change. In general, the main goal description should be short and concise and I think this can be explained better in the task description.

**Comment by kyordhel** [comment]
@JosjaG if your question has been answered, please close the issue.
