### ISSUE TITLE
GPSR command generator

### ISSUE THREAD

**Issue by LarsJanssenTUe** [RoboCupAtHome/RuleBook#621]
The command generator can create such a command:

```
The kitchen

kitchen
	 Place 3 objects randomly, at least one on the floor.
Remarks
	 This command is for DSPL and OPL only
```

what to do with this command?

**Comment by moriarty** [comment]
Sounds like the “clean up” from house keeper. I would expect the robot to move the random objects to their known locations

**Comment by LarsJanssenTUe** [comment]
"Sounds like"?
If we are not even sure what it should do I am at a loss of how our robots should know....
I think this needs either clarification (f.e. by adding the term "clean up" to get to "clean up the kitchen") or should be removed entirely.

**Comment by johaq** [comment]
Please open an issue on the generator github page. 
Preferably you would already propose a fix via pull request.

**Comment by kyordhel** [comment]
We are aware that the command generator may have some bugs. If a command does not make sense, it won't be asked to robots.
