### ISSUE TITLE
Q: How to introduce guest in Receptionist?

### ISSUE THREAD

**Issue by syedaraza** [RoboCupAtHome/RuleBook#622]
For the second guest, is it ok to first introduce each sitting person to the guest and in the end introduce the guest to all?
For example, the robot goes to william and says 'This is William', then goes to John and says 'This is John', and then turns to Alex (the second guest) and says 'Attention everyone, this is Alex'.
OR should the robot introduce the guest to each sitting person separately?
For example, 'This is William and this is Alex' while pointing to both.

When we introduce someone to a group of people, we first introduce everyone in the group and then introduce the newcomer or vice versa. I think here we are introducing a guest to a group of people sitting in a room. Thanks.

**Comment by johaq** [comment]
The score sheet says: "Introduce the 2nd guest to John and 1st guest"

So your first proposal seems perfectly fine.

**Comment by kyordhel** [comment]
I'd say that the robot must act as any normal human being would do. I expect no less than a natural interaction.

@syedaraza if your question has been answered, please close the issue

**Comment by syedaraza** [comment]
Thanks.
