### ISSUE TITLE
Carry my luggage (party host)

### ISSUE THREAD

**Issue by HareshMiriyala** [RoboCupAtHome/RuleBook#624]
How many bags will be placed near the operator ? Will the bags be placed in the space directly between the operator and the robot ? Or will it be placed such that the bags are to the left and right of the operator and he/she is pointing at the bag to be carried ?

**Comment by HareshMiriyala** [comment]
Also, do we know which hand will be used to point at the luggage ?

**Comment by LoyVanBeek** [comment]
Not an official anymore, but I'm pretty sure that the hand used will not be specified beforehand.

**Comment by johaq** [comment]
We will not disclose where exactly the bags are. As the rulebook states: "nearby the operator".
At German Open we used two bags but more is possible. Note that only carrying one of the bags is sufficient to complete the main goal.
