### ISSUE TITLE
HSR Sound; low volume

### ISSUE THREAD

**Issue by MatthijsBurgh** [RoboCupAtHome/RuleBook#626]
On the German Open, we experienced problems with the low volume of the HSR. The operator had troubles understanding the robot.

It is possible to change some parameters in the launch in the `tmc_talk_hoya_py` package. This allows for an increased volume. But a negative side effect is, the sound gets cracky.

We as Tech United are still tuning the parameters to find the best solution. Though we are not sure if the best solution will be satisfying.

So the question is if we should allow external audio devices.

**Comment by maximest-pierre** [comment]
Didn't we have a wireless pack for the sound output in Montreal?

**Comment by MatthijsBurgh** [comment]
The HSR doesn't have any audio jack. So only usb(->bluetooth)/ethernet devices can be connected to the HSR.

**Comment by johaq** [comment]
Also connecting a robot to the sound setup often does not help because then the robot itself is completely quiet and you only hear the speakers which mostly face the audience. Makes it even harder for the operator.

**Comment by LoyVanBeek** [comment]
Yes, you miss the direction of the audio and that makes for a weird interaction somehow. It does help a lot though. 
A [USB-to-audio-jack](https://www.amazon.com/TROND-External-Adapter-Integrated-Microphone/dp/B07L56C28R/ref=sr_1_6?keywords=usb+headphone+jack&qid=1557343277&s=electronics&sr=1-6) could help to plug into the arena audio if need be. 

Something like https://www.amazon.com/HONKYOB-Speaker-Computer-Multimedia-Notebook/dp/B075M7FHM1/ref=sr_1_4?keywords=usb+speaker&qid=1557343397&s=gateway&sr=8-4 can even fit on HSR's head in front of the screen so it can travel up with the head too.

**Comment by balkce** [comment]
What about having one of the speakers (or an additional one) pointing into the arena and using an external audio plug (as proposed by @LoyVanBeek )? The LOC could provide some insight if having one speaker pointing into the arena is possible.

**Comment by MatthijsBurgh** [comment]
So you agree with having an external audio device? The question remains what type, on the robot/arena speakers/etc. correct?
If this is correct, we can start looking into getting a usb-to-jack adapter working.

**Comment by johaq** [comment]
Thoughts by other DSPL teams?
As a referee I definitely think we need a solution for this cause it is just too hard to understand.

**Comment by kyordhel** [comment]
IDC, and considering the amazing teamwork display shown by DSPL while selecting an standard laptop, i’d say: **go**

Use onboard laptop speakers or an external usb audio device. If the robot fails or I can’t hear you, you get 0 points.

**Comment by LarsJanssenTUe** [comment]
Thanks for your comments. We would still like to hear from other DSPL teams, however if we do not hear anything else we will go with what @kyordhel told:

> IDC, and considering the amazing teamwork display shown by DSPL while selecting an standard laptop, i’d say: **go**
> 
> Use onboard laptop speakers or an external usb audio device. 

We will try and keep you informed of what we are doing, but currently the plan is to plug a USB-to-audio-jack into the arena in order to get a loud sound that both the judges and the audience can hear (as proposed by @LoyVanBeek). From this thread and specifically from the comment by @kyordhel we assume that this will be allowed. 

Please correct me if I interpreted comments wrong or came to a wrong conclusion!

**Comment by johaq** [comment]
I would feel better about it if it was part of the rule book. Can you make a pull request allowing solutions mentioned here, yours included?

**Comment by johaq** [comment]
Thank you for the PR! All help is appreciated.

**Comment by HareshMiriyala** [comment]
Has someone tested the backpack's audio output? Is it louder than what the HSR could produce ? :)

**Comment by MatthijsBurgh** [comment]
@HareshMiriyala How do you mean?

I think many teams have different laptops. So using the the laptop's speakers is different for each one. Also using the laptop's speakers, while the laptop is closed will really change the sound/volume.

Using the laptop to generate the sound and play it on external speakers, would require a lot of coding. So I would advise to connect external speakers directly to the robot.

**Comment by kyordhel** [comment]
@MatthijsBurgh do you think this issue is solved?

**Comment by MatthijsBurgh** [comment]
I think the RuleBook has created enough space for teams to come up with a solution. So solved IMO.
