### ISSUE TITLE
Handover in natural interaction

### ISSUE THREAD

**Issue by hibikino-musashi-athome** [RoboCupAtHome/RuleBook#627]
I saw "The human assistant will do as requested in a natural way." on issue #594.
But, isn't it penalty to hand over to robot by operator in natural interaction? (Ex; In Set the table task, if robot said "Please take that knife where the third from the right in cupboard drawer", does operator take the knife and handover to hand-grip of robot without point reduction?)

**Comment by johaq** [comment]
Yes, a handover means reduction in points.
Rulebook says in Set a Table:
"Handover: Handing over an object causes a score reduction of 100pts."

**Comment by hibikino-musashi-athome** [comment]
If so, why isn't handover regarded as point reduction behavior(on issue #594)?
I thought issue #594 says handover in natural reduction isn't regarded as point reduction behavior.

**Comment by johaq** [comment]
I believe you misunderstand what @kyordhel meant.
A referee is just more likely to interact with your robot if the interaction is natural and the robot explains it well. But you still get penalties for the handover. Simply put, if your planned interaction is really unnatural the referee might not even be able to do the handover.

**Comment by hibikino-musashi-athome** [comment]
Sorry, I understand. 

I'll write my misunderstand.
"The idea is that the robot has some sort of awareness and react accordingly. Both i) and ii) seem OK to me" This part. 
I thought "i) the human clearly offers the object expecting the robot to recognize it and take it" is OK(no point reduction).

**Comment by johaq** [comment]
No problem, that's what the issues are for.
Yes, that is meant as in "ok as a handover interaction" but point reductions are still applied.
