### ISSUE TITLE
Sydney Rulebook deadline

### ISSUE THREAD

**Issue by MatthijsBurgh** [RoboCupAtHome/RuleBook#628]
I think it is good to set a deadline for the Sydney RuleBook.

I suggest to set the deadline to end of May.

Do you agree?

**Comment by LarsJanssenTUe** [comment]
Ping @justinhart @moriarty @justinhart @johaq @awesomebytes

**Comment by johaq** [comment]
I think that's very reasonable.

**Comment by kyordhel** [comment]
Agreed. However, it requires commitment of several TC members.

@MatthijsBurgh, thanks for volunteering yourself to encourage people to meet this deadline.

**Comment by RemiFabre** [comment]
Can we consider the RuleBook frozen? If not, do we have an idea of what could change? 
Is master the correct branch for Sydney?

Thanks,

**Comment by kyordhel** [comment]
1. I'd say *stalled* more than *frozen*.

2. When will it change? Can't say. The TC promised to release it on June 1st, so anytime soon.

3. Yes, master is the right branch
