### ISSUE TITLE
TC Members attending Sydney

### ISSUE THREAD

**Issue by balkce** [RoboCupAtHome/RuleBook#630]
It'd be good to have a census of the available judges/referees that we'll know for sure will attend Sydney to either schedule around or ask teams to volunteer.

**Comment by justinhart** [comment]
I'll be there.

>

**Comment by awesomebytes** [comment]
I'll be there. I'll schedule teammates to help.

**Comment by moriarty** [comment]
:( I won’t be there

**Comment by johaq** [comment]
I also won't be attending :(

**Comment by maximest-pierre** [comment]
Not TC but me and Nathalie are going to be there

**Comment by YutaroISHIDA** [comment]
I'll be there.

**Comment by balkce** [comment]
As of now, I'm counting 5, with me, 6. @kyordhel you coming right?

**Comment by fabricejumel** [comment]
Hi everybody,
I finally had to cancel my travel and would not be able to be there.

**Comment by kyordhel** [comment]
Sorry for late answer. Got visa approved yesterday and booked flight. Can’t confirm 100% but is almost sure.

**Comment by balkce** [comment]
6 it is then.

We will definitely need volunteers. Can anybody assign to this issue somebody from the LOC to see how many we will have at hand?

**Comment by annkym** [comment]
Sorry I won't be there, good luck!

**Comment by moriarty** [comment]
Change of plans. I'll be there. Booked flights and AirBnB yesterday afternoon!

**Comment by moriarty** [comment]
I think we should volunteer @dirkholz :wink:

**Comment by kyordhel** [comment]
I think @dirkholz is too busy getting the 2018 proceedings ready to attend.
