### ISSUE TITLE
Q: Are there categories in GPSR and EGPSR?

### ISSUE THREAD

**Issue by kinmaru** [RoboCupAtHome/RuleBook#631]
In past competition, there were categories of commands like CategoryⅠ-10pts, CategoryⅡ-20pts, CategoryⅢ-30pts.
I read Rulebook and couldn't find the description about command categories.
Are there categories of commands as last year?
If so, are there point and difficulty level differences due to category?

**Comment by kyordhel** [comment]
No, this year there will be no categories. Robot should have become more general and be able to deal with any kind of command. Also, it is very likely at least one command will contain incomplete information.

Remember that now robots can rely on the *Deus ex Machina* to solve any command.

**Comment by kinmaru** [comment]
Okay, I understood.

Thanks.
