### ISSUE TITLE
Q: How the trash container lid looks like in Take Out the Garbage?

### ISSUE THREAD

**Issue by HareshMiriyala** [RoboCupAtHome/RuleBook#632]
Hi all, 

In the take out the garbage task, can we know what the lid looks like? Is it going to be something like this : 

![image](https://user-images.githubusercontent.com/5285984/57808053-34381a80-7728-11e9-8f4b-cafc194fb5b8.png)

or like this : 
![image](https://user-images.githubusercontent.com/5285984/57808076-40bc7300-7728-11e9-9991-22dc69b91d19.png)

or :

![image](https://user-images.githubusercontent.com/5285984/57808099-4914ae00-7728-11e9-9201-d79652129af2.png)

**Comment by kyordhel** [comment]
We won’t know until the setup days. Objects and furniture are based on what is locally available, LOC setup, and OC budget.

**Comment by kyordhel** [comment]
@HareshMiriyala if the question has been answered, please close the issue
