### ISSUE TITLE
Q: Where should the robot bring the objects in Clean Up?

### ISSUE THREAD

**Issue by kinmaru** [RoboCupAtHome/RuleBook#642]
In clean up task, the robot has to bring objects to their predefined locations, but do predefined locations differ depending on respective objects(or its categories)? Or, should the robot has to bring all objects to the same 1 location?
Thank you.

**Comment by kyordhel** [comment]
3.3.8 Predefined rooms and locations
Some tests in the RoboCup@Home league involve predefined locations where people or objects
can be found. The TC will compile a list of predefined locations that may include furniture (e.g.
bookshelf), decorations (e.g. plant, mirror), and doors. Each predefined location has assigned a
location class (e.g. an coach and a arm chair belong to the seat class). Room names, predefined
locations, and location classes are announced during setup days (See Section 4).

**Comment by kyordhel** [comment]
Let's check §3.3.8:

> ### 3.3.8 Predefined rooms and locations
> Some tests in the RoboCup@Home league involve predefined locations where people or objects can be found. The TC will compile a list of predefined locations that may include furniture (e.g. bookshelf), decorations (e.g. plant, mirror), and doors. Each predefined location has assigned a location class (e.g. an coach and a arm chair belong to the seat class). Room names, predefined locations, and location classes are announced during setup days (See Section 4).

We can have a distribution such as the following:

| Object Class   | Predefined Location |
|----------------|---------------------|
| Cleaning stuff | Bathroom shelf      |
| Drinks         | Bar                 |
| Food           | Fridge              |
| Fruits         | Kitchen Table       |
| Snacks         | Dining room table   |

If the robot finds an apple, it must be taken to the bar, the same as an onion should be put in the fridge. Unknown objects are considered garbage and must be thrown into the bin.

**Comment by kinmaru** [comment]
Thank you for rapid answer.
So, the robot has to bring objects to other rooms depending on the objects, right?

**Comment by kyordhel** [comment]
Pretty much yes. Not other rooms, but at the specific location. For example, if cutlery goes on the left drawer of the kitchen's cupboard, it won't count as a mark if a fork is left on the kitchen's table or on the cupboard (outside the drawer). The robot can, of course, request assistance to open doors and drawers as required.

**Comment by kinmaru** [comment]
Got it. Thank you.

**Comment by kinmaru** [comment]
For example, when the robot attempt to put drinks on Bar is it possible to be Cleaning stuff(or other category's objects) on Bar? We want to search the wrong placed objects before putting it.

**Comment by kyordhel** [comment]
It is. After a party it is not uncommon to find objects in the wrong place. For instance, I can find some drinks on the table next to the snacks and the fruit. Fruit should be in the kitchen and drinks in the bar, but snacks should be there. We expect robots to be context-aware.

In the end, the test is about cleaning a flat and leave it neat and comfy

**Comment by kinmaru** [comment]
I understood. Thanks.
