### ISSUE TITLE
Q:  Is the door of the drawer closed in stage1's "Serve the breakfast"?

### ISSUE THREAD

**Issue by KIM-MINJI96** [RoboCupAtHome/RuleBook#653]
In stage1's  "Serve the breakfast", does the robot need to open the door of the drawer containing spoons, milk and cereal? I wonder if the door of the drawer is closed.

**Comment by kyordhel** [comment]
## TL;DR Yes, will be closed

As in any home, cutlery and tableware will be stored inside drawers or behind the cupboard door. Te robot can request human assistance to open the drawers and doors if required.

**Comment by Ryangupta8** [comment]
Will teams lose points if the robot asks for assistance opening the door/drawer? Alternatively will the robot gain points for opening the door/drawer? This is not enumerated in the reductions/bonuses inside the task description for serve breakfast.

**Comment by kyordhel** [comment]
I don't think the robots would receive a penalty, but perhaps a bonus if can open both
