### ISSUE TITLE
Q: Day 3 - Is this meant to be Restaurant or Party Host?

### ISSUE THREAD

**Issue by mfinean** [RoboCupAtHome/RuleBook#656]
On page 30, the schedule says restaurant in the morning - does this mean teams must try this task or is this a type and meant to say party host?

**Comment by kyordhel** [comment]
Teams can skip Restaurant if they want. However, since we are testing robots in a real restaurant, referees won't be available for any other test. In addition, that schedule is explanatory and not binding, so we can move restaurant to the afternoon if convenient.

**Comment by mfinean** [comment]
Okay, cool - thanks.
