### ISSUE TITLE
Request: Mint DOIs for finalized rulebooks

### ISSUE THREAD

**Issue by nickswalker** [RoboCupAtHome/RuleBook#659]
I would like to reference the rulebook in a way that is both very easy for readers to follow while still durable (i.e. citation with a link that's guaranteed to not break). One way to do this would be to mint DOIs for finalized, official PDFs of the rulebook using something like [Zenodo](http://zenodo.org). There may be alternative archival repositories to consider as well, I am just familiar with Zenodo.

To check:
1. Are there DOIs that someone had issued set up already that just aren't visible? If so, I can put in a PR to list them in the readme
2. If not, would there be support for the idea of archiving rulebooks in this fashion? At the least, it provides a convenience. At best, it could make it easier to track back references to the rules.

**Comment by balkce** [comment]
Just playing devil's advocate for a moment: If you're going for something that is "easy for readers to follow", I'm not sure a DOI link is the best to go: the provided index are bunch of numbers that require either some HTML (for a simple click) or to copy/paste. If you're looking for "a link that's guaranteed to not break", I'm not sure doi.org can guarantee that, or any of us for that matter (anybody remember the hi5 social network? or altavista?).

[taking off the devil's advocate hat] Ok. Seriously, though: would the official archive http://www.robocupathome.org/rules be close enough to what you're looking for? Or are you looking for a link for each one of the rule books?

At one point, I remember somebody made a link to one of the rule books via purl.org. Arxiv.org could be another possibility. Or you can go ultra-jank and use bitly or tiny.cc.

In any case, I agree that we should add a link to the past rule books to the Readme file of this GitHub, regardless of what linking method is used.

**Comment by nickswalker** [comment]
I think the desirable properties for reference links are

* Will continue to work indefinitely
* Attached specifically to a single document
* The single document cannot be changed, or changes are officially noted

I think the league website works well for most purposes, but isn't appropriate for references. Because the actual rulebooks are hosted on Google Drive, there's no way to deep link directly to the official copy (URL is too long and gross), it's possible for them to be removed by error or intentionally, and it's possible for them to be changed in the future.

Also, since I first posted, I see that this note has appeared:
> Notice:
>The official RoboCup@Home website has been moved to http://athome.robocup.org.
> robocupathome.org is no longer maintained.

Agreed, DOIs are not very readable and are harder to remember or to copy off a printed page. Their primary benefit is durability (most DOI issuers serve as archives; promising to keep the material as long as they can, guaranteeing that they'll pass the materials to another archive if they fail, and enforcing that the referenced materials cannot be changed once submitted). 

arXiv would be an ideal location (well trafficked, so some visibility for the rulebook) but the rulebook falls outside their [guidelines](https://arxiv.org/help/moderation):

> arXiv only accepts submissions in the form of an article that would be refereeable by a conventional publication venue

**Comment by kyordhel** [comment]
> Also, since I first posted, I see that this note has appeared:

Yup. It was me. I don't have time to keep both websites updated and we got orders from above, so https://athome.robocup.org is the official website now. All rulebooks are there, in the old website, and in the wiki.

Now, as of DOIs, I think is more of the same bread with different jam. I'm old enough to remember those websites whose URL would never perish and today they are nowhere to be found. I'm not sure if DOI urls will work in 15 years, so using a direct link to the file, an URI shortener, or whatever is pretty much irrelevant. If @Home survives, there will be a search engine that will redirect you to the website with the rulebook archive, so anyone interested in reading 30 year-old rules will be able to find them somehow.

**Comment by moriarty** [comment]
DOIs seem reasonable and standard practice, just an extra step in a process which someone needs to do.

**Comment by kyordhel** [comment]
Shall we request the OC to do it?

**Comment by nickswalker** [comment]
I volunteer to archive finalized new and historical rulebooks. I will look around to see which provider we should use then comment here.

**Comment by nickswalker** [comment]
Looking around at the options in [Nature's general repository recommendations](https://www.nature.com/sdata/policies/repositories#general), the only suitable repositories are Zenodo and FigShare. Both are [comparable](http://stephane-mottin.blogspot.com/2017/05/comparison-figshare-versus-zenodo.html), but after trying them both, Zenodo's platform is easier to use and more polished.

Sometime next week I'll archive the official PDFs posted to the league website. This is straightforward and mostly entails seeking out ORCID ID's for contributors and discussing a license to apply to past rulebooks.

**Comment by johaq** [comment]
Can this be closed @nickswalker?

**Comment by nickswalker** [comment]
Had forgotten about this as we got licensing sorted. Now that that's done archiving is straightforward. I'll put a table of DOIs in the wiki when I'm done (maybe someone can copy it to the website eventually).
