### ISSUE TITLE
[Person Recognition] Minor corrections

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#66]
- [x] "Wait for start command" should allow a single key press since no audio is being tested.
- [x] The test may give a name to the operator
- [x] Remove or reduce the 1 minute setup waiting time.
- [x] When pointing at the operator, the robot should be at close distance (state that if pointing is ambiguous, no points are scored)
- [x] State that the operator is randomly chosen from the crowd on each run

**Comment by LoyVanBeek** [comment]
The setup waiting time is addressed already for the whole stage 1 in general. 
It states "as fast as possible, preferable with 1 minute" or something similar.

**Comment by LoyVanBeek** [comment]
@kyordhel what do you mean with the second point ( The test may give a name to the operator) ?
