### ISSUE TITLE
Q: External microphone use for DSPL?

### ISSUE THREAD

**Issue by joannetruong** [RoboCupAtHome/RuleBook#660]
Will an external microphone be provided for our use for DSPL, or will we have to depend on the microphone built into the OSL/HSR? Some tasks such as receptionist require volunteers to speak to the robot, and the arena might be too noisy for the built in microphones to adequately hear them.

**Comment by moriarty** [comment]
You’ll need to depend on the microphone(s) built into the HSR.

I just reread section 3.5 and it does appear that we forgot to remove a remark from a previous version of the RuleBook from the initial section, but in 3.5.4 it’s made more clear that we only allow enhancement of the audio out signal, not microphone enhancements.

The reason for this- is we do not want to have a competition we’re buying the best directional, noise cancelling microphone allows you an advantage over other teams in a Standard Platform League. All teams will be at the same disadvantage. But there are at least two microphones in the HSR and I have seen it perform very well in the past two RoboCups despite a lot of background noise.
