### ISSUE TITLE
Where should the robot place fruits? -- Smoothie Chef

### ISSUE THREAD

**Issue by kinmaru** [RoboCupAtHome/RuleBook#661]
According to the rulebook, in Smoothie Chef task, the robot should bring fruits in the right order.
Where should the robot place these fruits?
I thought the mixer is on the kitchen table, so the robot should bring fruits to the kitchen table from the kitchen counter, but is it correct?

Thank you.

**Comment by kyordhel** [comment]
## We don't know (yet)

We don't know the arena so we can't tell as of now. All locations will be published during setup days. Specific locations for each task are typically announced 2 hours before the test (e.g instruction position).
