### ISSUE TITLE
EEGPSR Attending when called

### ISSUE THREAD

**Issue by JulioCCruzE** [RoboCupAtHome/RuleBook#662]
I have some questions, At the beginning of the test, and every time a command is requested, an operator will call the robot, if after a certain time or attempts the robot is unable to find it. Is it permissible for the robot to ask the operator to come and say the command?

Also when the robot hears that the operator asks for help, can he automatically start looking for the operator, or should he wait for a referee's confirmation to start the search?

**Comment by johaq** [comment]
Yes, since finding the operator is a bonus reward the robot can skip it.

To your second question: I think that is entirely up to you. Whatever interaction works best for your robot. I would only advice for the robot to announce what it is doing, i.e. "I will look for my operator now."

**Comment by JulioCCruzE** [comment]
Thanks for response my questions.

I have another one question, my team have to announce to the technical committee, previous the start of the test, if our robot will try to search the operator?

**Comment by johaq** [comment]
No. Again, it is always best to have the robot guide the interaction. The robot can say "I will attempt to look for you." or sth similar.
