### ISSUE TITLE
[Speech Recognition & Audio Detection Test]

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#67]
- [x] State: if the answer is not understood by the operator, is considered as incorrect
- [x] Questions should not be asked more than once
- [x] Increase the number of questions to 50
- [x] robot must shown it has understood the question, for instance, if the robot is asked for the acronym of European Union, it should answer "The European Union's acronym is E.U." instead of just answering "E.U."
- [x] On the ssecond phase, questions are repeated only if the robot asks for it

**Comment by balkce** [comment]
Fixed these issues with the last commit, except for the number of questions. 50 seems to be too high.
