### ISSUE TITLE
Side quest proposal: some points for a nice video

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#674]
When we first got interested in the league, we found it hard to find quality footage of what the competition looks like and what the robots can actually do.

Filming the robot decently, adding subtitles to explain what is going on, speeding up boring sequences, uploading and sharing the video is definitely time consuming. But enciting teams to create quality videos and promote them would be good for the league in my opinion (debate is welcome). Also, it would capture those famous highlights that do happen.

My proposal is to add the following side quest:
Before the end of the stage 1 tests, each team can send a YouTube link to the OC that checks that:
- The video was uploaded during the competition
- The video showcasts a test performed by the team (to avoid viral videos of a robot cracking a joke, which is fun and all but doesn't promote the scientific competition)

A fixed amount of points (500 per league?) is shared between teams that uploaded valid videos. A team's share of points would be proportional to the number of views gathered.

**Comment by maximest-pierre** [comment]
The OC has already too much work to do during the competition and some venue in the past would block youtube or other video sharing site. I am not against the idea of having better video from the teams. We can look at adding that to the qualification process as community points.

**Comment by kyordhel** [comment]
@RemiFabre I would like to invite you to join the Organizing Committee of RoboCup@Home and handle the *PR & Media* for the event in France 2020, so you would be in charge of implementing this idea. Let's see how it runs before adding a juicy reward in points. So far, teams are encouraged to record their tests in case a referee misses a score, so I think there will be sufficient material available.

As you already know, @Home is build and sustained by the community. More often than not, teams are too busy coding and the OC barely has any time to handle external logistics such as uploading the scores to the official website. This, however, can be changed by a volunteer with the time, expertise, and energy to do the job, so we are counting on you.

**Comment by johaq** [comment]
I definitely agree that it would be nice to have great video material of the entire competition. Big props to Hibikino Musashi, they upload a lot to their channel: https://www.youtube.com/channel/UCJEeZZiDXijz6PidLiOtvwQ/videos

I think it would be optimal if there are cameras and operators provided by the organizers as it was the case in Japan where it was also projected on a big screen for the audience. However, I asked for that video material and that unfortunately never got anywhere.

**Comment by RemiFabre** [comment]
@kyordhel thanks for the invitation. As you know, I'm avoiding organizational tasks for this year. I hope that my contributions and ideas to the RuleBook are still welcome. However, the LOC OPL for the 2020 RoboCup is a member of CATIE Robotics and I'm pretty sure he'd like to make something happen along the lines of what was available in Japan, I've pinged him so he can participate in the discussion.

Editing and publishing the video seems like a good job for that team member that couldn't come this time but is willing to help from home. As for the point reward, it shouldn't be too impactful, merely inciting and if you don't do it it's no big deal. Maybe a formula like "0.1 point per view, capped at 100 points per team" would be better?

@maximest-pierre if YouTube is blocked in the specific RoboCup location, then the side quest would be off for that RoboCup, similar to what happened during GermanOpen for the bonus points for recording data (GDPR). I understand however that the implementation of this idea should not consume OC's time during the competition. Maybe this could be solved by local volunteers for 2020, to be discussed.

@johaq I didn't know, this is good content!


==> If at the end of this discussion a RuleBook modification is needed, I volunteer to PR it.

**Comment by johaq** [comment]
I don't think we will add this to the rules. New and small teams just might not have the ressources for this. We also have the wiki now where media can be collected.
