### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by justinhart** [RoboCupAtHome/RuleBook#675]
One current goal for the league is to establish a roadmap that can be used for guidance on the development of tasks. Tasks should fit into a roadmap of capabilities and research objectives, which will hopefully improve collaboration within the league, make the tasks more exciting to watch, and on a whole get us closer to a goal of domestic service robots.

We should also have a 2050 goal, similar to that of the soccer leagues.

I'm opening this issue, and closing related issues, so we can frame this conversation in terms of what should be on this roadmap.

The brief version of how this roadmap should come together, is that we should identify a core set of tasks that we believe a domestic service robot should be capable of performing. Tasks in the competition should exist on a roadmap to these capabilities.

For example:

High-level goal: A domestic service robot should be able to tidy the home.
Competition tasks related to this: Put away groceries. Move untidy objects to where they belong. Make a bed.

The competition tasks reflect the high-level goal. We then scale the competition tasks to be appropriately difficult such that the league has interesting research goals while not making the actual competition tasks unrealistically difficult. There should be "something to reach for" in any year's competition, but it shouldn't be so ridiculously hard that teams lean on deus ex machina to get through the task. If we scale the tasks like this and re-balance the rules annually, we can assure an exciting to watch competition and concrete progress towards these long-term goals, and make the tasks progressively more real-world.

**Comment by kyordhel** [comment]
Agreed, roadmaps are a must. Just a few remarks.

- The @Home goal has already been addressed in specialized literature on the competition.
- In addition to a general roadmap, we require several per-function roadmaps, including
    - ASR and NLP [Proposed]
    - Gesture, pose, and activity recognition
    - Navigation
    - Manipulation
    - Object detection, recognition, and tracking
    - Person detection, recognition, and tracking
    - Robot audition [Proposed]

I think we should work on each roadmap first, setting milestones as we foresee advances in the state of the art, and then merge conquered goals into more complex tasks. For instance, making a bed would require first that robots can recognize furniture and clothes, as well of handling the latter. Likewise, taking public transport makes mandatory an almost flawless HRI and outdoors navigation. Easier tashs such as frying sausages, cleaning toilers, uncapping beer bottles, and watering plants are within our grasp and have been already demonstrated, but most robots lack the skills, so we need to push in that direction.

**Comment by johaq** [comment]
You can contribute your roadmap ideas here: https://docs.google.com/document/d/1-QNMROnmVhEll8ZL-iTbqeeAhRjrcUbbdLcupx_hC2U/edit?usp=sharing
