### ISSUE TITLE
Robocup @home Network

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#677]
Pretty much every year there are some problems with the network because the needs and specs of the league are fairly unique and not easy to communicate to the local organizers.
During this years robocup I was asked by @LoyVanBeek about the network setup we run at the German Open which we used in the past two years and if we maybe could build from that so we organize the network ourselves as a league (do some of the other leagues do this?).
Because I personally was not attending in Sydney, can some maybe give their impressions of the network setup this year?
@warp1337 will post the hardware we use at GO as a basis to see what would be required.

**Comment by kyordhel** [comment]
I though this would be addressed within the Evergreen topic #363.

In Sydney the network setup worked pretty fine, although I've not the technical specs. I think this could be reviewed to make it more accessible to the teams, future LOC, and as cheap as possible.

The outcome must be some sort of technical manual we can handle to the local organizers so any technician can setup our network with standard commercial devices (e.g. CISCO compatible). This includes, but is not limited to:
- Bandwidth
- Number of SSIDs
- Wireless Channels
- Number of vLans
- Routing and tunneling
- Access controls
- Required devices
- Technical specifications of the required devices

**Comment by LoyVanBeek** [comment]
As for SSIDs: I had a brief chat with Timothy Wiley of the Soccer SPL LOC and he said the number of SSIDs we want (1 per team, for 25+ team) in one area would leave no bandwidth besides the SSID overhead. So that needs to change.

**Comment by warp1337** [comment]
I'd vote for continuing this discussion in #363 since all the history there

**Comment by johaq** [comment]
Yeah, continuing there is fine by me
