### ISSUE TITLE
TC Meeting Minutes 29.07.19

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#684]
Below a summary of the TC Meeting:
(Thanks to @nickswalker for taking notes)

    Introductions
    What went well
        Variety of tasks was nice for teams
        Open demos (teleop)
    Pain points
        Difference between what was written and how competition and task are carried out
            Ex: starting outside the arenas
        Tasks underspecified
        Breadth of tasks made refereeing, organizing hard
        GitHub issues for clarification didn’t reach everyone
        Lots of time spent training object recognition on site
        Dataset standardization
    Comments on pain points
        Underspecification
            Explicit aim of this year’s rulebook
            Was a drastic change
        Dataset standardization
            Will be addressed on the website in the future (@Alex)
        Research topics in tasks
            Stage 1: not meant to have research value, focused on integration of solved problems
            Stage 2: meant to be past current methods
            Ties in with better understanding purpose of the league
    Purpose of @Home
        A draft statement from early on (by league founder circa 2006): Salable domestic service robot by 2050
            Aim of roadmap effort is to determine an official goal
        Hard to come up with tasks when the balancing of objectives is not clear
            Objectives: Research value, value to audience, doable by all robots, easy to officiate…
            Having clear objective would clarify balance of concerns
        Roadmap will come later next year
            Should be interesting to watch, should help a PhD student graduate, should advance domestic service robotics
            Resolved: TC will send in area roadmaps
    Focus of efforts this year
        Make successful tasks (high participation, success rate) harder 
        Shorten rulebook
            Decided: Break out some part of the document, will figure out what parts can be separated
            @Home in a nutshell, LOC procedures, Rules, Networking
        Determining how to cut tasks
            Should low participation tasks be cut?
            EC: 4 tasks for stage 1 + GPSR, 2 tasks for stage 2 + EEGPSR & Restaurant
            Mandatory GPSR, EEGPSR, Restaurant
        Should we use standard objects?
            Some objects should be standardized
                Reduces on site time
                Potentially enables more advanced manipulation
        Networking handbook
            The moment you arrive to venue, should know what to do to connect to network
    Streamlining decision processes
        Proposed: TC votes on GitHub issues
            EC not enthusiastic about idea, but will let TC sort out
    Introducing Docker
        Strong suggestion for 2020
            Could appear on a guidelines document
        Make clear that robot interchangeability is a goal
            In the future, may only have one or two robots on site, all teams upload code
    VizBox 2020
        Works as both visualization and teleop interface
            Allows uniform judging of teleoperation intervention
            Fleet robotics work in industry is going this direction as well
            Robots are expensive (HSR cost 130K, Tiago 50K euro)
            Will come with point penalty
    Pepper problems
        Flakey communication with SoftBank
        Android-only support seems to be the future of the platform (NaoQi 2.9)
            No hardware level access, no ROS
            TC is encouraged to research alternatives to present to trustees if there is interest
        Hard to design tasks that work across the leagues
        EC is okay with tasks being different across leagues (change in opinion from last year)
    RCF League development funding
        Should be issued in August
        Possibility of funding for travel to a league workshop

**Comment by semaph0r** [comment]
Thanks @nickswalker !
Shall we do the notes in markdown to further improve readability and put them in to the wiki?
Or are there any confidential information? These might be omitted from the wiki.

In this way, we collect all information in one place and do not spread them over a bunch of services.
This might explain desicions to other which are not directly involved in the TC.
Just my two cents.
