### ISSUE TITLE
Reduce Number of Tasks

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#685]
Based on the competition in Sydney we want to reduce the number of tasks to:
2 tasks in Housekeeper and Party Host for Stage 1 (GPSR is mandatory)
1 task in Housekeeper and Party Host for Stage 2 (EEGPSR and Restaurant are mandatory)

Please write down which tasks you think should be kept. 

We will collect proposals until 05.08. Everyone is encouraged to participate, TC members are expected to. After that we will vote on the most popular choices.

**Comment by johaq** [comment]
- Stage 1
   - Housekeeper
       - Take out the Garbage: high participation numbers this year and easy to understand
       - Storing Groceries: Imo the most useful task of the remaining ones and I think we really need manipulation tasks in this scenario
   - Party Host
       - Carry my Luggage: Person tracking and following are imo very important skills
       - Receptionist: Useful and high participation numbers this year

- Stage 2
   - Housekeeper
       - Set the Table: useful and easy to understand, good participation this year
   - Party Host
       - New: I am not really happy with any of the Stage 2 Party Host tasks and would prefer a new one.

**Comment by semaph0r** [comment]
I agree on what @johaq have choosen for stage 1 and 2. 

AFAIK person tracking and following is not as stable as it should be, so emphasizing these may push teams in the right direction.

Regarding Stage 2 Party Host: What I would like to see is some sort of situation aware navigation in a highly dynamic environment, which party scenarios are. For example, find your way through a dynamic crowd and choose a strategy ad-hoc to decide whether to ask people to move or to find an alternative solution. For sure, a robot shall be as less interrupting as possible, but sometimes he needs to behave like a human waiter and say: Sorry, I have delicious food, may I pass by, please? Sure this may be hard to grade, but dealing with close proximities with robots is a thing.

Also dealing with good contact/forbiden contact during manipulation and the whole scenario might be an option.
Of course regarding this, safety has to be our top priority. But allowing the robot some sort of proximity and "contact interaction" with the environment (not people, this might be too dangerous as of now) would be a more natural apporach.

**Comment by moriarty** [comment]
August 5th 2019 is the deadline. Tomorrow.

Which timezone?

**Comment by peterpena** [comment]
- Stage 1

    - Housekeeper
        - Storing Groceries: It is a hard manipulation problem and has the potential for 
           human-robot interaction. The current 'Storing Groceries' needs to be expanded to contain 
           more areas where items can be stored and potential communication with a person that is 
           commanding the robot to store items in other places other than a pantry. Manipulation can 
           also be made harder by putting items in grocery bags or other containers where the robot 
           first has to unload items. This is why I did not choose 'Take Out Garbage' since the 
           technical challenge can expanded in 'Storing Groceries' 
        - Clean Up: Also a hard manipulation problem with soft materials and complex-shape items 
           that needs to be picked up in areas that are difficult to pick from such as the bed, floor, or 
           other surfaces. It can also be a very difficult navigation problem if it has to deal with items 
           that are blocking its path where it has to create a path by picking up items that are in its  
           way. It also has the potential for human-robot interaction where it has to ask for where 
           certain items belong or even dealing with someone who is in the environment making the 
           area "unclean", e.g., hand-over tasks if someone wants to throw something away.
    - Party Host
        - Carry My Luggage: I think this task should be named something like "Carry My Stuff" so that we have the possibility of expanding the scope such as carrying books, water, or other items that are not necessarily luggage.
        - Receptionist: I also agree that this is a great task because it has the potential for mediation of group conversations which is not available in other tasks and is an important feature to have for domestic robots.

- Stage 2

    - Housekeeper
        - Clean The Table: A cluttered table that needs to be cleaned is a good manipulation problem.
    - Party Host
        - Hand Me That: Having a task that deals with interpretation of human nonverbals for domestic robots is essential.

Another possibility is to use the same tasks of Stage 1 for Stage 2 but add extra components that make the problem harder. For instance, the technical challenges of 'Clean The Table' can be included in 'Clean Up' and 'Hand Me That ' can be included in 'Storing Groceries'. As an example for Stage 2 Storing Groceries, if a person wants tomatoes from the grocery bag to go in the refrigerator, the person can signal the refrigerator while he/she is doing something else.

**Comment by johaq** [comment]
@moriarty 
GMT-5 is our "latest" timezone. So using that makes most sense to me.

**Comment by PatrickNa** [comment]
Hi, 

we have been following the discussions about the rulebook a little bit, and while we understand that the new rulebook proved much harder to organize than previous years, we wanted to say that in German Open we found it great to have options to choose from. It allowed us to include research results in comparison to previous years when the options were very limited. We see that the rulebook is going back in that direction. In the end, we know that the way the tasks end 
up being written and the implementation details can make a huge difference, but we just wanted to highlight that making the rulebook modular so that teams with different research interests could show their work was one of the best things of this rulebook. 

From the proposed tasks, we were focusing on the following so far.

- Stage 1
  - Housekeeper
    - Take out the garbage.
    - Storing groceries.
  - Part host
    - Find my mates.
    - Where is this. 
- Stage 2
  - Housekeeper
    - Set the table or clean the table.

We share the view of @johaq about stage 2 party host tasks and would be in favor of a new task in this area. We also like the idea of @peterpena very much of increasing the complexity of stage 1 tasks for stage 2 tasks. Eventually this could be considered for stage 2 party host.

**Comment by YuqianJiang** [comment]
My selections are

* Stage 1
   * Housekeeper
      * Storing Groceries: It's a realistic domestic task with a set of nice manipulation challenges. I think more navigation can be required if we want to make this task more difficult.
      * Take Out the Garbage: I agree with @johaq that we should keep this task because it's straightforward and popular this year. However, I think the current scoring is too easy. The robot can bypass all manipulation and still score points by basically navigating to pre-defined locations. I think it would be nice to include putting trash into the trash can in this task (so it will be some combination with Clean Up).
   * Part Host
      * Carry My Luggage: Person following is an important service robot skill. The current rules about obstacles make this task difficult and interesting enough.
      * Serving Drinks: It's a realistic task for home robots and matches the theme Party Host. It tests a nice set of skills from person recognition to manipulation.
* Stage 2
   * Housekeeper
      * Clean the Table: It's a useful task and an appropriately difficult manipulation problem. Robot putting dishes in a dishwasher seems to draw excitement from participants and audience.
   * Party Host
      *  Hand Me That: I think this task will contrast with Restaurant nicely. It requires a different type of interaction and new perception and reasoning skills.

**Comment by nickswalker** [comment]
* Stage 1
  * Housekeeper
    * Clean Up
    * Storing Groceries
  * Party host
    * Carry my luggage
    * Find my mates
* Stage 2
  * Housekeeper: Clean the table
  * Party host: Hand me that

My picks have a lot of overlap with @peterpena's. 

Additional motivation for keeping Clean up: there is already an understanding that picking things up off the ground is an important assistive robotics task [0]. This is probably part of why Toyota runs a similar task in their HSR Household Chores Challenge [1].

Similar motivations for Hand me that: there are any number of research efforts in interpreting pointing gestures.

[0] [Dusty: an assistive mobile manipulator that retrieves dropped objects for people with motor impairments](https://www.tandfonline.com/doi/pdf/10.3109/17483107.2011.615374)
[1] [HHCC Tidy task](https://storage.googleapis.com/hhcc-movies/intro/hhcc_tidy.mp4)

**Comment by moriarty** [comment]
- House Keeper
    1. stage 1
        - Clean Up - General Purpose Tidying Robot. Define 3 different cleaning scenarios, Living Room, Kitchen, Bedroom. Team starts, open door, roll dice to pick room to tidy. For SSPL, have the robot instruct a child/naive operator to tidy the room.
        - Storing Groceries- cupboard doors are not optional.
    2. stage 2
        - Clean the table (actually clean the surface not simply pick objects)
- Party Host
    1. stage 1
        - serve drinks
        - hand me that (currently stage 2)
    2. stage 2
        - play chess ( OPL / DSPL ) something else for SSPL? to replace "smoothie chef" which had a lot of manipulation and was suppose to have a perception aspect.

**Comment by justinhart** [comment]
* Stage 1
    * House Keeper
        * Storing Groceries (make it harder)
        * Take out the Garbage (and make it harder)
    * Party Host
        * Carry my Luggage
        * Serve Drinks
* Stage 2
    * House Keeper
        * Clean the table
    * Party Host
        * Hand me that

**Comment by benatuts** [comment]
I like the suggestion of @peterpena of making Stage II more challenging versions of Stage I. One way to do this would be to have exactly the same tests, but to interpret tests during Stage I in a "friendly" way, while using Stage II to interpret the tests more aggressively.

e.g., Stage I rules are interpreted in the robot's favour (as typically happens at RoboCup): things are in their correct locations, objects are on tables at "eye-level", few obstacles, standardized objects, fully obedient people. In Stage II, the rules are interpreted from a more hostile perspective: non-standard objects, difficult obstacles, obstacles that need to be moved out of the way, things in the wrong place, furniture moved between tests, objects in clutter, delicate objects, (slightly) disobedient people acting more naturally, people going the wrong way, people taking off their glasses or removing their jacket, people getting in the way.

This would increase the ability for teams to improve and react over the competition. Also, referees will also benefit from the experience - in Stage II, they'll already be familiar with the basic flow of the test and can focus their attention to the fine-tuning the details of Stage II.

If clean the table and hand me that are popular Stage II tests, they could be reinterpreted in a more "friendly" way for Stage I versions (e.g., reduced types of objects with points-per-object; people pointing with more precise gestures from precise locations).

**Comment by johaq** [comment]
Ok so we have:
- Stage 1
   - Housekeeper
       - Storing Groceries: I think everyone chose this so probably a lock
       - Clean Up vs Take out the Garbage: Pretty split we'll discuss and vote in next TC Meeting
   - Party Host
       - Carry my Luggage: Most votes so probably a lock
       - Receptionist vs Serving Drinks vs Find my Mates vs Hand me That (shift from Stage 2) vs Where is This (shift from Stage 2): Discuss and vote in next TC Meeting

- Stage 2
   - Housekeeper
       - Clean the Table: Again chosen by everyone so probably locked in
   - Party Host
       - New vs Hand me That: We'll discuss and vote. Note that if you want a new task here you have to have a proposal ready in the meeting

**Comment by moriarty** [comment]
From the list @johaq just posted- to be removed are:

- Server Breakfast
- Farewell
- FindMyDisk
- SetTable
- SticklerForRules

**Comment by johaq** [comment]
Sorry for the late reply. I agree that the limited manipulation capabilities of the pepper make some tasks really hard. Personally, I am hesitant to just remove certain challenges for SSPL because from working with the robot I know that a lot of things people say are impossible are achievable, they just require lots of work. I know that when we started people said navigating in free spaces is pretty much impossible on pepper, which some teams made work. Similarly, I see potential in bi-manual manipulation on pepper and would love to see teams putting a lot of effort into it. Regarding your concrete proposals:
Storing Groceries: With this change, all the robot would be doing is standing in place and telling someone where to store on object. This would be an incredibly boring task. 
Carry my Luggage: Asking for assistance is already in the rules.
Clean the Table: I like this in principle, but is picking a cloth and wiping a dirty surface really easier? And if the robot is just handed the cloth and told where to clean, so the robot just "stupidly" wipes the table without recognizing where there is dirt, then I do not think this is Stage 2 worthy.

Regarding point 3. We are in principle open to alternative tasks for the SSPL. A way to get the ball rolling is to make an issue with task ideas. The best way is to create a PR with a concrete idea.

**Comment by johaq** [comment]
Number of tasks reduced for 2020.
