### ISSUE TITLE
Build rulebook and deploy to website

### ISSUE THREAD

**Issue by semaph0r** [RoboCupAtHome/RuleBook#693]
Sometimes latexonline.cc seems to fail. Occured several times for me over the last months. Reliability should be improved here.

```
pdflatex -interaction nonstopmode -recorder -output-directory latex.out /tmp/downloads/tmp_154/Rulebook.tex
/usr/share/texlive/texmf-dist/tex/latex/siunitx/siunitx.sty: warning: extra `}' in log; file names may be wrong
/usr/share/texlive/texmf-dist/tex/latex/siunitx/siunitx.sty: warning: extra `}' in log; file names may be wrong
/usr/share/texlive/texmf-dist/tex/latex/siunitx/siunitx.sty: warning: extra `}' in log; file names may be wrong
setup/packages.tex:19: warning: [scrbook] Usage of package `fancyhdr' together with a KOMA-Script class is not recommended. I'd suggest to use package `scrpage2' or `scrlayer-scrpage'. Nevertheless, using requested package `fancyhdr'
setup/packages.tex:69: error: File `doclicense.sty' not found
      at <read *>
    from ^^M
setup/packages.tex: Fatal error (no output file produced)
There were errors; /tmp/storage/compilation_13/output.pdf not updated
```
Also linking to this repository for viewing the rulebook is only suitable for a technical audience.

As @moriarty provides a docker container for building the rulebook, we can use it to be triggered by a release commit to a protected branch, where only a small group of responsibles is able to approve new commits and release new versions of the rulebook.

Second: After a successful build, the pdf version of the rulebook should be deployed to the website, too. This will increase visibility and accessibility.

Furthermore: If we opt-in for the solution to write a small leaflet for public audience, we are able to reuse such a build pipeline.

I will evaluate [Github Actions](https://github.com/features/actions) for this purpose and how it can be integrated into this workflow.

**Comment by nickswalker** [comment]
Has an owner already put the org onto the GitHub Actions Beta waitlist? @kyordhel

**Comment by nickswalker** [comment]
Another benefit of this; using GitHub actions or similar for CI would help us catch minor issues in PRs like in #689

**Comment by moriarty** [comment]
Actually I was working on a setting up Travis-Ci last night

**Comment by semaph0r** [comment]
I smelled this 😄

**Comment by kyordhel** [comment]
> Has an owner already put the org onto the GitHub Actions Beta waitlist?
No, but it can be done if required to update docker. We're hesitant about beta opt-ins.

The rulebook will not be deployed automatically to the website. Drafts are compiled on the fly (that's why master is protected), while the Final is carefully checked by the execs, submitted to teams, and uploaded manually to the website (I doubt website supports automation).

**Comment by semaph0r** [comment]
> No, but it can be done if required to update docker. We're hesitant about beta opt-ins.
Actually I do not have obligations about this. 2000min/month build time seems to be fair and I doubt that this might be exceeded by this repo.

I understand that there will not be a automatic deployment to the website regarding to the current policy. Nonetheless, it could be automated.

Beside this, we can use Github Releases for deploying drafts and maybe final releases too. Then we have two opportunities: Linking the website to a final release (also uploading the final to the RC Wordpress can be done too, if this is a policy thing) and give a changelog what was altered. Therefore, Teams do not need to look at diffs and pick commit messages rather than scrolling through the releases page and have an overview what's going on.

Some might say "Robot people are smart people, they don't need to be pampered".

Yes, but we should make it as easy as possible to aquire all relevant information regarding the rule book. Also to attract newcomers.

**Comment by nickswalker** [comment]
I think an owner should go ahead and request access to the GitHub Actions beta for the organization, if not to automate deployment, but at least to replace latex-online. It does't look like it's actively maintained anymore (https://github.com/aslushnikov/latex-online/issues/58) and a good way for people to view compiled output of a branch is important.

**Comment by semaph0r** [comment]
This might be considered done as there will be no automatic updates of the rulebook on the website.

IMHO all changes from @nickswalker address CD for the rulebook
