### ISSUE TITLE
Slim down the RuleBook

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#702]
## The RuleBook is TL;DR

We've cut some test, but there still needs to be some changes to the RuleBook to further reduce the size. I believe we can get the Table of Contents to fit on one page.

**Comment by nickswalker** [comment]
Building the rulebook just now, it's at 70 pages:
* 7 pages of title page, front matter, ToC, 
* 10 pages of intro and background
* 33 pages of general rules
* 30 pages of task rules and scoresheets

What do we think is a reasonable target?

**Comment by moriarty** [comment]
I think the 17 pages at the front should be possible to cut down by half.

It’d be great to get each of the task rules and scoresheets be 2 pages per task. One page of rules, one page for scoring.

General rules shouldn’t grow.

**Comment by johaq** [comment]
I absolutely agree. I think this belongs on the agenda for upcoming changes. Personally, I would like to resolve adding Standard Objects and updating all tasks first.

**Comment by MatthijsBurgh** [comment]
I think slimming down the Rulebook for the purpose of slimming down is incorrect. It is good read to all the general rules and check if it still should be in there. But we shouldn’t waste our time to rewriting 20/30 pages to contain the same information on less pages.

Also I prefer a long but complete Rulebook, which prevents discussions and trouble, over a short rulebook, which allows discussions and trouble.

**Comment by johaq** [comment]
Addressed in #722
