### ISSUE TITLE
Rulebook Update - Part II

### ISSUE THREAD

**Issue by ARTenshi** [RoboCupAtHome/RuleBook#713]
Carry My Luggage. The rulebook established a list of obstacles "The robot will face 4 obstacles along its way in any order", but they are in the "Bonus rewards" if avoided. It is not clear if the objects will be there by default or under the team's request for the bonus points (this year no obstacle was placed although some teams were able to avoid them (they hadn't the chance to show that skill)).

Receptionist. The rulebook established that "Every time a new guest arrives, people in the living room change places." but this year they didn't change places. 

[More on] HRI. Like any other device, we should predefine some input commands that are not affected by cultural differences (would be helpful for future commercial proposes), for example, "Robot yes" and "Robot no" for confirmation. Teams can work considering that minimum input while developing more complex systems for extra HRI.

Time limit. Very time-consuming tasks rely heavily on HRI for most of the task in order to be able to complete the task. More accurate timing per task will allow having robots performing most of the steps to solve a given task.

**Comment by semaph0r** [comment]
# Receptionist

It's more or less part of the TC briefing on-site. If the above mentioned is already in place no rule change needs to be done. For sure, we should focus on consistent behaviour of people acting as operators.

# HRI

I don't see any actions taken here. If someone want's to commercialize a system, it's up to them to define a neutral vocabulary based on their target markets. If you want to emphasize that there are some difficulties regarding the operation of the robot during competition, regardless of restaurant, please give an example.

# Time limit

I think you have the refBox in mind, which can be used to standardize the timekeeping? This may be an option but it needs to be tightly coupled with the "Open Door"-Command as it is the defacto standard for most of the tasks. Additionally, we need to examine the current state of the refBox and how to support that use case. I'll raise a separate issue on that

**Comment by ARTenshi** [comment]
HRI

I was thinking about standard confirmation commands or calling the attention of the robot. For example, some robots have their mic opened until they hear their name or a keyword. I saw a couple of teams struggling with this as they required to hear the word "Robot" and then they processed the rest of the sentence as addressed to them. For confirmation, they needed a "Robot yes" but the referee was giving a "Yes Robot" and therefore the robot opened the mic after the confirmation command was given. The robot asked "Please, say 'Robot yes' or 'Robot no'", but it received "Yes robot".

Maybe. after that experience, I might consider some standard inputs as in any electronic device.

**Comment by johaq** [comment]
1. Receptionist: This is already proposed in #705 and needs review.
2. I will not tell volunteers to use a specific hot-word. If the robots tells me clearly how to address it I will try to comply. But you cannot ever rely on everyone being 100% correct when addressing the robot. The same goes for giving a signal to start speaking. We cannot guarantee every volunteer will do exactly as told. The robot needs to make sure the interaction was successful. Honestly, relying on a specific word to activate speech recognition is probably just the wrong approach for @home.

**Comment by ARTenshi** [comment]
1. Thank you.

2. I don't have a problem with these, but some members that acted as referees complained about having to learn at the moment several interaction methods in each of the consecutive trials for all the slots for all robots. They suggested that maybe a minimum standard would be helpful for them in such situations.

**Comment by johaq** [comment]
If a team's method or description of how to address their robot is too complicated or too narrow, they'll have to live with tired and uncooperative referees

**Comment by kyordhel** [comment]
Guys, please, as I said in #711: Please open an issue per test.

The time limit constrain is being discussed on both issues. If you really want to address this, add an issue on the topic (schedule)

**Comment by ARTenshi** [comment]
I am fine with this outcome unless anyone wants to extend any of the topics.

**Comment by moriarty** [comment]
> [More on] HRI. Like any other device, we should predefine some input commands that are not affected by cultural differences (would be helpful for future commercial proposes), for example, "Robot yes" and "Robot no" for confirmation. 

No “Robot yes” or “Robot no” - starting with the keyword Robot or some other keyword like a name of the robot makes the task too easy.

**Comment by justinhart** [comment]
I don't like the idea of standardizing the commands. Giving the robots
standard commands to respond to would hinder actual HRI research. If the
team has a great interface, then the ref won't have a hard time interacting
with it.

**Comment by ARTenshi** [comment]
Ok, it was some referees suggestion based on their experience about consecutively addressing many robots in many ways. I will refer them to this issue.

**Comment by RemiFabre** [comment]
**HRI**
If even roboticians complain about the HRI, then it's probably bad HRI. 
In its current form, the rulebook rewards HRIs that are intuitive and reliable because of the tight timings of the tests. Teams doing the HRI effort are making real progress towards the final goal in my opinion. Creating an issue to discuss adding more naive operators into @Home.

**Comment by johaq** [comment]
@ARTenshi are your concerns still there with changes in #722? Can this be closed?

**Comment by ARTenshi** [comment]
Yes, thank you.
