### ISSUE TITLE
More naive operators

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#717]
Naive operators are messy, high variance and probably a nightmare to organize for the referees. Yet they are great:
1) The test becomes even more meaningful when lay persons are involved
2) This would increase the reward for teams that made the effort to create an efficient HRI (I think this is good, opinions?)
3) The public gets involved and everyone has fun
4) RoboCup2020 is in France and this would be a perfect match for "Hand me that"-> We are great at speaking English "but with only a limited vocabulary"

**Current state**
Naive operators were available in the following tests:
- GPSR
- EGPSR
- Where is this? (test deleted for 2020)

**Proposal**
Add the possibility to use naive operators in all of the Party Hosts tests a la "Where is this?" (i.e. bonus points when using naive operators). Teams must announce that they will use naive operators 2 hours in advance (and teams requesting naive operators owe referees one :)). If no naive operators are found, the test is performed as usual.

**Comment by johaq** [comment]
Well, basically all tests can feature naive operators if not stated otherwise. This is mostly dependant on if the referees can organize volunteers. For example, I see no problem to feature naive operators in the Receptionist and Carry my Luggage task. The rules do not state that volunteers/operator need to not be naive users.

**Comment by RemiFabre** [comment]
Okay but using naive operator should come with a reward in points for it to be worth it for the teams during the competition.

**Comment by johaq** [comment]
Dealing with naive operators is expected. If we have some for a task then every team encounters them.

**Comment by RemiFabre** [comment]
Sorry Johannes, I'm not sure I understand your point. Are you saying that naive operators can happen for any test already?
"If we have some for a task then every team encounters them." -> This was not the case last year, did it change? In "Where is This?" each team could chose whether or not to use naive operators. That choice did not impact other teams. This choice is a sort of difficulty setting that is rewarded by extra points.

My point is that this feature is great and should be expanded to other tests if it's feasible.

**Comment by johaq** [comment]
In where is this was, that was a special challenge due to the nature of the task (mainly focused on hri). This is not the case for any of the tasks as currently described in the rulebook. 
Yes, naive operators can happen in any task if not stated otherwise, see the Operators  bullet point in GPSR under Setup.

**Comment by RemiFabre** [comment]
OK so, **current situation:**
Only GPSR and EGPSR give extra points when the team choses to use naive operators. The referees could decide to use naive operators for other tests as well with no extra points, provided that the treatment is the same for all the teams participating in the same test.

**Proposal:**
Add the naive operators rules that are applied to GPSR to other tests. These rules would be roughly:
- The team can chose naive operators if they want
- Extra points if they succeed the task with naive operators
- Extra points if they provide a recording with naive operators

I would add this to the following tests:
- Carry my luggage
- Hand me that
- Receptionist

At first sight, naive operators don't seem very interesting for the Receptionist test. But we could add a twist: just before the end of the test the referee asks the naive operators to introduce John and the other guest along with their favorite drink. The "introduce guest to" points are only awarded if the answers were correct (name + drink).
(please say no to this idea, I will probably be hated for it if we do it)


Thoughts? I will write a pull request if we agree on the general principles of the change.

**Comment by johaq** [comment]
In principal, I like this, but from experience this is just very difficult to do organization wise. As stated before, it is usually pretty difficult to get volunteers that are not team members. To get multiple for several tasks that are only there in case a team might choose naive operators seems impossible to me.

**Comment by RemiFabre** [comment]
We could add some principles to alleviate the organisational burden : 
- The teams must announce naive operators ON/OFF on advance (2h? 1day?)
- Teams can't change their minds

Also this could be implemented in less than the 3 proposed tests for this year.

Or, if the experience shows that naive operators are too much to handle we could get rid of them all together (of course not my preference but I would understand).

Your call TC. I volunteer to PR the result of this discussion or close the issue if the answer is no.

**Comment by johaq** [comment]
So, I am open to the idea. I would like to hear from other TC members on this. 
Also, does the local OC for Bordeaux know how realistic it is to get volunteers for some tests?

**Comment by semaph0r** [comment]
I definetly say yes to naive operators as it strengthens the ability to "make a robot work" with literally anyone. In my opinion it is like generalizing an object dataset with prior unknown objects. Based on this, I'd like to see this in the competition.

**Comment by nickswalker** [comment]
This seems like the correct direction to move in, so adding it as bonus points makes sense. Even if it is not practically possible on-site, as long as we make that determination and announce as much with enough lead time, I don't see a downside.

**Comment by ARTenshi** [comment]
The drawback is that sometimes the robot doesn't move and the volunteers might feel that they are wasting their time and lose interest by just sitting there while the robot is stuck in the front entrance. Somewhere should be added that the use of naive operators expects a minimal execution of the task.
