### ISSUE TITLE
Gather data from teams

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#72]
Teams should upload their data like 
- map
- recorded audio
- object recognition training and testing images
- grammar files
- object models
- etc
to a central server or computer.
We will make this data public for all teams to use and for benchmarking the corresponding software.

We may need to give out some points for this as an incentive.

**Comment by kyordhel** [comment]
We may also score points for providing specific data ON SUCCESSFUL TASK COMPLETITION or FULL TEST DATA

For instance, if they provide a
- PNG picture (grayscale + RGB) the kineck depth/RGB sensor of the bookcase where the objects are if the robot was able to recognize them all or all the objects are visible.
- grayscale video file gathered from the kineck depth sensor (loseless compression) from the start and to the end of the test
- set of PCM wavefiles of all the commands given to the robot by the operator(s)

**Comment by LoyVanBeek** [comment]
I'd also like to see the data for incomplete of failed challenges. 
The reason for the failure is likely to be in that data in some cases

**Comment by kyordhel** [comment]
Yes, you are right, but we are not scoring for that. We also not want to get full of meaningless data. Right now I can see some teams providing a full data set of the robot looking at the open door for 8 minutes without moving.

**Comment by LoyVanBeek** [comment]
I'm actually not that interested in all the raw data. Only the relevant parts.
What is relevant can differ per use of course

**Comment by kyordhel** [comment]
I'm changing the milestone of this issue to Leipzig since no more changes will be made. I would like to discuss this issue right after the competition.

**Comment by LoyVanBeek** [comment]
I will ask teams casually this year already.

**Comment by LoyVanBeek** [comment]
Per challenge, we can request some data (Or make it obligatory):
- Navigation: maps inside and outside the arena and compare with other robots (ground truth is difficult outside the arena)
- Speech Recognition: Recorded audio data (hopefully the audio can be annotated with the ground truth afterwards by the team, if not the mic is broken :smile: )
- Person Recognition: annotated 2D/3D images annotated with ground truth age, gender etc. 
- Manipulation: 3D pointclouds of shelf, maybe annoted with grasp vectors
- Object Recognition: 3D pointclouds or 2D images again with all training data
- GPSR: Command voice recording, generated plan
