### ISSUE TITLE
Q: [Clean the Table: only points for all tableware]

### ISSUE THREAD

**Issue by JosjaG** [RoboCupAtHome/RuleBook#720]
## Summary
Will we only get points for the challenge if we succeed in placing **all** tableware and cutlery in the dishwasher similar to last year in DSPL, of will it be per piece similar to last year in OPL?

## Details
The rulebook states that for the Clean the Table challenge, one can only obtain points by placing **all** tableware and cutlery in the dishwasher. However, last year, I believe this rule was different between the leagues. For OPL (as I understood), you received points for each piece placed in the dishwasher, for DSPL you had to place all objects in the dishwasher to receive points.

**Comment by johaq** [comment]
You will get points for individual objects placed. This still needs to be changed in the rulebook. There won't be differences between the leagues.

**Comment by johaq** [comment]
Addressed in #722. @JosjaG, can this be closed?
