### ISSUE TITLE
Q: [Carry my Luggage: penalties]

### ISSUE THREAD

**Issue by JosjaG** [RoboCupAtHome/RuleBook#721]
## Summary
What does the ```5 x``` in the scoresheet penalties mean:
> Regain operator’s track by .....   5 x -400

## Details
In the Carry mt Luggage challenge, there are various ways in which you can regain the operator's track if you've lost it, these all have penalties. By looking at the scoresheet there appears to be a maximum of five times that you can do this. However, for example for the 'direct contact' method for regaining the operator's track (which has a penalty of -400) this does not really make sense as the point maximum is only 1000 points. My question therefore is; what does the ```5 x``` mean, are we only allowed to lose the operator's track at a maximum of 5 times?

**Comment by johaq** [comment]
>  are we only allowed to lose the operator's track at a maximum of 5 times?

Yes, basically. This should be clarified in the description. Personally, I think 5 is way too many times for retracking so this might be lowered. In terms of point maximum reached in penalties, it is up to the referee, if he wants to continue the task, even though no positive score can be reached, just for show. Of course, the overall points for a task cannot be negative.

**Comment by semaph0r** [comment]
> Personally, I think 5 is way too many times for retracking so this might be lowered.
Is it meant to be pushed to raise efforts in people tracking? What should be the number of retries?

**Comment by johaq** [comment]
Addressed in #722. No limit on how often the robot can re-find the person. Up to the referee's consideration to end the test if the robot already reached a score of 0pts with reductions.
@JosjaG, can this be closed?
