### ISSUE TITLE
Skill Certificates Do Not Make Sense Anymore

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#724]
As stated in #722, the current version of skill certificates does not make sense anymore since we cannot really determine whether a team has achieved 75% points in skill X. In the past this was possible due to basic ability tests which do not exist anymore. However, we want to give out more not less awards which leads to the questions.

Do we want to keep the best in X certificates and if so what is a good way with the current tests to award them?
If we do not want to keep them, what are good alternative certificates that make sense for robocup@home.

**Comment by RemiFabre** [comment]
What is the difference between a certificate and an award?
There is an "Open-source software award" but no "Open-source hardware award", maybe we could add that?
To be transparent, we're working on a project that could be useful for the league (albeit, only for OPL) and are planning on sharing it. It would come with some mechanical designs, electrical designs, low level code (micro-controller) and a high level ROS integration (PC). We would love to be candidates for an award on this but the software portion of this work alone wouldn't be enough.

**Comment by johaq** [comment]
No real difference afaik. Just a naming thing. I guess one difference is that awards are chosen by a jury and certificates are handed out based on hard criteria.

I like the idea of a hardware award.

**Comment by ARTenshi** [comment]
Maybe "Best performance award" or "Best performance award in Task X" if a team gets more than 75% of the points in a given task (without bonuses)?
