### ISSUE TITLE
Open Challenge Scheduling

### ISSUE THREAD

**Issue by johaq** [RoboCupAtHome/RuleBook#727]
We need to find a schedule spot for the Open Challenge.

Does your team intend to present an Open Challenge? 
If yes, when would be a convenient time (after Stage 1/2 or during Setup Day)?

**Comment by RemiFabre** [comment]
CATIE Robotics does not plan on presenting an Open Challenge.

**Comment by alex-mitrevski** [comment]
At this point, we (b-it-bots) also don't intend to present an open challenge.

**Comment by LarsJanssenTUe** [comment]
Tech United does not plan on presenting an Open challenge either

**Comment by RemiFabre** [comment]
Well, after some convincing from @kyordhel , we've been signed in an Open Challenge :)
The deal is that we cancel it if our ongoing project doesn't work out, but we got some good progress this week and hopefully it will be a decent demo.

**Comment by ARTenshi** [comment]
It should be on the first day of the second stage, I suggest, so teams that qualified and those who didn't have the same preparation time for that challenge (although it is voluntary, it offers an award that should be granted under similar participation conditions).

**Comment by kyordhel** [comment]
I don't think we can do it one day. Open Challenge will be spanned over two days, 10 mins per team (i.e. 6 teams). Currently we have 10 participating teams. Attendance is not mandatory

**Comment by ARTenshi** [comment]
Well, at least having most of the teams that didn't classify to the next stage performing the Open Demo on the first day while the others on the second.

**Comment by moriarty** [comment]
Closing this, it appears to be specific to the German Open 2020?
