### ISSUE TITLE
[Open Challenge] Is the open challenge mandatory?

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#73]
It also states that for the open challenge, it is required to participate in the other stage-2 challenges. 
This should be considered during scheduling

**Comment by kyordhel** [comment]
Scoring is made by TC/EC & Team leaders.
Open challenge does not logner requires participation in other tests.

**Comment by kyordhel** [comment]
It should be scheduled at the begining of the 2nd Stage.

**Comment by kyordhel** [comment]
Open challenge is not mandatory
