### ISSUE TITLE
Let the robot learn some faces + names beforehand, like objects

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#74]
For some challenges, it would make sense if the robots know beforehad which face goes with which names. For example, in the GPSR, there can be a command like 
"count the people at the kitchen and report to Luis at the office"

The robot must then know Luis beforehand for this to make sense.

**Comment by kyordhel** [comment]
+1

All TC/EC members should provide their lovely faces/voices (3D pictures + PCM wave files) so robots can recognize us! We may also upload data to this repo so all teams can train with the same data.

**Comment by LoyVanBeek** [comment]
Well, uploading a 3D picture of my face to the entire internet is not what I want.
I'd rather e-mail it to them

**Comment by LoyVanBeek** [comment]
The alternative is to sit in front all robots for a while. But if all 20 of them do this in direct sequence and it takes a minute each, I'd do that :-)

**Comment by kyordhel** [comment]
Still thinking we should provide TC/volunteers' faces for face recognition so robots can recognize them during tests. Emailing data is not a bad idea but I'm more into having open data

**Comment by LoyVanBeek** [comment]
We could use it in wake-me-up for example
