### ISSUE TITLE
More test slots?

### ISSUE THREAD

**Issue by RemiFabre** [RoboCupAtHome/RuleBook#742]
During the June 5 Q&A, the following tentative schedule was proposed:

June 22 – Poster
June 23 – Stage I (1 run per team)
June 24 – Stage I (1 run per team)
June 25 – Empty (preparation for stage 2)
June 26 – Stage II (1 run per team)
June 27 – Empty (or maybe a final of some sorts that doesn't award points)
June 28 – Tech Ch.

Each day has 2 time slots, 12 hours apart (to accommodate for time zones). Each teams chooses 1 time slot only (choosing 2 would not be healthy).

In its current version 50% of the teams will experience something like this:
- 1 run of task 1 (3 runs with the same code in DSPL, 1 run in OPL)
- 1 run of task 2 (3 runs with the same code in DSPL, 1 run in OPL)
- Elimination
The other 50% will qualify for Stage II and will get an extra run.

This seems rough and at least 1 other team (Jan?) shared the same opinion. If other teams feel the same way please say so.

Let's discuss some alternatives/ideas.

### Schedule
**Option A** (proposed by "Group" in Telegram, who is that? Mauricio's smurf account?)
June 22 – Poster
June 23 – Stage I (1 run per team)
June 24 – Stage I (1 run per team)
June 25 – Stage I (1 run per team)
June 26 – Empty (preparation for stage 2)
June 27 – Stage II (1 run per team)
June 28 – Tech Ch.

**Option B**
I'd rather skip the "debug day" and have 2 runs for stage 2, so:
June 22 – Poster
June 23 – Stage I (1 run per team)
June 24 – Stage I (1 run per team)
June 25 – Stage I (1 run per team)
June 26 – Stage II (1 run per team)
June 27 – Stage II (1 run per team)
June 28 – Tech Ch.

## 1) 2 slots per day per team
There are 6 SSPL teams, 14 OPL teams and  4 SSPL teams. I'll focus on OPL because it's the worst case (well, kind of):
 7 of the 14 OPL teams are European and will most likely choose the same time slot. Let's assume the other 7 choose the other slot. So we have 2 groups of 7 teams that work 12 hours apart. 
I think **having teams refereeing each other is a very good solution** because it's a solution that scales with the number of teams.
In its current state, the schedule for a stage 1 day would look like this (based on the Q&A session):

**Current schedule**
8:00-8:05 am TC/OC presentation.
8:05-8:15 am We open a room in Zoom per team and the referees.
8:15-8:20 am Team 1 OPL video shown by the Team
8:20-8:25 am Team 2 OPL video shown by the Team
8:25-8:30 am Team 3 OPL video shown by the Team
8:30-8:35 am Team 4 OPL video shown by the Team
8:35-8:40 am Team 5 OPL video shown by the Team
8:40-8:45 am Team 6 OPL video shown by the Team
8:45-8:50 am Team 7 OPL video shown by the Team
I think it's safe to add 2-3 minutes per team to be more realistic (delays when switching rooms, Gazebo doesn't run in real time for some teams, etc). Let's add 20 minutes:
9:10 am the day is over for the 7 teams.

** Proposed schedule**
8:00-8:05 am TC/OC presentation.
8:05-8:15 am We open a room in Zoom per team and the referees.
8:15-8:20 am Team 1 OPL video shown by the Team
8:20-8:25 am Team 2 OPL video shown by the Team
8:25-8:30 am Team 3 OPL video shown by the Team
8:30-8:35 am Team 4 OPL video shown by the Team
8:35-8:40 am Team 5 OPL video shown by the Team
8:40-8:45 am Team 6 OPL video shown by the Team
8:45-8:50 am Team 7 OPL video shown by the Team
+ 20 minutes of delay
9:10-9:40 am pause
9:40-9:45 am Team 1 OPL video shown by the Team
9:45-9:50 am Team 2 OPL video shown by the Team
9:50-9:55 am Team 3 OPL video shown by the Team
9:55-10:00 am Team 4 OPL video shown by the Team
10:00-10:05 am Team 5 OPL video shown by the Team
10:05-10:10 am Team 6 OPL video shown by the Team
10:10-10:15 am Team 7 OPL video shown by the Team
+ 20 minutes of delay
10:35 am the day is over for the 7 teams.

## 2) All teams qualify for Stage II
The test slot for stage II is thrice as long (15 minute vs 5 minutes) so for this to work some adjustments could be made, e.g:
- Make stage II 10 minutes instead of 15 minutes
- The referee stops the run if the robot is not actively trying to score for more than 1 minute (also this will prevent streaming a video where robots stand idle for 15 minutes)

## 3) Effort
During a normal RoboCup, a team could have ~4 stage I runs. What changes in this virtual edition to make that number drop to 1? Is it because the EC/OC/TC have to handle 2 shifts 12 hours apart?
The whole "virtual" aspect of the competition is understandably less engaging, our team shrank by a factor 2 and the preparation effort shrank by a factor I'd rather not calculate :) However, the ones that remain are very motivated so **ping us if we can somehow help**.

## 4) Time zones
This is what the time zones look like for each team:
https://docs.google.com/spreadsheets/d/1XaV-ULqu2yI8xa2niCpuiDk5L6MMKD2VIJ99SWvfOV8/edit?usp=sharing
Yeah, not sure what can be done here. It would certainly be rough for several teams if we were to share the same time of the day. But could this free some time from EC/OC/TC to run at least 2 runs per team?

**Comment by RemiFabre** [comment]
A decision has been made. 
I think it's good that all the teams will have at least 3 stage 1 runs.

The user "Group" answered in the Telegram thread:


_The updated schedule will be like this:

Poster Session (Tue 22nd), 11:00-13:00 UTC​

*First day (Tue 22nd), 23:00-25:00 and (Wed 23rd) 11:00-13:00 UTC​
*Second day (Wed 23rd), 23:00-25:00 and (Thu 24th) 11:00-13:00 UTC​
*Third day (Thu 23rd), 23:00-25:00 and (Fri 24th) 11:00-13:00 UTC​

Stage II (Sat 25th), 23:00-25:00 and (Sun 26th) 11:00-13:00 UTC​

​*Technical Challenge on Mon 28th at 01:00 UTC

We will keep the classification process as in any competition. I know myself how frustrating it's not classifying to the next phase but I have also experienced the joy of being into the next stage; this is part of the experience.

And we still need time between Stage I and Stage II for organasing and everything (as it's a worldwide competition, it's a 24 hours job for the TC/OC)_

**Comment by YuqianJiang** [comment]
How does the updated schedule affect DSPL teams? Will DSPL run another round of tests on the third day?

**Comment by RemiFabre** [comment]
That's my understanding of it at least. I don't think that the schedule was discussed for OPL only
