### ISSUE TITLE
Is there an official logistics and freight for RoboCup 2022?

### ISSUE THREAD

**Issue by Yoo-Youngjae** [RoboCupAtHome/RuleBook#750]
## Summary
Is there an official company for worldwide freight like in robocup 2019?

## Details
I am looking for a way for our robot's air transport. 
However, I couldn't find any information about this on the official site(https://2022.robocup.org/).

As in the 2019 robocup(https://2019.robocup.org/freight.php), I would be grateful if you could give me some further details (official guidance).

**Comment by MatthijsBurgh** [comment]
This is something organized the local OC. Nothing for the league.

P.S. This is not related to the HSR. A freighter does also ship other robots 😉. So I removed that from this issue.
