### ISSUE TITLE
Q: [Find My Mates: Duplicated feature as a description]

### ISSUE THREAD

**Issue by ikuzo198** [RoboCupAtHome/RuleBook#753]
The rule says "The description of each guest should be unique, i.e. not shared with any other guest." in the [Additional Rules and Remarks / 2.Description of a person].
Is it possible to use the same feature to describe a guest?
For example, "Guest A is male, wearing a mask, wearing a long sleeve shirt, and wearing glasses.”,  “Guest B is female, wearing a short-sleeve shirt, wearing a necklace, and not wearing a mask."
I.e. The description contains the same noun with different adjectives. Is it considered a unique description or do we have to change the feature (noun) for all guests?

**Comment by alex-mitrevski** [comment]
Hi @ikuzo198, it is definitely possible to use the same features (nouns) for describing the guests; we (people) also do that all the time. The example you gave makes a clear distinction between the two guests, so the two sentences are perfectly unique descriptions.

Repeated noun-adjective combinations would be non-unique descriptions, however.

**Comment by ikuzo198** [comment]
Hi @alex-mitrevski, I understood.
Thank you.
