### ISSUE TITLE
Harder manipulation

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#76]
Ideas for extending manipulation:
- Grasp something from a bin (with like 8-cm high borders)
- Place the object face-forward (so you need bi-hand manipulation or at least re-grasp and plan)
- Manipulate a switch
- Manipulate a big object so you need 2 hands.

**Comment by kyordhel** [comment]
Sorry for teams with only one manipulator. Then we are encouraging robot-robot cooperation (maybe from different teams)

My suggestions (not necessarily with 2 arms):
- Arrange the groceries from the shopping bag into a shelf
- Taking out the plastic bag from the trash bin.
- Use a ladle to serve soup from a pot
- Flipping omelette/meat
- Whipping eggs or cream with a whisk (manually).
- Mop the floor / Brush the floor (broomstick)
- Pressing buttons in a keyboard (dialing phone, copy machine, calculator).
- Handling digital (flat button) control panels (microwave, digital washing machine, conductive stove).

**Comment by LoyVanBeek** [comment]
For now:
- Picking something out of a box/bag
- Grasp a soft cloth
is hard enough... I'd love to see your's as well though

**Comment by kyordhel** [comment]
My what? I don't have a robot, not even a team (yet)
But my former robot, Justina, she will, oh yes, she will or heads will fall...

**Comment by LoyVanBeek** [comment]
Other manipulations:
- Grasp a old-style phone horn
- Wipe a table/shelf with a cloth (actual use case from @RobotRose)
- Grasp a towel from a hanger
- Pick up a pen
- Pick up a pill
- Pick up a tray/plate
- Pick cutlery from the drawer
- Grasp a moving object (with may be something simple for starters)

Perhaps we need a challenge for advanced manipulation

**Comment by LoyVanBeek** [comment]
For the advanced manipulation extension: 
Put some objects in a box thats is placed on the shelf. The robot must get the box from the shelf,'place it somewhere it can so it can take a look inside and get an object from the box.

**Comment by LoyVanBeek** [comment]
Maybe let teams propose "our robot can do this and this complex manpulation." They show it to us and we assign points to it, relative to how well it did and what other robots do. 

The teams should propose this early on so other teams can try them as well.

**Comment by LoyVanBeek** [comment]
Desicion: Let the teams show their awesome skill separately

**Comment by kyordhel** [comment]
I've seen no any initiative from the team side. Maybe making an open-call for "awesome skill" would be a nice idea. 

If instead of "pulling" teams TC encourages them to push themselves their own limits we may get a better response. Some certificates (innovation in manipulation or something like that) may also help.

**Comment by LoyVanBeek** [comment]
OK, in RoboCup@Home, the objects are always nicely on display. My home isn't like they, my groceries are usually in a closet, hidden by a door I have to open to see what I have. 
We could require the robots to open a door first as well, or give a little penalty for having the referee open the door first.

**Comment by kyordhel** [comment]
Let's see how this behaves from here till 2020. With 2017 results, I doub't difficulty can be increased too much. We need a roadmap.
