### ISSUE TITLE
Q: [Hand Me That: Could we use a custom operator?]

### ISSUE THREAD

**Issue by yuzoo0226** [RoboCupAtHome/RuleBook#762]
Can we use custom operators in Hand Me That?
If it is possible, does the point reduction rule which is specified in chapter 3.8.3 applied?

**Comment by alex-mitrevski** [comment]
Hi @yuzoo0226, indeed, the default point reduction in 3.8.3. applies in this case since there is no task-specific penalty for using a custom operator.

**Comment by yuzoo0226** [comment]
Hi, @alex-mitrevski , thank you for your prompt reply.
We understood.
