### ISSUE TITLE
Q: [Restaurant: Can we use a custom container?]

### ISSUE THREAD

**Issue by ikuzo198** [RoboCupAtHome/RuleBook#763]
Can we use a custom container in Restaurant?

If possible, can we achieve the optional goal (Use an unattached tray to transport the order.) with a custom container that is unattached?

**Comment by alex-mitrevski** [comment]
Yes, absolutely. It would only be considered attached if the tray is taped or tied to the robot in some manner, but grasping the tray is, of course, necessary so that an order can be delivered.

**Comment by ikuzo198** [comment]
OK, we understand that.
Thank you.
