### ISSUE TITLE
[Hand Me That: Is this action a clarifying question?]

### ISSUE THREAD

**Issue by ikuzo198** [RoboCupAtHome/RuleBook#764]
Is the following action a clarifying question?
The robot shows some pictures of the objects in the pointed area and asks the operator if it matches the pointed object.

**Comment by alex-mitrevski** [comment]
Hi @ikuzo198, do you mean (a) the robot shows a general picture of the scene and asks if the object is visible there, or (b) it shows a picture of a specific object (or a picture of the scene and a bounding box around one object) and asks whether that is the object pointed at? In the former case, this would be a clarifying question; in the latter case, it would be a guess.

**Comment by ikuzo198** [comment]
Hi @alex-mitrevski , we are considering method (b).
We understood the description.
Thank you.
