### ISSUE TITLE
Q: I want to know how calculate the bypassing rule using QR code

### ISSUE THREAD

**Issue by yuma116** [RoboCupAtHome/RuleBook#765]
I want to use a QR code for bypassing ASR, for example Restaurant.
However, I don't know how to calculate the score when to use bypassing rule.
Could you tell me how to calculate it?

**Comment by alex-mitrevski** [comment]
Hi @yuma116, unless specified otherwise in a given task, using a QR code results in 30% score reduction, in accordance with section 3.8.3: `A reduction of 30% of the maximum attainable score is applied when a QR code is used to instruct the robot.`

**Comment by yuma116** [comment]
I have a question about multiple voice recognition during a task such as a restaurant.
For example, if you use a QR code bypass when listening to order from a first customer and when listening to order from a second customer in a restaurant task, respectively.
(a) 60% deduction for applying the bypass rule for two times
(b) The deduction is applied only once and is deducted by 30%.

I would like to know which of these is the case or if there is another calculation method.

**Comment by alex-mitrevski** [comment]
The 30% is on the full task score, so option (b) applies. In the restaurant example, if you complete the task fully (which means obtaining 2000 points), you would effectively get 1400 points because of the 30% score reduction.
