### ISSUE TITLE
Q: [Restaurant]Number of objects ordered at one time.

### ISSUE THREAD

**Issue by ue-no-tsubaki** [RoboCupAtHome/RuleBook#766]
In the Setup/Objects column, it is stated that 'Orders have between one and three objects randomly chosen.
The Score sheet/Deus ex Machina Penalties column states '~~~(per object) 6 x ~~'.
Does this mean that 'the number of objects ordered at one time is always three'?

**Comment by johaq** [comment]
No, scoresheet just allows for the possibility that 3 objects were ordered both times.
