### ISSUE TITLE
Reduce significance of Finals?

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#78]
Relative to the stage 2 challenges, the finals can be really easy because teams get to decide the task. 
I suggest reducing the significance to e.g. 20-25%.

**Comment by LoyVanBeek** [comment]
Also, the Finals are easy to hardcode and this is what happened in previous years. 
If the task can still be achieved when after the robot is initialized, the TC can move things around a little bit before the robot actually starts, then it is a real good demo. 

If this cannot be done or is disliked by OC or EC etc for reasons like "it should be attractive to the audience", the significane should be reduced to a more reasonable level.

**Comment by LoyVanBeek** [comment]
Team Tobi, TechUnited both agree :+1:

**Comment by LoyVanBeek** [comment]
Currently, the finals grant 2000 points. But the highest score now at GermanOpen is 600-something. The finals make everything before it irrelevant. 
Maybe the max score for the finals should max out the 25% the maximal obtained score, so in this case 25% of 600-something points. 
Someone suggested maxing the points that a team can obtain in the finals to be a percentage of their current score. This means you have to do very well in stage 1 and 2. Then you have a robot that is good overall.

**Comment by dragonjack** [comment]
Team WrightEagle@Home also agrees. I would propose a percentage of between
20% to 30%, which means a 10% to 20% percent influence of league-internal
and -external jury each.

As for the hardcoding stuff, it should be the team's responsibility to make
the jury believe that their robot is actually doing 'perception' other than
'acting'...

On Sun, Apr 26, 2015 at 1:59 AM, Loy <notifications@github.com> wrote:

> Team Tobi, TechUnited both agree [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RoboCupAtHome/RuleBook/issues/78#issuecomment-96246472>
> .
>



-- 
Regards

Multi-Agent System Lab
University of Science and Technology of China

K.Chen

**Comment by LoyVanBeek** [comment]
But EC, trustees etc, the people that make the internal and external jury have the final say in this. And want to have such a big influence on the outcome.
