### ISSUE TITLE
Q: Scoring Carry my Luggage

### ISSUE THREAD

**Issue by Kathrin227** [RoboCupAtHome/RuleBook#792]
### Is dropping the bag a penalty or a bonus reward?

In the rulebook, "Dropping the bag" is listed under "Regular Penalties", but it is assigned *positive* points (50 to be exact) and the sum of 1050 points for the task can only be reached if this is indeed counted as a bonus. This does not make sense to our team so we would like to ask for some clarification, please.

**Comment by MatthijsBurgh** [comment]
This is a mistake, see https://github.com/RoboCupAtHome/RuleBook/pull/793
