### ISSUE TITLE
Q: what does "confirm" exactly mean in stickler for the rules

### ISSUE THREAD

**Issue by tsunekazuomija** [RoboCupAtHome/RuleBook#797]
## Summary
In the section of Stickler for The Rules, it reads that after the robot clarifies to the guest what action he/she should take, it “confirms that the guest is following the rule”. But I thought the meaning of "confirm" was a little ambiguous.

## Details

I think there are two ways of understanding.
In the case that the guest doesn’t follow the robot’s instructions,
1. Robot keeps telling the guest what rule is being broken and what action he/she should take until he/she follows the instruction.
2. Robot just declare that it asked the guest to follow the rules, but he/she did not.  

I interpreted 1 from the rulebook, but 2 is also a possible interpretation.  
I just want to make clear which interpretation is appropriate.

**Comment by johaq** [comment]
This test is very new, personally I have not run it yet at a competition. So other referees might chime in if they see it differently.
I view the phrasing in the goal "make sure" and the scoring item "confirm..." as the guest might not follow the rule immediately or needs assistance on how to follow it. For the shoes the robot might need to show the guest where the entrance is, for the drink the robot might need to show the guest where to find drinks, for the room the robot needs to show the nearest exit, for litter the robot might need to show the nearest bin etc.

**Comment by tsunekazuomija** [comment]
I'm sorry for the late reply.

I understand what you think and agree with your understanding of the rulebook.
In short, "make sure" or "confirm" means "successfully make the guest to follow the rule they were breaking".
I could clear up my question. So, I will close this issue now. 

Thank you.
