### ISSUE TITLE
Q: [GPSR] GPSR partial scoring

### ISSUE THREAD

**Issue by R2D2-like** [RoboCupAtHome/RuleBook#798]
I have a question about GPSR scoring.
The rulebook states that
```The main task allows partial scoring (per completed command).```
What exactly are the criteria for partial scoring, and how many points are rewarded for each specific action or Deus Ex Machina?

**Comment by johaq** [comment]
Partial scoring just means that not all three commands need to be completed to score any points. Solving one command gives points already.
