### ISSUE TITLE
Proposal to extend the execution time of GPSR

### ISSUE THREAD

**Issue by R2D2-like** [RoboCupAtHome/RuleBook#800]
I have a suggestion about the time limit for GPSR task execution.
How about extending the time limit?
Currently, it is 5 minutes, but our team believes 5 minutes is insufficient to execute three commands, so we prefer to extend it to 15 minutes (5 minutes per command * 3 commands).
We have three main reasons.
1. the time per task is shorter for GPSR than for other RoboCup tasks
Each command of GPSR includes other RoboCup tasks. 
Since each RoboCup task is given 5 minutes to execute, we think 5 minutes per command is reasonable for GPSR as well.
2. If the number of commands that can be executed is limited due to time constraints, the randomness of the commands will have a greater impact, making it more difficult to evaluate the performance of the GPSR.
3. 5 minutes is not enough based on our experience at the RoboCup Japan Open.

**Comment by johaq** [comment]
Time limit will not be changed so close to the competition. If in Bordeaux we notice that the time limit is repeatedly preventing cool performances we might reconsider a change for next year.
