### ISSUE TITLE
Q:[DSPL]Carry My Luggage

### ISSUE THREAD

**Issue by constantpi** [RoboCupAtHome/RuleBook#801]
## Summary
In Carry My Luggage, if the robot fail in the "Picking up the bag" phase, is it possible to proceed to the "Following the operator" phase?

## Details
In this task, it is required for the robot to initially pick up the bag, and it is stated that Deus Ex Machina is not present in this stage. If the robot fails to successfully pick up the bag, does it mean that it cannot proceed to the next stage, such as "Following the operator," and will receive a score of zero? Additionally, if the robot grabs the wrong bag out of several bags, will it also be unable to advance to the "Following the operator" stage and receive a score of zero?

If the answer to these questions is yes, I strongly urge for the reintroduction of Deus Ex Machina. In the previous competition in 2022, where Deus Ex Machina was not allowed for the Carry My Luggage task in the DSPL league, all teams ended up with a score of zero. However, in the years when Deus Ex Machina was permitted, there were teams that were able to score points.

**Comment by johaq** [comment]
The goal is to carry the bag outside. So yes, you need to transport the correct bag. If you fail to pick up the bag, you could ask to have it handed over. You could also ask if you picked the correct bag.

**Comment by constantpi** [comment]
I did not know that the robot could ask the operator to hand over the bag. Thanks for the reply!
