### ISSUE TITLE
Partial points for tasks (eg. points for pick up in pick-place-task)

### ISSUE THREAD

**Issue by PetervDooren** [RoboCupAtHome/RuleBook#808]
How should the rulebook adres partial scoring.

On the one hand. If the robot does not complete the task it has failed. If a robot drops your breakfast on the floor you have just as much breakfast as when the robot would not have tried in the first place. A robot that can only do half a task does not provide any value for that task.

On the other. It is strange if a robot can do a task nearly flawlessly but messes up at the last moment, yet still scores as much points as a robot that cant do anything.

(Issue outlined in TC meeting 31/07/2023)

**Comment by PetervDooren** [comment]
Suggestion: a robot can score up to half the maximum points with a partial execution. So teams earn some brownie points for doing things but only get a competitive score if they complete the task fully.

**Comment by MatthijsBurgh** [comment]
I think you should focus on the desired robot behaviour, not its implementation.

**Comment by ARTenshi** [comment]
>I think you should focus on the desired robot behaviour, not its implementation. 

I agree, we should focus on the goal and refrain from partial points. For example, if the task is to autonomously store groceries, we should count how many were stored and, maybe, apply a scale factor for those objects that needed help (only after the object has been stored, not when trying to store the object (e.g. grasping for transportation but dropping it)). An example of a scale factor would be as follows:

object_1_score = alpha_1 x max_points
alpha_1 = (1*object_stored) x (1 - 0.5*incorrect_category) x (1 - 0.5*deus_ex_machina )

where object_stored, incorrect_category, deus_ex_machina in [0, 1]

For example, an object stored in an incorrect category or that needed help would get half of the total points while an object with an incorrect category and that needed help would get a quarter of the total points. Using this kind of approach any team able to deposit an object will be able to score independently of the level.
