### ISSUE TITLE
Proposal for task guidelines

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#812]
## Is your idea/suggestion related to a problem? Please describe.
We want guidelines for the task design. 

## Describe the solution you'd like

- The robot is supposed to be useful, not annoying: The robots have to be helpful for everyone involved. Always frame the task in a way that you would want to have that robot independently of your role in the task; it mustn’t be annoying by design, it mustn’t try to enforce rules.
- Only design tasks you want to be solved. Don’t try hard to design „creative“ tasks. Keep it simple, desirable and intuitive. 
- Check if children or technophobes would like that feature (or at least cannot really argue against it)

## Describe alternatives you've considered
Just reframe the same task in a way, that the robot looks good.

## Additional context
This is motivated by the stickler for the rules task. I get strange vibes from this task. 
- The party was nice, but sadly the robot was invited too
- Can I take pictures of your feet? Maybe also smell on them?
- Obey me
- You have to get drunk

- A smart home would do that task, not a robot
- Just lock your room, if nobody should enter it

**Comment by PetervDooren** [comment]
So is this a call to implement general guidelines that challenges must adhere to? or is it specifically to fix the stickler for the rules challenge?

For the latter, I agree that stickler is a bit weird, we could recontextualise the challenge to make the rules less strict and penalise the robot when it makes guests uncomfortable.

**Comment by LeanderVonSeelstrang** [comment]
I think general guidelines are useful and the stickler for the rules task motivated me to call for general guidelines. 

Also I think not every task has to follow these guidelines, but it is desirable if they would follow them. More as a help for us while designing. Nothing strictly mandatory.
