### ISSUE TITLE
Discussable proposal for the introduction of a new first Stage (Stage 0)

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#813]
## Is your idea/suggestion related to a problem? Please describe.
Modularity should be enforced (intra team and especially inter team reusability of skills)
Comparability within the tournament and across the years is desirable
We need a foundation to go from gut feeling decisions to empirically driven decisions. For that we need statistics.
We also need statistics to visually demonstrate that the field progresses.
Everyone should be able to show off their work.

## Describe the solution you'd like
I would like Level I to test only atomic capabilities at various levels of complexity (uncertainty, time, or other conditions such as weight or illusions).

## Cons

- More work for the TCs and OCs
- In the end only solving the whole task is relevant
- Atomic skills are tested implicitly in the later stages anyway
- You don’t want to filter out a predefined percentage of teams in this Stage
- When do we find the time to test this Stage? Where do we test this Stage? I would want the teams to be able to do this Stage as often as they want to. 

## Pros

- I would argue that this Stage can be performed rather fast, because Navigation is only relevant in the navigation atomic task test. Maybe Navigation will be tested enough in the later stages anyway, so I’d be fine to cut navigation out of the first stage altogether. 
- You should get a minimum amount of points to make it to the next level.
- This Stage enforces modular design (I know the other tasks indirectly do that too, but they do it only indirectly. I want to do it explicitly.)
- This Stage can stay constant over the years. You just increase the available complexity. 
- Good teams will strive to solve the highest complexity, bad Teams will solve the task on the easy level.
- Modular design, combined with a shared foundation should lead to more usage of code from other teams and thus push the field forward over the years.
- We can aim to fully automate this stage (especially grasping and placing)
- Having a low constant Stage over the years allows for long term planning for the teams (and the Organisators) and to collect statistics over the years to visualize progress.
- You can improve the same tasks for a long time: be faster, be more careful and aware, handle heavy or fragile objects. I am pretty sure we can design different levels of complexity for every atomic task.
- Having a constant Stage over the years allows us to show statistics with an upwards tendency, so every child intuitively understands that we make progress (if we make progress), because the line has an upwards tendency. I know a stupid argument, but nevertheless an important one. Things like this help to gather more funding and to communicate with non-scientists.
- Every team can present everything they worked on. This is more satisfying as you never work for nothing and maybe uncover hidden gems that would be filtered out in a compiled task.

## Additional context
Even if we don't chose to introduce a new Stage I (or 0) I want atomic scores, so we can gather statistics and increase comparability by design.

**Comment by LeanderVonSeelstrang** [comment]
I really don’t like the idea to write a fundamentally new rulebook every two years. This should never be the goal. But I also don’t want to freeze it. I think a (more or less) constant Stage I is a good compromise.

**Comment by ARTenshi** [comment]
We can't add more stages; on the contrary, we need to reduce the number of tasks to a few significant ones (we have seen several teams not scoring at a given task and no team scoring at all tasks). 

Instead, I would like to propose updating the Robot Inspection task (entering and leaving the arena is too simple). Maybe a Storing-Groceries-like task where the robot enters the arena, evades some moving people, detects and recognizes objects, and places them in their correct location. We won't score the task but only check the minimum robot skills (navigation, object recognition, object manipulation (or bypassed manipulation for SSPL), and so on). So we will be sure that participating teams will have a base set of skills.

**Comment by PetervDooren** [comment]
I agree with @ARTenshi that we should not add more tasks to the rulebook. We want to keep the number to a minimum of significant tasks. 

I agree with @LeanderVonSeelstrang  that having a constant rulebook is favourable, but the rulebook must adapt to the state of the league so changes will be unavoidable. Hopefully we can prevent large changes like those of last few years.

I also like the idea of testing the atomic skills of the robots. since a lot of the challenges suffer from a problem where if you lack one skill the whole challenge fails and teams cant show what their robot can do. But I would suggest to place the focus of stage one tasks to these atomic skills rather than add a new stage for them. I definitely would not use the robot inspection for these base tasks, the rips is a test for safety not for performance.
I also like the idea of letting teams choose their own level (and kind) of difficulty. That gives them the opportunity to show what they can deal with (e.g. heavy or fragile objects).

**Comment by LeroyR** [comment]
Stages are split for scheduling/organizational reasons. I dont think you could reasonably "send teams home" after a short atomic test stage.

@ARTenshi Basic capabilities already have to be shown in TDP and video so we can assume teams are able to perform them in lab conditions athome is then about integration and transferring these into complex environments.

We want many teams to participate and solve complex/long tasks. i dont think atomic tests really align with the goals of athome but we could do better in measuring and giving opportunity to show atomic skills.

Agree with @PetervDooren that rips is for safety not for performance.

**Comment by LeanderVonSeelstrang** [comment]
Thank you for the comments.

I was not precise enough in the description of how I imagine the stage.

I thought of it as being designed last, like an introduction to a text. First we agree on the tasks we want to see solved (in Stage I and II). And then we sit down and try to divide the tasks into subtasks that can be done independently. These subtasks are then tested. 

So in a way, it doesn't increase the effort for the teams because they need the atomic tasks to do the actual tasks anyway. 

Nevertheless, modularity is rewarded. Modular code is easier to share and reuse. Further, each team can show everything they solved. And we get a very clear overview of which teams have which skills.

The different levels of complexity would be more of an add on and I shouldn't have emphasized it so much. But it would give the whole stage an additional reason for existence. 

All in all, I think that in perspective this stage can be automated over proportionally and at the same time kept above average constant over the years. If the teams are smart, the additional work for them should be limited. 

However, when and where this stage is tested during the event remains a problem.

**Comment by ARTenshi** [comment]
There is an atHome Education league for new teams, so we shouldn't focus on the lower level of the league (like scoring single skills) and, instead, focus on the higher level, like pushing further the state-of-the-art on domestic service robots, especially when we now have robots doing this:

https://youtu.be/xY5zqKRy8A8 

we can't spend time scoring partial skills like taking and then scoring delivering an object (again, the Education league can help new teams with that).

**Comment by PetervDooren** [comment]
I disagree @ARTenshi we should focus on lower level skills. Because getting better performance on lower level skills will allow us to complete more complex tasks. If we neglect the partial skills we will end up trying to do high level tasks with inadequate skills. 
We cant afford to neglect either the high nor low level skills.

**Comment by LeanderVonSeelstrang** [comment]
Most teams are university teams with high turnover that defacto have to learn a lot. But to me, that also has very little to do with beginner friendliness. That's one of the many positive effects of atomic scores. 

Zero points in a task contains almost zero information. I think there are more clever ways of scoring that contains information but rewards success disproportionately. Our data is not bad, it is simply non-existent. I don't think much of gut decisions (although I trust my emotional system a lot). We don't know which teams are good at which tasks. 

In software engineering you often find similar concepts like [Coupling](https://en.wikipedia.org/wiki/Coupling_(computer_programming)), [Low Coupling, High Cohesion](https://medium.com/clarityhub/low-coupling-high-cohesion-3610e35ac4a6), [Microservices](https://aws.amazon.com/microservices/?nc1=h_ls) going in a similar direction as atomic scoring in a rule book. We should try to write a rulebook that incentivizes writing code in a form that other teams can reuse in future years.

Without atomic scores, you tend to only score new things and potentially lose skills that have already been solved. Comparability across years is impossible. 

I think the benefits far outweigh the costs. At least if we do it right. For the next upcoming rulebook, however, I wouldn't aim for it yet, because I'd rather have a well thought-out concept and a fundamentally new stage needs a lot of planning the first time. In the background, however, I would already go in the direction and strive for that in the long run.
