### ISSUE TITLE
Is it too early for GPSR?

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#814]
## Is your idea/suggestion related to a problem? Please describe.
Currently, only something is hacked together. I think the field is simply not advanced enough to solve this task. At least not in a way that one would wish (like e.g. in Asimov's iRobot).
I know we all want a general purpose robot, but I don't currently see Robocup really laying the foundation for that. I think the solutions for a general purpose robot will ultimately be developed in a company and not as part of a Stage I (or II) 5 minute task.

## Describe the solution you'd like
Controversial opinion: I do not believe that the general purpose robot task is purposeful. I would have no problem eliminating it completely and only reintroducing it in 10 years when development is further along.  

## Describe alternatives you've considered
On the other hand we will never get a solution if we don’t ask for one. 

## Additional context
Eliminating GPSR all together would solve our task generator problem on the fly

**Comment by LoyVanBeek** [comment]
I'd say that now with all these LLMs popping up that this is the perfect time to do GPSR.

Models like [`SayCan`](https://say-can.github.io/), [`RT2`](https://www.deepmind.com/blog/rt-2-new-model-translates-vision-and-language-into-action)

This does speak for 
> the solutions for a general purpose robot will ultimately be developed in a company

though. 

It has been part of RoboCup@Home for as long as I know (since 2011) and possibly longer even, with some varying levels of success (similar to manipulation I guess). Using (classical) speech recognition, natural language understanding, planning etc.
As former TC, my idea was even to go the other way, to frame essentially all tasks in terms of GPSR, eg. build a task like 'Carry my luggage' as a sequence of simpler commands like 'follow me', 'hold this', 'bring this to X' etc.

**Comment by moriarty** [comment]
I disagree with removing GPSR. I do admit that it is unfortunate to see the performance of some teams in GPSR but I disagree that the field as a whole is not advanced enough to solve this task.

In the past teams have done very well in GPSR, eg: Nimbro a decade ago.

It is unfortunate that some labs which are advanced enough to solve this task do not participate in RoboCup@Home.

But the field itself is advanced enough to participate in this task.
And as @LoyVanBeek mentioned there are LLMs and recent developments.
I've been inside of BostonDynamics and Alphabet's robotics labs, the field is ready to push hard on GPSR.
1. https://ai.googleblog.com/2023/02/google-research-2022-beyond-robotics.html
2. https://news.mit.edu/2023/ai-helps-household-robots-cut-planning-time-half-0714
3. https://sites.research.google/palm-saycan

Delaying RoboCup@Home 10 years in this area would be bad timing.

In my opinion, teams should be spending most of their time focusing on two things:
1) Their labs specific area of research and publishing scientific results.
2) Applying that for GPSR in a robust, reliable and reproducible way.

If you spend most of your time on your area of research and apply it to GPSR the other tests in the competition are just smaller milestones as they are just rearranged components or integration tests for GPSR.

I believe teams focus on the order of the tests as the RuleBook is written or the tests are run at the competition, they aim to solve the challenges in Stage 1 and then will take it from there, but they should be aiming for the finish line which is solving GPSR and the other tests from Stage 2.

**Comment by LeanderVonSeelstrang** [comment]
Yes. I agree with both of you. Above all, GPSR is what we actually want. We can close the issue for all I care.
