### ISSUE TITLE
Task idea: Foreign Instructor

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#815]
## Is your idea/suggestion related to a problem? Please describe.
Pointing as a human-robot interface will never be solved if it is punished and more work than just detecting the desired objects. If you still want this feature implemented you have to design the task in a way, that detecting the pointing direction is actually rewarded.

## Content

- Request an item
- Coinflip if the requested item is the wanted item
- Robot grasps the requested item
- If the referee says „No“ or „Stop“ loudly the robot stops the pick up process (or places it back)
  - The referee points at the correct, wanted item
  - The robot picks the wanted item and tells the user the correct name

## Describe alternatives you've considered
Don't provide pointing as an alternative HRI to make the rulebook shorter

**Comment by PetervDooren** [comment]
This is comparable to the task 'Hand me that' we had in previous years. But the task was scrapped in favor of others. 
But indeed, at the moment no task requires human gesture recognition.
