### ISSUE TITLE
Task idea: House sitter robot

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#816]
## Is your idea/suggestion related to a problem? Please describe.
My plants suffer when I am away from home. I don't have pets, but I am sure they would suffer as well if you don't feed them for a couple of weeks.

## Content
The robot is supposed to find and water plants with a watering can. The robot has to fill the pet’s feeding dish with food and water. Finally the robot navigates back to the recharging station.

**Comment by PetervDooren** [comment]
I dont see what skills this challenge should test that are not aleady in another challenge. 
I do like the context of this challenge it seems like a real usecase. (safe for the fact that pets probably need more than just food and water when you go on holiday)

**Comment by LeroyR** [comment]
Could be a replacement for serving breakfast (pouring, placing food bowl?) 

But handling a watering can sounds much harder than pouring a milk bottle and not all robots are able to reach the floor. The scoring does not suggest that serve breakfast is too easy :sweat_smile:
