### ISSUE TITLE
Task idea: End user friendly tidy up task

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#817]
## Is your idea/suggestion related to a problem? Please describe.
Average people usually cannot program robots. In the end you need to be able to setup your newly bought robot on your own. I imagine the setup process to tidy up your room once, let the robot understand where things belong and the robot will try to transform the room back into the original state.

## Task Setup
The robot moves around, scans the room and stores the locations for all movable objects.

## Task
The robot restores the original state of the room. Laundry is picked up and placed into the laundry basket. Dish is placed into the dishwasher. All other items are moved back to their original position. 

## Additional context
This is a very complicated task. I would make this task the final task or choose it instead of GPSR.

**Comment by PetervDooren** [comment]
We probably wont change GPSR as that is the core functionality of the service robot.
However this does touch on the problem that a lot of things are programmed at Robocup and not much thought is given to how a user might instruct the robot.

**Comment by LeroyR** [comment]
> The robot moves around, scans the room and stores the locations for all movable objects. 
> The robot restores the original state of the room. Laundry is picked up and placed into the laundry basket. Dish is placed into the dishwasher. All other items are moved back to their original position.

While this is just an 'enhanced storing groceries++ combined with cleanup++ i like the idea. We already talked about more open tasks and combining different tasks into one where the robot can choose what to solve sounds good.

> To add to this, I would add a task where the robot cannot use a map of the arena. And has to get the users help to map the environment. semantic mapping

Not enforceable (could be mapped beforehand), restructuring the arena and moving furniture can be hard to impossible (shelf mounted on wall, fixed kitchen). 
The user could define names and locations e.g. go or point to one of two tables and define the name and what objects should be stored there but i think embedding this 'setup' in another task could take too much time. 
Some older restaurant tasks had guiding and learning table numbers as part of the task, we could bring this back?

**Comment by PetervDooren** [comment]
> Not enforceable (could be mapped beforehand), restructuring the arena and moving furniture can be hard to impossible (shelf mounted on wall, fixed kitchen).

We can get creative with this. :)
