### ISSUE TITLE
Task idea: Welcome robot

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#818]
## Is your idea/suggestion related to a problem? Please describe.
This is a robot competition. I want to see robots as soon as I enter the building. I want to be welcomed, possibly guided (by showing, not by following) by robots. Visitors can take pictures with the robots and post them on their social media.

## Describe the solution you'd like
Robots are to greet participants and guests at the entrance. This should be a task, otherwise it will not be done. 

## Additional context
This is the only real-world application for Pepper anyway, so it's quite obvious that we should do it.

**Comment by PetervDooren** [comment]
Nice idea, A few issue I can foresee.

1) safety. You are interacting with people so we should be able to guarantee their safety.
2) this will be hard to judge as presumably all robots are acting at the same time.
3) logistics. getting all the robots to the entrance takes a lot of time from the teams. This is already the case for restaurant. And depending on the location of robocup the entrance might not be suited to this.

**Comment by johaq** [comment]
#481

Maybe something exclusively for SSPL?
