### ISSUE TITLE
Proposal for collaborative multi robot tasks

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#819]
## Is your idea/suggestion related to a problem? Please describe.
Teams don't share their code. Teams don't work together or help each other out. Teams have no incentive to use a shared software foundation.

## Describe the solution you'd like
Collaborative tasks would encourage using common foundation and helping assigned partners as one benefits from their good performance.

## Describe alternatives you've considered
On the other hand, it's unfair if you have to rely on a bad team and therefore can't win the competition. Probably one robot would prepare a task and the other robot would execute the task. 

## Additional context
I think it is hard to design (fair) collaborative tasks.

**Comment by PetervDooren** [comment]
One way to design a fair collaborative task is to collaborate with a human operator. That way you are not dependent on another team. If you design this correctly you can make it so you can exchange the human with a robot. That does not even require them to have a shared software foundation. The human can still fill in when the robot falls short.

Bigger question is what kind of collaboration we want. shared task divided among agents (e.g. serve breakfast) or physical cooperation (e.g. carrying a large object with two robots)

**Comment by LeroyR** [comment]
I don't see how collaborative tasks would lead to shared software foundation. 

There could be like a challenge where the team provides open source repositories and instructions for the jury to setup a fresh DSPL robot to solve some task :upside_down_face:
