### ISSUE TITLE
Discussable proposal for the introduction of a new Stage I (and separation to Stage II)

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#820]
## Is your idea/suggestion related to a problem? Please describe.
The TC's and everyone else involved should know why the tasks are clustered as they are. I would like to have rules, when a tasks belongs to Stage I (or II) or to Stage II (or III).

## Describe the solution you'd like
I want Stage II to not be about manipulation, but only about navigation and perception. I would argue that manipulation always needs perception, so perception on its own is easier than perception and manipulation. 
However, this separation could be easily understood by the spectators. In addition, it gives the TC's a guideline of what kind of task is to be arranged in which stage.
Stage III should test navigation, perception and especially manipulation.

## Cons
One could argue that you can design reasonably complex perception only tasks. The claim that perception is generally easier than manipulation is easily attacked. 
This is why I don't have particularly strong feelings about this separation. If you want to keep the manipulation tasks in Stage II, that would be fine, too.

**Comment by MatthijsBurgh** [comment]
Since when is there a stage 3?

**Comment by LeanderVonSeelstrang** [comment]
O there isn't. I am just proposing one. Basically I think it would be nice to introduce a new first Stage. I should have called the newly proposed stage "Stage 0", not "Stage I" to avoid confusion. This wasn't smart, as it is quite likely to be rejected and now this issue will confuse everyone. 

https://github.com/RoboCupAtHome/RuleBook/issues/813
#813

**Comment by PetervDooren** [comment]
The stages are divided based on difficulty right now. But there are indeed no strict guidelines for where a challenge belongs. I would not separate the stages by what skills are tested though as that would be disadvantageous to a team that can do manipulation well but not perception. (even though they are dependent on eachother, that team might not progress to stage 2)
