### ISSUE TITLE
Strive for a comprehensible goal-oriented and fair scoring.

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#821]
## Is your idea/suggestion related to a problem? Please describe.
# Problem 1: Inconsistent, badly comparable and thus unfair scoring
Alias missing intra comparability. The exact same task should not lead to different scores in different contexts. E.g. picking up a spoon in Serve Breakfast results in 15 points. In Clean Up the exact same action scores you 60 points, even though it is in a later stage (if anything you should get fewer points).

# Problem 2: Predefined scores for a task
Setting the scores for a task to a predefined value, regardless of the content is unreasonable

# Problem 3: Too harsh punishments
Most punishments are too harsh and thus not enforced. E.g. -500 points for not attending. Team disqualification and confiscation of the device for opening a hotspot (not even legal). If the punishments are not that bad the referees would think it is reasonable to reinforce them, which is desirable. 

# Problem 4: Punish for work
Some features are hard to implement and at the same time you get a punishment for solving the task (e.g. pointing as fallback). No team will ever implement that, because it is easier to just detect and recognize the wanted items correctly.

# Problem 5: Stingy with points
The rulebook is very stingy with points in an attempt to push the field forward. I highly doubt that this is the best way to design incentives:

- It is rather depressing for newcomers to getting started
- You don't gather feedback that you are on the right track, because you score 0 points for a long time, which contains 0 information
- Teams with less funding frequently leave the competition with 0 points. This is depressing, does not appreciate their performance, and greatly reduces the likelihood that the teams involved will promote the event.
- Solved tasks won't stay solved, if solving is not rewarded. One team having solved a task does not automatically mean that all future teams will solve the task as well
- If you plot the average scores of the tournament over the years you would see a downwards trend. However we want to display an upwards trend. You all know this is relevant when communicating with non scientists e.g. journalists.

# Problem 6: No statistics 
Collecting and compiling statistics is not an integral part of the TC task catalog. This forces us to fall back to gut feeling decisions (rather than empirically driven decisions). 
We want to emphasize the science aspect. Good science can be based on data.

## Describe the solution you'd like
# Problems 1, 2, 5, 6.
Reuse the same atomic scores for the same subtask over the years. Collect data about those scores: 

1. How often is this atomic task used in tasks?
2. How often do teams attempt to score this atomic task? 
3. How often do teams succeed to score this atomic task?

This is only viable if we manage to set up a scoring app. I am working on that already.

This can solve the problems 1, 2, 5, 6. At least partially. 

Related:
#808 
#813 

# Solution for Problem 3
Reduce the punishments, use other means as well (e.g. posters as a reminder to switch off hotspots) and actually enforce those punishments. (Also a OC thing to do). 

Related:
#810 

# Solution for Problem 4
Smarter task design and guidelines. Don't just transfer the complexity for humans to solve a task to robots. 

Related:
#810 
#812

**Comment by ARTenshi** [comment]
Problem 1 is quite interesting, thank you for highlighting it. I've always wanted to reduce all redundant tasks into a single one,-- e.g. Storing groceries, Serving breakfast, and Clean the table, all involve moving objects from their current location to their correct locations (with some bonuses like opening a shelf, pouring something, or adding small soap to the dishwasher). We need to encourage that. 

Regarding a consistent, measurable benchmark/baseline scoring, you can see our experience with World Robot Summit here ( https://www.tandfonline.com/doi/abs/10.1080/01691864.2022.2109428 ). It helped to improve Asian teams' performance (four out of six teams in Stage II have participated in the World Robot Summit and their performance evolution can be objectively tracked through the years thanks to the scoring system). We can have both benchmark-like tasks (e.g. WRS' Tidy Up) and general tasks (e.g. gpsr, restaurant).

**Comment by LoyVanBeek** [comment]
Note that all of the tasks mentioned include perception, manipulation and a bit of navigation. I don't think any skill can really be done, in a somewhat realistic setting like RoboCup, without the others.

I've tried setting up a more even scoring (and considered handing out eg. a 'best manipulator' award for the robot scoring the most manipulation points), in the past, but found that very very hard to do. 
Then, some challenges bring in more points than others as they have a different skill mix. That points to Problem 2 you are highlighting. But maybe there doesn't need to be a roughly even score per challenge.

**Comment by LeroyR** [comment]
All tasks having the same score does not make sense with fixed tasks, i hoped that was just an artifact of the previous rulebook (teams could select tasks)

It also gives an easy knob to turn during the "tick" phase of the rulebook e.x:
Receptionist scored pretty high across the teams so points could be reduced.

**Comment by LoyVanBeek** [comment]
> an artifact of the previous rulebook (teams could select tasks)

Could be, I'm not up-to-date enough anymore.
