### ISSUE TITLE
Tasks should make full use of the objects in the Arena

### ISSUE THREAD

**Issue by ARTenshi** [RoboCupAtHome/RuleBook#822]
## Is your idea/suggestion related to a problem? Please describe.
Every year we request specific furniture from the LOC (e.g. fridge, bed, most of the tables) but it's rarely used except for some general-purpose surfaces (tables) and containers (shelves).

## Describe the solution you'd like
We should either remove redundant or generic tasks and add some new home-specific tasks (like setting up a bedroom) or refrain from requesting such furniture to the LOC (the fridge has never been used and the dishwasher can be changed to a dish rack, for example).

**Comment by LeroyR** [comment]
Fully agree with @PetervDooren

**Comment by ARTenshi** [comment]
And yet, we should make an effort to show some respect to the LOC work. 

In particular, the bedroom was only used as a "forbidden room" in the "Stickler for the rules" task and to detect how many persons are raising their hands in GPSR; similarly, the studio was a fixed location for drinks in Stickler and to detect persons in GPSR. They could easily be empty rooms or those tasks could have taken place in a different room and reduce the environment to a two-rooms house.

I agree that we don't want that but, again, we should focus on meaningful requests and not only for decoration; in this sense, if we consider that three tasks take place in the kitchen (Storing groceries, Clean the table, Serving breakfast), with very little work we can change the context of those tasks leaving everything the same (including the scoring), for example, "Clean the table" can be "Clean the studio's desk", and "Storing groceries" can be "Tidy up the bedroom".

**Comment by ARTenshi** [comment]
Again, I am not against fully furnished homes but I am in favor of having meaningful tasks. Being objectives, if we remove all unused furniture/rooms, the state-of-the-art in RoboCup at Home tasks are limited to flat surfaces and open deposits in single rooms. Having several rooms with unused furniture is misleading.

Little changes like going from "Storing groceries" to "Storing shopping" where the robot stores not only food but any item with a predefined location in any room (like bed items, studio items, and so on) will add some meaning to the "at home" league (instead of "at single-room-with-flat-and-open-surfaces" league).
