### ISSUE TITLE
Why do so few companies participate in the competition?

### ISSUE THREAD

**Issue by LeanderVonSeelstrang** [RoboCupAtHome/RuleBook#823]
## Is your idea/suggestion related to a problem? Please describe.
I have the feeling that almost exclusively universities compete in the @Home League. At the same time, companies, at least some, have more resources and less turnover. So, in theory, they can concentrate significantly more work-power and capital than universities. 
In my opinion, it would be desirable to be attractive to corporations. 

## Describe the solution you'd like
I think we should identify why this competition is unattractive to companies. 
A very discouraging factor should be the improvable organization and publicity, since participation currently cannot be used as an effective advertising space. We need to provide something that employees can present internally as an argument to their bosses. 
Another problem is that not winning is much more expensive for companies than for universities. 
The planning horizons for companies are greater. A constantly changing rulebook could also have a disincentive effect.

In particular, I would like to see us incentivize any form of publicity in the form of points.

## Describe alternatives you've considered
This is more of a problem for the organizing team. Still, it should be in the back of TC's mind as well, which is why I opened an Issue.

**Comment by LeanderVonSeelstrang** [comment]
We, or the organizers, must provide arena interfaces. If this is basically used, then the team will get a noticeable amount of points once. Once, so that teams don't go to the arena for tasks they haven't solved to get the points off. Noticeable so that it is done by everyone (basically as a bias).
But I think this point has already been noted by everyone.

In addition, I would like to identify the problems that discourage companies from participating in the competition.

I don't think it's just poor public relations and thus lack of attention. Although poor visibility may be the most relevant factor.

I think it's also the lack of planning security. In order to allocate resources for a project like Robocup@Home in a larger company (which can afford such fun), it would take at least one year from the idea to the commitment. As soon as the rulebook changes too much, the basis for which the money is approved has changed too much again.

Any prize money would probably be too irrelevantly small to motivate companies anyway. 

But besides advertising, perhaps the hope that artifacts will be produced in the course of participation that are valuable to the company will pop out would be a motivator. 

I would like it if we have a task in the catalog that focuses on solving a commercially relevant problem in such a way that a minimally viable product is created. 

That would be something like cleaning bathrooms as in [ARTenshi](https://github.com/ARTenshi)'s [video](https://github.com/RoboCupAtHome/RuleBook/issues/813#issuecomment-1685178164) ([direct Link to video](https://www.youtube.com/watch?v=xY5zqKRy8A8&ab_channel=getSOMATIC)), making beds for hotels, so doing cleanup. Or alternatively the restaurant task that comes closest to the requirement of a minimal viable product that can be used in an economically lucrative way. 

This task should remain as constant as possible, so that planning reliability is created. In addition, it should be as close as possible to a real world scenario, i.e. it should be free of all artificial complications. The task should be structured in such a way that the solution to the task is the prize money, because the solution can then be rolled out directly in the real world, saving someone real money and thus being economically relevant. 

For the restaurant task, for example, the location should be known in advance. All tools that make the robot more useful should be allowed. For example, no one really wants to interact verbally with a robot to order something when they could use a tablet on the table.

The delivery (later also the preparation), on the other hand, must be performed by a robot. It is important to optimize for speed and safety. The robot should be perceived as friendly. It should be able to orient itself even in a very crowded environment with many people. It should be able to run for a very long time without the intervention of experts. To any operators, it would probably be more important for the robot to take care of charging itself than for it to be able to talk to guests. 

Ultimately, in the real world, speed is also probably less relevant than the robot running stably for an afternoon without intervention from a technician.

The audience could provide feedback on whether an order was successful (scanning the NFC tag on the plate or glass). This way, there is no need for a "trained" referee to be present either, just a volunteer to make sure no one is obviously cheating. The task could run for hours, if a team has several robots available even permanently. 

At least that is what I believe we could design as TC's. A task whose solution is economically relevant.

**Comment by hawkina** [comment]
It's cheaper and more effective for the companies to sponsor Teams, than actually invest into employing people to permanently work on tasks like this. Also there is a logistics competition within the RoboCup, for example. 
Also things become quite unfair once a big company decides to join, since they might potentially allocate a rediculous amount of ressources for that project. It happened in RoboCup Junior a few years ago. A soccer robot used pressurized air for shooting the ball - since parents had connections to industry - and the robot was so powerfull that it literally destroyed the opponent robots. Or having access to sensors which are proprietory and out of scope for any university to actually by... I would really be careful with thart.

**Comment by hawkina** [comment]
One could make it a slightly separate thing... for example, a company wcould want a new sensor/software module tested and would give acces to it to the qualified robocup teams, and make it a separate challenge to have the sensor/software module used. They would get a lot of data out of it maybe and people would get access to it. 🤷 Could be like these extra challenges in Soccer which are out of scope of the regular competition, but for which one can earn an extra award.
