### ISSUE TITLE
Create BIG posters for challenges to appeal audience

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#84]
To advertise the league and challenges, make posters for each challenge. 
In English and Chinese, with the time, a picture of the actions performed.

**Comment by kyordhel** [comment]
Great idea. Questions as follows

- Who is going to do posters?
- Who is going to pay for the posters' printing?

**Comment by LoyVanBeek** [comment]
I don't know, @robotijn asked me to :smiley: But I do think this is a good idea, for every league. 
I'll ask the LOC.

**Comment by LoyVanBeek** [comment]
E-mail sent...
