### ISSUE TITLE
[Wake-me-up] Robot-human cooperation while doing the bed

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#85]

**Comment by LoyVanBeek** [comment]
Do we want this for China already or maybe in Leipzig 2016? For this year, i'd be glad is a robot even touches the blanket for example.

**Comment by kyordhel** [comment]
We may soften the requirements, but we face the problem that this test is easy to hard-code and play with luck. 

We want robots try to grasp a blanket with a purpose, not grasping blindly to score. In this challenge I see the chance of action planning which is not possible if we reduce the challenge to grasping. 

Same as the door challenge. It has been there for eons and there is few advances on it. We may also create a 2nd stage test for doing the bed

**Comment by LoyVanBeek** [comment]
Maybe do this as a more general tidy up the house-task: 
- make bed
- put dishes in dishwasher
- rubbing a brush over dishes before putting them in the dishwasher
- Clean up the table (grasp spoon etc)

**Comment by kyordhel** [comment]
Tidying up the house sounds good for me, however I would constrain to one task and provide specifications in the rulebook for good start, such as:

- Standard (IKEA?) bed with well-defined sheets on happy colours so corners are easy to identify 
- Standard plastic cutlery, brushes, and dishes with bright colours or patterns, but FIRST
  - have robots opening microwave, fridge, dishwasher, etc.
  - have robots placing objects in special containers
  - have robots grasping those objects and THEN rub or polish

Bedsheets
![bedsheets](https://cloud.githubusercontent.com/assets/8583949/10821709/19a7b750-7e54-11e5-8df6-461d117e73ae.jpg)

Special dish container
![dishdry](https://cloud.githubusercontent.com/assets/8583949/10821841/c589f416-7e54-11e5-8042-26a16b0cd972.JPG)
