### ISSUE TITLE
Duplicate scoring entry in Storing Groceries

### ISSUE THREAD

**Issue by Shimarisu-kun** [RoboCupAtHome/RuleBook#855]
The following scoring item is duplicated with different point deductions in Scoring Groceries:

"A human placing an object in the cabinet at a location clearly indicated by the robot"

The issue seems to have been introduced with commit 807610c.

**Comment by MatthijsBurgh** [comment]
You are correct, see:
https://github.com/RoboCupAtHome/RuleBook/blob/5a3961f153ad5448bae4bbd7c18648cbfba7c054/scoresheets/StoringGroceries.tex#L24-L26

I leave it up to the current TC members, to fix this.
