### ISSUE TITLE
[General Rules] Multi-robot task solving

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#86]
Shall we allow more than 2 robots working on the same task?

**Comment by LoyVanBeek** [comment]
That is really difficult, we want that, so yes! In the Restaurant challenge, if 1 robot takes order and another delivers them, that would be cool I guess. The maximum time could then be reduced maybe.

**Comment by kyordhel** [comment]
+1

I wouldn't reduce the time for solving the task. If a team can afford 2 robots: perfect. If two teams cooperate solving the task we may use the same rules from Wake me up. Otherwise, it makes no sense to increase difficulty for teams that work with only one robot.

**Comment by LoyVanBeek** [comment]
Do we instead award extra points for multi-robot and multi-team cooperation?
Like, increase score by 20% is it is clear that the robots meaningfully cooperated? And like 30% if robots form 2 teams clearly cooperated in a useful way?

**Comment by LoyVanBeek** [comment]
@kyordhel @balkce what kind of incentive do we give for team&robot co-op?

**Comment by balkce** [comment]
I think the possibility of earning the points scored in the co-op test when not being the main team  tested is incentive enough.

**Comment by kyordhel** [comment]
None. 

If a team with 2 robots solves a task, it scores normal. 

If a team with one robot solves a task helped by another team, it scores normal. Also, the helper team scores for the solved task.

So the incentive is only for the helper team. His way, team ToBI (one arm) may ask help of team TU/e (two arms) for solving a task so both teams may score: ToBI for the whole test and TU/e for the task solves by its robot. 

That should be enough

**Comment by LoyVanBeek** [comment]
Then we leave it as is now in the text with https://github.com/RoboCupAtHome/RuleBook/commit/0a0890d1731bc9e6538447146d0a279be53c6fc7
