### ISSUE TITLE
Q: How does the scoring work?

### ISSUE THREAD

**Issue by m-barker** [RoboCupAtHome/RuleBook#874]
For the attempts for a given task, is the mean/median/max score taken as the team's final score?

For the total score, is there a maximum number of tasks that count towards scoring, or is it simply the sum of all attempted tasks that score?

**Comment by johaq** [comment]
The max score is counted for any given test. 
Overall score is the sum of all attempted tests.

**Comment by m-barker** [comment]
Got it -- thanks!
