### ISSUE TITLE
Q: [DSPL]Scoring of speech recognition

### ISSUE THREAD

**Issue by mochimochi510** [RoboCupAtHome/RuleBook#878]
In speech recognitions in some tests(e.g. receptionist), if a person is asked to tap the robot's hand after he/she has finished speaking, will scores be deducted?
(This question seems to relate to sec2.2.2(Scoring) and 2.2.3(Bypassing Automatic Speech Recognition) in the rulebook.)

**Comment by LeroyR** [comment]
Disregarding scoring, it is possible that the person either forgets or does not understand the instruction (maybe holds the gripper while speaking).

e.x: 
- Robot says: "tell me your name and touch my gripper afterwards."
- Person says: Peter
- nothing happens, Person waits and is confused, maybe shouts "MY NAME IS PETER!"
- You team shouts: press the gripper.
- I would now disallow the person to touch the gripper until the robot gives the instruction again.

**Comment by PetervDooren** [comment]
> Disregarding scoring, it is possible that the person either forgets or does not understand the instruction (maybe holds the gripper while speaking).
> 
> e.x:
> 
>     * Robot says: "tell me your name and touch my gripper afterwards."
> 
>     * Person says: Peter
> 
>     * nothing happens, Person waits and is confused, maybe shouts "MY NAME IS PETER!"
> 
>     * You team shouts: press the gripper.
> 
>     * I would now disallow the person to touch the gripper until the robot gives the instruction again.

In this instance I would disallow this. The team is not allowed to instruct the volunteer. When the team interferes they have already broken the rules.
If the volunteer cannot work intuitively with the robot than that is a flaw in the interface design.
