### ISSUE TITLE
Structured Scoresheets

### ISSUE THREAD

**Issue by LeroyR** [RoboCupAtHome/RuleBook#883]
## Is your idea/suggestion related to a problem? Please describe.
To influence further Rulebook decisions we want information on how the tasks went.
Currently the Refs scribble notes at the bottom of the scoresheets.

## Describe the solution you'd like
More structured Template for the Referee including:
- start stop time or duration
- why did the task stop
- what commands were given to the robot, how often commands where repeated etc

## Describe alternatives you've considered
- Referee could use an Program/App that keeps track of some of these things, e.g. time and generated commands instead of paper based scoresheets.
- Review Videos

## Additional context
Also helps new Referees?

**Comment by johaq** [comment]
Very good idea. I think it should include:
- Stop Time:
- Reason for Stoppage: 30 seconds or e stop and the reason
- "Commands" given: this can be task specific. I.e. for Receptionist it would be name and drink
- Robot statements (couldn't think of a better name): anything the robot indicates to the referee. I.e. object recognition
- Notes: for anything out of the ordinary. I.e. placement was dropped.
