### ISSUE TITLE
Remove Oustanding Performance

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#89]
Never used before. Why should we keep it?

**Comment by LoyVanBeek** [comment]
+1 for simplification.
What would a team need to do to get this award :confused:

**Comment by kyordhel** [comment]
Doing something super awesome and perfect with a brand new scope.

For instance, in the Wake Me Up, if a robot pours the milk and the cereal in the bowl, then places the spoon in the bowl and carries out the try (with the bowl full of milk) to the dinning room table. That's outstanding!

**Comment by LoyVanBeek** [comment]
That should be the default task description :smile:

**Comment by kyordhel** [comment]
We leave it as is!
