### ISSUE TITLE
Optional Start Signal (Avoid Door Bumps)

### ISSUE THREAD

**Issue by SparkRibeiro21** [RoboCupAtHome/RuleBook#890]
## Is your idea/suggestion related to a problem? Please describe.
In some arenas, in order to make the door frame more robust, there may be a small bump or some other physical structure that may be hard for some robots to overcome. For example DSPL in RoboCup 2024 and some teams that use 'Tiago' robots.

## Describe the solution you'd like
The goal would be to have an alternative start signal for these teams so they can at least overcome the navigation through the door and continue performing the task. This may include some penalty sort of penalty. 

## Describe alternatives you've considered
Some alternatives considered are:
- The robot starts after the door (inside the house, next to the door)
- Teams may use some sort of structure (i.e. small ramp)

## Additional context
Other considerations:
- For the start inside the house solution, a penalty should be considered, as this saves the overall task time. (Penalty can be point related or time related)

**Comment by ARTenshi** [comment]
And allowing this change is going backwards even further. For example, for "Clean the table", we moved from 2019:

* Place all tableware and cutlery inside the dishwasher

to 2022/2023

* Picking tableware and cutlery for transportation to the dishwasher
* Placing the tableware and cutlery inside the dishwasher

to 2024

* Navigate to the table to pick up items
* Picking tableware (cup, bowl) for transportation to the dishwasher​
* Picking up a plate for transportation to the dishwasher​
* Picking up cutlery (spoon, fork) for transportation to the dishwasher
* Placing the tableware and cutlery inside the dishwasher​
* Placing an item correctly (cleanable, convenient like a human would) in the dishwasher​

So, changing it to starting inside the arena can be rephrased to:

* Using the controller to move the robot inside the arena

If we allow it, we are in the wrong direction that might allow "using the controller to move the robot to the table" or "using the controller to take the object", and so on. So I strongly oppose this idea, and I might ask you to go in the opposite direction (making the tasks, at least for Stage II, more challenging).

**Comment by hawkina** [comment]
> And allowing this change is going backwards even further. For example, for "Clean the table", we moved from 2019:
> 
>     * Place all tableware and cutlery inside the dishwasher
> 
> 
> to 2022/2023
> 
>     * Picking tableware and cutlery for transportation to the dishwasher
> 
>     * Placing the tableware and cutlery inside the dishwasher
> 
> 
> to 2024
> 
>     * Navigate to the table to pick up items
> 
>     * Picking tableware (cup, bowl) for transportation to the dishwasher​
> 
>     * Picking up a plate for transportation to the dishwasher​
> 
>     * Picking up cutlery (spoon, fork) for transportation to the dishwasher
> 
>     * Placing the tableware and cutlery inside the dishwasher​
> 
>     * Placing an item correctly (cleanable, convenient like a human would) in the dishwasher​
> 
> 
> So, changing it to starting inside the arena can be rephrased to:
> 
>     * Using the controller to move the robot inside the arena
> 
> 
> If we allow it, we are in the wrong direction that might allow "using the controller to move the robot to the table" or "using the controller to take the object", and so on. So I strongly oppose this idea, and I might ask you to go in the opposite direction (making the tasks, at least for Stage II, more challenging).

I totally see your point but then we really need to somehow ensure the edge is smooth enough. We have seen several teams loosing their run to simply being unlucky and getting stuck in the door, one wheel hanging in the air long enough to completly loose localisation or even have the robot rotate on that edge (we have some videos of this happening even when driving the robot with a controller). I'm all for the tasks being challenging, but it has to somehow be fair. If a robot gets stuck on that edge, that's not fair.

**Comment by PetervDooren** [comment]
I would like to counter that a service robot that cannot make it over a doorstep as low as the one we had in 2024 would never be able to be helpful in a household. 
I know it sucks when your robot cannot enter the arena. But most doors will come with a doorstep and especially in OPL teams have the option to customise their hardware to deal with them. 
Even in DSPL I think doorsteps should be something the robots can deal with. I know the HSR's hardware has trouble with them, I have seen the HSR get stuck on a wheelchair accesible doorstep. But if the problem is localization that is something that can be taken care of in software.

And having organised a tournament myself. It is very difficult to make a door that is structurally sound without a bar at the bottom.

**Comment by sunava** [comment]
Here's a professional English formulation:

A robot should be able to enter through doors, even if they’re located within the arena. This year, we encountered a major bump between the hallway and the outer waiting area that forced most teams to disable safety settings on the HSR and proceed using only velocity control. Until we can guarantee that no obstacle is severe enough to completely obstruct the HSR’s wheels, robots should be permitted to start within the arena. A fixed point just beyond the doorway could serve as the designated starting position. Additionally, a door within the bump-free arena area would allow demonstrations without restricting movement. After all, one wouldn’t install a service robot in an environment it cannot navigate. Denying this setup only penalizes teams that prioritize safety, limiting their ability to showcase their work, which seems counterproductive.

**Comment by johaq** [comment]
Based on last TC meeting discussion:
I want the door opening to be the default start signal. If there is a problem for HSR with i.e. a door bump I want a clear decider on whether we allow an alternative. My idea was:
If the HSR in standard configuration (meaning nothing that violates the lease agreement) is not able to consistently cross the door while being remote controlled we allow an alternative start.

OPL teams need to handle door bumps. I would stick to if it is an extreme gap we modify it during setup days (tape, ramps, carpet etc.)

**Comment by ARTenshi** [comment]
> If the HSR in standard configuration (meaning nothing that violates the lease agreement) is not able to consistently cross the door while being remote controlled we allow an alternative start.

EC may detect and decide it during the "Robot inspection" based on the number of robots having an issue with the door access. But, again, the standard start signal remains unchanged unless it is decided different on site.

Luis

**Comment by LeroyR** [comment]
The Rulebook states
```
Walls: Walls are fixed and cannot be modified during the competition. The minimum
wall height is 60 cm; a maximum height is not specified, but must allow the audience to
watch the competition.
```
