### ISSUE TITLE
Change CML logic? (when should the robot transport the bag)

### ISSUE THREAD

**Issue by SparkRibeiro21** [RoboCupAtHome/RuleBook#891]
Just to start the discussion whether it makes more sense in Carry my Luggage to transport the bag while following the person or when coming back to the start point. Does it make sense to have the robot transport luggage to the car (to load the car) or to help the user bring its stuff to the house (like the groceries). 

Advantages of transporting the bag while following the person (load the car):
- Teams that struggle to follow a person may showcase their ability to pick the bag (better for audience)
- More options for teams as they may skip picking the bag but may not skip following

Advantages of transporting the bag when coming back to the initial position (unload the car):
- Easier for obstacle avoidance when transporting the bag, as teams have already mapped using the navigation from the first trajectory

**Comment by LeroyR** [comment]
Making the Task Easier should not be a goal i think we can disregard this advantage :smile: 

IMHO: As the only Task that focuses on Navigation we should ensure that actually moving (as in driving around) should be the Main focus. Doing the Handover only after the follow is a easy change to reduce the time until the robot starts Navigation. I would like to have the robot move and avoid some obstacle before doing recognition/learning of the operator - but i dont think thats feasible.

**Comment by johaq** [comment]
As I said before, I'm also in favor of getting the bag on the way back. There are other tests where teams can showcase their manipulation capabilities. Teams should not skip following, it is the main point of the test.

**Comment by ARTenshi** [comment]
True. The bag is part of the story around the skill. However, as Leroy mentioned, making it easier is not the goal but making it meaningful. Try to reintroduce person reidentification that, somehow, has been left out for a while (i.e. the tracked person gets out of sight of the robot long enough while some other people is around and the robot should be able to retrack the person when s/he reappears); also, in previous editions, we also had the robot following the person in challenging spaces (like inside an elevator). Let's think on new challenges like those.
