### ISSUE TITLE
[Manipulation] Buff and finish the test

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#90]
Following changes are required:
- [x] The test will be performed in a bookcase, not in a table.
- [x] Teams may choose the "middle empty shelf"
- [x] There is a penalty for false positives
- [x] The test may be performed OUTSIDE the arena
- [x] Easy-to-grasp, hard-to-grasp, and  hard-to-reach objects will be replaced with:
  - Known object in a middle shelf
  - Known object in a lower shelf
  - Known object in an upper shelf
  - Alike object in a middle shelf
  - Cloth / tray / bowl in a middle shelf
- [x] Rework the Task subsection to make it clear and easy to understand

**Comment by LoyVanBeek** [comment]
Please be sure to make these changes on the prepare_china_2015 branch of the rulebook.
That is supposed to make the changes since GermanOpen2015 clearly visible.

**Comment by kyordhel** [comment]
I'm working on that branch I guess, at least it says on the last 2 commits.

**Comment by LoyVanBeek** [comment]
Ok, great. Just checking :-)
