### ISSUE TITLE
Review Organization Document

### ISSUE THREAD

**Issue by LeroyR** [RoboCupAtHome/RuleBook#900]
## Describe the bug
The Rulebook got split into rulesbook and organization document to reduce the size of the rulebook but currently there are some rule related information in the orga document. 
Also orga and rule doc depend on each other.

We should either undo the split or cleanup the current mess e.g. rule document should not depend on the orga and vice versa.

**Comment by johaq** [comment]
Yes, we should move everything that the rulebook references in the organization document back to the rulebook document

**Comment by PetervDooren** [comment]
As the person who made this mess I would recommend to merge them back into one document
