### ISSUE TITLE
Idea: lower wall height

### ISSUE THREAD

**Issue by moriarty** [RoboCupAtHome/RuleBook#910]
Copying this from an issue comment:

> Another problem is that the walls of the arena often prevent the audience from seeing what is going on. I would suggest to drastically lower the front wall of the arena to a height of 50cm so the audience can see in. We can still use retractable barriers or likewise to prevent people from leaning or stepping in. The wall would still be high enough for the robots to do localization with them using their Lidars. A result of this is that the audience can see what is happening from the audience stands. Which prevents a crowd from forming very close to the arena itself.

_Originally posted by @PetervDooren in https://github.com/RoboCupAtHome/RuleBook/issues/882#issuecomment-2252671920_

**Comment by hawkina** [comment]
I would think it would mess with perception since the robot would perceive a lot more clutter outside of the arena. Not sure how well perception systems can handle that. could we test this prior to implementation?

**Comment by PetervDooren** [comment]
It would mess with perception. But to a degree that is manageable. Teams already experience clutter perceived outside the arena including people. 
We would need to ensure people keep some distance to the arena, which can be done with proper marking.

There would be no way of testing this beforehand. Even if we could. The result would depend on which team is doing the testing.
