### ISSUE TITLE
[Restaurant] Missing information in Restaurant

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#92]
- [x] **2nd order's else:** The in the Task description (Section 6.2.3), subsection 4.3 rulebook states that if the robot detexts the waving/calling from the other table, it must get close to it to fetch the order. However, it does not state what happens if the robot fails to detect the calling.
- [x] **Instructing the Professional Waiter:** Is it allowed for the team to give a piece of paper with easy explicit instructions to guide the robot to the *Professional Waiter*?
- [x] **Combo:** The test must specify from which categories (food & snacks / known & alike) are the combos made of.
- [x] **Kitchen Bar location**: The robot may be instructed on which side the Kitchen bar is, if it cannot detect it by itself.
- [x] **Loud & Clear:** State that no points are scored if the barman is not able to understand the robot's voice.
- [ ] **Correctly memorized tables (BUG!):** Points for learning the location of a table should be granted only when the robot goes back to a table to take the first order. Otherwise there is no way to know if the robot has memorized table location or is just playing dumb.
- [x] **End of guiding phase:** State that the *Professional Waiter* must end the guidance at the same point it started.

We may also add more tables to the training, 3 seems to be few.

**Comment by LoyVanBeek** [comment]
The combo should be clear with ff431f12cc70997567a3715ff3b7e317442c2d73 and 722d2e36b627f373a631e3ca282b58497b3b0c4a

**Comment by kyordhel** [comment]
Didn't noticed that you have already corrected some of them

**Comment by LoyVanBeek** [comment]
If we add more tables to be learned, then there is no way to check that they are learned correctly without going to all tables... 
How was this done before?

**Comment by kyordhel** [comment]
Loy!

4~5 tables and we choose randomly 3 for ordering so there is always a chance for the robot not having memorizing them all. Plus, most robots just finished the training phase without reaching any table at all, just for scoring. There was a suggestion about requesting teams for a PDF with the map, but Restaurant is too complex setup so making it more complex is not a good idea.

To prevent this issue, in this rulebook we score no points for training phase until the robot reaches the table for fetching the order. There is no way to be sure the map was properly build, so we trust the teams.

**Comment by LoyVanBeek** [comment]
So, https://github.com/RoboCupAtHome/RuleBook/commit/d170da7beec6faa07fdefa1c9214644fa675d4e0#diff-b870a27e338e0ac054e4ef0b7af8b6faR91 is good enough already?
The example map already indicates 6 tables. Learning tables already takes a lot of time and I actually don't want to increase this further.

**Comment by kyordhel** [comment]
Then 3 is Ok

**Comment by LoyVanBeek** [comment]
So that means we leave it as it is now.

**Comment by kyordhel** [comment]
Just to clarify, we are using only 3 tables (to train), but there can be many in the environment (to be ignored).
