### ISSUE TITLE
[Finals] revert finals

### ISSUE THREAD

**Issue by kyordhel** [RoboCupAtHome/RuleBook#93]
In German Open, the finals were driven as previous years regardless the rulebook. Since is the EC which is evaluating this test, we should roll back the test to it's state on 2014.

**Comment by LoyVanBeek** [comment]
OK, agreed in TC meeting

**Comment by LoyVanBeek** [comment]
I don't have the TeX-source for the old finals as they were last year.

**Comment by balkce** [comment]
Done.
