### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboCupAtHome/RuleBook#94]
```
rubber -c 'setlist arguments --shell-escape' --pdf --force Rulebook.tex
command line: unknown directive 'setlist'
compiling Rulebook.tex...
/usr/share/texmf-texlive/tex/latex/was/gensymb.sty:32: Command \celsius already defined.
/usr/share/texmf-texlive/tex/latex/was/gensymb.sty:32: leading text: \newcommand\celsius{}
/usr/share/texmf-texlive/tex/latex/was/gensymb.sty:34: Command \ohm already defined.
/usr/share/texmf-texlive/tex/latex/was/gensymb.sty:34: leading text: \newcommand\ohm{}
Traceback (most recent call last):
  File "/usr/bin/rubber", line 9, in <module>
    sys.exit(Main()(sys.argv[1:]))
  File "/usr/share/rubber/rubber/cmdline.py", line 296, in __call__
    return self.main(cmdline)
  File "/usr/share/rubber/rubber/cmdline.py", line 265, in main
    for err in env.final.failed().get_errors():
  File "/usr/share/rubber/rubber/rules/latex/__init__.py", line 382, in parse
    info["file"] = pos[-1]
IndexError: list index out of range
make: *** [dirk] Error 1
```

Even after I install rubber. The version 0a340fcc works though

**Comment by kyordhel** [comment]
Pffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

Sorry, dirk took too much to solve it.

**Comment by dirkholz** [comment]
Guys, that is my personal Make rule. There is still "all" and that is the one that should be used.

'make dirk' is only useful iff 1) you have the latest TeX releases installed, and 2) if you have a proper setup. It then allows you to build (efficiently), e.g., inside emacs or vim with jumping to errors etc.

That is, there is no need for a fix, just don't build it! :)

**Comment by dirkholz** [comment]
and 'all' should still be "all: dofullpdf wall"

**Comment by dirkholz** [comment]
I reverted the change to the 'all' rule. Mauricio, just call make mauBuild, don't change the default behavior for all others! :)
