### ISSUE TITLE
Lots of "it's" should be "its"

### ISSUE THREAD

**Issue by rokusottervanger** [RoboCupAtHome/RuleBook#97]
Very annoying

**Comment by LoyVanBeek** [comment]
Some examples? A pull request with fixes would be nice :smile: ?

**Comment by rokusottervanger** [comment]
Here's a grep for "it's", I believe they are all supposed to be its, but I didn't check thorhoughly.

./Rulebook.tex:164:In the \iterm{Open Challenge} the robot must be able to show to the \iaterm{Technical Committee}{TC} the achievements on the main research line of it's own team. This test grants up to 20 points.
./ExampleSkills.tex:46:	\item Following a human by grasping it's hand.
./WakeMeUp.tex:3:The robot's owner has overslept. Knowing the schedule of the owner and noticing it is getting late, the robot helps it's owner to wake up and start the day.
./WakeMeUp.tex:16:	\item \textbf{Awakening the owner:} The robot enters the bedroom, approaches to the bed, and starts to awaken the owner (operator lying on the bed) for one minute by playing an alarm-like sound or using it's own voice. Within one minute starting from the first call, the owner will wake up in a natural way (sit on the bed and rub face; sit on bed, rise arms and yawn; stand up etc.), then the robot must announce it has successfully detected the awakening by greeting it's owner.
./WakeMeUp.tex:23:	\item \textbf{Delivering the newspaper [Optional]:} After awakening it's owner, the robot approaches to her and delivers a newspaper into the owner's hand (the owner will face the robot after being awakened and extend her hand to it). Robot must release the newspaper only after the human has grasped it.
./WakeMeUp.tex:25:	\item \textbf{Taking breakfast order:} The robot asks to it's owner for a breakfast of her preference. The order will include: one random fruit/snack, one kind of cereal, and one kind of milk (stating no milk means whole milk), but those can be given in any order. The robot may ask for a confirmation of the order up to three times. If the robot is not able to handle a tray (see below), it must state that breakfast will be delivered to the dining room. Examples of the order are:
./Restaurant.tex:7:The robot will need to create it's own map from the environment and then move into it to handle human requests, such as delivering drinks or snacks, while people are walking around.
./Restaurant.tex:20:	\item \textbf{Guide phase:} Starting from the \textit{Kitchen}, the robot is guided through the environment by a \quotes{Professional Waiter} which shows to the robot the location of each of the tables, it's number, and on which side the table is (there is a total of 3 tables). After visiting all the tables, the robot must be guided again to the \textit{Kitchen}.
./Navigation.tex:61:\item \textbf{Waypoint B (dynamic obstacles):} The robot must navigate to waypoint B which is also reachable via (the same) two doors, one of each may still be closed. On it's path the robot may find a dynamic obstacle (movable people, other robot, pets, etc.) which blocks its path to waypoint B. The robot may:
./Navigation.tex:80:	\item \textbf{Moving objects:} If the robot finds on it's way a \textit{static movable obstacle} (chair, cubes, toys, etc.) which is capable to move, it may move the object apart with it's manipulator.

**Comment by LoyVanBeek** [comment]
I'll check them somewhere this week if I find some time
